##### __\*You are viewing and editing the Developmental File\*__

## Initialization

In [226]:
#Import libraries
from __future__ import annotations
import pandas as pd
import requests, json, lxml
from bs4 import BeautifulSoup
import numpy as np
import re
import time
import random
import tempfile
from datetime import datetime, date
from pathlib import Path
from typing import Dict, List, Optional, Set
import sqlite3
import csv
import os
from tqdm import tqdm
import ftfy
from selenium import webdriver
from seleniumbase import Driver
import pyautogui
# Disable pyautogui fail-safe
pyautogui.FAILSAFE = False
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException, TimeoutException, ElementNotInteractableException, JavascriptException, StaleElementReferenceException
from webdriver_manager.chrome import ChromeDriverManager
from markdown_it import MarkdownIt
from urllib.parse import urljoin
from pdfminer.high_level import extract_text
from selenium.webdriver.common.keys import Keys
import glob
import io
from tabulate import tabulate
import google.generativeai as genai
import PyPDF2
import pdfplumber
import shutil
import pypdf
import concurrent.futures
from concurrent.futures import ThreadPoolExecutor
import html
import logging
import subprocess

genai.configure(api_key=os.getenv("GENAI_API_KEY"))

model = genai.GenerativeModel('gemma-3-27b-it')

## Configuration & Execution Tools
Run this cell to define the helper functions. To execute scrapers, uncomment the lines at the bottom or call `run_all_scrapers()` in a new cell at the end of the notebook.

In [418]:
#--CONFIGURATION & UTILS--
import traceback
import os
import pandas as pd
# Ensure datetime is the class, not the module, to match user code usage
from datetime import datetime
# Ensure ThreadPoolExecutor is available
from concurrent.futures import ThreadPoolExecutor

# ---------------- CONFIGURATION ----------------
# Define paths - adjusted to be robust if E: drive is missing
BASE_PATH = "E:\\Ace\\Awards Scrape\\" # Original path from your code
RESULTS_PATH = os.path.join(BASE_PATH, "Results v4\\")
INDEX_PATH = os.path.join(BASE_PATH, "Award INDEX.xlsx")

# Fallback: If the absolute path doesn't exist, use a local folder
if not os.path.exists(BASE_PATH):
    RESULTS_PATH = "downloaded_files/"
    os.makedirs(RESULTS_PATH, exist_ok=True)
    print(f"Info: '{BASE_PATH}' not found. Saving results locally to '{RESULTS_PATH}'")

# Ensure global 'filepath' variable exists for the scrapers to use
filepath = RESULTS_PATH 
# -----------------------------------------------

def get_award_name(aid):
    """Retrieves award name from the index file if available."""
    try:
        if os.path.exists(INDEX_PATH):
            awardindex = pd.read_excel(INDEX_PATH)
            awardindex['Id'] = awardindex['Id'].astype(str).str.strip()
            row = awardindex[awardindex['Id'] == str(aid)]
            if not row.empty:
                return row['AwardName'].values[0]
    except Exception:
        pass
    return f"Award {aid}"

def run_single_scraper(aid):
    """Runs a single scraper by ID (e.g., '1809')."""
    func_name = f"scrape{aid}"
    if func_name in globals():
        print(f"🔎 Found scraper for ID {aid}: {get_award_name(aid)}")
        try:
            globals()[func_name]()
            print(f"✅ Finished {func_name}")
        except Exception as e:
            print(f"❌ Error in {func_name}: {e}")
            traceback.print_exc()
    else:
        print(f"⚠️ Function {func_name} not loaded. Run the cell defining it first.")

def run_all_scrapers(log_file="scraping_run_log.csv"):
    """
    Finds and runs all functions matching 'scrape' + digits in globals().
    Logs success/failure/duration to CSV.
    """
    # 1. Identify all scraper functions dynamically
    all_scrapers = sorted([
        name for name, val in globals().items() 
        if name.startswith("scrape") and name[6:].isdigit() and callable(val)
    ])
    
    print(f"📋 Found {len(all_scrapers)} scrapers loaded in memory.")
    results = []
    
    for func_name in all_scrapers:
        aid = func_name.replace("scrape", "")
        print(f"\n{'='*60}")
        print(f"🚀 STARTING Award ID: {aid} ({func_name})")
        
        start_ts = datetime.now()
        status = "Success"
        error_details = ""
        
        try:
            # 2. Run the scraper
            globals()[func_name]()
            
        except Exception as e:
            status = "Failure"
            error_details = str(e)
            print(f"❌ ERROR: {e}")
            # traceback.print_exc() 
        except KeyboardInterrupt:
            print("\n🛑 Execution stopped by user.")
            break
        
        # 3. Log results
        end_ts = datetime.now()
        duration = (end_ts - start_ts).total_seconds()
        
        print(f"🏁 FINISHED {func_name} - {status} ({duration:.2f}s)")
        
        results.append({
            "Award_ID": aid,
            "Function_Name": func_name,
            "Status": status,
            "Start_Time": start_ts,
            "Duration_Seconds": duration,
            "Error_Message": error_details
        })
        
        # Incremental save
        pd.DataFrame(results).to_csv(log_file, index=False)
        
    print(f"\n{'='*60}\n✅ BATCH RUN COMPLETE. Log saved to {log_file}")
    return pd.DataFrame(results)

def run_failed_scrapers(log_file="scraping_run_log.csv"):
    """
    Reads the scraping log and re-runs only the functions that failed.
    Updates the log file with new results.
    """
    if not os.path.exists(log_file):
        print(f"❌ Log file '{log_file}' not found. Run run_all_scrapers() first.")
        return pd.DataFrame()
    
    # Read existing log
    log_df = pd.read_csv(log_file)
    
    # Find failed scrapers
    failed = log_df[log_df['Status'] == 'Failure']
    
    if failed.empty:
        print("✅ No failed scrapers found. All scrapes were successful!")
        return pd.DataFrame()
    
    print(f"📋 Found {len(failed)} failed scrapers to retry:")
    for _, row in failed.iterrows():
        print(f"   - {row['Function_Name']} (ID: {row['Award_ID']})")
    
    print(f"\n{'='*60}")
    
    results = []
    
    for _, row in failed.iterrows():
        func_name = row['Function_Name']
        aid = row['Award_ID']
        
        if func_name not in globals():
            print(f"⚠️ {func_name} not loaded in memory. Skipping.")
            continue
        
        print(f"\n{'='*60}")
        print(f"🔄 RETRYING Award ID: {aid} ({func_name})")
        
        start_ts = datetime.now()
        status = "Success"
        error_details = ""
        
        try:
            globals()[func_name]()
            
        except Exception as e:
            status = "Failure"
            error_details = str(e)
            print(f"❌ ERROR: {e}")
            traceback.print_exc()
        except KeyboardInterrupt:
            print("\n🛑 Execution stopped by user.")
            break
        
        end_ts = datetime.now()
        duration = (end_ts - start_ts).total_seconds()
        
        print(f"🏁 FINISHED {func_name} - {status} ({duration:.2f}s)")
        
        results.append({
            "Award_ID": aid,
            "Function_Name": func_name,
            "Status": status,
            "Start_Time": start_ts,
            "Duration_Seconds": duration,
            "Error_Message": error_details
        })
    
    if results:
        # Append results to existing log
        retry_df = pd.DataFrame(results)
        updated_log = pd.concat([log_df, retry_df], ignore_index=True)
        updated_log.to_csv(log_file, index=False)
        print(f"\n{'='*60}\n✅ RETRY COMPLETE. Updated log saved to {log_file}")
        
        # Summary
        success_count = sum(1 for r in results if r['Status'] == 'Success')
        print(f"\n📊 Retry Summary: {success_count}/{len(results)} succeeded")
        
        return retry_df
    else:
        print("⚠️ No scrapers were retried.")
        return pd.DataFrame()

def run_scraper_list(scraper_ids):
    """
    Runs a specific list of scrapers by ID.
    Example: run_scraper_list(['2878', '3233'])
    """
    print(f"📋 Running {len(scraper_ids)} selected scrapers: {scraper_ids}", flush=True)
    
    for aid in scraper_ids:
        # Support both string and int IDs
        aid_str = str(aid)
        run_single_scraper(aid_str)
        
    print(f"\n✅ Selected scrapers run complete!", flush=True)

# --- USAGE EXAMPLES (Uncomment to use) ---
# run_single_scraper('1809') 
run_scraper_list(["479", "3007", "8258", "3000", "3001", "3011"])
# run_all_scrapers()
# run_failed_scrapers()

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
|    | name                     |   year | affiliation                                 |   id |   govid | govname                                      | award                               |
|----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------|
|  0 | Steve F. Anderson        |   2014 | University of Southern California           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  1 | Stephen Berry            |   2017 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  2 | Peter K. Bol             |   2010 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  3 | Alison Booth             |   2013 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  4 | Jesse Casana             |   2016 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  5 | Pramit Chaudhuri         |   2015 | University of Texas at Austin               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  6 | Kimberly Christen        |   2020 | Washington State University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  7 | Daniel J. Cohen          |   2006 | George Mason University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  8 | Ryan Cordell             |   2015 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  9 | Nathan M. Craig          |   2009 | Pennsylvania State University               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 10 | David G. Dickason        |   2009 | Western Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 11 | Elizabeth Maddock Dillon |   2014 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 12 | Gregory Downs            |   2013 | City University of New York, City College   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 13 | S. Max Edelson           |   2010 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 14 | Margot E. Fassler        |   2012 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 15 | Abigail A. Firey         |   2016 | University of Kentucky                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 16 | Mary Flanagan            |   2010 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 17 | John M. Flower           |   2007 | University of North Carolina at Charlotte   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 18 | Richard Freedman         |   2020 | Haverford College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 19 | Kim T. Gallon            |   2015 | Purdue University                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 20 | Edward John Garrett      |   2006 | Eastern Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 21 | Aaron Glass              |   2020 | Bard Graduate Center                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 22 | Margaret Rich Greer      |   2009 | Duke University                             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 23 | Meghan Howey             |   2014 | University of New Hampshire                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 24 | Eric Kansa               |   2012 | The Alexandria Archive Institute            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 25 | Caren Kaplan             |   2006 | University of California, Davis             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 26 | Peter J. Kastor          |   2012 | Washington University in St. Louis          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 27 | William A. Kretzschmar   |   2013 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 28 | Massimo Lollini          |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 29 | Marit J. MacArthur       |   2015 | California State University, Bakersfield    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 30 | Anne MacNeil             |   2014 | University of North Carolina at Chapel Hill | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 31 | Ruth A. Mostern          |   2011 | University of California, Merced            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 32 | Natalie M. Phillips      |   2015 | Michigan State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 33 | Eric E. Poehler          |   2013 | University of Massachusetts Amherst         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 34 | Todd Samuel Presner      |   2006 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 35 | Kenneth M. Price         |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 36 | F. Jamil Ragep           |   2006 | University of Oklahoma                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 37 | K.J. Rawson              |   2017 | College of the Holy Cross                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 38 | Dwight F. Reynolds       |   2008 | University of California, Santa Barbara     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 39 | Massimo Riva             |   2011 | Brown University                            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 40 | Jesse Rodin              |   2017 | Stanford University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 41 | Anne Sarah Rubin         |   2007 | University of Maryland, Baltimore County    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 42 | Warren Sack              |   2012 | University of California, Santa Cruz        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 43 | Philip Sapirstein        |   2010 | University of Pennsylvania                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 44 | Patricia Seed            |   2007 | University of California, Irvine            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 45 | Andrew Sluyter           |   2012 | Louisiana State University                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 46 | Daniel L. Smail          |   2015 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 47 | M. Alison Stones         |   2008 | University of Pittsburgh                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 48 | Elaine A. Sullivan       |   2012 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 49 | Nicolas Tackett          |   2018 | University of California, Berkeley          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 50 | Timothy R. Tangherlini   |   2009 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 51 | Diana Taylor             |   2013 | New York University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 52 | William G. Thomas        |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 53 | James T. Tice            |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 54 | Daniel Trueman           |   2015 | Princeton University                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 55 | Yuri Tsivian             |   2007 | University of Chicago                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 56 | Ted Underwood            |   2013 | University of Illinois at Urbana-Champaign  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 57 | Cynthia M. Vakareliyska  |   1987 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 58 | Susan L. Wiesner         |   2011 | Kennesaw State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 59 | Matthew Wilkens          |   2014 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
AwardID 3000: 60 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3000.csv
✅ Finished scrape3000
🔎 Found scraper for ID 3001: ACLS Collaborative Research Fellowships

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
|    | name                     |   year | affiliation                                 |   id |   govid | govname                                      | award                               |
|----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------|
|  0 | Steve F. Anderson        |   2014 | University of Southern California           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  1 | Stephen Berry            |   2017 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  2 | Peter K. Bol             |   2010 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  3 | Alison Booth             |   2013 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  4 | Jesse Casana             |   2016 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  5 | Pramit Chaudhuri         |   2015 | University of Texas at Austin               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  6 | Kimberly Christen        |   2020 | Washington State University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  7 | Daniel J. Cohen          |   2006 | George Mason University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  8 | Ryan Cordell             |   2015 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  9 | Nathan M. Craig          |   2009 | Pennsylvania State University               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 10 | David G. Dickason        |   2009 | Western Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 11 | Elizabeth Maddock Dillon |   2014 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 12 | Gregory Downs            |   2013 | City University of New York, City College   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 13 | S. Max Edelson           |   2010 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 14 | Margot E. Fassler        |   2012 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 15 | Abigail A. Firey         |   2016 | University of Kentucky                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 16 | Mary Flanagan            |   2010 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 17 | John M. Flower           |   2007 | University of North Carolina at Charlotte   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 18 | Richard Freedman         |   2020 | Haverford College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 19 | Kim T. Gallon            |   2015 | Purdue University                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 20 | Edward John Garrett      |   2006 | Eastern Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 21 | Aaron Glass              |   2020 | Bard Graduate Center                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 22 | Margaret Rich Greer      |   2009 | Duke University                             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 23 | Meghan Howey             |   2014 | University of New Hampshire                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 24 | Eric Kansa               |   2012 | The Alexandria Archive Institute            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 25 | Caren Kaplan             |   2006 | University of California, Davis             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 26 | Peter J. Kastor          |   2012 | Washington University in St. Louis          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 27 | William A. Kretzschmar   |   2013 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 28 | Massimo Lollini          |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 29 | Marit J. MacArthur       |   2015 | California State University, Bakersfield    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 30 | Anne MacNeil             |   2014 | University of North Carolina at Chapel Hill | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 31 | Ruth A. Mostern          |   2011 | University of California, Merced            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 32 | Natalie M. Phillips      |   2015 | Michigan State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 33 | Eric E. Poehler          |   2013 | University of Massachusetts Amherst         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 34 | Todd Samuel Presner      |   2006 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 35 | Kenneth M. Price         |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 36 | F. Jamil Ragep           |   2006 | University of Oklahoma                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 37 | K.J. Rawson              |   2017 | College of the Holy Cross                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 38 | Dwight F. Reynolds       |   2008 | University of California, Santa Barbara     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 39 | Massimo Riva             |   2011 | Brown University                            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 40 | Jesse Rodin              |   2017 | Stanford University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 41 | Anne Sarah Rubin         |   2007 | University of Maryland, Baltimore County    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 42 | Warren Sack              |   2012 | University of California, Santa Cruz        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 43 | Philip Sapirstein        |   2010 | University of Pennsylvania                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 44 | Patricia Seed            |   2007 | University of California, Irvine            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 45 | Andrew Sluyter           |   2012 | Louisiana State University                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 46 | Daniel L. Smail          |   2015 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 47 | M. Alison Stones         |   2008 | University of Pittsburgh                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 48 | Elaine A. Sullivan       |   2012 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 49 | Nicolas Tackett          |   2018 | University of California, Berkeley          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 50 | Timothy R. Tangherlini   |   2009 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 51 | Diana Taylor             |   2013 | New York University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 52 | William G. Thomas        |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 53 | James T. Tice            |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 54 | Daniel Trueman           |   2015 | Princeton University                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 55 | Yuri Tsivian             |   2007 | University of Chicago                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 56 | Ted Underwood            |   2013 | University of Illinois at Urbana-Champaign  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 57 | Cynthia M. Vakareliyska  |   1987 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 58 | Susan L. Wiesner         |   2011 | Kennesaw State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 59 | Matthew Wilkens          |   2014 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
AwardID 3000: 60 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3000.csv
✅ Finished scrape3000
🔎 Found scraper for ID 3001: ACLS Collaborative Research Fellowships

Scraping pages: 100%|██████████| 7/7 [01:01<00:00,  8.73s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
|    | name                     |   year | affiliation                                 |   id |   govid | govname                                      | award                               |
|----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------|
|  0 | Steve F. Anderson        |   2014 | University of Southern California           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  1 | Stephen Berry            |   2017 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  2 | Peter K. Bol             |   2010 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  3 | Alison Booth             |   2013 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  4 | Jesse Casana             |   2016 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  5 | Pramit Chaudhuri         |   2015 | University of Texas at Austin               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  6 | Kimberly Christen        |   2020 | Washington State University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  7 | Daniel J. Cohen          |   2006 | George Mason University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  8 | Ryan Cordell             |   2015 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  9 | Nathan M. Craig          |   2009 | Pennsylvania State University               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 10 | David G. Dickason        |   2009 | Western Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 11 | Elizabeth Maddock Dillon |   2014 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 12 | Gregory Downs            |   2013 | City University of New York, City College   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 13 | S. Max Edelson           |   2010 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 14 | Margot E. Fassler        |   2012 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 15 | Abigail A. Firey         |   2016 | University of Kentucky                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 16 | Mary Flanagan            |   2010 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 17 | John M. Flower           |   2007 | University of North Carolina at Charlotte   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 18 | Richard Freedman         |   2020 | Haverford College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 19 | Kim T. Gallon            |   2015 | Purdue University                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 20 | Edward John Garrett      |   2006 | Eastern Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 21 | Aaron Glass              |   2020 | Bard Graduate Center                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 22 | Margaret Rich Greer      |   2009 | Duke University                             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 23 | Meghan Howey             |   2014 | University of New Hampshire                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 24 | Eric Kansa               |   2012 | The Alexandria Archive Institute            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 25 | Caren Kaplan             |   2006 | University of California, Davis             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 26 | Peter J. Kastor          |   2012 | Washington University in St. Louis          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 27 | William A. Kretzschmar   |   2013 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 28 | Massimo Lollini          |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 29 | Marit J. MacArthur       |   2015 | California State University, Bakersfield    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 30 | Anne MacNeil             |   2014 | University of North Carolina at Chapel Hill | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 31 | Ruth A. Mostern          |   2011 | University of California, Merced            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 32 | Natalie M. Phillips      |   2015 | Michigan State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 33 | Eric E. Poehler          |   2013 | University of Massachusetts Amherst         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 34 | Todd Samuel Presner      |   2006 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 35 | Kenneth M. Price         |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 36 | F. Jamil Ragep           |   2006 | University of Oklahoma                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 37 | K.J. Rawson              |   2017 | College of the Holy Cross                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 38 | Dwight F. Reynolds       |   2008 | University of California, Santa Barbara     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 39 | Massimo Riva             |   2011 | Brown University                            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 40 | Jesse Rodin              |   2017 | Stanford University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 41 | Anne Sarah Rubin         |   2007 | University of Maryland, Baltimore County    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 42 | Warren Sack              |   2012 | University of California, Santa Cruz        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 43 | Philip Sapirstein        |   2010 | University of Pennsylvania                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 44 | Patricia Seed            |   2007 | University of California, Irvine            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 45 | Andrew Sluyter           |   2012 | Louisiana State University                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 46 | Daniel L. Smail          |   2015 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 47 | M. Alison Stones         |   2008 | University of Pittsburgh                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 48 | Elaine A. Sullivan       |   2012 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 49 | Nicolas Tackett          |   2018 | University of California, Berkeley          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 50 | Timothy R. Tangherlini   |   2009 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 51 | Diana Taylor             |   2013 | New York University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 52 | William G. Thomas        |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 53 | James T. Tice            |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 54 | Daniel Trueman           |   2015 | Princeton University                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 55 | Yuri Tsivian             |   2007 | University of Chicago                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 56 | Ted Underwood            |   2013 | University of Illinois at Urbana-Champaign  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 57 | Cynthia M. Vakareliyska  |   1987 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 58 | Susan L. Wiesner         |   2011 | Kennesaw State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 59 | Matthew Wilkens          |   2014 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
AwardID 3000: 60 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3000.csv
✅ Finished scrape3000
🔎 Found scraper for ID 3001: ACLS Collaborative Research Fellowships

Scraping pages: 100%|██████████| 7/7 [01:01<00:00,  8.73s/page]

+-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------+
|     | name                            |   year | affiliation                                             |   id |   govid | govname                                      | award                                   |
|-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------|
|   0 | Molly Emma Aitken               |   2014 | City University of New York, City College               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   1 | Anna Arabindan-Kesson           |   2017 | Princeton University                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   2 | Roger Ariew                     |   2016 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   3 | Mia L. Bagneris                 |   2017 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   4 | Debby Banham                    |   2016 | University of Cambridge, UK                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   5 | Jeffrey M. Banister             |   2014 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   6 | Martha Bayless                  |   2016 | University of Oregon                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   7 | Alastair James Bellany          |   2012 | Rutgers University-New Brunswick                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   8 | Mario Biagioli                  |   2016 | University of California, Davis                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   9 | Michelle Bigenho                |   2015 | Colgate University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  10 | S. Elizabeth Bird               |   2015 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  11 | Heather Blurton                 |   2013 | University of California, Santa Barbara                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  12 | Manuela Boatcă                  |   2018 | Albert Ludwigs Universität Freiburg, Germany            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  13 | Erik-Jan Bos                    |   2016 | Independent Scholar                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  14 | Daniel Botsman                  |   2018 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  15 | Phillippe Bourgois              |   2013 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  16 | Katherine Brading               |   2017 | University of Notre Dame                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  17 | Elio Brancaforte                |   2018 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  18 | Joseph Bristow                  |   2015 | University of California, Los Angeles                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  19 | Kate Brown                      |   2015 | University of Maryland, Baltimore County                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  20 | Judkin Browning                 |   2013 | Appalachian State University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  21 | Chad C. Bryant                  |   2018 | University of North Carolina at Chapel Hill             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  22 | Allison Busch                   |   2014 | Columbia University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  23 | Rachel Sagner Buurma            |   2012 | Swarthmore College                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  24 | Elisabeth L. Cameron            |   2009 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  25 | Katerina Capkova                |   2018 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  26 | Frances M. Clarke               |   2014 | University of Sydney, Australia                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  27 | Adam Clulow                     |   2018 | Monash University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  28 | Thomas E. Cogswell              |   2012 | University of California, Riverside                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  29 | Clare Haru Crowston             |   2012 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  30 | Catherine D'Ignazio             |   2018 | Emerson College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  31 | Derrick Darby                   |   2015 | University of Michigan-Ann Arbor                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  32 | Alejandro de la Fuente          |   2017 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  33 | Carolyn Dean                    |   2012 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  34 | Lara Deeb                       |   2020 | Scripps College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  35 | Karen Detlefsen                 |   2012 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  36 | Sapana Doshi                    |   2017 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  37 | Jeremy H. Douglass              |   2012 | University of California, San Diego                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  38 | Joshua Dubler                   |   2015 | University of Rochester                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  39 | Diana V. Dumitru                |   2018 | Universitatea Pedagogică de Stat "Ion Creangă", Moldova | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  40 | Marc V. Eagle                   |   2015 | Western Kentucky University                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  41 | George Edmondson                |   2014 | Dartmouth College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  42 | Melodie H. Eichbauer            |   2016 | Florida Gulf Coast University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  43 | Nadia El-Shaarawi               |   2018 | Colby College                                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  44 | Andrés Enrique-Arias            |   2011 | The University of the Balearic Islands                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  45 | Sarah J. Eyerly                 |   2017 | Florida State University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  46 | Judith Farquhar                 |   2012 | University of Chicago                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  47 | David Fedman                    |   2017 | University of California, Irvine                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  48 | Damián Fernández                |   2018 | Northern Illinois University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  49 | Martha Few                      |   2017 | Pennsylvania State University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  50 | Donald A. Filtzer               |   1978 | University of East London                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  51 | Cheryl Finley                   |   2015 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  52 | Abigail A. Firey                |   2016 | University of Kentucky                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  53 | Michael W. Fitzgerald           |   2017 | St. Olaf College                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  54 | Finbarr Flood                   |   2015 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  55 | Beate Fricke                    |   2015 | University of California, Berkeley                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  56 | Peter L. Galison                |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  57 | Stefanos Nikolaou Geroulanos    |   2013 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  58 | Vinay Gidwani                   |   2015 | University of Minnesota, Twin Cities                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  59 | Luis M. Girón-Negrón            |   2011 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  60 | Wendy Z. Goldman                |   2010 | Carnegie Mellon University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  61 | Victoria González-Rivera        |   2017 | San Diego State University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  62 | Susan R. Grayzel                |   2014 | University of Mississippi                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  63 | Ariela J. Gross                 |   2017 | University of Southern California                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  64 | Sarah B.H. Hamill               |   2017 | Sarah Lawrence College                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  65 | Xing Hang                       |   2018 | Brandeis University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  66 | Mona Harb                       |   2009 | American University of Beirut                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  67 | Laurie Hart                     |   2013 | Haverford College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  68 | Penelope M. Harvey              |   2010 | University of Manchester, UK                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  69 | Laura Heffernan                 |   2012 | University of North Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  70 | Christopher G. Hodson           |   2010 | Brigham Young University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  71 | Nick Huggett                    |   2010 | University of Illinois at Chicago                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  72 | Yvonne Ivory                    |   2015 | University of South Carolina                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  73 | Andrew Janiak                   |   2012 | Duke University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  74 | Thupten Jinpa                   |   2009 | McGill University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  75 | Hannah R. Johnson               |   2013 | University of Pittsburgh                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  76 | Jay T. Johnson                  |   2014 | University of Kansas                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  77 | Rebecca Jordan-Young            |   2016 | Barnard College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  78 | Sandra R. Joshel                |   2011 | University of Washington                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  79 | Stefan Jurasinski               |   2014 | The College at Brockport, State University of New York  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  80 | Karen Kampwirth                 |   2017 | Knox College                                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  81 | Steven L. Kaplan                |   2012 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  82 | Cary Karacas                    |   2017 | City University of New York, College of Staten Island   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  83 | Katrina Karkazis                |   2016 | Stanford University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  84 | Kevin C. Karnes                 |   2010 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  85 | Gavin A.J. Kelly                |   2013 | University of Edinburgh                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  86 | Jungwon Kim                     |   2009 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  87 | Sun Joo Kim                     |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  88 | Lauren Klein                    |   2018 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  89 | Eve Krakowski                   |   2014 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
|    | name                     |   year | affiliation                                 |   id |   govid | govname                                      | award                               |
|----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------|
|  0 | Steve F. Anderson        |   2014 | University of Southern California           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  1 | Stephen Berry            |   2017 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  2 | Peter K. Bol             |   2010 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  3 | Alison Booth             |   2013 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  4 | Jesse Casana             |   2016 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  5 | Pramit Chaudhuri         |   2015 | University of Texas at Austin               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  6 | Kimberly Christen        |   2020 | Washington State University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  7 | Daniel J. Cohen          |   2006 | George Mason University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  8 | Ryan Cordell             |   2015 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  9 | Nathan M. Craig          |   2009 | Pennsylvania State University               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 10 | David G. Dickason        |   2009 | Western Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 11 | Elizabeth Maddock Dillon |   2014 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 12 | Gregory Downs            |   2013 | City University of New York, City College   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 13 | S. Max Edelson           |   2010 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 14 | Margot E. Fassler        |   2012 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 15 | Abigail A. Firey         |   2016 | University of Kentucky                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 16 | Mary Flanagan            |   2010 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 17 | John M. Flower           |   2007 | University of North Carolina at Charlotte   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 18 | Richard Freedman         |   2020 | Haverford College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 19 | Kim T. Gallon            |   2015 | Purdue University                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 20 | Edward John Garrett      |   2006 | Eastern Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 21 | Aaron Glass              |   2020 | Bard Graduate Center                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 22 | Margaret Rich Greer      |   2009 | Duke University                             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 23 | Meghan Howey             |   2014 | University of New Hampshire                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 24 | Eric Kansa               |   2012 | The Alexandria Archive Institute            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 25 | Caren Kaplan             |   2006 | University of California, Davis             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 26 | Peter J. Kastor          |   2012 | Washington University in St. Louis          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 27 | William A. Kretzschmar   |   2013 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 28 | Massimo Lollini          |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 29 | Marit J. MacArthur       |   2015 | California State University, Bakersfield    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 30 | Anne MacNeil             |   2014 | University of North Carolina at Chapel Hill | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 31 | Ruth A. Mostern          |   2011 | University of California, Merced            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 32 | Natalie M. Phillips      |   2015 | Michigan State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 33 | Eric E. Poehler          |   2013 | University of Massachusetts Amherst         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 34 | Todd Samuel Presner      |   2006 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 35 | Kenneth M. Price         |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 36 | F. Jamil Ragep           |   2006 | University of Oklahoma                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 37 | K.J. Rawson              |   2017 | College of the Holy Cross                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 38 | Dwight F. Reynolds       |   2008 | University of California, Santa Barbara     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 39 | Massimo Riva             |   2011 | Brown University                            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 40 | Jesse Rodin              |   2017 | Stanford University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 41 | Anne Sarah Rubin         |   2007 | University of Maryland, Baltimore County    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 42 | Warren Sack              |   2012 | University of California, Santa Cruz        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 43 | Philip Sapirstein        |   2010 | University of Pennsylvania                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 44 | Patricia Seed            |   2007 | University of California, Irvine            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 45 | Andrew Sluyter           |   2012 | Louisiana State University                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 46 | Daniel L. Smail          |   2015 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 47 | M. Alison Stones         |   2008 | University of Pittsburgh                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 48 | Elaine A. Sullivan       |   2012 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 49 | Nicolas Tackett          |   2018 | University of California, Berkeley          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 50 | Timothy R. Tangherlini   |   2009 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 51 | Diana Taylor             |   2013 | New York University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 52 | William G. Thomas        |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 53 | James T. Tice            |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 54 | Daniel Trueman           |   2015 | Princeton University                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 55 | Yuri Tsivian             |   2007 | University of Chicago                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 56 | Ted Underwood            |   2013 | University of Illinois at Urbana-Champaign  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 57 | Cynthia M. Vakareliyska  |   1987 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 58 | Susan L. Wiesner         |   2011 | Kennesaw State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 59 | Matthew Wilkens          |   2014 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
AwardID 3000: 60 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3000.csv
✅ Finished scrape3000
🔎 Found scraper for ID 3001: ACLS Collaborative Research Fellowships

Scraping pages: 100%|██████████| 7/7 [01:01<00:00,  8.73s/page]

+-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------+
|     | name                            |   year | affiliation                                             |   id |   govid | govname                                      | award                                   |
|-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------|
|   0 | Molly Emma Aitken               |   2014 | City University of New York, City College               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   1 | Anna Arabindan-Kesson           |   2017 | Princeton University                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   2 | Roger Ariew                     |   2016 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   3 | Mia L. Bagneris                 |   2017 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   4 | Debby Banham                    |   2016 | University of Cambridge, UK                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   5 | Jeffrey M. Banister             |   2014 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   6 | Martha Bayless                  |   2016 | University of Oregon                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   7 | Alastair James Bellany          |   2012 | Rutgers University-New Brunswick                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   8 | Mario Biagioli                  |   2016 | University of California, Davis                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   9 | Michelle Bigenho                |   2015 | Colgate University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  10 | S. Elizabeth Bird               |   2015 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  11 | Heather Blurton                 |   2013 | University of California, Santa Barbara                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  12 | Manuela Boatcă                  |   2018 | Albert Ludwigs Universität Freiburg, Germany            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  13 | Erik-Jan Bos                    |   2016 | Independent Scholar                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  14 | Daniel Botsman                  |   2018 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  15 | Phillippe Bourgois              |   2013 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  16 | Katherine Brading               |   2017 | University of Notre Dame                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  17 | Elio Brancaforte                |   2018 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  18 | Joseph Bristow                  |   2015 | University of California, Los Angeles                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  19 | Kate Brown                      |   2015 | University of Maryland, Baltimore County                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  20 | Judkin Browning                 |   2013 | Appalachian State University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  21 | Chad C. Bryant                  |   2018 | University of North Carolina at Chapel Hill             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  22 | Allison Busch                   |   2014 | Columbia University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  23 | Rachel Sagner Buurma            |   2012 | Swarthmore College                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  24 | Elisabeth L. Cameron            |   2009 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  25 | Katerina Capkova                |   2018 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  26 | Frances M. Clarke               |   2014 | University of Sydney, Australia                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  27 | Adam Clulow                     |   2018 | Monash University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  28 | Thomas E. Cogswell              |   2012 | University of California, Riverside                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  29 | Clare Haru Crowston             |   2012 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  30 | Catherine D'Ignazio             |   2018 | Emerson College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  31 | Derrick Darby                   |   2015 | University of Michigan-Ann Arbor                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  32 | Alejandro de la Fuente          |   2017 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  33 | Carolyn Dean                    |   2012 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  34 | Lara Deeb                       |   2020 | Scripps College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  35 | Karen Detlefsen                 |   2012 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  36 | Sapana Doshi                    |   2017 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  37 | Jeremy H. Douglass              |   2012 | University of California, San Diego                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  38 | Joshua Dubler                   |   2015 | University of Rochester                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  39 | Diana V. Dumitru                |   2018 | Universitatea Pedagogică de Stat "Ion Creangă", Moldova | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  40 | Marc V. Eagle                   |   2015 | Western Kentucky University                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  41 | George Edmondson                |   2014 | Dartmouth College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  42 | Melodie H. Eichbauer            |   2016 | Florida Gulf Coast University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  43 | Nadia El-Shaarawi               |   2018 | Colby College                                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  44 | Andrés Enrique-Arias            |   2011 | The University of the Balearic Islands                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  45 | Sarah J. Eyerly                 |   2017 | Florida State University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  46 | Judith Farquhar                 |   2012 | University of Chicago                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  47 | David Fedman                    |   2017 | University of California, Irvine                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  48 | Damián Fernández                |   2018 | Northern Illinois University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  49 | Martha Few                      |   2017 | Pennsylvania State University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  50 | Donald A. Filtzer               |   1978 | University of East London                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  51 | Cheryl Finley                   |   2015 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  52 | Abigail A. Firey                |   2016 | University of Kentucky                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  53 | Michael W. Fitzgerald           |   2017 | St. Olaf College                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  54 | Finbarr Flood                   |   2015 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  55 | Beate Fricke                    |   2015 | University of California, Berkeley                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  56 | Peter L. Galison                |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  57 | Stefanos Nikolaou Geroulanos    |   2013 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  58 | Vinay Gidwani                   |   2015 | University of Minnesota, Twin Cities                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  59 | Luis M. Girón-Negrón            |   2011 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  60 | Wendy Z. Goldman                |   2010 | Carnegie Mellon University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  61 | Victoria González-Rivera        |   2017 | San Diego State University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  62 | Susan R. Grayzel                |   2014 | University of Mississippi                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  63 | Ariela J. Gross                 |   2017 | University of Southern California                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  64 | Sarah B.H. Hamill               |   2017 | Sarah Lawrence College                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  65 | Xing Hang                       |   2018 | Brandeis University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  66 | Mona Harb                       |   2009 | American University of Beirut                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  67 | Laurie Hart                     |   2013 | Haverford College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  68 | Penelope M. Harvey              |   2010 | University of Manchester, UK                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  69 | Laura Heffernan                 |   2012 | University of North Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  70 | Christopher G. Hodson           |   2010 | Brigham Young University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  71 | Nick Huggett                    |   2010 | University of Illinois at Chicago                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  72 | Yvonne Ivory                    |   2015 | University of South Carolina                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  73 | Andrew Janiak                   |   2012 | Duke University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  74 | Thupten Jinpa                   |   2009 | McGill University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  75 | Hannah R. Johnson               |   2013 | University of Pittsburgh                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  76 | Jay T. Johnson                  |   2014 | University of Kansas                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  77 | Rebecca Jordan-Young            |   2016 | Barnard College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  78 | Sandra R. Joshel                |   2011 | University of Washington                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  79 | Stefan Jurasinski               |   2014 | The College at Brockport, State University of New York  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  80 | Karen Kampwirth                 |   2017 | Knox College                                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  81 | Steven L. Kaplan                |   2012 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  82 | Cary Karacas                    |   2017 | City University of New York, College of Staten Island   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  83 | Katrina Karkazis                |   2016 | Stanford University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  84 | Kevin C. Karnes                 |   2010 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  85 | Gavin A.J. Kelly                |   2013 | University of Edinburgh                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  86 | Jungwon Kim                     |   2009 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  87 | Sun Joo Kim                     |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  88 | Lauren Klein                    |   2018 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  89 | Eve Krakowski                   |   2014 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |

Scraping pages: 100%|██████████| 3/3 [00:23<00:00,  8.00s/page]

📋 Running 6 selected scrapers: ['479', '3007', '8258', '3000', '3001', '3011']
🔎 Found scraper for ID 479: ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)

Scraping pages: 100%|██████████| 182/182 [29:26<00:00,  9.71s/page]

,id,govid,govname,award,name,year,affiliation
0,Hans Aarsleff,1964,Princeton University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
1,Richard O. Abel,1985,Drake University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
2,Natalie Abell,2018,University of Michigan-Ann Arbor,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
3,Anna Maria Abernathy,1953,Radcliffe College,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4,Rachel Ablow,2012,"University at Buffalo, State University of New...",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
...,...,...,...,...,...,...,...
4142,Brook A. Ziporyn,2005,Northwestern University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4143,Vera L. Zolberg,1995,The New School,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4144,Charles H. P. Zuckerman,2022,"University of Sydney, Australia",479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4145,Rachel Elizabeth Zuckert,2003,Rice University,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...
4146,Arnulf Zweig,1953,University of Oregon,479,54,American Council of Learned Societies (ACLS),ACLS Fellows (ACLS/SSRC/NEH International and ...

AwardID 479: 4147 records across 182 pages saved to E:\Ace\Awards Scrape\Results v4\479.csv
✅ Finished scrape479
🔎 Found scraper for ID 3007: Andrew W Mellon/ACLS Dissertation Completion Fellowships

Scraping pages: 100%|██████████| 44/44 [06:43<00:00,  9.18s/page]

,id,govid,govname,award,name,year,affiliation
0,Arash Abazari,2015,Johns Hopkins University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1,Celia Abele,2019,Columbia University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
2,Jennifer Ann Adair,2011,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
3,Begum Adalet,2013,University of Pennsylvania,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
4,Marcus P. Adams,2020,"University at Albany, State University of New ...",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
...,...,...,...,...,...,...,...
1040,Tyler Zoanni,2018,New York University,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1041,Anna Zogas,2015,University of Washington,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1042,Leonora Zoninsein,2021,"University of California, Berkeley",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1043,Iskandar Zulkarnain,2014,University of Rochester,3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...
1044,Ran Zwigenberg,2011,"City University of New York, The Graduate Center",3007,54,American Council of Learned Societies (ACLS),Andrew W Mellon/ACLS Dissertation Completion F...

AwardID 3007: 1045 records across 44 pages saved to E:\Ace\Awards Scrape\Results v4\3007.csv
✅ Finished scrape3007
🔎 Found scraper for ID 8258: Mellon/ACLS Public Fellows

Scraping pages: 100%|██████████| 8/8 [01:11<00:00,  8.95s/page]

+-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------+
|     | name                         |   year | affiliation                                                    |   id |   govid | govname                                      | award                      |
|-----+------------------------------+--------+----------------------------------------------------------------+------+---------+----------------------------------------------+----------------------------|
|   0 | Franky Abbott                |   2013 | Digital Public Library of America                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   1 | Aixa M. Aleman-Diaz          |   2020 | Washington Center for Equitable Growth                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   2 | Michael James Alijewicz      |   2017 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   3 | Richard Anderson             |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   4 | Sean K. Andrews              |   2011 | National Institute for Technology in Liberal Education (NITLE) | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   5 | Anna J. Armentrout           |   2013 | International Student Exchange Programs                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   6 | Loy L. Azalia                |   2020 | Children's Defense Fund                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   7 | Deborah J. Bailin            |   2012 | Union of Concerned Scientists                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   8 | John Carl Baker              |   2016 | Ploughshares Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|   9 | Mariam Banahi                |   2020 | Refugees International                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  10 | Christopher A. Barthel       |   2013 | Center for Jewish History                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  11 | Elizabeth Sarah Berkowitz    |   2018 | Rockefeller Archive Center                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  12 | Johanna Best                 |   2016 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  13 | Jessica Bird                 |   2019 | Center for Justice Innovation                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  14 | James J. A. Blair            |   2017 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  15 | Erin D. Boon                 |   2016 | The Texas Tribune                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  16 | Ashley E. Bowen              |   2018 | Science History Institute                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  17 | Aleia M. Brown               |   2017 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  18 | Bathsheba F. Bryant-Tarpeh   |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  19 | Alison Denise Brzenchek      |   2017 | Free Press                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  20 | Emily Button Kambic          |   2016 | National Park Service                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  21 | Kathryn Cai                  |   2020 | PowerSwitch Action                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  22 | Jessica Ann Carey-Webb       |   2019 | Natural Resources Defense Council                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  23 | Jane Greenway Carr           |   2014 | New America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  24 | Barbara Ceptus Schreiber     |   2011 | Council on Foundations                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  25 | Christa D. Cesario           |   2017 | Yerba Buena Center for the Arts                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  26 | Huibin A. Chew               |   2018 | PolicyLink                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  27 | Alyson Clary                 |   2019 | American Public Media                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  28 | Jaime Shearn Coan            |   2020 | One Institute                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  29 | Jennifer E. Cossyleon        |   2019 | Community Change                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  30 | Valeria Dani                 |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  31 | Anh Thang Dao-Shah           |   2014 | San Francisco Arts Commission                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  32 | Elandre Dedrick              |   2019 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  33 | Elizabeth Della Zazzera      |   2018 | Lapham's Quarterly                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  34 | Elizabeth H. DeYoung         |   2019 | Reinvestment Fund                                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  35 | Amelia J. Dietrich           |   2015 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  36 | Megan K. Doherty             |   2012 | German Marshall Fund of the US                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  37 | Andrew Donnelly              |   2020 | National Book Foundation                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  38 | Edith Doron                  |   2015 | Carnegie Museums of Pittsburgh                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  39 | Emily Dufton                 |   2014 | Center for Public Integrity                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  40 | Sara Duvisac                 |   2020 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  41 | Carolyn Eisert               |   2013 | Amnesty International                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  42 | Indra Ekmanis                |   2018 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  43 | Craig Eley                   |   2014 | Wisconsin Public Radio                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  44 | Pamela I. Epstein            |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  45 | Raquel Escobar               |   2020 | Humanities Action Lab                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  46 | Erin Evans-Walker            |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  47 | Timothy Philip Fadgen        |   2014 | American Refugee Committee                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  48 | Maria Faini                  |   2018 | Race Forward                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  49 | Rebecca L. Fall              |   2017 | The Public Theater                                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  50 | Kristen M. Fallica           |   2016 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  51 | Victoria R. Farmer           |   2015 | PRX                                                            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  52 | Rachel Feinmark              |   2015 | Tenement Museum                                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  53 | Lisa D. Feldkamp             |   2013 | The Nature Conservancy                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  54 | Anne Flannery                |   2012 | The Newberry                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  55 | Megan French-Marcelin        |   2015 | American Civil Liberties Union                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  56 | Elizabeth Frohlich           |   2012 | Forum on Education Abroad                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  57 | Vittorio N. Galasso          |   2012 | Oxfam America                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  58 | Annie Galvin                 |   2019 | Public Books                                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  59 | Cecily R. Garber             |   2014 | Council of Independent Colleges                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  60 | Robin M. Garcia              |   2022 | University of Virginia                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  61 | Nilofar Gardezi              |   2015 | Bay Area Video Coalition                                       | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  62 | Nicole Marie Gervasio        |   2019 | PEN America                                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  63 | Jeanette Goddard             |   2013 | Chicago Humanities Festival                                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  64 | Sara S. Goek                 |   2017 | Association of College & Research Libraries                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  65 | Barry Goldberg               |   2020 | Partnership for Public Service                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  66 | Carly Goodman                |   2016 | American Friends Service Committee                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  67 | Lindsay N. Green-Barber      |   2013 | Center for Investigative Reporting                             | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  68 | Joseph Haley                 |   2019 | World Justice Project                                          | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  69 | Molly O'Hagan Hardy          |   2013 | American Antiquarian Society                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  70 | Caroline Harper              |   2014 | United Negro College Fund                                      | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  71 | Rebecca Hewett               |   2011 | New York City Department of Cultural Affairs                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  72 | Lauren Leigh Hinthorne       |   2013 | US Department of State                                         | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  73 | Kristen N. Hodge-Clark       |   2011 | Association of American Universities                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  74 | Franz D. Hofer               |   2015 | Vienna Museum                                                  | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  75 | Umi Hsu                      |   2013 | Los Angeles Department of Cultural Affairs                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  76 | Stephanie Catanese Iasiello  |   2020 | Alliance for Higher Education in Prison                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  77 | Nicole Ivy                   |   2015 | American Alliance of Museums                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  78 | Korey Jackson                |   2012 | Council on Library and Information Resources (CLIR)            | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  79 | Antonnet Johnson             |   2018 | Participatory Budgeting Project                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  80 | Katelyn Christine Jones      |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  81 | Jane Joann Jones             |   2013 | BronxWorks                                                     | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  82 | Nandi Dill Jordan            |   2016 | Los Angeles County Museum of Art                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  83 | Emily Kane                   |   2013 | Center for Global Education, Hobart and William Smith Colleges | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  84 | Nana Kaneko                  |   2018 | Smithsonian Institution                                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  85 | Rebecca Kaplan               |   2016 | The Pulitzer Center on Crisis Reporting                        | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  86 | Madhuri Karak                |   2019 | Rare                                                           | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  87 | Catherine Lena Kelly         |   2015 | American Bar Association Rule of Law Initiative                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  88 | Samuel Kling                 |   2018 | Chicago Council on Global Affairs                              | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  89 | Margarita Kompelmakher       |   2019 | Alliance Theatre                                               | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  90 | Jessica Koski                |   2018 | Stockholm Environment Institute - US Center                    | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  91 | Margaret H. Kunde            |   2013 | North Carolina General Assembly                                | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  92 | Molly Laas                   |   2019 | Data & Society                                                 | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |
|  93 | Lara R. Langer               |   2019 | Harriet Beecher Stowe Center                                   | 8258 |      54 | American Council of Learned Societies (ACLS) | Mellon/ACLS Public Fellows |

Scraping pages: 100%|██████████| 3/3 [00:19<00:00,  6.44s/page]

+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
|    | name                     |   year | affiliation                                 |   id |   govid | govname                                      | award                               |
|----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------|
|  0 | Steve F. Anderson        |   2014 | University of Southern California           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  1 | Stephen Berry            |   2017 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  2 | Peter K. Bol             |   2010 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  3 | Alison Booth             |   2013 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  4 | Jesse Casana             |   2016 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  5 | Pramit Chaudhuri         |   2015 | University of Texas at Austin               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  6 | Kimberly Christen        |   2020 | Washington State University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  7 | Daniel J. Cohen          |   2006 | George Mason University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  8 | Ryan Cordell             |   2015 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
|  9 | Nathan M. Craig          |   2009 | Pennsylvania State University               | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 10 | David G. Dickason        |   2009 | Western Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 11 | Elizabeth Maddock Dillon |   2014 | Northeastern University                     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 12 | Gregory Downs            |   2013 | City University of New York, City College   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 13 | S. Max Edelson           |   2010 | University of Virginia                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 14 | Margot E. Fassler        |   2012 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 15 | Abigail A. Firey         |   2016 | University of Kentucky                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 16 | Mary Flanagan            |   2010 | Dartmouth College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 17 | John M. Flower           |   2007 | University of North Carolina at Charlotte   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 18 | Richard Freedman         |   2020 | Haverford College                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 19 | Kim T. Gallon            |   2015 | Purdue University                           | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 20 | Edward John Garrett      |   2006 | Eastern Michigan University                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 21 | Aaron Glass              |   2020 | Bard Graduate Center                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 22 | Margaret Rich Greer      |   2009 | Duke University                             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 23 | Meghan Howey             |   2014 | University of New Hampshire                 | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 24 | Eric Kansa               |   2012 | The Alexandria Archive Institute            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 25 | Caren Kaplan             |   2006 | University of California, Davis             | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 26 | Peter J. Kastor          |   2012 | Washington University in St. Louis          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 27 | William A. Kretzschmar   |   2013 | University of Georgia                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 28 | Massimo Lollini          |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 29 | Marit J. MacArthur       |   2015 | California State University, Bakersfield    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 30 | Anne MacNeil             |   2014 | University of North Carolina at Chapel Hill | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 31 | Ruth A. Mostern          |   2011 | University of California, Merced            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 32 | Natalie M. Phillips      |   2015 | Michigan State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 33 | Eric E. Poehler          |   2013 | University of Massachusetts Amherst         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 34 | Todd Samuel Presner      |   2006 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 35 | Kenneth M. Price         |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 36 | F. Jamil Ragep           |   2006 | University of Oklahoma                      | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 37 | K.J. Rawson              |   2017 | College of the Holy Cross                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 38 | Dwight F. Reynolds       |   2008 | University of California, Santa Barbara     | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 39 | Massimo Riva             |   2011 | Brown University                            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 40 | Jesse Rodin              |   2017 | Stanford University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 41 | Anne Sarah Rubin         |   2007 | University of Maryland, Baltimore County    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 42 | Warren Sack              |   2012 | University of California, Santa Cruz        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 43 | Philip Sapirstein        |   2010 | University of Pennsylvania                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 44 | Patricia Seed            |   2007 | University of California, Irvine            | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 45 | Andrew Sluyter           |   2012 | Louisiana State University                  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 46 | Daniel L. Smail          |   2015 | Harvard University                          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 47 | M. Alison Stones         |   2008 | University of Pittsburgh                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 48 | Elaine A. Sullivan       |   2012 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 49 | Nicolas Tackett          |   2018 | University of California, Berkeley          | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 50 | Timothy R. Tangherlini   |   2009 | University of California, Los Angeles       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 51 | Diana Taylor             |   2013 | New York University                         | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 52 | William G. Thomas        |   2019 | University of Nebraska-Lincoln              | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 53 | James T. Tice            |   2012 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 54 | Daniel Trueman           |   2015 | Princeton University                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 55 | Yuri Tsivian             |   2007 | University of Chicago                       | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 56 | Ted Underwood            |   2013 | University of Illinois at Urbana-Champaign  | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 57 | Cynthia M. Vakareliyska  |   1987 | University of Oregon                        | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 58 | Susan L. Wiesner         |   2011 | Kennesaw State University                   | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
| 59 | Matthew Wilkens          |   2014 | University of Notre Dame                    | 3000 |      54 | American Council of Learned Societies (ACLS) | ACLS Digital Innovation Fellowships |
+----+--------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------+
AwardID 3000: 60 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3000.csv
✅ Finished scrape3000
🔎 Found scraper for ID 3001: ACLS Collaborative Research Fellowships

Scraping pages: 100%|██████████| 7/7 [01:01<00:00,  8.73s/page]

+-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------+
|     | name                            |   year | affiliation                                             |   id |   govid | govname                                      | award                                   |
|-----+---------------------------------+--------+---------------------------------------------------------+------+---------+----------------------------------------------+-----------------------------------------|
|   0 | Molly Emma Aitken               |   2014 | City University of New York, City College               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   1 | Anna Arabindan-Kesson           |   2017 | Princeton University                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   2 | Roger Ariew                     |   2016 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   3 | Mia L. Bagneris                 |   2017 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   4 | Debby Banham                    |   2016 | University of Cambridge, UK                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   5 | Jeffrey M. Banister             |   2014 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   6 | Martha Bayless                  |   2016 | University of Oregon                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   7 | Alastair James Bellany          |   2012 | Rutgers University-New Brunswick                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   8 | Mario Biagioli                  |   2016 | University of California, Davis                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|   9 | Michelle Bigenho                |   2015 | Colgate University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  10 | S. Elizabeth Bird               |   2015 | University of South Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  11 | Heather Blurton                 |   2013 | University of California, Santa Barbara                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  12 | Manuela Boatcă                  |   2018 | Albert Ludwigs Universität Freiburg, Germany            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  13 | Erik-Jan Bos                    |   2016 | Independent Scholar                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  14 | Daniel Botsman                  |   2018 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  15 | Phillippe Bourgois              |   2013 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  16 | Katherine Brading               |   2017 | University of Notre Dame                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  17 | Elio Brancaforte                |   2018 | Tulane University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  18 | Joseph Bristow                  |   2015 | University of California, Los Angeles                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  19 | Kate Brown                      |   2015 | University of Maryland, Baltimore County                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  20 | Judkin Browning                 |   2013 | Appalachian State University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  21 | Chad C. Bryant                  |   2018 | University of North Carolina at Chapel Hill             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  22 | Allison Busch                   |   2014 | Columbia University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  23 | Rachel Sagner Buurma            |   2012 | Swarthmore College                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  24 | Elisabeth L. Cameron            |   2009 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  25 | Katerina Capkova                |   2018 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  26 | Frances M. Clarke               |   2014 | University of Sydney, Australia                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  27 | Adam Clulow                     |   2018 | Monash University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  28 | Thomas E. Cogswell              |   2012 | University of California, Riverside                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  29 | Clare Haru Crowston             |   2012 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  30 | Catherine D'Ignazio             |   2018 | Emerson College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  31 | Derrick Darby                   |   2015 | University of Michigan-Ann Arbor                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  32 | Alejandro de la Fuente          |   2017 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  33 | Carolyn Dean                    |   2012 | University of California, Santa Cruz                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  34 | Lara Deeb                       |   2020 | Scripps College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  35 | Karen Detlefsen                 |   2012 | University of Pennsylvania                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  36 | Sapana Doshi                    |   2017 | University of Arizona                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  37 | Jeremy H. Douglass              |   2012 | University of California, San Diego                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  38 | Joshua Dubler                   |   2015 | University of Rochester                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  39 | Diana V. Dumitru                |   2018 | Universitatea Pedagogică de Stat "Ion Creangă", Moldova | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  40 | Marc V. Eagle                   |   2015 | Western Kentucky University                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  41 | George Edmondson                |   2014 | Dartmouth College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  42 | Melodie H. Eichbauer            |   2016 | Florida Gulf Coast University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  43 | Nadia El-Shaarawi               |   2018 | Colby College                                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  44 | Andrés Enrique-Arias            |   2011 | The University of the Balearic Islands                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  45 | Sarah J. Eyerly                 |   2017 | Florida State University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  46 | Judith Farquhar                 |   2012 | University of Chicago                                   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  47 | David Fedman                    |   2017 | University of California, Irvine                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  48 | Damián Fernández                |   2018 | Northern Illinois University                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  49 | Martha Few                      |   2017 | Pennsylvania State University                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  50 | Donald A. Filtzer               |   1978 | University of East London                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  51 | Cheryl Finley                   |   2015 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  52 | Abigail A. Firey                |   2016 | University of Kentucky                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  53 | Michael W. Fitzgerald           |   2017 | St. Olaf College                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  54 | Finbarr Flood                   |   2015 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  55 | Beate Fricke                    |   2015 | University of California, Berkeley                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  56 | Peter L. Galison                |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  57 | Stefanos Nikolaou Geroulanos    |   2013 | New York University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  58 | Vinay Gidwani                   |   2015 | University of Minnesota, Twin Cities                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  59 | Luis M. Girón-Negrón            |   2011 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  60 | Wendy Z. Goldman                |   2010 | Carnegie Mellon University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  61 | Victoria González-Rivera        |   2017 | San Diego State University                              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  62 | Susan R. Grayzel                |   2014 | University of Mississippi                               | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  63 | Ariela J. Gross                 |   2017 | University of Southern California                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  64 | Sarah B.H. Hamill               |   2017 | Sarah Lawrence College                                  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  65 | Xing Hang                       |   2018 | Brandeis University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  66 | Mona Harb                       |   2009 | American University of Beirut                           | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  67 | Laurie Hart                     |   2013 | Haverford College                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  68 | Penelope M. Harvey              |   2010 | University of Manchester, UK                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  69 | Laura Heffernan                 |   2012 | University of North Florida                             | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  70 | Christopher G. Hodson           |   2010 | Brigham Young University                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  71 | Nick Huggett                    |   2010 | University of Illinois at Chicago                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  72 | Yvonne Ivory                    |   2015 | University of South Carolina                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  73 | Andrew Janiak                   |   2012 | Duke University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  74 | Thupten Jinpa                   |   2009 | McGill University                                       | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  75 | Hannah R. Johnson               |   2013 | University of Pittsburgh                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  76 | Jay T. Johnson                  |   2014 | University of Kansas                                    | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  77 | Rebecca Jordan-Young            |   2016 | Barnard College                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  78 | Sandra R. Joshel                |   2011 | University of Washington                                | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  79 | Stefan Jurasinski               |   2014 | The College at Brockport, State University of New York  | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  80 | Karen Kampwirth                 |   2017 | Knox College                                            | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  81 | Steven L. Kaplan                |   2012 | Cornell University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  82 | Cary Karacas                    |   2017 | City University of New York, College of Staten Island   | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  83 | Katrina Karkazis                |   2016 | Stanford University                                     | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  84 | Kevin C. Karnes                 |   2010 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  85 | Gavin A.J. Kelly                |   2013 | University of Edinburgh                                 | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  86 | Jungwon Kim                     |   2009 | University of Illinois at Urbana-Champaign              | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  87 | Sun Joo Kim                     |   2009 | Harvard University                                      | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  88 | Lauren Klein                    |   2018 | Emory University                                        | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |
|  89 | Eve Krakowski                   |   2014 | Yale University                                         | 3001 |      54 | American Council of Learned Societies (ACLS) | ACLS Collaborative Research Fellowships |

Scraping pages: 100%|██████████| 3/3 [00:23<00:00,  8.00s/page]

+----+--------------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------------------------------+
|    | name                           |   year | affiliation                                 |   id |   govid | govname                                      | award                                                       |
|----+--------------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------------------------------|
|  0 | Angelica Jimena Afanador Pujol |   2008 | University of California, Los Angeles       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  1 | Nosheen Ali                    |   2009 | Cornell University                          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  2 | Richard Patrick Anderson       |   2010 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  3 | Yuen Yuen Ang                  |   2009 | Stanford University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  4 | Jonathan Shapiro Anjaria       |   2019 | Brandeis University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  5 | Jelena Batinic                 |   2009 | Stanford University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  6 | Lucas Bessire                  |   2010 | New York University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  7 | Claudia L. Brittenham          |   2008 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  8 | Melissa K. Byrnes              |   2008 | Georgetown University                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
|  9 | Sarah Isabel Cameron           |   2010 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 10 | Kushanava Choudhury            |   2008 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 11 | Adam Clulow                    |   2018 | Monash University                           | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 12 | Alex Csiszar                   |   2010 | Harvard University                          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 13 | Alex S. Cummings               |   2009 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 14 | Sarah Zukerman Daly            |   2010 | Massachusetts Institute of Technology       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 15 | Valeria De Lucca               |   2008 | Princeton University                        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 16 | Erin Katherine Debenport       |   2009 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 17 | Meghan C. Doherty              |   2010 | University of Wisconsin-Madison             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 18 | Ahmed El Shamsy                |   2009 | Harvard University                          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 19 | Jesse Ferris                   |   2008 | Princeton University                        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 20 | Gregg Gardner                  |   2009 | Princeton University                        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 21 | Pablo F. Gómez                 |   2009 | Vanderbilt University                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 22 | Rob Harper                     |   2007 | University of Wisconsin-Madison             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 23 | Chriscinda Claire Henry        |   2009 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 24 | Andrew Robert Highsmith        |   2009 | University of Michigan-Ann Arbor            | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 25 | Karen L. Hiles                 |   2009 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 26 | Michael Gibbs Hill             |   2016 | University of South Carolina                | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 27 | Faith C. Hillis                |   2009 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 28 | Katie Hornstein                |   2018 | Dartmouth College                           | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 29 | Carmen Alvaro Jarrin           |   2010 | Duke University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 30 | Ryan Tucker Jones              |   2008 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 31 | Andrew W. Kahrl                |   2012 | Marquette University                        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 32 | Ozan Karaman                   |   2010 | University of Minnesota, Twin Cities        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 33 | Emily Alice Katz               |   2008 | Jewish Theological Seminary of America      | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 34 | Melissa R. Kerin               |   2014 | Washington and Lee University               | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 35 | David Matthew Klotz            |   2008 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 36 | Jeffrey Todd Knight            |   2008 | Northwestern University                     | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 37 | Julilly Kohler-Hausmann        |   2010 | University of Illinois at Urbana-Champaign  | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 38 | James Krapfl                   |   2005 | University of California, Berkeley          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 39 | Jonathan Levy                  |   2008 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 40 | Valeria Manzano                |   2010 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 41 | Kathryn Merkel-Hess            |   2009 | University of California, Irvine            | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 42 | Sara J. Milstein               |   2009 | Rutgers University-New Brunswick            | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 43 | Tatiana Nikitina               |   2008 | Stanford University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 44 | Hisyar Ozsoy                   |   2009 | University of Texas at Austin               | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 45 | Emily J. Pawley                |   2009 | University of Pennsylvania                  | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 46 | Monica M. Penick               |   2008 | University of Texas at Austin               | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 47 | Natalie M. Phillips            |   2015 | Michigan State University                   | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 48 | Elizabeth J. Pillsbury         |   2009 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 49 | Peter Polak-Springer           |   2010 | Rutgers University-New Brunswick            | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 50 | Chitra Ramalingam              |   2009 | Harvard University                          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 51 | Johanna Sirera Ransmeier       |   2008 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 52 | Jacob Aaron Carliner Remes     |   2010 | Duke University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 53 | Laura C. Robson                |   2009 | Yale University                             | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 54 | Caroline Emily Shaw            |   2010 | University of California, Berkeley          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 55 | Lihong Shi                     |   2008 | Washington University in St. Louis          | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 56 | Tes Slominski                  |   2010 | New York University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 57 | Anton Braxton Soderman         |   2010 | Brown University                            | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 58 | Noah H. Thomas                 |   2008 | University of Arizona                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 59 | Elizabeth S. Todd-Breland      |   2010 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 60 | Neal A. Tognazzini             |   2009 | University of California, Riverside         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 61 | Julie A. Turnock               |   2008 | University of Chicago                       | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 62 | Theresa Marie Ventura          |   2007 | Columbia University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 63 | Moulie Vidas                   |   2009 | Princeton University                        | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 64 | Janelle Werner                 |   2008 | University of North Carolina at Chapel Hill | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 65 | Johanna Elisabeth Wolff        |   2010 | Stanford University                         | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
| 66 | Chad D. Wriglesworth           |   2010 | The University of Iowa                      | 3011 |      54 | American Council of Learned Societies (ACLS) | Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships |
+----+--------------------------------+--------+---------------------------------------------+------+---------+----------------------------------------------+-------------------------------------------------------------+
AwardID 3011: 67 records across 3 pages saved to E:\Ace\Awards Scrape\Results v4\3011.csv
✅ Finished scrape3011

✅ Selected scrapers run complete!

## Individual Award Scrape Codes

### List A

In [228]:
def scrape1809():
    aid = "1809"
    FAILED_URLS = []
    SESSION = requests.Session()
    HEADERS = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        )
    }
    NAME_RX = re.compile(r"\s+")

    def wait_for_links(driver, timeout=10, min_count=80):
        start = time.time()
        while time.time() - start < timeout:
            elems = driver.find_elements(
                By.CSS_SELECTOR,
                "a[data-modalfellow-target][data-modalfellow-fellow]"
            )
            if len(elems) >= min_count:
                return elems
            time.sleep(0.25)
        return elems

    def collect_links(max_pages=200, delay=0.5, headless=True):
        base_url = "https://www.gf.org/fellows?page="
        chrome_opts = Options()
        if headless:
            chrome_opts.add_argument("--headless=new")
        chrome_opts.add_argument("--no-sandbox")
        chrome_opts.add_argument("--disable-dev-shm-usage")
        chrome_opts.add_argument("--window-size=1920,1080")

        driver1 = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), 
            options=chrome_opts
        )
        seen = set()
        retry_pages = []

        def scrape_page(driver, page):
            driver.get(f"{base_url}{page}")
            time.sleep(delay)
            if page == 1:
                try:
                    driver.find_element(
                        By.CSS_SELECTOR, 
                        "button.cky-btn-reject"
                    ).click()
                    time.sleep(0.5)
                except:
                    pass
            driver.execute_script(
                "window.scrollTo(0, document.body.scrollHeight);"
            )
            time.sleep(0.75)
            links = wait_for_links(driver, timeout=10, min_count=80)
            new_links = 0
            for a in links:
                url = a.get_attribute("data-modalfellow-target")
                if url and url not in seen:
                    seen.add(url)
                    new_links += 1
            print(
                f"Page {page:>3}: Found {len(links):>3} links "
                f"({new_links} new), total unique: {len(seen)}"
            )
            return new_links

        try:
            for page in range(1, max_pages + 1):
                new = scrape_page(driver1, page)
                if new == 0:
                    retry_pages.append(page)
        finally:
            driver1.quit()

        if retry_pages:
            print(
                f"\n🔁 Retrying {len(retry_pages)} pages "
                "with 0 new links...\n"
            )
            driver2 = webdriver.Chrome(
                service=Service(ChromeDriverManager().install()), 
                options=chrome_opts
            )
            try:
                for page in retry_pages:
                    new = scrape_page(driver2, page)
                    if new == 0:
                        print(
                            f"⚠️ Page {page} still has "
                            "0 new links after retry."
                        )
            finally:
                driver2.quit()

        return sorted(seen)

    def get_html_with_retry(url, retries=5, backoff=3):
        for i in range(retries):
            try:
                resp = SESSION.get(
                    url, headers=HEADERS, timeout=30
                )
                if resp.status_code != 200:
                    raise Exception(f"Status {resp.status_code}")
                return resp.text
            except Exception:
                if i < retries - 1:
                    time.sleep(backoff * (2 ** i))
                else:
                    raise

    def parse_profile(url):
        try:
            html = get_html_with_retry(url)
            soup = BeautifulSoup(html, "html.parser")
            
            el_first = soup.select_one("[data-modalfellow-firstname]")
            el_last = soup.select_one("[data-modalfellow-lastname]")
            el_field = soup.select_one("[data-modalfellow-study]")
            el_years = soup.select_one("[data-modalfellow-awarded-years]")

            if not el_first or not el_last:
                 raise ValueError("Missing name elements in page")

            first = el_first.text.strip()
            last = el_last.text.strip()
            field = el_field.text.strip() if el_field else ""
            
            years = [
                y.strip() 
                for y in (el_years.text.split(",") if el_years else [])
            ]
            bio_tag = soup.select_one(
                "[data-modalfellow-biography]"
            )
            bio = (
                NAME_RX.sub(" ", bio_tag.get_text(" ", strip=True))
                if bio_tag else ""
            )
            base = {
                "name": f"{first.strip()} {last.strip()}",
                "field": field.strip(),
                "biography": bio.strip() if bio else "",
                "award": "Guggenheim Fellowship",
                "govid": "191",
                "govname": "John Simon Guggenheim Memorial Foundation",
                "aid": "1809",
            }
            return [dict(base, year=y) for y in years]
        except Exception as e:
            print(f"Error on {url}: {e}")
            FAILED_URLS.append(url)
            return []

    def scrape_guggenheim(max_pages=200, threads=8):
        urls = collect_links(max_pages=max_pages)
        print(
            f"\n✅ Total unique profile URLs "
            f"collected: {len(urls)}\n"
        )
        rows = []
        with concurrent.futures.ThreadPoolExecutor(
            max_workers=threads
        ) as pool:
            for result in tqdm(
                pool.map(parse_profile, urls),
                total=len(urls),
                desc="Parsing profiles"
            ):
                rows.extend(result)

        if FAILED_URLS:
            with open("failed_profiles.txt", "w") as f:
                f.writelines(f"{u}\n" for u in FAILED_URLS)
            print(
                f"\n⚠️ {len(FAILED_URLS)} failed profiles "
                "written to failed_profiles.txt"
            )

        df = pd.DataFrame(rows)
        print(f"\n✅ Scraped {len(df)} rows.")
        return df

    # Run the full pipeline
    df = scrape_guggenheim(max_pages=200, threads=8)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")\
        
    return df

In [229]:
def scrape2988():
    award = "Whiting Writers' Award"
    govid = "410"
    govname = "Whiting Foundation"
    aid = "2988"
    url = "https://www.whiting.org/writers/awards/search#"
    db = []

    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/122.0.0.0 Safari/537.36'
        )
    }

    options = Options()
    options.headless = False
    options.add_argument(f"user-agent={headers['User-Agent']}")
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()

    driver.get(url)
    time.sleep(2)

    while True:
        try:
            table = driver.find_element(By.TAG_NAME, 'tbody')
            rows = table.find_elements(By.TAG_NAME, 'tr')

            for row in rows:
                cols = row.find_elements(By.TAG_NAME, 'td')
                name = ' '.join(cols[0].text.split())
                year = cols[3].text.strip()
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

            next_button = driver.find_element(By.XPATH, "//a[@rel='next']")
            driver.execute_script("arguments[0].click();", next_button)
            WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.TAG_NAME, 'tbody'))
            )

        except NoSuchElementException:
            print("No more pages to scrape.")
            break

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {now}")
    
    return df

In [230]:
def scrape3262():
    award = "Mead Johnson Award"
    govid = "322"
    govname = "American Society for Nutrition"
    aid = "3262"
    url = "https://nutrition.org/asn-foundation/past-award-honorees/"
    db = []

    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/122.0.0.0 Safari/537.36'
        )
    }

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    block = soup.find('h2', id='h-mead-johnson-award')
    div = block.find_next_sibling('div', class_='wp-block-columns-is-layout-flex')

    response = model.generate_content(
        contents = f"""
            Please extract **only** the winner **Name** and **Year** from the text below and output it as a Markdown table with exactly two columns.

            **Requirements**  
            - Table must have a header row: `| Name | Year |`  
            - Each subsequent row: one person’s full name in the first column, their year in the second  
            - If a year lists multiple names (e.g. “Fred Brooks, Erich Bloch and Bob Evans”), split them so each name gets its own row with the same year  
            - Do **not** include any affiliations or extraneous text  

            **Text to parse:**  
            {div.text}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]
    data_rows = table_lines[2:]

    for row in data_rows:
        # parse exactly two columns: Name, Year
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 2:
            name, year = cols
            if len(name) > 3:
                db.append({
                    'id':      aid.strip(),
                    'govid':   govid.strip(),
                    'govname': govname.strip(),
                    'award':   award.strip(),
                    'year':    year.strip(),
                    'name':    name.strip()
                })

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {now}")

    return df

In [231]:
def scrape2026(): #Defunct Award
    print("This award is defunct and no longer has any recipients listed.")
    # award = "William O Baker Award for Initiatives in Research"
    # govid = "222"
    # govname = "National Academy of Sciences"
    # aid = "2026"
    # url = "https://www.nasonline.org/programs/awards/initiatives-in-research.html"
    # db = []
    # headers = {
    #     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    # }
    
    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")
    
    # h3tag = soup.find('h3', string="Recipients:")
    
    # ptags = h3tag.find_all_next('p')
    
    # for p in ptags:
    #     strongs = p.find_all('strong')
    #     if len(strongs) == 1:
    #         prof = strongs[0].text.strip()
            
    #         pattern = r"([\w\s\.\-]+?)\s*\((\d{4}),"
    #         matches = re.findall(pattern, prof)

    #         if matches:
    #             name, year = matches[0]

    #         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            
    #     if len(strongs) > 1:
    #         name = strongs[0].text.strip()
    #         yrtxt = strongs[1].text.strip()
    #         pattern = r"\((\d{4}),"
    #         match = re.search(pattern, yrtxt)
    #         year = match.group(1)
            
    #         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    # df = pd.DataFrame(db)
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

In [232]:
def scrape1888():
    award = "Lifetime Achievement Award in Honor of Nicolas Appert"
    govid = "200"
    govname = "Institute of Food Technologists"
    aid = "1888"
    url = "https://www.ift.org/community/awards-and-recognition/achievement-awards/nicolas-appert-award"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }
    
    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(5)

    try:
        # Try to handle cookie consent if present
        cookie_btn = driver.find_element(By.CSS_SELECTOR, "button.cky-btn-accept")
        driver.execute_script("arguments[0].click();", cookie_btn)
        time.sleep(2)
    except:
        pass

    try:
        button = driver.find_element(By.ID, 'PastAwardRecipients')
        # Use JavaScript click to bypass interruptions
        driver.execute_script("arguments[0].click();", button)
    except Exception as e:
        print(f"Error clicking button: {e}")

    time.sleep(5)

    div = driver.find_element(By.CLASS_NAME, 'accordion__content')
    dots = div.find_elements(By.TAG_NAME, 'p')
    
    for dot in dots:
        text = dot.text.strip()
        year = text[0:4]
        name = text[6:].strip()

        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    driver.quit()

    return df

In [233]:
def scrape1758():
    award   = "William Skinner Cooper Award"
    govid   = "180"
    govname = "Ecological Society of America"
    aid     = "1758"
    url     = "https://www.esa.org/history/2014/02/william-s-cooper-award/"
    db      = []

    download_dir = tempfile.mkdtemp(prefix=f"award_{aid}_")
    chrome_options = Options()
    chrome_options.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })

    driver = webdriver.Chrome(options=chrome_options)

    try:
        driver.get(url)
        export_btn = driver.find_element(By.XPATH, '//button[contains(@class, "buttons-csv")]')
        export_btn.click()

        timeout = time.time() + 30
        while time.time() < timeout:
            files = os.listdir(download_dir)
            csv_files = [f for f in files if f.lower().endswith(".csv")]
            if csv_files:
                csv_file = csv_files[0]
                break
            time.sleep(0.5)
        else:
            raise FileNotFoundError("CSV download did not complete in time")

        csv_path = os.path.join(download_dir, csv_file)
        df_raw = pd.read_csv(csv_path)

    finally:
        driver.quit()

    df_raw['year'] = df_raw['Year'].astype(str).str.strip()
    df_raw['name'] = df_raw['Authors'].astype(str).str.strip()
    df_raw['award'] = award
    df_raw['govid'] = govid
    df_raw['govname'] = govname
    df_raw['id'] = aid
    
    split_names = df_raw['name'].str.split(r"[,;]\s*", expand=True)
    df_expanded = (
        split_names
        .stack()
        .reset_index(level=1, drop=True)
        .rename("name")
        .to_frame()
        .join(df_raw.drop(columns="name"), how="left")
    )

    df = df_expanded[['award', 'name', 'year', 'govid', 'govname', 'id']]
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    try:
        for f in os.listdir(download_dir):
            os.remove(os.path.join(download_dir, f))
        os.rmdir(download_dir)
    except Exception:
        pass

    return df

In [234]:
def scrape2466():
    award = "AAAS Newcomb Cleveland Prize"
    govid = "286"
    govname = "American Association for the Advancement of Science, The (AAAS)"
    aid = "2466"
    url = "https://www.aaas.org/awards/newcomb-cleveland-prize/recipients"
    db = []

    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/122.0.0.0 Safari/537.36'
        )
    }

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    div = soup.find('div', class_="aa-body-text__inset")
    dl = div.find('dl')

    full_text = dl.text.strip()
    n = len(full_text)
    chunks = [
        full_text[:n // 3],
        full_text[n // 3: 2 * n // 3],
        full_text[2 * n // 3:]
    ]

    print(chunks)

    for chunk in chunks:
        print(f"Processing chunk of length {len(chunk)} characters...")
        response = model.generate_content(
            contents=f"""
            Please extract only the **Name** and **Year** of winners from the following award history.

            **Instructions:**
            - Return a Markdown table with this exact header: `| Name | Year |`
            - Each winner must be on their own row
            - Only include winners (ignore honorable mentions or notes)
            - Prioritize person names only
            - Do not include affiliations or extra text

            **Text to process:**  
            {chunk}
            """
        )

        lines = response.text.strip().splitlines()
        table_lines = [l for l in lines if l.strip().startswith("|")]
        data_rows = table_lines[2:]  # skip header + separator

        for row in data_rows:
            columns = [col.strip() for col in row.split("|")[1:-1]]
            if len(columns) == 2:
                name, year = columns
                if len(name) > 3:
                    db.append({
                        'id': aid,
                        'govid': govid,
                        'govname': govname,
                        'award': award,
                        'year': year[:4],
                        'name': name.strip("*").strip()
                    })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        print(f"AwardID {aid} --- scraped and saved to path at {datetime.now().strftime('%H:%M:%S')}")

    return df

In [235]:
def scrape1750():
    aid = "1750"
    award = "Packard Fellowships for Science and Engineering"
    govid = "178"
    govname = "David and Lucile Packard Foundation"
    base_url = "https://www.packard.org/approach/fellowships-for-science-engineering/fellows-directory"
    db = []
    session = requests.Session()

    def get_max_pages():
        try:
            res = session.get(base_url)
            res.raise_for_status()
            soup = BeautifulSoup(res.text, 'html.parser')
            pages = [int(a.text) for a in soup.select("nav.pagination a.page-numbers") if a.text.isdigit()]
            return max(pages) if pages else 1
        except Exception as e:
            print(f"Failed to determine max page number: {e}")
            return 1

    def scrape_card(link):
        try:
            res = session.get(link)
            soup = BeautifulSoup(res.text, 'html.parser')
            card = soup.find('header', class_='single-fellow__header')
            if not card:
                print(f"No card found at {link}")
                return

            name = card.find('h1').get_text(strip=True)
            year, fell_int, curr_int, field = "", "", "", ""

            for li in card.find_all('li'):
                if ":" in li.text:
                    key, val = map(str.strip, li.text.split(":", 1))
                    if key == "Year":
                        year = val
                    elif key == "Disciplines":
                        field = val
                    elif key == "Current Institution":
                        curr_int = val
                    elif key == "Fellowship Institution":
                        fell_int = val

            if curr_int and not fell_int:
                fell_int, curr_int = curr_int, ""

            db.append({
                "id": aid,
                "award": award,
                "govid": govid,
                "govname": govname,
                "name": name,
                "year": year,
                "affiliation": fell_int,
                "currentaffiliation": curr_int,
                "field": field
            })

        except Exception as e:
            print(f"Error scraping card {link}: {e}")
            print(traceback.format_exc())

    def scrape_page(page_num):
        url = f"{base_url}/page/{page_num}/?display=list"
        try:
            res = session.get(url)
            res.raise_for_status()
            soup = BeautifulSoup(res.text, 'html.parser')
            fellows = soup.find_all('article', class_="list-item-fellow")
            print(f"Page {page_num}: Found {len(fellows)} fellows")

            for post in fellows:
                for a in post.find_all('a', href=True):
                    scrape_card(a['href'])

        except Exception as e:
            print(f"Error scraping page {page_num}: {e}")

    max_pages = get_max_pages()
    print(f"Max pages detected: {max_pages}")

    for i in range(1, max_pages + 1):
        scrape_page(i)
        print(f"Scraped page {i} at {datetime.now().strftime('%H:%M:%S')}")
        time.sleep(1)

    df = pd.DataFrame(db)
    print(f"Total fellows scraped: {len(df)}")

    if not df.empty:
        df.to_csv(f'{filepath}{aid}.csv', index=False)
        print(f"AwardID {aid} --- saved at {datetime.now().strftime('%H:%M:%S')}")
    else:
        print("No data collected")

    return df

In [236]:
def scrape3009():
    award = "National Medal of Technology and Innovation"
    govid = "365"
    govname = "National Science and Technology Medals Foundation"
    aid = "3009"
    url = "https://en.wikipedia.org/wiki/National_Medal_of_Technology_and_Innovation"
    db = []

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        )
    }

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    table = soup.find('table', class_="wikitable")
    tabletxt = table.text.strip()

    response = model.generate_content(
        contents=f"""
        Please extract only the **Name** and **Year** from the following award table text.

        **Instructions:**
        - Output a Markdown table with this exact header: `| Name | Year |`
        - Each winner must be on their own row
        - If a year has multiple winners (e.g., "Fred Brooks, Erich Bloch and Bob Evans"), split them so each name is on a separate row with the same year
        - Do not include affiliations, organizations, or any other data
        - Only include actual award recipients, no empty or invalid entries

        **Text to process:**
        {tabletxt}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]
    table_rows = table_lines[2:]  # skip header and separator

    for row in table_rows:
        columns = [col.strip() for col in row.split("|")[1:-1]]
        if len(columns) == 2:
            name, year = columns
            if len(name.strip()) > 3:
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name.strip("*").strip()
                })

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)


    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [237]:
def scrape2004():
    aid = "2004"
    award = "Bernard M Gordon Prize for Innovation in Engineering and Technology Education"
    db = []
    govid = '221'
    govname = 'National Academy of Engineering'
    
    url = "https://www.nae.edu/55293/GordonWinners?id=55293"

    driver = webdriver.Chrome()
    driver.get(url)
    
    try:
        dropdown = driver.find_element("name", "ctl06$ContentControls$awardsRecipientsList$ctl02$pagerControlBottom$ddlPageSize")
        Select(dropdown).select_by_value("-1")

    except NoSuchElementException:
        print("Element not found")
        driver.quit()
        return

    page = driver.page_source
    soup = BeautifulSoup(page, "html.parser")
    
    ul_elements = soup.find('ul', class_="items")
    li_elements = ul_elements.find_all('li')
    year = 0
    
    for li in li_elements:
        if li.find('div', class_='listHeading') is not None:
            year = li.find('div', class_='listHeading').text.strip()
            
        name = li.find('span', class_='name').text.strip()
        name = name.replace("  ", " ")
        prefixes = ["Dr.", "Professor", "Mr.", "Ms.", "Mrs.", "Dean"]

        for prefix in prefixes:
            if name.startswith(prefix):
                name = name[len(prefix):].strip()
                break
                
        affiliation = li.find('div', class_='organization').text.strip()
        affType_elem = li.find('div', class_='jobTitle')
        affType = affType_elem.text.strip() if affType_elem else ""
        affiliation = affiliation.replace("â€™", "\u2019")
        
        db.append({"id": aid, "award": award, "govid": govid, "govname": govname, "name": name, "year": year, "affiliation": affiliation, "position": affType})
    
    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [238]:
def scrape101():
    aid = "101"
    tasks = [
        ("https://www.amacad.org/directory?field_class_section=All&field_class_section_1=All&field_deceased=1&sort_bef_combine=field_election_year_DESC", "N"),
        ("https://www.amacad.org/directory?field_class_section=All&field_class_section_1=All&field_deceased=2&sort_bef_combine=field_election_year_DESC", "Y"),
    ]

    session = requests.Session()
    session.headers.update({
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/122.0.0.0 Safari/537.36'
        )
    })

    def fetch_profile_data(profile_url):
        """Fetches and parses a single profile URL."""
        area = ''
        biography = ''
        affiliation = ''
        try:
            prof_resp = session.get(profile_url, timeout=10) # Added timeout for robustness
            if prof_resp.status_code == 200:
                prof_soup = BeautifulSoup(prof_resp.text, 'html.parser')

                # Extract area
                for det in prof_soup.select('div.person-header__detail.inline'):
                    lbl = det.select_one('.field-label').get_text(strip=True)
                    if lbl == 'Area':
                        area = det.select_one('.field-item').get_text(strip=True)
                        break

                # Extract biography text
                bio_div = prof_soup.select_one('div.person__body.person__body--full .field-item')
                if bio_div:
                    biography = bio_div.get_text(' ', strip=True)

                # Derive affiliation from biography: first sentence
                if biography:
                    affiliation = biography.split('.', 1)[0].strip()
            else:
                print(f"Failed to fetch profile {profile_url}: {prof_resp.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"Request error for {profile_url}: {e}")
        except Exception as e:
            print(f"Error parsing profile {profile_url}: {e}")
            traceback.print_exc()

        return area, biography, affiliation

    def scrape_page_101(url, db, deceased_status):
        """
        Scrape one directory page for the American Academy listings,
        then follow each profile link to get affiliation, area, and biography.
        Uses ThreadPoolExecutor for concurrent profile scraping.
        """
        resp = session.get(url)
        if resp.status_code != 200:
            print(f"Failed to fetch {url}: {resp.status_code}")
            return

        soup = BeautifulSoup(resp.text, 'html.parser')
        cards = soup.select('div.views-row')

        profile_tasks = []
        card_data_for_profiles = []

        for card in cards:
            try:
                # Name and year from directory card
                name = card.select_one(
                    'h3.node-title.person-card__name.person-card-directory__name span'
                ).get_text(strip=True)
                values = card.select('div.person-card-directory__value')
                year = values[2].get_text(strip=True) if len(values) > 1 else values[0].get_text(strip=True)

                # Extract profile link
                link_tag = card.select_one(
                    'h3.node-title.person-card__name.person-card-directory__name a'
                )
                profile_url = 'https://www.amacad.org' + link_tag['href']

                profile_tasks.append(profile_url)
                card_data_for_profiles.append({'name': name, 'year': year, 'deceased_status': deceased_status})

            except Exception as e:
                print(f"Error parsing main card on {url}: {e}")
                traceback.print_exc()
                continue # Continue to the next card even if one fails

        # Concurrently fetch profile data
        # You can adjust max_workers based on your system and network.
        # A common starting point is os.cpu_count() * 2 or higher for I/O-bound tasks.
        with ThreadPoolExecutor(max_workers=10) as executor: # Increased workers for I/O-bound tasks
            profile_results = list(executor.map(fetch_profile_data, profile_tasks))

        # Combine results
        for i, (area, biography, affiliation) in enumerate(profile_results):
            card_data = card_data_for_profiles[i]
            db.append({
                'id': "101",
                'award': "American Academy of Arts and Sciences Member/Fellow",
                'govid': "6",
                'govname': "American Academy of Arts and Sciences",
                'year': card_data['year'],
                'name': card_data['name'],
                'affiliation': affiliation,
                'field': area,
                'biography': biography,
                'deceased': card_data['deceased_status']
            })


    db = []
    
    for base_url, deceased_status in tasks:
        # Detect max pages from pagination text
        resp = session.get(base_url)
        if resp.status_code == 200:
            soup = BeautifulSoup(resp.text, 'html.parser')
            span = soup.select_one("li.pager__item.pagerer-prefix span[role='presentation']")
            if span:
                try:
                    max_pages = int(span.get_text().split(' of ')[1])
                except IndexError: # Handle case where "of" might not be found
                    max_pages = 0
                except ValueError: # Handle case where conversion to int fails
                    max_pages = 0
            else:
                max_pages = 0
        else:
            print(f"Failed pagination fetch {base_url}: {resp.status_code}")
            max_pages = 0

        # Iterate pages with minimal throttle
        for i in range(max_pages):
            url = f"{base_url}&page={i}"
            scrape_page_101(url, db, deceased_status)
            print(
                f"Page {i+1}/{max_pages} (deceased={deceased_status}) "
                f"scraped at {datetime.now().strftime('%H:%M:%S')}"
            )
            time.sleep(random.uniform(0.75, 1.25)) # Keep the sleep between page requests

    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv', index=False)
    print(f"AwardID {aid} scraped {len(df)} records and saved to {filepath}")

    return df

In [239]:
def scrape2138():
    award   = "NEH Fellowship Programs at Independent Research Institutions"
    govid   = "234"
    govname = "National Endowment for the Humanities (NEH)"
    aid     = "2138"
    url     = ("https://apps.neh.gov/publicquery/main.aspx?"
               "q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&p=1&pv=21&"
               "d=0&at=0&y=0&prd=0&cov=0&prz=0&wp=0&sp=0&ca=0&arp=0&"
               "ob=year&or=DESC")

    download_dir = tempfile.mkdtemp(prefix=f"neh_{aid}_")
    chrome_opts = Options()
    chrome_opts.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })
    chrome_opts.add_argument("--headless")
    driver = webdriver.Chrome(options=chrome_opts)

    try:
        driver.get(url)
        btn = driver.find_element(
            By.XPATH,
            '//button[contains(@id, "ExportToCSV")]'
        )
        btn.click()

        timeout = time.time() + 30
        csv_path = None
        while time.time() < timeout:
            files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
            if files:
                csv_path = os.path.join(download_dir, files[0])
                break
            time.sleep(0.5)
        if not csv_path:
            raise FileNotFoundError("NEH CSV download timed out")

    finally:
        driver.quit()

    df = pd.read_csv(csv_path)

    df.iloc[:, 4] = df.iloc[:, 4].fillna("")
    df["name"] = (
        df.iloc[:, 3]
          .str.cat(df.iloc[:, 4], sep=" ")
          .str.cat(df.iloc[:, 5], sep=" ")
          .str.strip()
    )
    df["year"]        = df.iloc[:, 14]
    df["field"]       = df.iloc[:, 15]
    df["affiliation"] = df.iloc[:, 9]
    df["id"]          = aid
    df["govid"]       = govid
    df["govname"]     = govname
    df["award"]       = award

    df = df[["name", "year", "field", "affiliation", "id", "govid", "govname", "award"]]

    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
        
    return df

In [240]:
def scrape3768():
    aid     = "3768"
    award   = "NEH Fellowships for University Teachers"
    govid   = "234"
    govname = "National Endowment for the Humanities (NEH)"
    url     = (
        "https://apps.neh.gov/publicquery/main.aspx?"
        "q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&"
        "p=1&pv=1&d=0&at=0&y=0&prd=0&cov=0&prz=0&"
        "wp=0&sp=0&ca=0&arp=0&ob=year&or=DESC"
    )

    # create a fresh temp dir for the download
    download_dir = tempfile.mkdtemp(prefix=f"neh_{aid}_")
    chrome_opts  = Options()
    chrome_opts.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })
    chrome_opts.add_argument("--headless")
    driver = webdriver.Chrome(options=chrome_opts)

    try:
        driver.get(url)
        btn = driver.find_element(
            By.XPATH,
            '//button[contains(@id, "ExportToCSV")]'
        )
        btn.click()

        # wait up to 30s for the CSV to appear
        timeout, csv_path = time.time() + 30, None
        while time.time() < timeout:
            files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
            if files:
                csv_path = os.path.join(download_dir, files[0])
                break
            time.sleep(0.5)
        if not csv_path:
            raise FileNotFoundError("NEH CSV download timed out")
    finally:
        driver.quit()

    # load and clean up
    df = pd.read_csv(csv_path)
    df.iloc[:, 4] = df.iloc[:, 4].fillna("")
    df["name"] = (
        df.iloc[:, 3]
          .str.cat(df.iloc[:, 4], sep=" ")
          .str.cat(df.iloc[:, 5], sep=" ")
          .str.strip()
    )
    df["year"]        = df.iloc[:, 14]
    df["field"]       = df.iloc[:, 15]
    df["affiliation"] = df.iloc[:, 9]
    df["id"]          = aid
    df["govid"]       = govid
    df["govname"]     = govname
    df["award"]       = award

    df = df[["name", "year", "field", "affiliation", "id", "govid", "govname", "award"]]
    df.to_csv(f"{filepath}{aid}.csv", index=False)

    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {now}")

    return df

In [241]:
def scrape21776():
    aid     = "21776"
    award   = "Fellowships"
    govid   = "234"
    govname = "National Endowment for the Humanities (NEH)"
    url     = (
        "https://apps.neh.gov/PublicQuery/Default.aspx?"
        "q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&"
        "p=1&pv=318&d=0&at=0&y=0&prd=0&cov=0&prz=0&"
        "wp=0&sp=0&ca=0&arp=0&ob=Institution%20name&or=ASC"
    )

    download_dir = tempfile.mkdtemp(prefix=f"neh_{aid}_")
    chrome_opts  = Options()
    chrome_opts.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })
    chrome_opts.add_argument("--headless")
    driver = webdriver.Chrome(options=chrome_opts)

    try:
        driver.get(url)
        btn = driver.find_element(
            By.XPATH,
            '//button[contains(@id, "ExportToCSV")]'
        )
        btn.click()

        timeout, csv_path = time.time() + 30, None
        while time.time() < timeout:
            files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
            if files:
                csv_path = os.path.join(download_dir, files[0])
                break
            time.sleep(0.5)
        if not csv_path:
            raise FileNotFoundError("NEH CSV download timed out")
    finally:
        driver.quit()

    df = pd.read_csv(csv_path)
    df.iloc[:, 4] = df.iloc[:, 4].fillna("")
    df["name"] = (
        df.iloc[:, 3]
          .str.cat(df.iloc[:, 4], sep=" ")
          .str.cat(df.iloc[:, 5], sep=" ")
          .str.strip()
    )
    df["year"]        = df.iloc[:, 14]
    df["field"]       = df.iloc[:, 15]
    df["affiliation"] = df.iloc[:, 9]
    df["id"]          = aid
    df["govid"]       = govid
    df["govname"]     = govname
    df["award"]       = award

    df = df[["name", "year", "field", "affiliation", "id", "govid", "govname", "award"]]
    df.to_csv(f"{filepath}{aid}.csv", index=False)

    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {now}")

    return df

In [242]:
def scrape2157():
    aid = "2157"
    award = "NHC Fellow"
    govid = "237"
    govname = "National Humanities Center"

    db = []
    url = "https://nationalhumanitiescenter.org/all-fellows/"
    
    page = requests.get(url)
    soup = BeautifulSoup(page.text, "html.parser")
    
    divsoup = soup.find('div', class_="all-current-fellows")
    fellows = divsoup.find_all('div', class_="current-fellow")
    
    for fellow in fellows:
        title = fellow.find('a', class_='fellow-name')
        title = title.get_text(strip=True)
        
        affiliation = fellow.find('p', class_='fellow-discipline').get_text(strip=True)
        
        pattern = r'^(.*?)\s*\(.*?(\d{4})–(\d{2})(?:;\s*(\d{4})–(\d{2}))?\)$'

        match = re.match(pattern, title)

        if match:
            name = match.group(1).strip()
            year = match.group(2)
            yearperiod = year + "-" + match.group(3)
            
            
        db.append({"id": aid, "award": award, "govid": govid, "govname": govname, "name": name, "year": year, "affiliation": affiliation})
        
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [243]:
def scrape152():
    aid = "152"
    db = []
    URL = "https://www.americanantiquarian.org/fellowships/fellows-directory?field_name=&title=&field_fellowship_target_id_verf=24&tid=All"
    award = "Hench Post-Dissertation Fellowship"
    govid = '13'
    govname = 'American Antiquarian Society'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(URL)
    soup = BeautifulSoup(page.content, "html.parser")
    table = soup.find('table', class_ = 'views-table')
    
    trs = table.find_all('tr')
    for tr in trs[1:]:
        tds = tr.find_all('td')
        name = tds[0].find('a').text.strip()
        affiliation = tds[0].find('small').text.split(',')[1].strip()
        year = tds[1].text.strip()[:4]

        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': affiliation})
    
    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [244]:
def scrape147():
    aid = "147"
    db = []
    URL = "https://www.americanantiquarian.org/fellowships/fellows-directory?field_name=&title=&field_fellowship_target_id_verf=88&tid=All"
    award = "AAS-National Endowment for the Humanities Fellows"
    govid = '13'
    govname = 'American Antiquarian Society'
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}
    
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, "html.parser")
    table = soup.find('table', class_ = 'views-table')
    
    trs = table.find_all('tr')
    for tr in trs[1:]:
        tds = tr.find_all('td')
        name = tds[0].find('a').text.strip()
        affiliation = tds[0].find('small').text.split(',')[1].strip()
        year = tds[1].text.strip()[:4]

        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': affiliation})
   
    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [245]:
def scrape479():
    # Takes 30 mins
    aid     = "479"
    award   = "ACLS Fellows (ACLS/SSRC/NEH International and Area Studies Fellowships and ACLS/New York Public Library Fellowships)"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url  = "https://www.acls.org/fellows-grantees/?_fellow_program=363"
    
    # Adjusted Driver Setup (Undetected Chromedriver)
    options = uc.ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-infobars")
    options.add_argument(
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )

    driver = uc.Chrome(options=options)
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        })
    except Exception as e:
        print(f"[WARN] Failed to inject script: {e}")
    
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6)

    try:
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15)
            
        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["id", "govid", "govname", "award", "name", "year", "affiliation"]
    )
    display(df)

    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [246]:
def scrape3007():
    aid     = "3007"
    award   = "Andrew W Mellon/ACLS Dissertation Completion Fellowships"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url  = "https://www.acls.org/fellows-grantees/?_fellow_program=380"

    # Adjusted Driver Setup (Undetected Chromedriver)
    options = uc.ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-infobars")
    options.add_argument(
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )

    driver = uc.Chrome(options=options)
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        })
    except Exception as e:
        print(f"[WARN] Failed to inject script: {e}")
    
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6)

    try:
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15)
            
        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["id", "govid", "govname", "award", "name", "year", "affiliation"]
    )
    display(df)

    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [247]:
def scrape3004():
    aid     = "3004"
    award   = "National Medal of Science"
    govid   = "365"
    govname = "National Science and Technology Medals Foundation"
    url     = "https://www.nsf.gov/od/nms/results.jsp?showItems=All"

    # use TemporaryDirectory for auto-cleanup of downloaded CSV
    with tempfile.TemporaryDirectory(prefix=f"nsf_{aid}_") as download_dir:
        chrome_opts = Options()
        chrome_opts.add_experimental_option("prefs", {
            "download.default_directory": download_dir,
            "download.prompt_for_download": False,
            "directory_upgrade": True
        })

        driver = webdriver.Chrome(options=chrome_opts)
        try:
            driver.get(url)
            
            export_btn = WebDriverWait(driver, 20).until(
                EC.element_to_be_clickable((
                    By.CSS_SELECTOR,
                    "div.header-exposed-form__export-results "
                    "div.csv-feed.views-data-export-feed a"
                ))
            )
            export_btn.click()

            timeout, csv_path = time.time() + 30, None
            while time.time() < timeout:
                files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
                if files:
                    csv_path = os.path.join(download_dir, files[0])
                    break
                time.sleep(0.5)
            if not csv_path:
                raise FileNotFoundError("NSF CSV download timed out")
        finally:
            driver.quit()

        df_raw = pd.read_csv(csv_path)

    df = df_raw[["First name", "Last name", "Institution", "Award year", "Research area"]].copy()
    df["name"] = df["First name"].str.strip() + " " + df["Last name"].str.strip()
    df = (
        df
        .drop(columns=["First name", "Last name"])
        .rename(columns={
            "Institution":   "affiliation",
            "Award year":    "year",
            "Research area": "field"
        })
    )
    df["id"]      = aid
    df["award"]   = award
    df["govid"]   = govid
    df["govname"] = govname
    display(df)

    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records scraped and saved at {datetime.now().strftime('%H:%M:%S')}")

    return df

In [248]:
def scrape3504():
    aid = "3504"
    award = "Center for Advanced Studies in the Behavioral Sciences/CASBS Residency Fellow"
    govid = '2554'
    govname = 'Stanford University'
    url = "https://casbs.stanford.edu/fellowships"
    page = requests.get(url)
    
    soup = BeautifulSoup(page.content,"html.parser")
    parent_div = soup.find("div", class_="file")

    if parent_div:
        a_tag = parent_div.find("a")
        if a_tag:
            href_value = a_tag.get("href")
    
    baseurl = "https://casbs.stanford.edu/"
    
    if href_value.startswith("/"):
        href_value = baseurl + href_value

    response = requests.get(href_value)

    if response.status_code == 200:
        file_content = response.text
        data = json.loads(file_content)
        columns = ["Image URL", "name", "afftype", "yearperiod", "affiliation", "Department/Field", "field", "Rank", "Profile URL", "Last Name"]
        
        df = pd.DataFrame(data["data"], columns=columns)
        
        df['id'] = aid
        df['award'] = award
        df['govid'] = govid
        df['govname'] = govname
        df['year'] = df['yearperiod'].apply(lambda x: x.split("-")[0])
        df = df[['id', 'award', 'govid', 'govname', 'name', 'year', 'yearperiod', 'affiliation', 'afftype', 'field']]
        df['deceased'] = df['affiliation'].apply(lambda x: 'Y' if x.lower() == 'deceased' else '')
        df['affiliation'] = df['affiliation'].apply(lambda x: '' if x.lower() == 'deceased' else x)

        display(df)
        df.to_csv(f'{filepath}{aid}.csv',index=False)
    
        if not df.empty:
            now = datetime.now()
            current_time = now.strftime("%H:%M:%S")
            print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

            return df
        
    else:
        print(f"Failed to retrieve content from {href_value}. Status code: {response.status_code}")

In [249]:
def scrape2980():
    aid     = "2980"
    award   = "Pulitzer Prize"
    govid   = "404"
    govname = "Pulitzer Board, The"
    all_db  = []

    start_year = 1917
    current_year = datetime.now().year

    opts = uc.ChromeOptions()
    opts.add_argument("--no-sandbox")
    opts.add_argument("--disable-blink-features=AutomationControlled")
    opts.add_argument("--disable-infobars")
    opts.add_argument(
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )

    driver = uc.Chrome(options=opts)
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        })
    except Exception as e:
        print(f"[WARN] Failed to inject script: {e}")

    def scrape_year(driver, year):
        url = f"https://www.pulitzer.org/prize-winners-by-year/{year}"
        year_db = []
        batch_data = []

        try:
            driver.get(url)
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "span[ng-bind='::page.year']"))
            )
            soup = BeautifulSoup(driver.page_source, "html.parser")
        except Exception as e:
            print(f"Error loading year {year}: {e}")
            return year_db

        try:
            page_year = soup.find("span", {"ng-bind": "::page.year"}).get_text(strip=True)
        except:
            page_year = str(year)

        divs = soup.find_all("div", attrs={"ng-if": "page.winnersCount || page.finalistsCount"})

        for div in divs:
            cards = div.select("div.row.table-row.ng-scope")
            for card in cards:
                try:
                    category_elem = card.select_one("a[ng-bind='::category.name']")
                    winner_elem = card.select_one("a[ng-bind-html='::winner.awardsTitle']")
                    if category_elem and winner_elem:
                        category = category_elem.get_text(strip=True)
                        winner = winner_elem.get_text(strip=True)
                        batch_data.append({
                            'category': category,
                            'winner': winner,
                            'year': page_year
                        })
                except Exception as e:
                    print(f"Error processing card in year {year}: {e}")
                    continue

        if batch_data:
            print(f"Found {len(batch_data)} entries for year {year}, processing with Gemini...")
            processed_data = process_batch_with_gemini(batch_data)

            for item in processed_data:
                for name in item['names']:
                    year_db.append({
                        "id":        aid,
                        "govid":     govid,
                        "govname":   govname,
                        "award":     award,
                        "year":      item['year'],
                        "name":      name.strip(),
                        "subaward":  item['category']
                    })

        print(f"Year {year}: {len(year_db)} entries processed")
        return year_db

    def process_batch_with_gemini(batch_data):
        table_text = "Category\tWinner\tYear\n"
        for item in batch_data:
            table_text += f"{item['category']}\t{item['winner']}\t{item['year']}\n"

        prompt = f"""Extract person names from the following Pulitzer Prize winners table. 
            For each row, extract only individual person names if present, otherwise the organization name.
            When both persons and organizations are listed, prioritize persons.

            Return results in this exact format:
            Category: [category] | Year: [year] | Names: [name1, name2, name3]

            Table:
            {table_text}"""

        try:
            response = model.generate_content(
                contents=(prompt)
            )
            return parse_gemini_table_response(response.text, batch_data)
        except Exception as e:
            print(f"Error with Gemini processing: {e}")
            return [{'category': item['category'], 'year': item['year'], 'names': [item['winner']]} 
                    for item in batch_data]

    def parse_gemini_table_response(response_text, original_data):
        processed_data = []
        lines = response_text.strip().split('\n')

        for line in lines:
            if 'Category:' in line and 'Year:' in line and 'Names:' in line:
                try:
                    parts = line.split(' | ')
                    category = parts[0].replace('Category:', '').strip()
                    year = parts[1].replace('Year:', '').strip()
                    names_part = parts[2].replace('Names:', '').strip()
                    names = [name.strip() for name in names_part.replace('[', '').replace(']', '').split(',')]
                    names = [name for name in names if name]
                    processed_data.append({
                        'category': category,
                        'year': year,
                        'names': names
                    })
                except Exception as e:
                    print(f"Error parsing line: {line}, Error: {e}")
                    continue

        if not processed_data:
            print("Gemini parsing failed, using fallback")
            processed_data = [{'category': item['category'], 'year': item['year'], 'names': [item['winner']]} 
                              for item in original_data]

        return processed_data

    try:
        for year in range(start_year, current_year + 1):
            print(f"\n=== Processing Year {year} ===")
            year_db = scrape_year(driver, year)
            all_db.extend(year_db)
            time.sleep(2)
    finally:
        driver.quit()

    df = pd.DataFrame(all_db)
    display(df)
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"\nTotal AwardID {aid}: {len(df)} entries saved at {datetime.now().strftime('%H:%M:%S')}")
    
    return df

### List B

In [250]:
def scrape3008():
    # --- Constants ---
    AID        = "3008"
    AWARD      = "NAE Membership"
    GOVID      = "221"
    GOVNAME    = "National Academy of Engineering"
    BASE_URL   = "https://www.nae.edu/20412/MemberDirectory"
    WAIT_SEC   = 10
    PAGE_PAUSE = 0.2
    JITTER_MAX = 0.15
    PAGE_SIZE  = "100"
    TEST_LIMIT = None  # Set to None to scrape all, or an integer (e.g. 1) to test a subset

    # --- Imports/Backup Utility ---
    try:
        from monitor.backup_utils import save_backup_snapshot
    except ImportError:
        def save_backup_snapshot(*args, **kwargs):
            return None

    # --- Helpers ---
    def new_driver(headless: bool = False) -> webdriver.Chrome:
        opts = webdriver.ChromeOptions()
        if headless:
            opts.add_argument("--headless=new")

        # SPEED: return control right after DOMContentLoaded
        opts.page_load_strategy = "eager"

        opts.add_argument("--window-size=1920,1080")
        opts.add_argument("--disable-blink-features=AutomationControlled")
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-logging")
        opts.add_argument("--disable-dev-shm-usage")
        opts.add_argument("--disable-background-timer-throttling")
        opts.add_argument("--disable-backgrounding-occluded-windows")
        opts.add_argument("--disable-renderer-backgrounding")
        opts.add_argument("--log-level=3")
        opts.add_argument("--silent")
        opts.add_argument("--disable-sync")
        opts.add_argument("--disable-background-networking")
        opts.add_argument("--disable-default-apps")

        prefs = {
            "profile.managed_default_content_settings.images": 2,
            "profile.default_content_setting_values.notifications": 2
        }
        opts.add_experimental_option("prefs", prefs)
        opts.add_experimental_option('excludeSwitches', ['enable-logging'])
        opts.add_experimental_option('useAutomationExtension', False)

        drv = webdriver.Chrome(options=opts)
        drv.implicitly_wait(0.25)
        return drv

    def norm_text(s: Optional[str]) -> str:
        if not s:
            return ""
        s = s.strip()
        s = re.sub(r"\s+", " ", s)
        return s

    def clean_name(name: str) -> str:
        name = norm_text(name)
        prefixes = ["Dr. ", "Dr ", "Mr. ", "Mr ", "Ms. ", "Ms ", "Mrs. ", "Mrs ", "Prof. ", "Professor "]
        suffixes = [" Jr.", " Jr", " Sr.", " Sr", " II", " III", " IV", ", PhD", ", MD", ", DSc"]
        for p in prefixes:
            if name.startswith(p):
                name = name[len(p):]
        for s in suffixes:
            if name.endswith(s):
                name = name[:-len(s)]
        return norm_text(name)

    def clean_url(url: str) -> str:
        if not url:
            return ""
        return url.split("?")[0].split("#")[0].strip()

    def safe_attr(driver, by, selector, attr="text") -> str:
        try:
            el = driver.find_element(by, selector)
            if attr == "text":
                return norm_text(el.text)
            return norm_text(el.get_attribute(attr))
        except NoSuchElementException:
            return ""

    def set_page_size(driver: webdriver.Chrome, wait: WebDriverWait) -> None:
        try:
            dropdown = wait.until(EC.presence_of_element_located((
                By.NAME,
                "ctl06$ctl05$ctl00$MembersList$members$ctl01$ctl22$filterTopPager$ddlPageSize"
            )))
            Select(dropdown).select_by_visible_text(PAGE_SIZE)
            wait.until(EC.presence_of_element_located((By.CLASS_NAME, "flexible-list-item")))
        except (TimeoutException, NoSuchElementException):
            pass

    def discover_years(driver: webdriver.Chrome, wait: WebDriverWait) -> List[int]:
        driver.get(BASE_URL)
        WebDriverWait(driver, 8).until(EC.presence_of_element_located((By.TAG_NAME, "body")))
        years: List[int] = []

        selectors = [
            (By.CSS_SELECTOR, "select[id*='Year']"),
            (By.CSS_SELECTOR, "select[name*='Year']"),
            (By.XPATH, "//select[contains(@id,'Year') or contains(@name,'Year')]"),
        ]
        for by, sel in selectors:
            try:
                el = WebDriverWait(driver, 4).until(EC.presence_of_element_located((by, sel)))
                options = el.find_elements(By.TAG_NAME, "option")
                for opt in options:
                    txt = norm_text(opt.text)
                    m = re.search(r"\b(19|20)\d{2}\b", txt)
                    if m:
                        years.append(int(m.group(0)))
                if years:
                    years = sorted(set(years))
                    return years
            except (TimeoutException, NoSuchElementException):
                continue

        this_year = date.today().year
        return list(range(this_year - 60, this_year + 1))

    def _collect_links_from_current_listing(driver: webdriver.Chrome, wait: WebDriverWait, max_links: Optional[int] = None) -> List[str]:
        links: List[str] = []
        seen: Set[str] = set()
        page_num = 1

        while True:
            wait.until(EC.presence_of_all_elements_located((By.CLASS_NAME, "flexible-list-item")))

            try:
                first_href_before = driver.find_element(By.CSS_SELECTOR, "span.name a").get_attribute("href")
            except NoSuchElementException:
                first_href_before = None

            page_links_count = 0
            for item in driver.find_elements(By.CLASS_NAME, "flexible-list-item"):
                try:
                    href = item.find_element(By.CSS_SELECTOR, "span.name a").get_attribute("href")
                    href = clean_url(href)
                    if href and href not in seen:
                        seen.add(href)
                        links.append(href)
                        page_links_count += 1
                        
                        if max_links is not None and len(links) >= max_links:
                            break
                            
                except NoSuchElementException:
                    continue

            print(f"[{AID}] Collected {len(links)} links after page {page_num} (+{page_links_count} this page)")

            if max_links is not None and len(links) >= max_links:
                break

            next_buttons = driver.find_elements(By.CSS_SELECTOR, "li.pager-pagenextb a.next_page")
            if not next_buttons or not next_buttons[0].is_displayed():
                break

            btn = next_buttons[0]
            driver.execute_script("arguments[0].scrollIntoView(true); window.scrollBy(0, -100);", btn)
            driver.execute_script("arguments[0].click();", btn)

            try:
                WebDriverWait(driver, 2).until(
                    lambda d: d.find_element(By.CSS_SELECTOR, "span.name a").get_attribute("href") != first_href_before
                )
            except TimeoutException:
                time.sleep(0.3)

            try:
                first_href_after = driver.find_element(By.CSS_SELECTOR, "span.name a").get_attribute("href")
                if first_href_before == first_href_after:
                    break
            except NoSuchElementException:
                break

            time.sleep(0.15)
            page_num += 1

        return links

    def collect_all_links(driver: webdriver.Chrome, wait: WebDriverWait, max_links: Optional[int] = None) -> List[str]:
        driver.get(f"{BASE_URL}?qdec=both")
        WebDriverWait(driver, 8).until(EC.presence_of_all_elements_located((By.CLASS_NAME, "flexible-list-item")))
        set_page_size(driver, wait)
        return _collect_links_from_current_listing(driver, wait, max_links=max_links)

    def collect_links_for_year(driver: webdriver.Chrome, wait: WebDriverWait, year: int, max_links: Optional[int] = None) -> List[str]:
        url = f"{BASE_URL}?qey={year}&qdec=both"
        driver.get(url)
        WebDriverWait(driver, 8).until(EC.presence_of_all_elements_located((By.CLASS_NAME, "flexible-list-item")))
        set_page_size(driver, wait)
        return _collect_links_from_current_listing(driver, wait, max_links=max_links)

    def scrape_profile(driver: webdriver.Chrome, wait: WebDriverWait, url: str, fallback_year: Optional[int] = None) -> Dict[str, str]:
        driver.get(url)
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, "name")))

        raw_name    = safe_attr(driver, By.CSS_SELECTOR, "div.name", attr="text")
        name        = clean_name(raw_name)
        title       = safe_attr(driver, By.CSS_SELECTOR, ".personInfo.hidden-xs .jobOrg .jobTitle", attr="text")
        affiliation = safe_attr(driver, By.CSS_SELECTOR, ".personInfo.hidden-xs .jobOrg .organization", attr="text")

        other_affs = ", ".join(
            norm_text(el.text)
            for el in driver.find_elements(
                By.XPATH, "//label[normalize-space()='Other Affiliations']/following-sibling::*//li"
            ) if norm_text(el.text)
        )

        location = safe_attr(
            driver, By.XPATH,
            "//label[normalize-space()='Location']/following-sibling::div[contains(@class,'address')]"
        )

        # Try multiple strategies to find 'Election Year'
        election_year = ""
        strategies = [
            # 1. Exact list item containing label + following span (most precise)
            "//li[label[normalize-space()='Election Year']]/span",
            "//li[label[normalize-space()='ELECTION YEAR']]/span",
            
            # 2. Label text contains 'Election Year' -> following sibling span
            "//label[contains(text(), 'Election Year')]/following-sibling::span",
            "//label[contains(text(), 'ELECTION YEAR')]/following-sibling::span",

            # 3. Any element with text 'Election Year' -> following sibling
            "//*[contains(text(),'Election Year')]/following-sibling::span",
            "//*[contains(text(),'ELECTION YEAR')]/following-sibling::span",
            
            # 4. Fallback to ordList (legacy)
            "(//ul[contains(@class,'ordList')])[last()]/li[label[normalize-space()='Election Year']]/span"
        ]
        
        for xpath in strategies:
            val = safe_attr(driver, By.XPATH, xpath, attr="text")
            if val:
                election_year = val
                break
        
        # Fallback: brute force search in list items if specific structure failed
        if not election_year:
             try:
                 # Find list items that might contain the text
                 candidates = driver.find_elements(By.XPATH, "//li[contains(., 'lection Year') or contains(., 'LECTION YEAR')]")
                 for c in candidates:
                     txt = norm_text(c.text)
                     # Look for "Election Year" followed by 4 digits
                     # e.g. "Election Year 2008" or "Election Year: 2008"
                     m = re.search(r"(?:lection Year|LECTION YEAR)[^0-9]*(\d{4})", txt)
                     if m:
                         election_year = m.group(1)
                         break
             except Exception:
                 pass
        
        # Fallback to the provided year if still empty
        if not election_year and fallback_year is not None:
             election_year = str(fallback_year)

        deceased = "Y"
        try:
            driver.find_element(By.CSS_SELECTOR, "span.badge.deceased")
        except NoSuchElementException:
            deceased = ""

        death_year = ""
        if deceased:
            try:
                years_el = driver.find_element(By.CSS_SELECTOR, "span.years")
                years_text = norm_text(years_el.text)
                parts = years_text.split("-")
                if len(parts) > 1:
                    death_year = parts[1].strip()
            except NoSuchElementException:
                pass

        try:
            employment_items = driver.find_elements(By.XPATH, 
                "//div[contains(@class, 'header-box') and contains(., 'Employment')]"
                "/following-sibling::div[contains(@class, 'collapse')]"
                "//ul/li"
            )
            if employment_items:
                aff_list = []
                for li in employment_items:
                    txt = norm_text(li.text)
                    if txt:
                        aff_list.append(txt)
                if aff_list:
                    affiliation = "; ".join(aff_list)
        except Exception:
            pass

        return {
            "id":                 AID,
            "govid":              GOVID,
            "govname":            GOVNAME,
            "award":              AWARD,
            "name":               name,
            "profile_url":        url,
            "year":               norm_text(election_year),
            "affiliation":        norm_text(affiliation),
            "location":           norm_text(location),
            "title":              norm_text(title),
            "other_affiliations": norm_text(other_affs),
            "deceased":           deceased,
            "death_year":         death_year,
        }

    # --- Main Execution (Scraper Logic) ---
    all_years = None
    if "YEARS" in globals():
        all_years = YEARS

    headless = True # Default from original code/expectation

    print(f"[{AID}] Starting scrape_nae (headless={headless})")
    driver = new_driver(headless=headless)
    wait_short = WebDriverWait(driver, 3)

    records: List[Dict[str, str]] = []
    errors_count = 0

    try:
        unique_links: List[str] = []
        seen_links: Set[str] = set()
        fallback_year_for: Dict[str, int] = {}

        years = all_years or []
        if years:
            print(f"Years provided ({len(years)}): {years}")
        else:
            print(f"[{AID}] Collecting all profile links (single pass)...")
            unique_links = collect_all_links(driver, wait_short, max_links=TEST_LIMIT)
            print(f"[{AID}] Finished collecting all profile links.")
            seen_links = set(unique_links)
            print(f"[{AID}] Collected {len(unique_links)} unique links total")

        for idx, yr in enumerate(years, 1):
            if TEST_LIMIT is not None and len(unique_links) >= TEST_LIMIT:
                print(f"[{AID}] Reached global TEST_LIMIT of {TEST_LIMIT}. Stopping year processing.")
                break

            print(f"[{AID}] Collecting links for year {yr} ({idx}/{len(years)}) …")
            
            needed = None
            if TEST_LIMIT is not None:
                needed = TEST_LIMIT - len(unique_links)
                if needed <= 0:
                     break
            
            links = collect_links_for_year(driver, wait_short, yr, max_links=needed)
            print(f"[{AID}] Year {yr}: {len(links)} profile links")

            for href in links:
                if href not in seen_links:
                    seen_links.add(href)
                    unique_links.append(href)
                    fallback_year_for[href] = yr
            print(f"[{AID}] Finished collecting links for year {yr} ({idx}/{len(years)})")

        if TEST_LIMIT is not None:
             print(f"[{AID}] TEST_LIMIT set to {TEST_LIMIT}. Truncating unique_links.")
             unique_links = unique_links[:TEST_LIMIT]

        total_links = len(unique_links)
        print(f"[{AID}] Starting to scrape {total_links} unique profiles...")

        for i, href in enumerate(unique_links, 1):
            print(f"[{AID}] Scraping profile {i}/{total_links}: {href}")
            try:
                rec = scrape_profile(
                    driver, wait_short, href, fallback_year=fallback_year_for.get(href)
                )
                records.append(rec)
                time.sleep(PAGE_PAUSE + random.random() * JITTER_MAX)
                if i % 25 == 0:
                    print(f"[{AID}] Scraped {i}/{total_links} profiles... ({len(records)} successful)")
            except Exception as e:
                errors_count += 1
                print(f"  - Error scraping profile {i}/{total_links} ({href}): {e}")
                continue

        print(f"[{AID}] Scraping complete: {len(records)} successful, {errors_count} errors")

    finally:
        print(f"[{AID}] Quitting driver.")
        driver.quit()

    df = pd.DataFrame(records, dtype=str).fillna("")
    if not df.empty:
        print(f"[{AID}] Deduplicating DataFrame on profile_url and name.")
        # Ensure we don't crash if columns are missing
        if "profile_url" in df.columns:
            df = df.sort_values(["profile_url", "name"]).drop_duplicates(subset=["profile_url"], keep="first")

    display(df)

    # Legacy CSV save
    try:
        # Check if filepath is defined in outer scope
        out_path = f"{filepath}{AID}.csv"
        df.to_csv(out_path, index=False)
        print(f"[{AID}] Saved CSV to {out_path}")
    except NameError:
        pass
    except Exception as e:
         print(f"[{AID}] Could not save CSV: {e}")

    return df

In [251]:
def scrape1909(): #NAM
    # Constants / Config
    AID        = "1909"
    AWARD      = "NAM Member"
    GOVID      = "202"
    GOVNAME    = "National Academy of Medicine"
    BASE_URL   = (
        "https://nam.edu/membership/members/directory/?jsf=epro-posts:content-feed&tax=health_status:include_all"
    )
    WAIT_SEC   = 8  # Increased for better reliability
    PAGE_PAUSE = 2.0  # Increased for better page loading

    # Helper functions
    def new_driver() -> webdriver.Chrome:
        """Create a reasonably stealthy Chrome driver."""
        opts = webdriver.ChromeOptions()
        opts.add_argument("--window-size=1920,1080")
        opts.add_argument("--disable-blink-features=AutomationControlled")
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-gpu")
        opts.add_argument("--disable-dev-shm-usage")
        opts.add_argument("--disable-logging")
        opts.add_argument("--disable-web-security")
        opts.add_argument("--disable-features=TranslateUI")
        opts.add_argument("--disable-ipc-flooding-protection")
        opts.add_argument("--disable-renderer-backgrounding")
        opts.add_argument("--disable-backgrounding-occluded-windows")
        opts.add_argument("--disable-client-side-phishing-detection")
        opts.add_argument("--disable-sync")
        opts.add_argument("--disable-default-apps")
        opts.add_argument("--disable-extensions")
        opts.add_argument("--log-level=3")
        opts.add_argument("--headless=new")
        return webdriver.Chrome(options=opts)

    def norm_text(s: str) -> str:
        """Basic normalization: strip, collapse internal whitespace."""
        if s is None:
            return ""
        s = s.strip()
        s = re.sub(r"\s+", " ", s)
        return s

    def clean_name(name: str) -> str:
        """Remove common prefixes/suffixes and normalize whitespace."""
        name = norm_text(name)
        prefixes = ["Dr. ", "Dr ", "Mr. ", "Mr ", "Ms. ", "Ms ", "Mrs. ", "Mrs ", "Prof. ", "Professor "]
        suffixes = [" Jr.", " Jr", " Sr.", " Sr", " II", " III", " IV", ", PhD", ", MD", ", DSc"]
        for p in prefixes:
            if name.startswith(p):
                name = name[len(p):]
        for s in suffixes:
            if name.endswith(s):
                name = name[: -len(s)]
        return norm_text(name)

    def clean_url(url: str) -> str:
        """Remove query parameters and fragments to stabilize the primary key."""
        if not url:
            return ""
        return url.split("?")[0].split("#")[0].strip()

    def first_href_in(card) -> str:
        """Best-effort: fetch a member profile URL from various possible anchors."""
        try:
            el = card.find_element(By.CSS_SELECTOR, "a.elementor-post__thumbnail__link")
            href = el.get_attribute("href") or ""
            if clean_url(href):
                return clean_url(href)
        except NoSuchElementException:
            pass
        
        selectors = [
            "h3.elementor-heading-title a",
            "a.elementor-post__read-more", 
            "header a",
            "a",
        ]
        for sel in selectors:
            try:
                el = card.find_element(By.CSS_SELECTOR, sel)
                href = el.get_attribute("href") or ""
                href = clean_url(href)
                if href:
                    return href
            except NoSuchElementException:
                continue
        return ""

    # Core scraper
    driver = new_driver()
    driver.get(BASE_URL)
    time.sleep(6)

    db: List[Dict[str, str]] = []
    page_num = 1
    total_cards_attempted = 0
    total_records_extracted = 0

    print(f"[{AID}] Starting NAM scraper...")

    try:
        while True:
            print(f"[{AID}] Scraping page {page_num}...")

            # Wait longer and more reliably for page content
            page_loaded = False
            for load_attempt in range(10):
                try:
                    WebDriverWait(driver, WAIT_SEC).until(
                        EC.presence_of_all_elements_located((By.CSS_SELECTOR, "article.elementor-post"))
                    )
                    time.sleep(1.5)
                    cards = driver.find_elements(By.CSS_SELECTOR, "article.elementor-post")
                    if len(cards) > 0:
                        page_loaded = True
                        break
                    else:
                        print(f"[{AID}] Page {page_num}: No cards found (attempt {load_attempt + 1}), retrying...")
                        time.sleep(2)
                except TimeoutException:
                    print(f"[{AID}] Page {page_num}: Timeout waiting for cards (attempt {load_attempt + 1}), retrying...")
                    time.sleep(2)
            
            if not page_loaded:
                print(f"[{AID}] Page {page_num}: Failed to load after multiple attempts, stopping...")
                break

            initial_card_count = len(driver.find_elements(By.CSS_SELECTOR, "article.elementor-post"))
            print(f"[{AID}] Page {page_num}: found {initial_card_count} cards on page")
            total_cards_attempted += initial_card_count

            page_records = 0

            for i in range(initial_card_count):
                card_processed = False
                card_attempts = 0
                
                while not card_processed and card_attempts < 50:
                    try:
                        card_attempts += 1
                        
                        # Helper function to safely extract data with retry
                        def get_card_data(card_index):
                            """Re-fetch card and extract all data to minimize stale references."""
                            cards_fresh = driver.find_elements(By.CSS_SELECTOR, "article.elementor-post")
                            if card_index >= len(cards_fresh):
                                return None
                            card = cards_fresh[card_index]
                            
                            data = {}
                            
                            # Extract all data in one go while card is fresh
                            try:
                                data["card_class"] = card.get_attribute("class") or ""
                            except:
                                data["card_class"] = ""
                            
                            # Year
                            try:
                                year_text = card.find_element(By.CSS_SELECTOR, "span.sd-post-date").text
                                if year_text:
                                    m = re.search(r"\b(19|20)\d{2}\b", year_text)
                                    data["year"] = m.group(0) if m else ""
                                else:
                                    data["year"] = ""
                            except:
                                data["year"] = ""
                            
                            # Name
                            data["name_raw"] = ""
                            name_selectors = [
                                "div.elementor-heading-title.elementor-size-default",
                                "h3.elementor-heading-title",
                                ".elementor-heading-title",
                                ".sd-member-name",
                            ]
                            for name_sel in name_selectors:
                                try:
                                    name_el = card.find_element(By.CSS_SELECTOR, name_sel)
                                    data["name_raw"] = name_el.text or ""
                                    if data["name_raw"].strip():
                                        break
                                except:
                                    continue
                            
                            # Profile URL
                            data["profile_url"] = ""
                            try:
                                el = card.find_element(By.CSS_SELECTOR, "a.elementor-post__thumbnail__link")
                                href = el.get_attribute("href") or ""
                                data["profile_url"] = clean_url(href)
                            except:
                                pass
                            
                            if not data["profile_url"]:
                                selectors = ["h3.elementor-heading-title a", "a.elementor-post__read-more", "header a", "a"]
                                for sel in selectors:
                                    try:
                                        el = card.find_element(By.CSS_SELECTOR, sel)
                                        href = clean_url(el.get_attribute("href") or "")
                                        if href:
                                            data["profile_url"] = href
                                            break
                                    except:
                                        continue
                            
                            # Member Type
                            data["member_type"] = ""
                            try:
                                type_elements = card.find_elements(By.CSS_SELECTOR, "div.sd-member-institutions span")
                                for elem in type_elements:
                                    text = (elem.text or "").strip()
                                    if text.lower() in ["emeritus", "international", "foreign associate"]:
                                        data["member_type"] = text
                                        break
                            except:
                                pass
                            
                            # Affiliation
                            data["affiliation"] = ""
                            try:
                                aff_container = card.find_element(By.CSS_SELECTOR, "div.sd-member-institutions")
                                aff_spans = aff_container.find_elements(By.CSS_SELECTOR, "span")
                                
                                for span in aff_spans:
                                    text = (span.text or "").strip()
                                    if text and text.lower() not in ["emeritus", "international", "foreign associate", "no affiliation", ""]:
                                        data["affiliation"] = text
                                        break
                                
                                if not data["affiliation"]:
                                    full_text = (aff_container.text or "").strip()
                                    lines = [line.strip() for line in full_text.split("\n") if line.strip()]
                                    for line in lines:
                                        if line.lower() not in ["emeritus", "international", "foreign associate", "no affiliation"]:
                                            data["affiliation"] = line
                                            break
                            except:
                                pass
                            
                            # Location
                            data["location"] = ""
                            try:
                                loc_el = card.find_element(By.CSS_SELECTOR, "div.sd-post-categories--card-pills span.sd-post-category")
                                data["location"] = loc_el.text or ""
                            except:
                                pass
                            
                            return data
                        
                        # Extract all data at once
                        card_data = get_card_data(i)
                        
                        if card_data is None:
                            print(f"[{AID}] Page {page_num}, Card {i+1}: Card disappeared, waiting...")
                            time.sleep(3.0)
                            continue
                        
                        # Process extracted data
                        deceased = "Y" if "health_status-deceased" in card_data["card_class"] else ""
                        name = clean_name(card_data["name_raw"])
                        profile_url = card_data["profile_url"]
                        year = card_data["year"]
                        member_type = card_data["member_type"]
                        aff = card_data["affiliation"]
                        location = card_data["location"]

                        # Create record
                        fallback_id = f"page_{page_num}_card_{i+1}"
                        
                        record = {
                            "id":             AID,
                            "govid":          GOVID,
                            "govname":        GOVNAME,
                            "award":          AWARD,
                            "name":           name or f"missing_name_{fallback_id}",
                            "profile_url":    norm_text(profile_url) or f"missing_url_{fallback_id}",
                            "year":           norm_text(year),
                            "affiliation":    norm_text(aff),
                            "location":       norm_text(location),
                            "member_type":    norm_text(member_type),
                            "deceased":       norm_text(deceased),
                        }
                        
                        db.append(record)
                        page_records += 1
                        total_records_extracted += 1
                        card_processed = True

                        if not name.strip() or not profile_url.strip():
                            print(f"[{AID}] Page {page_num}, Card {i+1}: Captured incomplete record - name: '{name[:30]}', url: '{profile_url[:50]}'")

                    except StaleElementReferenceException as e:
                        print(f"[{AID}] Page {page_num}, Card {i+1}: StaleElementReferenceException (attempt {card_attempts}), retrying...")
                        time.sleep(min(0.5 * (card_attempts // 5 + 1), 3.0))
                    except TimeoutException as e:
                        print(f"[{AID}] Page {page_num}, Card {i+1}: TimeoutException (attempt {card_attempts}) - {e}")
                        time.sleep(min(0.5 * (card_attempts // 5 + 1), 3.0))
                    except Exception as e:
                        print(f"[{AID}] Page {page_num}, Card {i+1}: Error processing (attempt {card_attempts}) - {type(e).__name__}: {e}")
                        time.sleep(min(0.5 * (card_attempts // 5 + 1), 3.0))

                if not card_processed:
                    print(f"[{AID}] Page {page_num}, Card {i+1}: FAILED after {card_attempts} attempts, creating placeholder record")
                    fallback_id = f"page_{page_num}_card_{i+1}_failed"
                    db.append({
                        "id":             AID,
                        "govid":          GOVID,
                        "govname":        GOVNAME,
                        "award":          AWARD,
                        "profile_url":    f"failed_to_extract_{fallback_id}",
                        "year":           "",
                        "name":           f"failed_extraction_{fallback_id}",
                        "affiliation":    "",
                        "location":       "",
                        "member_type":    "",
                        "deceased":       "",
                    })
                    total_records_extracted += 1

            print(f"[{AID}] Page {page_num}: processed {initial_card_count} cards, extracted {page_records} records (running total: {total_records_extracted})")

            # Pagination: more robust navigation detection
            try:
                time.sleep(1.0)
                
                current_url = driver.current_url
                current_article_count = len(driver.find_elements(By.CSS_SELECTOR, "article.elementor-post"))

                navigated = False
                for nav_attempt in range(5):
                    try:
                        next_btn = WebDriverWait(driver, WAIT_SEC).until(
                            EC.element_to_be_clickable((By.CSS_SELECTOR, "div.jet-filters-pagination__item.prev-next.next"))
                        )

                        if not next_btn or "disabled" in (next_btn.get_attribute("class") or ""):
                            print(f"[{AID}] Page {page_num}: No next button or disabled, scraping complete.")
                            navigated = False
                            break

                        print(f"[{AID}] Navigating to page {page_num + 1}...")
                        try:
                            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", next_btn)
                            time.sleep(0.5)
                            next_btn.click()
                        except Exception:
                            # Fallback to JS click if intercepted or other issues
                            driver.execute_script("arguments[0].click();", next_btn)

                        navigated = True
                        break
                    except StaleElementReferenceException:
                        print(f"[{AID}] Page {page_num}: Navigation button stale, retrying (attempt {nav_attempt + 1})")
                        time.sleep(1.0)
                    except TimeoutException:
                        print(f"[{AID}] Page {page_num}: Next button not found/clickable.")
                        navigated = False
                        break

                if not navigated:
                    break
                
                navigation_success = False
                for wait_attempt in range(40):
                    time.sleep(0.2)
                    try:
                        new_url = driver.current_url
                        new_article_count = len(driver.find_elements(By.CSS_SELECTOR, "article.elementor-post"))
                        
                        if (new_url != current_url or 
                            new_article_count != current_article_count or
                            new_article_count >= 10):
                            
                            WebDriverWait(driver, 3).until(
                                EC.presence_of_all_elements_located((By.CSS_SELECTOR, "article.elementor-post"))
                            )
                            navigation_success = True
                            break
                    except Exception:
                        continue
                
                if not navigation_success:
                    print(f"[{AID}] Page {page_num}: Navigation might have failed, but continuing...")
                
                time.sleep(PAGE_PAUSE)
                page_num += 1

            except (NoSuchElementException, TimeoutException):
                print(f"[{AID}] No more pages found. Scraping complete.")
                break
                
    finally:
        try:
            driver.quit()
        except Exception as e:
            print(f"[{AID}] Warning: driver.quit() raised an exception: {e}")

    # Build DataFrame
    df = pd.DataFrame(db, dtype=str).fillna("")
    print(f"Total records extracted: {len(df)}")
    
    if not df.empty:
        # Deduplication logic (Profile URL, Name+Year, Exact Row)
        df = df.sort_values(["profile_url", "name"])
        df = df.drop_duplicates()  # Exact row
        df = df.drop_duplicates(subset=["profile_url"], keep="first")
        df = df.drop_duplicates(subset=["name", "year"], keep="first")
        print(f"Final unique records: {len(df)}")

    # Save to CSV
    print(tabulate(df.head(20), headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{AID}.csv", index=False)
    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {AID} — scraped and saved at {now}")
    else:
        print(f"AwardID {AID} — no rows scraped.")

    return df

In [252]:
def scrape2023(): #NAS
    # Constants / Config
    AID        = "2023"
    AWARD      = "NAS Member"
    GOVID      = "222"
    GOVNAME    = "National Academy of Sciences"
    BASE_URL   = (
        "https://www.nasonline.org/membership/member-directory/"
        "?_member_directory_sort=last_name_asc&_per_page=100"
    )
    WAIT_SEC   = 15
    PAGE_PAUSE = 2.0

    # Helpers
    def new_driver() -> webdriver.Chrome:
        """Create a Chrome driver with sensible defaults."""
        opts = Options()
        opts.add_argument("--headless=new")
        opts.add_argument("--window-size=1920,1080")
        opts.add_argument("--disable-gpu")
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-dev-shm-usage")
        opts.add_argument(
            "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
        )
        opts.add_argument("--disable-background-sync")
        opts.add_argument("--disable-background-timer-throttling")
        opts.add_argument("--log-level=3")
        opts.add_argument("--disable-logging")
        return webdriver.Chrome(options=opts)

    def norm_text(s: Optional[str]) -> str:
        if not s:
            return ""
        s = s.strip()
        s = re.sub(r"\s+", " ", s)
        return s

    def clean_name(name: str) -> str:
        name = norm_text(name)
        prefixes = ["Dr. ", "Dr ", "Mr. ", "Mr ", "Ms. ", "Ms ", "Mrs. ", "Mrs ", "Prof. ", "Professor "]
        suffixes = [" Jr.", " Jr", " Sr.", " Sr", " II", " III", " IV", ", PhD", ", MD", ", DSc"]
        for p in prefixes:
            if name.startswith(p):
                name = name[len(p):]
        for s in suffixes:
            if name.endswith(s):
                name = name[:-len(s)]
        return norm_text(name)

    def clean_url(url: str) -> str:
        if not url:
            return ""
        return url.split("?")[0].split("#")[0].strip()

    def extract_card_info(card) -> Dict[str, str]:
        """Extract basic information from a member card on the directory page."""
        try:
            link_element = card.find_element(By.XPATH, ".//h5/a")
            profile_url = clean_url(link_element.get_attribute("href") or "")
            name_text = norm_text(link_element.text)
            
            card_classes = card.get_attribute("class") or ""
            membership_type = ""
            if "membership-type-member" in card_classes:
                membership_type = "member"
            elif "membership-type-international-member" in card_classes:
                membership_type = "international-member"
            elif "membership-type-emeritus" in card_classes:
                membership_type = "emeritus"
            elif "membership-type-public-welfare-medalist" in card_classes:
                membership_type = "public-welfare-medalist"
            
            deceased_status = ""
            if "living-deceased-deceased" in card_classes:
                deceased_status = "Y"
            
            affiliation = ""
            death_year = ""
            try:
                card_meta = card.find_element(By.CSS_SELECTOR, ".card-meta")
                meta_paragraphs = card_meta.find_elements(By.TAG_NAME, "p")
                
                membership_labels = ["member", "international member", "emeritus", "public welfare medalist"]
                for p in meta_paragraphs:
                    p_text = norm_text(p.text)
                    p_lower = p_text.lower()
                    if (p_text and 
                        p_lower not in membership_labels and
                        not p_text.startswith("Primary Section") and 
                        not p_text.startswith("Secondary Section") and
                        not p_text.startswith("Section ")):
                        
                        date_match = re.search(r'-\s*[A-Za-z]+\s+\d{1,2},\s+(\d{4})', p_text)
                        if date_match:
                            death_year = date_match.group(1)
                            affiliation = "" 
                        else:
                            affiliation = p_text
                        break
            except NoSuchElementException:
                affiliation = ""
            
            return {
                "profile_url": profile_url,
                "name": clean_name(name_text),
                "membership_type": membership_type,
                "deceased": deceased_status,
                "affiliation": affiliation,
                "death_year": death_year,
            }
        except Exception as e:
            return {}

    def scrape_year_cards(driver: webdriver.Chrome, year: int, url: str, processed_urls: Set[str]) -> List[Dict[str, str]]:
        cards_info: List[Dict[str, str]] = []
        try:
            driver.get(url)
            WebDriverWait(driver, WAIT_SEC).until(
                EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]"))
            )
            
            member_cards = driver.find_elements(By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]")
            if not member_cards:
                return cards_info
                
            page_num = 1
            while True:
                for card in member_cards:
                    try:
                        card_info = extract_card_info(card)
                        if card_info and card_info.get("profile_url"):
                            url_key = card_info["profile_url"]
                            if url_key not in processed_urls:
                                card_info["year"] = str(year)
                                cards_info.append(card_info)
                                processed_urls.add(url_key)
                    except Exception:
                        continue
                
                try:
                    next_button = driver.find_element(By.XPATH, "//a[@class='next page-numbers']")
                    driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", next_button)
                    time.sleep(0.5)
                    driver.execute_script("arguments[0].click();", next_button)
                    time.sleep(PAGE_PAUSE)
                    
                    WebDriverWait(driver, 10).until(
                        EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]"))
                    )
                    member_cards = driver.find_elements(By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]")
                    page_num += 1
                except (NoSuchElementException, TimeoutException):
                    break
        except TimeoutException:
            pass
        except Exception:
            pass
        return cards_info

    def scrape_all_pages(driver: webdriver.Chrome, processed_urls: Set[str]) -> List[Dict[str, str]]:
        try:
            driver.get(BASE_URL)
            WebDriverWait(driver, WAIT_SEC).until(
                EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]"))
            )
        except Exception:
            return []

        cards_info: List[Dict[str, str]] = []
        current_page = 1
        consecutive_empty_pages = 0
        max_consecutive_empty = 3

        while consecutive_empty_pages < max_consecutive_empty:
            try:
                member_cards = WebDriverWait(driver, WAIT_SEC).until(
                    EC.presence_of_all_elements_located((By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]"))
                )
                
                cards_found_on_page = 0
                for card in member_cards:
                    try:
                        card_info = extract_card_info(card)
                        if card_info and card_info.get("profile_url"):
                            url = card_info["profile_url"]
                            if url not in processed_urls:
                                cards_info.append(card_info)
                                processed_urls.add(url)
                                cards_found_on_page += 1
                    except Exception:
                        continue
                
                if cards_found_on_page == 0:
                    consecutive_empty_pages += 1
                else:
                    consecutive_empty_pages = 0

                next_button = None
                try:
                    next_button = WebDriverWait(driver, 5).until(
                        EC.element_to_be_clickable((By.XPATH, "//a[@class='next page-numbers']"))
                    )
                except (NoSuchElementException, TimeoutException):
                    try:
                        next_button = driver.find_element(By.XPATH, "//a[contains(@class, 'next')]")
                    except NoSuchElementException:
                        break

                if next_button:
                    try:
                        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", next_button)
                        time.sleep(1)
                        driver.execute_script("arguments[0].click();", next_button)
                        time.sleep(PAGE_PAUSE)
                        
                        WebDriverWait(driver, 10).until(
                            EC.presence_of_element_located((By.XPATH, "//div[contains(@class, 'fl-post-grid-post')]"))
                        )
                        current_page += 1
                    except Exception:
                        break
                else: 
                    break
            except Exception:
                break
        return cards_info

    # Core scraper logic
    driver = new_driver()
    driver.implicitly_wait(5)
    
    all_cards_info: List[Dict[str, str]] = []
    processed_urls: Set[str] = set()
    
    current_year = datetime.now().year
    start_year = 1863
    
    print(f"[{AID}] Starting card collection by iterating through years {start_year}-{current_year}")
    
    for year in range(start_year, current_year + 1):
        year_url = f"{BASE_URL}&_election_year={year}"
        cards_from_year = scrape_year_cards(driver, year, year_url, processed_urls)
        all_cards_info.extend(cards_from_year)
        time.sleep(0.2)
    
    print(f"[{AID}] Year-based scraping collected {len(all_cards_info)} profiles")
    
    if len(all_cards_info) < 1000:
        print(f"[{AID}] Year-based scraping yielded only {len(all_cards_info)} results, trying full directory scan...")
        processed_urls.clear()
        fallback_cards = scrape_all_pages(driver, processed_urls)
        
        if len(fallback_cards) > len(all_cards_info):
            print(f"[{AID}] Using fallback results: {len(fallback_cards)} profiles")
            all_cards_info = fallback_cards
        else:
            print(f"[{AID}] Keeping year-based results: {len(all_cards_info)} profiles")

    driver.quit()
    
    # Add standard metadata fields
    for card_info in all_cards_info:
        card_info.setdefault("id", AID)
        card_info.setdefault("govid", GOVID)
        card_info.setdefault("govname", GOVNAME)
        card_info.setdefault("award", AWARD)

    # Build DataFrame
    df = pd.DataFrame(all_cards_info, dtype=str).fillna("")
    print(f"Total records extracted: {len(df)}")
    
    # Standardize columns
    desired_order = [
        "id", "govid", "govname", "award", 
        "name", "profile_url", "year", 
        "affiliation", "location", "membership_type", 
        "deceased", "death_year"
    ]
    existing_cols = df.columns.tolist()
    final_cols = [c for c in desired_order if c in existing_cols]
    remaining_cols = [c for c in existing_cols if c not in final_cols]
    if not df.empty:
        df = df[final_cols + remaining_cols]

    if not df.empty:
        # Deduplication logic (Profile URL, Name+Year, Exact Row)
        df = df.sort_values(["profile_url", "name"])
        df = df.drop_duplicates()  # Exact row
        df = df.drop_duplicates(subset=["profile_url"], keep="first")
        df = df.drop_duplicates(subset=["name", "year"], keep="first")
        print(f"Final unique records: {len(df)}")

    print(tabulate(df.head(20), headers='keys', tablefmt='psql'))
    # Save CSV
    df.to_csv(f"{filepath}{AID}.csv", index=False)
    if not df.empty:
        now = datetime.now().strftime("%H:%M:%S")
        print(f"AwardID {AID} — scraped ({len(df)} rows) and saved at {now}")
    else:
        print(f"AwardID {AID} — no rows scraped.")

    return df

### List C

In [253]:
def scrape2092():
    award = "National Book Award-Fiction"
    govid = "228"
    govname = "National Book Foundation"
    aid = "2092"
    url = "https://www.nationalbook.org/national-book-awards/search/?type=category&search=fiction"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    while True:
        try:
            page_data = driver.find_element(By.ID, 'books-results')
            book_datas = page_data.find_elements(By.CLASS_NAME, 'book-item')
            for bookdata in book_datas:
                link = bookdata.get_attribute('href')
                links.append(link)

            driver.find_element(By.PARTIAL_LINK_TEXT, "Next").click()

            time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        title = driver.find_element(By.TAG_NAME, 'h1').text
        print(title)
        
        subtitle = driver.find_element(By.TAG_NAME, 'h2').text
        
        split_parts = subtitle.split(", ")
        position = split_parts[0]
        
        year = re.findall(r'\d+', subtitle)[0]
        print(year)

        bio = driver.find_element(By.CLASS_NAME, 'authors-wrapper')
        try:
            name = bio.find_element(By.TAG_NAME, 'figcaption').text
            print(name)
        except NoSuchElementException:
            name = None
        
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'title': title, 'position': position})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [254]:
def scrape2094():
    award = "National Book Award-Nonfiction"
    govid = "228"
    govname = "National Book Foundation"
    aid = "2094"
    url = "https://www.nationalbook.org/national-book-awards/search/?type=category&search=nonfiction"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    while True:
        try:
            page_data = driver.find_element(By.ID, 'books-results')
            book_datas = page_data.find_elements(By.CLASS_NAME, 'book-item')
            for bookdata in book_datas:
                link = bookdata.get_attribute('href')
                links.append(link)

            driver.find_element(By.PARTIAL_LINK_TEXT, "Next").click()

            time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        title = driver.find_element(By.TAG_NAME, 'h1').text
        
        subtitle = driver.find_element(By.TAG_NAME, 'h2').text
        
        split_parts = subtitle.split(", ")
        position = split_parts[0]
        
        year = re.findall(r'\d+', subtitle)[0]

        bio = driver.find_element(By.CLASS_NAME, 'authors-wrapper')
        try:
            name = bio.find_element(By.TAG_NAME, 'figcaption').text

        except NoSuchElementException:
            name = None
        
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'title': title, 'position': position})

    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [255]:
def scrape2095():
    award = "National Book Award-Poetry"
    govid = "228"
    govname = "National Book Foundation"
    aid = "2095"
    url = "https://www.nationalbook.org/national-book-awards/search/?type=category&search=poetry"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    while True:
        try:
            page_data = driver.find_element(By.ID, 'books-results')
            book_datas = page_data.find_elements(By.CLASS_NAME, 'book-item')
            for bookdata in book_datas:
                link = bookdata.get_attribute('href')
                links.append(link)

            driver.find_element(By.PARTIAL_LINK_TEXT, "Next").click()

            time.sleep(3)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        title = driver.find_element(By.TAG_NAME, 'h1').text
        
        subtitle = driver.find_element(By.TAG_NAME, 'h2').text
        
        split_parts = subtitle.split(", ")
        position = split_parts[0]
        try:
            year = re.findall(r'\d+', subtitle)[0]
        except IndexError:
            print('IndexError')
        bio = driver.find_element(By.CLASS_NAME, 'authors-wrapper')
        try:
            name = bio.find_element(By.TAG_NAME, 'figcaption').text

        except NoSuchElementException:
            name = None
        
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'title': title, 'position': position})

    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [256]:
def scrape2835():
    award = "Templeton Prize"
    govid = "354"
    govname = "John Templeton Foundation"
    aid = "2835"
    url = "https://www.templetonprize.org/templeton-prize-winners-2/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    while True:
            try:
                page_data = driver.find_element(By.ID, 'laureate-container')
                print(page_data.text)
                lau_data = page_data.find_elements(By.CLASS_NAME, 'laureate-item')
                for lau in lau_data:
                    lc = lau.find_element(By.CLASS_NAME, 'laureate-content')
                    print(lc.text)
                    h2 = lc.find_element(By.TAG_NAME, 'h2')

                    ltext = h2.get_attribute('textContent')
                    name = ltext.split('(')[0].strip()
                    year = ltext.split('(')[1].strip().strip(')')

                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

                driver.find_element(By.CLASS_NAME, "mixitup-control mixitup-control-next").click()

                time.sleep(2)

            except NoSuchElementException:
                break

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [257]:
def scrape2708():
    award = "The Beckman Scholars Program"
    govid = "329"
    govname = "Arnold and Mabel Beckman Foundation"
    aid = "2708"
    url = "https://www.beckman-foundation.org/awarded-scientists/?award_program=Beckman%20Scholar"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    while True:
                try:
                    page_data = driver.find_element(By.CLASS_NAME, 'card-grid--3')
                    lau_data = page_data.find_elements(By.CLASS_NAME, 'card-large')
                    for lau in lau_data:
                        link = lau.get_attribute('href')
                        links.append(link)

                    wait = WebDriverWait(driver, 10)
                    button = wait.until(EC.element_to_be_clickable((By.XPATH, '//nav[@role="navigation"]//a[@class="next"]')))
                    driver.execute_script("arguments[0].click();", button)

                    time.sleep(2)

                except NoSuchElementException:
                    break

                except TimeoutException:
                    print("Reached the last page.")
                    break

    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        try:
            card = driver.find_element(By.CLASS_NAME, "person-overview__content-container")
            name = card.find_element(By.TAG_NAME, 'h1').text
            year = card.find_element(By.CLASS_NAME, 'icon-link-text__date').text

            card2 = driver.find_element(By.CLASS_NAME, 'award-item')
            affiliation = card2.find_element(By.CLASS_NAME, 'award-item__location').text
            affiliation = affiliation.split(': ')[1]
            
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': affiliation})

        except NoSuchElementException:
            print(link + " ERROR: NoSuchElementException")

    df = pd.DataFrame(db)

    pattern = r"(?:Mr\.|Ms\.|Dr\.|Prof\.)\s*([A-Z][a-z]+(?:-[A-Z][a-z]+)*)"
    df['name_without_title'] = df['name'].apply(lambda x: re.sub(pattern, r"\1", x))
    df = df.drop(columns=['name']).rename(columns={'name_without_title': 'name'})
    display(df)

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [258]:
def scrape2096():
    award = "National Book Award-Young People's Literature"
    govid = "228"
    govname = "National Book Foundation"
    aid = "2096"
    url = "https://www.nationalbook.org/national-book-awards/search/?type=category&search=ypl"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    while True:
        try:
            page_data = driver.find_element(By.ID, 'books-results')
            book_datas = page_data.find_elements(By.CLASS_NAME, 'book-item')
            for bookdata in book_datas:
                link = bookdata.get_attribute('href')
                links.append(link)

            driver.find_element(By.PARTIAL_LINK_TEXT, "Next").click()

            time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        title = driver.find_element(By.TAG_NAME, 'h1').text
        
        subtitle = driver.find_element(By.TAG_NAME, 'h2').text
        
        split_parts = subtitle.split(", ")
        position = split_parts[0]
        
        year = re.findall(r'\d+', subtitle)[0]

        bio = driver.find_element(By.CLASS_NAME, 'authors-wrapper')
        try:
            name = bio.find_element(By.TAG_NAME, 'figcaption').text

        except NoSuchElementException:
            name = None
        
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'title': title, 'position': position})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [259]:
def scrape2937():
    award = "Donald B Lindsley Prize in Behavioral Neuroscience"
    govid = "390"
    govname = "Society for Neuroscience"
    aid = "2937"
    url = "https://www.sfn.org/careers/awards/early-career/donald-b-lindsley-prize-in-behavioral-neuroscience"
    db = []

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    pastawardees = soup.find('h2', string='Past Awardees')
    pattern = r'(\d{4}): (.+), PhD'
    if pastawardees:
        ultag = pastawardees.find_next_sibling('ul')
        if ultag:
            lis = ultag.find_all('li')
            for li in lis:
                li_text = li.text.replace('\xa0', ' ')
                li = li_text.split(':')
                year = li[0]
                name = li[1].strip()
                name = name.replace('; ', ', ')
                name = name.replace('and ', ', ')
                names = [n.strip() for n in name.split(',') if n.strip()]
                nl = []
                for n in names:
                    if n != 'PhD' and n != 'MD':
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': n})
    df = pd.DataFrame(db)
    df = df[df['name'].str.len() >= 3]
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [260]:
def scrape2942():
    award = "Ralph W Gerard Prize in Neuroscience"
    govid = "390"
    govname = "Society for Neuroscience"
    aid = "2942"
    url = "https://www.sfn.org/careers/awards/outstanding-career-and-research-achievements-awards/ralph-w-gerard-prize"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    pastawardees = soup.find('h2', string='Past Awardees')
    pattern = r'(\d{4}): (.+), PhD'
    if pastawardees:
        ultag = pastawardees.find_next_sibling('ul')
        if ultag:
            lis = ultag.find_all('li')
            for li in lis:
                li_text = li.text.replace('\xa0', ' ')
                li = li_text.split(':')
                year = li[0]
                name = li[1].strip()
                name = name.replace('; ', ', ')
                name = name.replace('and ', ', ')
                names = [n.strip() for n in name.split(',') if n.strip()]
                nl = []
                for n in names:
                    if n != 'PhD' and n != 'MD':
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': n})
    df = pd.DataFrame(db)
    df = df[df['name'].str.len() > 3]
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [261]:
def scrape2770():
    award = "Grawemeyer Award for Music Composition"
    govid = "347"
    govname = "Grawemeyer Foundation"
    aid = "2770"
    url = "http://grawemeyer.org/music-composition/#toggle-id-3"
    db = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    prevwinners = soup.find('div', id='toggle-id-3')
    strong_texts = [strong_tag.get_text() for strong_tag in prevwinners.find_all('strong')]
    for text in strong_texts:
        text = text.replace('–\xa0', ' – ')
        splittext = text.split(' – ')
        name = splittext[1]
        year = splittext[0]
        if name != 'No Award Given':
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [262]:
def scrape2771():
    award = "Grawemeyer Award in Religion"
    govid = "347"
    govname = "Grawemeyer Foundation"
    aid = "2771"
    url = "http://grawemeyer.org/religion/#toggle-id-3"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    prevwinners = soup.find('div', id='toggle-id-3')
    ps =  prevwinners.find_all('p')

    for p in ps:
        strong_texts = [strong_tag.get_text() for strong_tag in p.find_all('strong')]
        if len(strong_texts) > 1:
            concat_text = strong_texts[0] + " " + strong_texts[1]
            strong_texts = [concat_text]
    
        for text in strong_texts:
            text = text.replace('–\xa0', ' – ')
            splittext = text.split(' – ')
            name = splittext[1]
            year = splittext[0]
            if name != 'No Award Given':
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [263]:
def scrape2778():
    award = "Kyoto Prize"
    govid = "349"
    govname = "Inamori Foundation of Japan"
    aid = "2778"
    url = "https://www.kyotoprize.org/en/laureates/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    ul = soup.find('ul', class_="laureates")
    lis = ul.find_all('li')
    for li in lis:
        name = li.find('p', class_="laureate__name").text
        year = li.find('span', string=lambda text: text.isnumeric()).text
        field = li.find('p', class_="laureate__department").text.strip("[]")
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [264]:
def scrape2853():
    award = "Haskins Medal for a Distinguished Book"
    govid = "359"
    govname = "Medieval Academy of America"
    aid = "2853"
    url = "https://www.medievalacademy.org/page/Haskins_Recipients"
    db = []
    
    chrome_options = Options()
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36')
    
    driver = webdriver.Chrome(options=chrome_options)
    
    try:
        driver.get(url)
        
        wait = WebDriverWait(driver, 10)
        mdiv = wait.until(EC.presence_of_element_located((By.ID, 'CustomPageBody')))
        
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'html.parser')
        
        mdiv = soup.find('div', id='CustomPageBody')
        ps = mdiv.find_all('p')
        
        for p in ps[:2]:
            ptext = p.text
            year = ptext.split(':')[0].strip()
            name = ptext.split(':')[1].split(',')[0].strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
        for p in ps[2:]:
            spans = p.find_all('span')
            for span in spans:
                ems = span.find_all('em')
                for em in ems:
                    emtext = em.previous_sibling.strip()
                    year = emtext.split(':')[0].strip()
                    names = emtext.split(':')[1].strip(',').strip().split(' and ')
                    for name in names:
                        name = name.strip()
                        name = re.sub(r'^(Dr\.|Prof\.|Professor|Mr\.|Mrs\.|Ms\.|Rev\.|Sir)\s+', '', name)
                        name = re.sub(r',?\s+(Ph\.?D\.?|M\.?D\.?|Esq\.?)$', '', name)
                        name = re.sub(r'\s+', ' ', name)
                        if len(year) == 4:
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    finally:
        driver.quit()
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [265]:
def scrape2662():
    award = "ASBMB-Merck Award"
    govid = "318"
    govname = "American Society for Biochemistry and Molecular Biology"
    aid = "2662"
    url = "https://www.asbmb.org/about/award-winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    links = []

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    main = driver.find_element(By.CLASS_NAME, "section--flushEnd")
    cards = main.find_elements(By.CLASS_NAME, "contentSlab-headingLink")
    for card in cards:
        link = card.get_attribute('href')
        links.append(link)

    for link in links:
        driver.get(link)
        year = driver.find_element(By.CLASS_NAME, 'articleView-title').text.split()[0]
        profcards = driver.find_elements(By.CLASS_NAME, 'profileSlab')
        for card in profcards:
            awaname = card.find_element(By.CLASS_NAME, 'profileSlab-heading')
            if awaname.text == "ASBMB–Merck Award":
                name_parts = card.find_element(By.CLASS_NAME, "profileSlab-infoItem-awardee").text.split('&')
                for name_part in name_parts:
                    name = name_part.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

In [266]:
def scrape2565():
    award = "Lifetime Achievement Award"
    govid = "304"
    govname = "American Association for the History of Medicine"
    aid = "2565"
    url = "https://histmed.org/genevieve-miller-lifetime-achievement-award/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    list_title = soup.find('h3', string='Lifetime Achievement Award Winners')
    ul_tag = list_title.find_next_sibling('ul')
    lis = ul_tag.find_all('li')
    for li in lis:
        row = li.text.split(':')
        year = row[0].strip()
        names = row[1].split('&')
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

In [267]:
def scrape2561():
    award = "ASA Best Book Prize"
    govid = "302"
    govname = "African Studies Association"
    aid = "2561"
    url = "https://africanstudies.org/awards-prizes/asa-best-book-prize/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    list = driver.find_element(By.CLASS_NAME, 'eb-feature-list-items')
    lis = list.find_elements(By.CLASS_NAME, 'eb-feature-list-item')
    for li in lis:
        year = li.find_element(By.TAG_NAME, 'h3').text
        line = li.find_element(By.CLASS_NAME, 'eb-feature-list-content').text.split(',')
        name = line[0].strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    now = datetime.now()
    if not df.empty:
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

In [268]:
def scrape2274():
    # Configure logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger("OAH_Scraper_2274")
    logger.setLevel(logging.INFO)
    
    award = "Merle Curti Award"
    govid = "252"
    govname = "Organization of American Historians"
    aid = "2274"
    target_url = "https://www.oah.org/awards/book-awards-and-prizes/merle-curti-social-history-award/"
    
    profile_path = os.path.join(os.getcwd(), "chrome_profile")
    if not os.path.exists(profile_path): 
        os.makedirs(profile_path)
    
    # Close existing Chrome
    try:
        os.system("taskkill /f /im chrome.exe >nul 2>&1")
    except: 
        pass
    time.sleep(1)

    # Find Chrome executable
    chrome_paths = [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        os.path.expanduser(r"~\AppData\Local\Google\Chrome\Application\chrome.exe")
    ]
    chrome_exe = next((p for p in chrome_paths if os.path.exists(p)), None)
    
    if not chrome_exe:
        logger.error("Could not find Chrome executable!")
        return pd.DataFrame()

    # Launch Chrome with CDP
    start_cmd = [
        chrome_exe,
        f"--user-data-dir={profile_path}", 
        "--remote-debugging-port=9222",
        "--no-first-run",
        "--disable-blink-features=AutomationControlled", 
        target_url
    ]
    
    subprocess.Popen(start_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    logger.info("Chrome launched via CDP. Connecting...")
    time.sleep(3)

    raw_text_content = ""
    try:
        from selenium.webdriver.chrome.options import Options as ChromeOptions
        
        chrome_opts = ChromeOptions()
        chrome_opts.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
        
        from selenium import webdriver
        driver = webdriver.Chrome(options=chrome_opts)
        
        # Wait for actual page content to load
        logger.info("Waiting for page to fully load...")
        max_wait = 30
        wait_interval = 2
        content_loaded = False
        
        for attempt in range(max_wait // wait_interval):
            time.sleep(wait_interval)
            
            try:
                title = driver.title
                body_text = driver.find_element(By.TAG_NAME, "body").text
                toggles = driver.find_elements(By.CSS_SELECTOR, ".ep_toggles_item, .ep_toggles_icon, span.eplusicon-chevron-down")
                
                if "just a moment" not in title.lower() and len(toggles) > 0 and len(body_text) > 1000:
                    logger.info(f"✅ Content loaded! Found {len(toggles)} toggle elements after {(attempt + 1) * wait_interval}s")
                    content_loaded = True
                    break
            except:
                pass
        
        if not content_loaded:
            logger.warning("⚠️ Content may not be fully loaded, but proceeding...")
        
        # Verify we're not still on CAPTCHA page
        final_title = driver.title
        if "just a moment" in final_title.lower():
            logger.error("❌ Still on CAPTCHA/loading page. Extraction failed.")
            return pd.DataFrame()
        
        # Extract content
        logger.info(f"Extracting content from '{final_title}'...")
        
        # Dismiss cookie consent popup if present
        try:
            consent_buttons = driver.find_elements(By.CSS_SELECTOR, "#wpconsent-container button, .cookie-consent button, button[id*='accept'], button[id*='consent']")
            if consent_buttons:
                for btn in consent_buttons:
                    try:
                        if 'accept' in btn.text.lower() or 'agree' in btn.text.lower():
                            btn.click()
                            logger.info("✅ Dismissed cookie consent popup")
                            time.sleep(0.5)
                            break
                    except:
                        pass
        except:
            pass
        
        # Click "Past Winners" toggle using the full div element (more reliable)
        try:
            # Find the toggle by the title div that contains "Past Winners"
            toggle_divs = driver.find_elements(By.CSS_SELECTOR, ".ep_toggle_item_title")
            for toggle_div in toggle_divs:
                if "past winners" in toggle_div.text.lower():
                    # Use JavaScript click to avoid overlay issues
                    driver.execute_script("arguments[0].click();", toggle_div)
                    logger.info("✅ Clicked 'Past Winners' toggle")
                    time.sleep(0.5)
                    break
        except Exception as e:
            logger.warning(f"⚠️ Could not click toggle via div: {e}")
            # Fallback to original method
            toggle_elements = driver.find_elements(By.CSS_SELECTOR, "span.ep_toggles_icon.eplusicon-chevron-down")
            if len(toggle_elements) >= 3:
                driver.execute_script("arguments[0].click();", toggle_elements[2])
                time.sleep(0.5)

        # Extract text from "Past Winners" section
        try:
            # Find the content div that follows "Past Winners" title
            content_divs = driver.find_elements(By.CLASS_NAME, 'ep_toggle_item_content')
            # Try to find the one that contains winner text (usually has year patterns)
            for idx, mdiv in enumerate(content_divs):
                text_preview = mdiv.text[:100]
                # Check if this looks like winner data (contains years like 2024, 2023, etc.)
                if any(str(year) in mdiv.text for year in range(2020, 2026)):
                    logger.info(f"Found winner content in section {idx}")
                    break
            else:
                # Fallback to third element (index 2)
                logger.info("Using fallback: content section index 2")
                mdiv = content_divs[2]
        except Exception as e:
            logger.warning(f"Content section detection failed: {e}, using index 2")
            mdiv = driver.find_elements(By.CLASS_NAME, 'ep_toggle_item_content')[2]
        ps = mdiv.find_elements(By.TAG_NAME, 'p')

        ptexts = []
        for p in ps:
            ptext = p.text
            ptexts.append(ptext)
        
        raw_text_content = '\n'.join(ptexts)
        
        if len(raw_text_content) < 500:
            logger.error(f"❌ Content too short ({len(raw_text_content)} chars).")
            return pd.DataFrame()
            
        logger.info(f"✅ Successfully captured {len(raw_text_content)} characters.")

    except Exception as e:
        logger.error(f"Error during extraction: {e}")
        return pd.DataFrame()

    if not raw_text_content:
        logger.error(f"Failed to retrieve winner text for Award {aid}.")
        return pd.DataFrame()

    db = []
    try:
        prompt = f"""
            Please extract the winner's Name, Year, Affiliation, and Subaward from the text below. Output the result as a Markdown table.

            **Requirements:**
            - Header row must be: `| Year | Name | Affiliation | Subaward |`
            - Each winner must get their own row. If an award is shared, create separate rows for each winner.
            - 'Year' column must be a four-digit year.
            - 'Name' column must be the full name of the winner.
            - 'Affiliation' column is the university/institution. Leave blank if not provided.
            - 'Subaward' column is 'Social History' or 'Intellectual History'. Leave blank if not specified.
            - Do not include book titles or honorable mentions.
            - Output only the Markdown table.

            **Text to parse:**
            {raw_text_content}
        """
        
        logger.info("Sending text to AI model...")
        response = model.generate_content(prompt)
        
        lines = response.text.strip().splitlines()
        table_lines = [l for l in lines if l.strip().startswith("|")]
        data_rows = table_lines[2:]

        for row in data_rows:
            cols = [c.strip() for c in row.split("|")[1:-1]]
            if len(cols) == 4:
                year, name, affiliation, subaward = cols
                if name and year.isdigit():
                    db.append({
                        'id': aid, 'govid': govid, 'govname': govname, 'award': award,
                        'year': int(year), 'name': name, 'affiliation': affiliation, 'subaward': subaward
                    })
    except Exception as e:
        logger.error(f"AI processing error for Award {aid}: {e}")
        return pd.DataFrame()

    if not db:
        logger.warning(f"No data was extracted for Award {aid}.")
        return pd.DataFrame()

    driver.quit()

    df = pd.DataFrame(db)
    df.drop_duplicates(subset=['name', 'year', 'subaward'], inplace=True)
    df['affiliation'] = df['affiliation'].fillna("")
    df['subaward'] = df['subaward'].fillna("")
        
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    logger.info(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [269]:
def scrape2270():
    # Configure logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger("OAH_Scraper")
    logger.setLevel(logging.INFO)

    # --- Classes customized for OAH ---

    class OAHCookieManager:
        def __init__(self, profile_folder):
            self.cookie_path = os.path.join(profile_folder, "oah_cookies.json")
            
        def load(self):
            try:
                if not os.path.exists(self.cookie_path):
                    return []
                with open(self.cookie_path, "r", encoding="utf-8") as fh:
                    data = json.load(fh)
                return data if isinstance(data, list) else []
            except Exception as exc:
                logger.warning(f"Failed to read cookies: {exc}")
            return []

        def save(self, cookies: list) -> bool:
            try:
                with open(self.cookie_path, "w", encoding="utf-8") as fh:
                    json.dump(cookies, fh, ensure_ascii=False, indent=2)
                return True
            except Exception as exc:
                logger.error(f"Failed to save cookies: {exc}")
                return False

        def _sanitize_cookie(self, cookie: dict) -> dict:
            sanitized = {
                "name": cookie.get("name"),
                "value": cookie.get("value"),
            }
            if cookie.get("domain"): sanitized["domain"] = cookie["domain"]
            else: sanitized["domain"] = ".oah.org"
            
            if cookie.get("path"): sanitized["path"] = cookie["path"]
            else: sanitized["path"] = "/"
            
            if "secure" in cookie: sanitized["secure"] = cookie["secure"]
            if "httpOnly" in cookie: sanitized["httpOnly"] = cookie["httpOnly"]
            if "expiry" in cookie: sanitized["expiry"] = int(cookie["expiry"])
            return sanitized

        def apply_to_driver(self, driver, base_url="https://www.oah.org/"):
            cookies = self.load()
            if not cookies:
                return False
            
            logger.info(f"Loading {len(cookies)} cookies from file...")
            try:
                driver.get(base_url)
            except:
                pass
            
            # When attaching via CDP, deleting cookies manually can be flaky, skipping blanket delete
            # driver.delete_all_cookies()
            
            applied_count = 0
            for cookie in cookies:
                if "oah.org" in cookie.get("domain", ""):
                    try:
                        driver.add_cookie(self._sanitize_cookie(cookie))
                        applied_count += 1
                    except:
                        pass
            
            logger.info(f"Applied {applied_count} OAH-specific cookies.")
            driver.get(base_url)
            return True

        def capture_from_driver(self, driver):
            try:
                cookies = driver.get_cookies()
                if self.save(cookies):
                    logger.info("Cookies captured and saved.")
            except Exception as exc:
                logger.error(f"Error capturing cookies: {exc}")

    class AdaptiveHumanBehaviorSimulator:
        def __init__(self):
            self.last_action_time = time.time()
        
        def human_delay(self, min_sec: float = 0.5, max_sec: float = 2.0):
            delay = random.uniform(min_sec, max_sec)
            time.sleep(delay)

    # --- Main Scraper Execution ---
    award = "Frederick Jackson Turner Award"
    govid = "252"
    govname = "Organization of American Historians"
    aid = "2270"
    target_url = "https://www.oah.org/awards/book-awards-and-prizes/frederick-jackson-turner-award/"
    
    profile_path = os.path.join(os.getcwd(), "chrome_profile")
    if not os.path.exists(profile_path): os.makedirs(profile_path)
    
    cookie_manager = OAHCookieManager(profile_path)
    simulator = AdaptiveHumanBehaviorSimulator()
    
    # -------------------------------------------------------------------------
    # STRATEGY: Remote Debugging Port (CDP)
    # -------------------------------------------------------------------------
    
    # logger.info("Step 1: Closing any existing Chrome instances...")
    try:
        os.system("taskkill /f /im chrome.exe >nul 2>&1")
    except: 
        pass
    time.sleep(1)

    # logger.info("Step 2: Launching Chrome Manually...")
    # Find Chrome executable
    chrome_paths = [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        os.path.expanduser(r"~\AppData\Local\Google\Chrome\Application\chrome.exe")
    ]
    chrome_exe = next((p for p in chrome_paths if os.path.exists(p)), None)
    
    if not chrome_exe:
        logger.error("Could not find Chrome executable in standard paths!")
        return pd.DataFrame()

    # Launch args
    start_cmd = [
        chrome_exe,
        f"--user-data-dir={profile_path}", 
        "--remote-debugging-port=9222",
        "--no-first-run",
        "--disable-blink-features=AutomationControlled", 
        target_url
    ]
    
    # Clean output
    subprocess.Popen(start_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    logger.info("Chrome launched via CDP. Connecting...")
    time.sleep(3)

    try:
        from selenium.webdriver.chrome.options import Options as ChromeOptions
        
        chrome_opts = ChromeOptions()
        chrome_opts.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
        
        from selenium import webdriver
        driver = webdriver.Chrome(options=chrome_opts)
        
        # Wait for actual page content to load (not just CAPTCHA page)
        logger.info("Waiting for page to fully load...")
        max_wait = 30  # Maximum 30 seconds
        wait_interval = 2  # Check every 2 seconds
        content_loaded = False
        
        for attempt in range(max_wait // wait_interval):
            time.sleep(wait_interval)
            
            try:
                title = driver.title
                body_text = driver.find_element(By.TAG_NAME, "body").text
                toggles = driver.find_elements(By.CSS_SELECTOR, ".ep_toggles_item, .ep_toggles_icon, span.eplusicon-chevron-down")
                
                # Check if actual content has loaded (not CAPTCHA page)
                if "just a moment" not in title.lower() and len(toggles) > 0 and len(body_text) > 1000:
                    logger.info(f"✅ Content loaded! Found {len(toggles)} toggle elements after {(attempt + 1) * wait_interval}s")
                    content_loaded = True
                    break
                else:
                    logger.debug(f"Still loading... (attempt {attempt + 1}/{max_wait // wait_interval}) Title: '{title}', Toggles: {len(toggles)}, Text length: {len(body_text)}")
            except:
                pass
        
        if not content_loaded:
            logger.warning("⚠️ Content may not be fully loaded, but proceeding with extraction anyway...")
        
        # Save cookies for next run
        try:
            cookie_manager.capture_from_driver(driver)
        except:
            pass
        
        # Extract Data
        final_title = driver.title
        logger.info(f"Extracting content from '{final_title}'...")
        
        # Verify we're not still on CAPTCHA page
        if "just a moment" in final_title.lower():
            logger.error("❌ Still on CAPTCHA/loading page. Extraction failed.")
            return pd.DataFrame()
        
        # Expand toggles to reveal all content
        try:
            toggles = driver.find_elements(By.CSS_SELECTOR, ".ep_toggles_icon")
            if toggles:
                logger.info(f"Expanding {len(toggles)} data toggles...")
                for t in toggles:
                    try: 
                        driver.execute_script("arguments[0].click();", t)
                        time.sleep(0.1)
                    except: 
                        pass
                time.sleep(1)
        except: 
            pass
        
        # Grab all page content
        raw_text_content = driver.find_element(By.TAG_NAME, "body").text
        
        # Final verification
        if len(raw_text_content) < 500:
            logger.error(f"❌ Content too short ({len(raw_text_content)} chars). Page may not have loaded properly.")
            return pd.DataFrame()
            
        logger.info(f"✅ Successfully captured {len(raw_text_content)} characters. Sending to AI...")
             
    except Exception as e:
        logger.error(f"Error during CDP execution: {e}")
        return pd.DataFrame()
    finally:
        # Don't quit driver, just detach, or kill chrome if you want cleanup
        # driver.quit() # This closes the browser
        pass

    # 5. Process with AI
    db = []
    
    # Debug: Check if we actually got text
    logger.info(f"Captured Text Length: {len(raw_text_content)}")
    if len(raw_text_content) < 1000:
        logger.warning(f"Text seems too short! Preview: {raw_text_content[:200]}")
    
    try:
        # Check if 'model' exists in global scope
        if 'model' not in globals():
             logger.error("Global variable 'model' is not defined. Cannot run AI extraction.")
             return pd.DataFrame()

        prompt = f"""
            Please extract the winner's Name, Year, Affiliation, and Subaward from the text below. Output the result as a Markdown table.
            **Requirements:**
            - Header row must be: `| Year | Name | Affiliation | Subaward |`
            - 'Year' must be 4 digits.
            - Output only the Markdown table.
            **Text:**
            {raw_text_content[:15000]} 
        """ 
        # Truncate content slightly to fit context window if huge
        
        logger.info("Sending text to AI model...")
        response = model.generate_content(prompt)
        
        if not response.text:
            logger.error("AI returned empty response.")
            return pd.DataFrame()

        # Robust Parsing
        lines = response.text.strip().splitlines()
        table_lines = [l for l in lines if l.strip().startswith("|")]
        
        logger.info(f"AI returned {len(table_lines)} table rows.")
        
        # Determine start of data (Skip Header and Separator)
        start_idx = 0
        for idx, line in enumerate(table_lines):
            if "---" in line:
                start_idx = idx + 1
                break
        
        data_rows = table_lines[start_idx:]

        for row in data_rows:
            # Clean split
            cols = [c.strip() for c in row.split("|")]
            # Remove empty strings from ends due to leading/trailing pipes
            cols = [c for c in cols if c] 
            
            if len(cols) >= 2: # At least Year and Name
                # Map columns flexibly
                year = cols[0] if len(cols) > 0 else ""
                name = cols[1] if len(cols) > 1 else ""
                affiliation = cols[2] if len(cols) > 2 else ""
                subaward = cols[3] if len(cols) > 3 else ""
                
                if name and (year.isdigit() or "year" in year.lower()):
                     if year.isdigit():
                        db.append({
                            'id': aid, 'govid': govid, 'govname': govname, 'award': award,
                            'year': int(year), 'name': name, 'affiliation': affiliation, 'subaward': subaward
                        })
    except Exception as e:
        logger.error(f"AI processing error: {e}")
        return pd.DataFrame()

    driver.quit() # Keep open for debugging

    df = pd.DataFrame(db)
    if not df.empty:
        df.drop_duplicates(subset=['name', 'year', 'subaward'], inplace=True)
        print(tabulate(df, headers='keys', tablefmt='psql'))
        df.to_csv(f'{filepath}{aid}.csv', index=False)
        logger.info(f"Saved to {filepath}{aid}.csv")

    return df

In [270]:
def scrape2037():
    award = "Selman A Waksman Award in Microbiology"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2037"
    url = "https://www.nasonline.org/award/selman-a-waksman-award-in-microbiology/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        df.to_csv(f'{filepath}{aid}.csv',index=False)

    return df

In [271]:
def scrape2036():
    award = "Richard Lounsbery Award"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2036"
    url = "https://www.nasonline.org/award/richard-lounsbery-award/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [272]:
def scrape2035():
    award = "Public Welfare Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2035"
    url = "https://www.nasonline.org/award/nas-public-welfare-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [273]:
def scrape2034():
    award = "NAS Award in the Neurosciences"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2034"
    url = "https://www.nasonline.org/award/nas-award-in-the-neurosciences/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [274]:
def scrape2033():
    award = "NAS Award in Molecular Biology"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2033"
    url = "https://www.nasonline.org/award/nas-award-in-molecular-biology/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [275]:
def scrape2032():
    award = "Maryam Mirzakhani Prize in Mathematics"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2032"
    url = "https://www.nasonline.org/award/maryam-mirzakhani-prize-in-mathematics/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [276]:
def scrape2031():
    award = "NAS Award in Chemical Sciences"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2031"
    url = "https://www.nasonline.org/award/nas-award-in-chemical-sciences/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [277]:
def scrape2030(): #Defunct
    pass
    # award = "NAS Award in Applied Mathematics and Numerical Analysis"
    # govid = "222"
    # govname = "National Academy of Sciences"
    # aid = "2030"
    # url = "http://www.nasonline.org/programs/awards/nas-award-in-applied.html"
    # db = []
    # headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")

    # header = soup.find('h3', string="Recipients:")
    # ps = header.find_next_siblings('p')
    # for p in ps:
    #     ptext = p.text
    #     try:
    #         name = ptext.split('(')[0].strip()
    #         year = ptext.split('(')[1].split(')')[0].strip()
    #         if len(year.split(',')) > 1:
    #             year = year.split(',')[0].strip()
            
    #         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    #     except IndexError:
    #         pass
    
    # df = pd.DataFrame(db)
    # display(df)
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    # return df

In [278]:
def scrape2029():
    award = "J C Hunsaker Award in Aeronautical Engineering"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2029"
    url = "https://www.nae.edu/219194/HunsakerWinners#tabs"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(2)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                year = li.find_element(By.CLASS_NAME, 'listHeading')
                year = year.text.strip()
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    position = ""
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl03_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [279]:
def scrape2028():
    award = "NAS Award for the Industrial Application of Science"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2028"
    url = "https://www.nasonline.org/award/nas-award-for-the-industrial-application-of-science/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = re.split(r', | and ', names)
    year1 = recentdiv.find('h6').text.split(" (")
    year = year1[0]
    field = ""
    if len(year1) > 1:
        field = year1[1].strip(")").capitalize()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = re.split(r', | and ', names)
        year1 = card.find('h6').text.split(" (")
        year = year1[0]
        field = ""
        if len(year1) > 1:
            field = year1[1].strip(")").capitalize()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [280]:
def scrape2027():
    award = "NAS Award for Scientific Reviewing"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2027"
    url = "https://www.nasonline.org/award/nas-award-for-scientific-discovery/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.split()[0].strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.split()[0].strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [281]:
def scrape2025():
    award = "NAS Award for Chemistry in Service to Society"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2025"
    url = "https://www.nasonline.org/award/nas-award-for-chemistry-in-service-to-society/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.split()[0].strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.split()[0].strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [282]:
def scrape2022():
    award = "NAS Award in the Evolution of Earth and Life"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2022"
    url = "https://www.nasonline.org/award/nas-award-in-the-evolution-of-earth-and-life/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.split()[0].strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.split()[0].strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [283]:
def scrape2021():
    award = "John J Carty Award for the Advancement of Science"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2021"
    url = "https://www.nasonline.org/award/john-j-carty-award-for-the-advancement-of-science/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = re.split(r', | and ', names)
    year = recentdiv.find('h6').text.split(" (")[0]
    field = recentdiv.find('h6').text.split(" (")[1].strip(")").capitalize()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = re.split(r', | and ', names)
        year = card.find('h6').text.split(" (")[0]
        field = card.find('h6').text.split(" (")[1].strip(")").capitalize()
        for name in names:
            name = name.strip("and").strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [284]:
def scrape2020():
    award = "Jessie Stevenson Kovalenko Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2020"
    url = "https://www.nasonline.org/award/jessie-stevenson-kovalenko-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [285]:
def scrape2019():
    award = "James Craig Watson Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2019"
    url = "https://www.nasonline.org/award/james-craig-watson-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [286]:
def scrape2018():
    award = "J Lawrence Smith Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2018"
    url = "https://www.nasonline.org/award/j-lawrence-smith-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [287]:
def scrape2230():
    award = "Nobel Prize-Chemistry"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2230"
    url = "https://www.nobelprize.org/prizes/lists/all-nobel-prizes-in-chemistry/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
        
    return df

In [288]:
def scrape2231():
    award = "Nobel Prize-Economics (Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel)"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2231"
    url = "https://www.nobelprize.org/prizes/lists/all-prizes-in-economic-sciences/"
    db = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [289]:
def scrape2232():
    award = "Nobel Prize-Literature"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2232"
    url = "https://www.nobelprize.org/prizes/lists/all-nobel-prizes-in-literature/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [290]:
def scrape2233():
    award = "Nobel Prize-Physiology or Medicine"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2233"
    url = "https://www.nobelprize.org/prizes/lists/all-nobel-laureates-in-physiology-or-medicine/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [291]:
def scrape2234():
    award = "Nobel Prize-Peace"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2234"
    url = "https://www.nobelprize.org/prizes/lists/all-nobel-peace-prizes/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [292]:
def scrape2235():
    award = "Nobel Prize-Physics"
    govid = "248"
    govname = "Nobel Foundation"
    aid = "2235"
    url = "https://www.nobelprize.org/prizes/lists/all-nobel-prizes-in-physics/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(2)
    button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    button.click()

    time.sleep(2)

    try:
        while True:
            # Locate the button using its class name
            load_more_button = driver.find_element(By.CLASS_NAME, "dynamic-list-load-more")
            driver.execute_script("arguments[0].scrollIntoView(true);", load_more_button)
            time.sleep(1)
            # Click the button
            load_more_button.click()
            
            # Wait for 3 seconds before the next iteration
            time.sleep(3)
            
    except ElementNotInteractableException:
        print("No more 'Load more' button found. Exiting loop.")

    mdiv = driver.find_element(By.CLASS_NAME, "dynamic-list")
    divs = mdiv.find_elements(By.CLASS_NAME, "card-prize")  # All divs with class 'card-prize'

    for div in divs:
        # Extract the header containing the year
        header = div.find_element(By.TAG_NAME, "a")
        year = header.text.split()[-1]
        
        # Extract names from 'card-prize--laureates--links'
        nameline = div.find_elements(By.CLASS_NAME, "card-prize--laureates--links")
        for person in nameline:
            links = person.find_elements(By.TAG_NAME, "a")
            for link in links:
                name = link.text.replace(',', '').replace(' and', '').strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    
    return df

In [293]:
def scrape2959():
    award = "Parkman Prize"
    govid = "396"
    govname = "Society of American Historians"
    aid = "2959"
    base_url = "https://sah.columbia.edu/content/prizes/francis-parkman-prize?page="
    db = []

    # Pool of User-Agent strings
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    ]

    for page_num in range(3):  # Pages start from 0
        options = webdriver.ChromeOptions()
        options.add_argument("start-maximized")
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_argument(f"user-agent={random.choice(user_agents)}")  # Randomize User-Agent
        options.headless = True

        # Create a new WebDriver instance for each page
        driver = webdriver.Chrome(options=options)

        try:
            page_url = f"{base_url}{page_num}"
            print(f"Scraping: {page_url}")
            driver.get(page_url)
            time.sleep(random.uniform(3, 7))  # Random delay

            # Scrape data from the current page
            try:
                mdiv = driver.find_element(By.CLASS_NAME, 'view-content')
                rows = mdiv.find_elements(By.CLASS_NAME, 'views-row')

                for row in rows:
                    a = row.find_element(By.TAG_NAME, 'a')
                    atext = a.text.strip()
                    year = atext[:4]
                    name = atext[5:].split(',')[0]
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            except Exception as e:
                print(f"Error scraping page {page_num}: {e}")

        finally:
            # Close the WebDriver after finishing the page
            driver.quit()

    # Save the data
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [294]:
def scrape2956():
    award = "Theodosius Dobzhansky Prize"
    govid = "394"
    govname = "Society for the Study of Evolution"
    aid = "2956"
    url = "http://www.evolutionsociety.org/index.php?module=content&type=user&func=view&pid=13"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    table = soup.find('table')
    trs = table.find_all('tr')
    for tr in trs:
        tds = tr.find_all('td')
        name = ""
        year = ""
        for td in tds:
            tdclean = td.text.replace("\u00A0", "").strip()
            if tdclean != "":
                if tdclean.isdigit():
                    year = tdclean
                elif tdclean.isdigit() is False:
                    name = tdclean
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    df = df[df['year'] != '']
    df = df[df['year'] != ''].sort_values(by='year', ascending=True)
    display(df)
    
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [295]:
def scrape2973():
    award = "Stockholm Water Prize"
    govid = "401"
    govname = "Stockholm Water Foundation"
    aid = "2973"
    url = "https://stockholmwaterfoundation.org/stockholm-water-prize/laureates"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    def prefixr(name):
        prefixes = ['Professors', 'Professor Emeritus', 'Professor', 'Dr.', 'Dr', 'Mr.','Mr']
        for prefix in prefixes:
            name = name.replace(prefix, '').strip()
        return name
    
    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
        soup = BeautifulSoup(page.content, "html.parser")
    except Exception as e:
        print(f"Error fetching page: {e}")
        return pd.DataFrame()

    # mdiv = soup.find('div', class_='grid-msnry') # No longer exists
    
    # Direct search for blurb_div-content
    divs = soup.find_all('div', class_='blurb_div-content')
    if not divs:
        print("No divs found with class 'blurb_div-content'")
        return pd.DataFrame()

    for div in divs:
        year_span = div.find('span', class_="pre-title")
        if not year_span:
            continue
        year = year_span.text.strip()
        
        h3 = div.find('h3')
        if not h3:
            continue
        h3text = h3.text
        
        fnames = []
        if '/' in h3text:
            fnames = h3text.split('/')
        elif ' and ' in h3text and 'Centre' not in h3text:
            fnames = h3text.split(' and ')
        else:
            # Single name or Centre
            fname = h3text.split(',')[0] # Remove country if appended with comma
            fnames = [fname]

        for fname in fnames:
            lname = fname.split(',')[0]
            name = prefixr(lname)
            name = name.strip()
            if name:
                 db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    
    # Check for global filepath, default to empty string
    fpath = globals().get('filepath', '')
    try:
        df.to_csv(f'{fpath}{aid}.csv',index=False)
    except Exception as e:
         print(f"Could not save CSV to {fpath}{aid}.csv: {e}")

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [296]:
def scrape2893():
    award = "Rolf Schock Prizes"
    govid = "377"
    govname = "Royal Swedish Academy of Sciences"
    aid = "2893"
    url = "https://www.kva.se/en/prizes/rolf-schock-prizes/laureates/?"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []
    wait = WebDriverWait(driver, 10)

    while True:
        try:
            plist = wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'award-winners__list')))
            lis = plist.find_elements(By.CLASS_NAME, 'person-card')
            for li in lis:
                html_content = li.get_attribute('outerHTML')
                a = li.find_element(By.TAG_NAME, 'a')
                link = a.get_attribute('href')
                links.append(link)

            nextnest = driver.find_element(By.CLASS_NAME, 'button--next')
            nextbt = nextnest.find_element(By.XPATH, ".//a[@class='page-link' and @tabindex='0']")
            
            if "button--disabled" in nextbt.get_attribute("class"):
                print("Next button is disabled. Stopping scraping.")
                break
            
            try:
                nextbt.click()
            except Exception as e:
                print(f"Error clicking next button: {e}")
                break
                time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        name = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-title').text

        atext = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-prize').text
        btext = atext.split('-')[1].strip()
        fieldlist = btext.split()[:-1]
        field = ' '.join(fieldlist)
        year = btext.split()[-1]
    
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'field': field})

    df = pd.DataFrame(db)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [297]:
def scrape2892():
    award = "Gregori Aminoff Prize"
    govid = "377"
    govname = "Royal Swedish Academy of Sciences"
    aid = "2892"
    url = "https://www.kva.se/en/prizes/gregori-aminoff-prize/laureates/?"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []
    wait = WebDriverWait(driver, 10)

    while True:
        try:
            plist = wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'award-winners__list')))
            lis = plist.find_elements(By.CLASS_NAME, 'person-card')
            for li in lis:
                html_content = li.get_attribute('outerHTML')
                a = li.find_element(By.TAG_NAME, 'a')
                link = a.get_attribute('href')
                links.append(link)

            nextnest = driver.find_element(By.CLASS_NAME, 'button--next')
            nextbt = nextnest.find_element(By.XPATH, ".//a[@class='page-link' and @tabindex='0']")
            
            if "button--disabled" in nextbt.get_attribute("class"):
                print("Next button is disabled. Stopping scraping.")
                break
            
            try:
                nextbt.click()
            except Exception as e:
                print(f"Error clicking next button: {e}")
                break
                time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        name = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-title').text

        atext = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-prize').text
        year = atext.split()[-1]
    
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [298]:
def scrape2891():
    award = "Crafoord Prize"
    govid = "377"
    govname = "Royal Swedish Academy of Sciences"
    aid = "2891"
    url = "https://www.crafoordprize.se/about-the-prize/laureates/?"
    db = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
    }

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []
    wait = WebDriverWait(driver, 10)

    while True:
        try:
            plist = wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'award-winners__list')))
            lis = plist.find_elements(By.CLASS_NAME, 'person-card')
            for li in lis:
                html_content = li.get_attribute('outerHTML')
                a = li.find_element(By.TAG_NAME, 'a')
                link = a.get_attribute('href')
                links.append(link)

            nextnest = driver.find_element(By.CLASS_NAME, 'button--next')
            nextbt = nextnest.find_element(By.XPATH, ".//a[@class='page-link' and @tabindex='0']")
            
            if "button--disabled" in nextbt.get_attribute("class"):
                print("Next button is disabled. Stopping scraping.")
                break
            
            try:
                nextbt.click()
            except Exception as e:
                print(f"Error clicking next button: {e}")
                break
                time.sleep(2)

        except NoSuchElementException:
            break
    
    print(f'Completed link extraction, Total links: {len(links)}')

    for link in links:
        driver.get(link)
        name = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-title').text

        atext = driver.find_element(By.CLASS_NAME, 'single-award-winner__item-prize').text
        btext = atext.split('-')[1].strip()
        fieldlist = btext.split()[:-1]
        field = ' '.join(fieldlist)
        year = btext.split()[-1]
    
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [299]:
def scrape2879():
    award = "Ruth Lilly Poetry Prize"
    govid = "369"
    govname = "Poetry Foundation"
    aid = "2879"
    url = "https://www.poetryfoundation.org/awards/prizes-lilly"
    db = []

    # Use standard Selenium with anti-detection flags to avoid 403 and SessionNotCreatedException
    options = Options()
    # options.add_argument('--headless') # Comment out if you want to see the browser for debugging
    options.add_argument('--headless=new') # Newer headless mode is less detectable
    options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)
    
    # Use ChromeDriverManager to ensure driver matches installed Chrome version
    try:
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)
        
        # Additional stealth: execute CDP command to potential detection
        driver.execute_cdp_cmd('Network.setUserAgentOverride', {"userAgent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'})

        driver.get(url)
        time.sleep(5)  # Wait for page load
        soup = BeautifulSoup(driver.page_source, "html.parser")
    except Exception as e:
        print(f"Selenium error: {e}")
        if 'driver' in locals():
            driver.quit()
        return pd.DataFrame() # Return empty on error
    finally:
        if 'driver' in locals():
            driver.quit()

    mdiv = soup.find("div", class_="max-w-full flex-1 md:mb-6")
    if not mdiv:
        print("Could not find the target div. The page structure might have changed or access was blocked.")
        return pd.DataFrame()

    mdivtxt = mdiv.text

    json_prompt = f"""
    I have text from an award website. For each entry, extract the winner's name, year, and affiliation.

    RULES:
    - If an affiliation is not present, the value for the 'affiliation' key should be an empty string "".
    - The word "press" is not a real affiliation and should be ignored or left as an empty string.
    - Return the data as a single, valid JSON array of objects.
    - Each object in the array must have three keys: "name", "year", and "affiliation".
    - Do not include any introductory text, explanations, or markdown code formatting like ```json. Only output the raw JSON array.

    THE TEXT TO PARSE IS:
    ---
    {mdivtxt}
    """
    response = model.generate_content(json_prompt)

    try:
        award_data = json.loads(response.text)
        
        for item in award_data:
            name = item.get('name', '').strip()
            year = item.get('year', '')

            if len(name) > 3:
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

    except json.JSONDecodeError:
        print("Error: Model did not return valid JSON. Skipping this section.")
        print("Model output was:", response.text)

    mdivs = soup.find_all('div', class_='c-tier_weighted_light')
    for div in mdivs:
        cards = div.find_all('div', class_='o-card_stretch')
        for card in cards:
            h2 = card.find('h2')
            span = card.find('span', class_='c-txt_catMeta')
            if h2 and h2.find('a') and span:
                name = h2.find('a').text
                year = span.text
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    if not df.empty:
        df['year'] = df['year'].replace('author', pd.NA)
        df['year'] = df['year'].ffill()
        display(df)
        df.to_csv(f'{filepath}{aid}.csv',index=False)

        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    else:
        print("No data extracted.")

    return df

In [300]:
def scrape2878():
    award = "PEN/Faulkner Award for Fiction"
    govid = "368"
    govname = "PEN/Faulkner Foundation"
    aid = "2878"
    url = "https://www.penfaulkner.org/our-awards/pen-faulkner-award/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    links = []
    mdivs = soup.find_all('div', class_='et_section_specialty')
    for div in mdivs:
        div = div.find('div', class_='et_pb_has_overlay')
        if div and div.a:
            link = div.a.get('href')
            if link:
                links.append(link)

    for link in links:
        page = requests.get(link, headers=headers)
        soup = BeautifulSoup(page.content, "html.parser")

        name = None
        year = None
        
        # Try new page structure first (2023-2025)
        # Get title from H2
        h2_elem = soup.find('h2')
        if h2_elem:
            title_text = h2_elem.text.strip()
        
        # Get year from et_pb_text_inner (contains "2025 PEN/Faulkner Award for Fiction Winner")
        yeart_elem = soup.find('div', class_='et_pb_text_inner')
        if yeart_elem:
            yeart = yeart_elem.text
            # Extract 4-digit year
            import re
            year_match = re.search(r'\b(20\d{2})\b', yeart)
            if year_match:
                year = year_match.group(1)
        
        # Get author name from paragraph that starts with "[Name] is the author of"
        for p in soup.find_all('p'):
            text = p.get_text()
            if ' is the author of' in text or ' is an author' in text:
                # Extract the name (first part before "is the author")
                name = text.split(' is ')[0].strip()
                break
        
        # Try old page structure (before 2023) if name not found
        if not name:
            name_elem = soup.find('p', class_='et_pb_member_position')
            if name_elem:
                name = name_elem.text
                name = name.replace('by ', '')
            
        # If year not found yet, try old structure
        if not year:
            yeart_elem = soup.find('div', class_='et_pb_text_inner')
            if yeart_elem:
                yeart = yeart_elem.text
                yeart = yeart.split()
                for yearx in yeart:
                    if yearx.isdigit() and len(yearx) == 4:
                        year = yearx
        
        if name and year:
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    link2 = 'https://www.penfaulkner.org/2011/08/01/past_award_winners/'
    page = requests.get(link2, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    h2s = soup.find_all('h2')
    for h2 in h2s:
        h2text = h2.text.strip()
        if h2text.isdigit():
            year = h2text
        elif "WINNER" in h2text:
            namex = h2text.split(':')[1]
            name = namex.split(',')[0].strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        else:
            name = h2text.split(',')[0].strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['year', 'name'])
    display(df)

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [301]:
def scrape2875():
    award = "National Science Board/Vannevar Bush Award"
    govid = "366"
    govname = "National Science Foundation (NSF)"
    aid = "2875"
    url = "https://en.wikipedia.org/wiki/Vannevar_Bush_Award"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # 1. Scrape Wikipedia
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    # print(soup.prettify())

    lis = soup.find_all('li')
    for li in lis:
        text = li.get_text()
        parts = text.split(':', 1)
        if len(parts) == 2:
            year_candidate = parts[0].strip()
            rest = parts[1].strip()
            if year_candidate.isdigit() and len(year_candidate) == 4:
                year = year_candidate
                if "nobody awarded" in rest.lower():
                    continue
                
                links = li.find_all('a')
                if links:
                    for link in links:
                        # Avoid citation links like [1]
                        if link.text.strip().startswith('['):
                            continue
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': link.text.strip(), 'position': ''})
                else: 
                     names = rest.split(' and ')
                     for name in names:
                        name = name.strip()
                        if name:
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': ''})
    
    # 2. Scrape NSF
    url2 = "https://www.nsf.gov/nsb/vannevar-bush-award"
    try:
        page2 = requests.get(url2, headers=headers)
        soup2 = BeautifulSoup(page2.content, "html.parser")
        
        # Look for div with class text__content text-formatted
        content_divs = soup2.find_all('div', class_='text__content text-formatted')
        for div in content_divs:
            # Look for strong tags or p tags that might contain the year and name
            # Pattern from user: <p><strong>2024: John Hennessy</strong></p>
            strongs = div.find_all('strong')
            for s in strongs:
                text = s.get_text().strip()
                # Expected format "YYYY: Name"
                parts = text.split(':', 1)
                if len(parts) == 2:
                    y = parts[0].strip()
                    n = parts[1].strip()
                    if y.isdigit() and len(y) == 4:
                         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': y, 'name': n})
    except Exception as e:
        print(f"Error scraping second URL: {e}")

    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['year', 'name'])
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [302]:
def scrape2873():
    award = "Alan T Waterman Award"
    govid = "366"
    govname = "National Science Foundation (NSF)"
    aid = "2873"
    url = "https://new.nsf.gov/od/honorary-awards/waterman#past-recipients-0f9"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    recent = soup.find('div', class_='palette palette--light-gray layout-container--wrapper nsf-layout nsf-layout--threecol full-browser-width')
    recenttxt = recent.text

    table = soup.find('table')
    tabletxt = table.text

    response = model.generate_content(
        contents=f"I have a text from an award website that lists the winner name, year, and affiliation for some. If affiliation is empty keep blank, also note that press is not affiliation. Return to me a table with the name, year, and affiliation in this order only. The text is as follows: {recenttxt} this is the 2024 winners"
    )
    lines = response.text.strip().split("\n")
    table_rows = lines[3:]

    for row in table_rows:
        # Split the row by the pipe ('|') and strip extra spaces
        columns = [col.strip() for col in row.split("|") if col.strip()]
        
        # Ensure there are at least two columns (name, year), and handle missing affiliation
        if len(columns) == 2:
            name, year = columns
            affiliation = ''  # Set affiliation to an empty string if missing
        elif len(columns) == 3:
            name, year, affiliation = columns
        else:
            # Handle unexpected case where there are fewer than 2 columns
            name = columns[0]
            year = ''
            affiliation = ''
        
        # Append the data to your database
        if len(name.strip()) > 3:
            db.append({
                'id': aid,
                'govid': govid,
                'govname': govname,
                'award': award,
                'year': year,
                'name': name,
                'affiliation': affiliation
            })
    
    response = model.generate_content(
        contents=f"I have a text from an award website that lists the winner name, year, and affiliation for some. If affiliation is empty keep blank, also note that press is not affiliation. Return to me a table with the name, year, and affiliation in this order only. The text is as follows: {tabletxt}"
    )
    lines = response.text.strip().split("\n")
    table_rows = lines[3:]

    for row in table_rows:
        # Split the row by the pipe ('|') and strip extra spaces
        columns = [col.strip() for col in row.split("|") if col.strip()]
        
        # Ensure there are at least two columns (name, year), and handle missing affiliation
        if len(columns) == 2:
            name, year = columns
            affiliation = ''  # Set affiliation to an empty string if missing
        elif len(columns) == 3:
            name, year, affiliation = columns
        else:
            # Handle unexpected case where there are fewer than 2 columns
            name = columns[0]
            year = ''
            affiliation = ''
        
        # Append the data to your database
        if len(name.strip()) > 3:
            db.append({
                'id': aid,
                'govid': govid,
                'govname': govname,
                'award': award,
                'year': year,
                'name': name,
                'affiliation': affiliation
            })

    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['year', 'name'])
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [303]:
def scrape2775():
    award = "Sarton Medal for Lifetime Scholarly Achievement"
    govid = "348"
    govname = "History of Science Society"
    aid = "2775"
    url = "https://hssonline.org/page/sartonmedal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    wait = WebDriverWait(driver, 10)

    h4 = driver.find_element(By.TAG_NAME, 'h4')
    sdiv = h4.find_element(By.XPATH, 'following-sibling::div')
    ps = sdiv.find_elements(By.TAG_NAME, 'p')
    for p in ps:
        if p.text.isdigit():
            year = p.text.strip()
        else:
            name = p.text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['year', 'name'])
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [304]:
def scrape2545():
    award = "The Carl-Gustaf Rossby Research Medal"
    govid = "299"
    govname = "American Meteorological Society"
    aid = "2545"
    url = "https://www.ametsoc.org/index.cfm/ams/about-ams/ams-awards-honors/awards/past-award-honors-recipients/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}


    options = Options()
    # options.headless = True # Commented out to avoid Cloudflare detection and allow manual intervention

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    try:
        # Wait for the page to load - removing iframe switch as content appears to be on main page
        time.sleep(5)
        
        wait = WebDriverWait(driver, 20)

        # Try to locate the search input directly on the page
        try:
            print("Looking for input with id='ams-query'...")
            input_element = wait.until(EC.visibility_of_element_located((By.ID, "ams-query")))
        except:
            raise Exception("Search input 'ams-query' not found.")

        # Scroll to element to make sure it's in view
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", input_element)
        time.sleep(1) 

        try:
            input_element.clear()
        except:
            pass 
            
        search_term = "Carl-Gustaf Rossby" 
        input_element.send_keys(search_term)
        input_element.send_keys(Keys.RETURN)
        
        print(f"Searching for: {search_term}")
        
        # Wait for results container to appear
        time.sleep(5) 

        # Scrape results
        while True:
            # Re-locate the results area to ensure freshness
            try:
                # Wait for the results area to be present
                wait.until(EC.presence_of_element_located((By.CLASS_NAME, "results-area")))
                results_area = driver.find_element(By.CLASS_NAME, "results-area")
            except:
                print("Results area not found.")
                break

            # Find all year headers
            # Structure: h5 (year) -> div (content) -> hr (separator) -> h5 (next year) ...
            # The structure provided shows h5 and div siblings.
            
            # Get all child elements of results-area
            children = results_area.find_elements(By.XPATH, "./*")
            
            current_year = ""
            
            for child in children:
                tag_name = child.tag_name.lower()
                class_name = child.get_attribute("class")
                
                # Check for year header
                if tag_name == "h5" and "fw-bold" in class_name:
                    current_year = child.text.strip()
                
                # Check for award content div
                elif tag_name == "div" and "mb-3" in class_name and not "d-flex" in class_name:
                    # ensure we have a year
                    if not current_year:
                        continue
                        
                    try:
                        # Extract Award Name
                        try:
                            award_name_el = child.find_element(By.CLASS_NAME, "fw-bold")
                            award_name = award_name_el.text.strip()
                        except:
                            award_name = award
                        
                        # Extract Recipient and Affiliation
                        try:
                            recipient_div = child.find_element(By.CSS_SELECTOR, ".text-dark:not(.fw-bold)")
                            full_text = recipient_div.text.strip()
                            
                            # Check for affiliation in span
                            try:
                                affiliation_span = recipient_div.find_element(By.TAG_NAME, "span")
                                affiliation = affiliation_span.text.strip()
                                # Remove affiliation from name if it's there
                                name = full_text.replace(affiliation, "").strip().rstrip(",")
                            except:
                                # Fallback splitting by comma if no span structure
                                # Only split if the part after comma is not a suffix like Jr., Sr., III, etc. or 'posthumously'
                                if "," in full_text:
                                    parts = full_text.split(",", 1)
                                    potential_aff = parts[1].strip()
                                    # List of known suffixes or non-affiliation texts
                                    suffixes = ['Jr.', 'Sr.', 'II', 'III', 'IV', 'posthumously']
                                    if potential_aff in suffixes:
                                        name = full_text
                                        affiliation = ""
                                    else:
                                        name = parts[0].strip()
                                        affiliation = potential_aff
                                else:
                                    name = full_text
                                    affiliation = ""
                        except:
                            name = "Unknown"
                            affiliation = ""

                        # Extract Citation - optional
                        # citation = child.find_element(By.CLASS_NAME, "fst-italic").text.strip()

                        # Only add if it matches the target award
                        if "Carl-Gustaf Rossby" in award_name:
                             db.append({
                                'id': aid, 
                                'govid': govid, 
                                'govname': govname, 
                                'award': award, 
                                'year': current_year, 
                                'name': name,
                                'affiliation': affiliation
                            })
                    except Exception as e:
                        print(f"Error parsing row: {e}")

            # Check for pagination
            try:
                next_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Next')]")
                parent_li = next_button.find_element(By.XPATH, "./..")
                
                if "disabled" not in parent_li.get_attribute("class"):
                    print("Navigating to next page...")
                    driver.execute_script("arguments[0].click();", next_button)
                    time.sleep(3) # Wait for load
                    # verify content changed or just wait
                else:
                    print("Reached last page.")
                    break
            except:
                print("No pagination found or error checking pagination.")
                break

    except Exception as e:
        print(f"Error during execution: {str(e)}")
        driver.quit() # Keep open for debugging if needed
        return
        
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)
    
    driver.quit()

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [305]:
def scrape2467():
    award = "AAAS Philip Hauge Abelson Prize"
    govid = "286"
    govname = "American Association for the Advancement of Science, The (AAAS)"
    aid = "2467"
    url = "https://www.aaas.org/awards/philip-hauge-abelson/recipients"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='aa-body-text__inset')
    year_found1 = False
    ps = mdiv.find_all('p')

    year = mdiv.find('h2').text.split()[0]

    name_tag = soup.find('p').find('a')
    if name_tag:
        name = name_tag.text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year.strip(), 'name': name.strip()})
    try:
        for p in ps:
            p_text = p.text.strip()

            # Check for year (if the text starts with a year)
            if len(p_text) < 5:
                year = p_text
                year_found1 = True

            elif p_text.startswith('The'):
                year = p_text.split()[1]
                name = p.find('a').text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year.strip(), 'name': name.strip()})

            elif p_text.strip().startswith(('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')):  # Likely starts with a year
                year = p_text[:4]
                if p.find('a'):
                    name = p.find('a').text.strip()
                else:
                    # Extract name using regex or fallback logic
                    name_match = re.match(r'^([\w\s.-]+?)(?=\swas|,|$)', p_text[4:].strip())
                    name = name_match.group(1) if name_match else p_text[4:].split(',')[0].strip()

                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year.strip(), 'name': name.strip()})

            elif year_found1:
                if p.find('a'):
                    name = p.find('a').text.strip()
                elif p.find('strong'):
                    # Extract name from <strong> tag if <a> is not present
                    name = p.find('strong').text.strip()
                else:
                    # Extract name using regex from the full sentence
                    name_match = re.match(r'^([\w\s.-]+?)(?=\swas|,|$)', p_text)
                    name = name_match.group(1) if name_match else p_text.strip()

                year_found1 = False
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year.strip(), 'name': name.strip()})

    except AttributeError:
        pass

    df = pd.DataFrame(db)
    df['name'] = df['name'].str.replace(r'\b\s*The\s+Honorable\s+', '', regex=True)
    df['name'] = df['name'].str.strip()
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [306]:
def scrape2313():
    award = "Paul Oskar Kristeller Lifetime Achievement Award"
    govid = "258"
    govname = "Renaissance Society of America"
    aid = "2313"
    url = "https://www.rsa.org/page/pokaward"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = uc.Chrome(version_main=144)
    driver.get(url)

    time.sleep(10)

    try:
        mdiv = driver.find_element(By.ID, 'CustomPageBody')

        # Attempt to find the "Recipients" section for the most recent winner
        # Looking for a header containing "Recipients" or "Award" that is followed by a paragraph with the year
        try:
            # Flexible XPath to find the header (could be h1, h2, etc.)
            headers_list = mdiv.find_elements(By.XPATH, ".//*[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'recipients of')]")
            
            for h in headers_list:
                # Look for the immediate next paragraph
                try:
                    # following-sibling::p finds the first p tag after the header
                    next_p = h.find_element(By.XPATH, "following-sibling::p[normalize-space()!='']")
                    p_text = next_p.text.strip()
                    # Check if it starts with a year (4 digits)
                    if len(p_text) >= 4 and p_text[:4].isdigit():
                        # Format: "2025, Sheila ffolliott, ..."
                        parts = p_text.split(',')
                        if len(parts) > 1:
                            year = parts[0].strip()
                            name = parts[1].strip()
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                            break # Found the recent one
                except NoSuchElementException:
                    continue
        except Exception as e:
            print(f"DEBUG: Error processing recent winner: {e}")

        # Attempt to find "Previous Winners" list
        try:
            prev_headers = mdiv.find_elements(By.XPATH, ".//*[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'previous winners')]")
            for ph in prev_headers:
                try:
                    ul = ph.find_element(By.XPATH, "following-sibling::ul")
                    lis = ul.find_elements(By.TAG_NAME, 'li')
                    for li in lis:
                        litext = li.text.strip()
                        # Format: "2024 Paul F. Gehl"
                        if litext and litext[:4].isdigit():
                            parts = litext.split(' ', 1)
                            if len(parts) > 1:
                                year = parts[0].strip()
                                name = parts[1].strip()
                                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                except NoSuchElementException:
                    continue
        except Exception as e:
            print(f"DEBUG: Error processing previous winners: {e}")

    except NoSuchElementException:
        print("DEBUG: Could not find 'CustomPageBody'")
    except Exception as e:
        print(f"DEBUG: General error: {e}")

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    
    # Check if filepath is defined, if not use current dir
    try:
        save_path = f'{filepath}{aid}.csv'
    except NameError:
        print("DEBUG: 'filepath' not defined")
        
    df.to_csv(save_path, index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [307]:
def scrape2129():
    award   = "Fellowships for Advanced Research on Japan"
    govid   = "234"
    govname = "National Endowment for the Humanities (NEH)"
    aid     = "2129"
    url     = "https://apps.neh.gov/PublicQuery/Default.aspx?q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&p=1&pv=207&d=0&at=0&y=0&prd=0&cov=0&prz=0&wp=0&sp=0&ca=0&arp=0&ob=Institution%20name&or=ASC"
    db      = []

    download_dir = tempfile.mkdtemp(prefix=f"award_{aid}_")
    chrome_options = Options()
    chrome_options.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })

    driver = webdriver.Chrome(options=chrome_options)

    try:
        driver.get(url)
        export_btn = driver.find_element(By.ID, "ctl00_cphMainContent_rgResults_ctl00_ctl02_ctl00_ExportToCSV")
        export_btn.click()

        timeout = time.time() + 30
        while time.time() < timeout:
            files = os.listdir(download_dir)
            csv_files = [f for f in files if f.lower().endswith(".csv")]
            if csv_files:
                csv_file = csv_files[0]
                break
            time.sleep(0.5)
        else:
            raise FileNotFoundError("CSV download did not complete in time")

        csv_path = os.path.join(download_dir, csv_file)
        df_raw = pd.read_csv(csv_path)

    finally:
        driver.quit()

    # Clean and combine name columns
    df_raw['Project Director Middle Name'] = df_raw['Project Director Middle Name'].fillna('')
    df_raw['name'] = (df_raw['Project Director First Name'].astype(str) + ' ' +
                      df_raw['Project Director Middle Name'].astype(str) + ' ' +
                      df_raw['Project Director Last Name'].astype(str))
    df_raw['name'] = df_raw['name'].str.replace(r'\s+', ' ', regex=True).str.strip()

    # Assign and clean other columns
    df_raw['year']        = df_raw['Year Awarded'].astype(str).str.strip()
    df_raw['affiliation'] = df_raw['Organization'].astype(str).str.strip()

    # Assign standard metadata
    df_raw['award']   = award
    df_raw['govid']   = govid
    df_raw['govname'] = govname
    df_raw['id']      = aid
    
    # Since each row is a unique person, no name splitting is needed.
    # Select and order the final columns.
    df = df_raw[['award', 'name', 'year', 'affiliation', 'govid', 'govname', 'id']]
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    try:
        for f in os.listdir(download_dir):
            os.remove(os.path.join(download_dir, f))
        os.rmdir(download_dir)
    except Exception:
        pass

    return df

In [308]:
def scrape2134():
    award = "Faculty Research Awards"
    govid = "234"
    govname = "National Endowment for the Humanities (NEH)"
    aid = "2134"
    url = "https://apps.neh.gov/PublicQuery/Default.aspx?q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&p=1&pv=169&d=0&at=0&y=0&prd=0&cov=0&prz=0&wp=0&sp=0&ca=0&arp=0&ob=Institution%20name&or=ASC"
    
    # Create a temporary directory for the download
    download_dir = tempfile.mkdtemp(prefix=f"award_{aid}_")
    chrome_options = Options()
    chrome_options.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })

    driver = webdriver.Chrome(options=chrome_options)

    try:
        driver.get(url)
        # Find the export button by its unique ID for reliability
        export_btn = driver.find_element(By.ID, "ctl00_cphMainContent_rgResults_ctl00_ctl02_ctl00_ExportToCSV")
        export_btn.click()

        # Wait for the download to complete with a timeout
        timeout = time.time() + 30
        while time.time() < timeout:
            files = os.listdir(download_dir)
            csv_files = [f for f in files if f.lower().endswith(".csv")]
            if csv_files:
                csv_file = csv_files[0]
                break
            time.sleep(0.5)
        else:
            raise FileNotFoundError("CSV download did not complete in time")

        csv_path = os.path.join(download_dir, csv_file)
        df_raw = pd.read_csv(csv_path)

    finally:
        driver.quit()

    # Clean and combine name columns using column headers instead of indices
    df_raw['Project Director Middle Name'] = df_raw['Project Director Middle Name'].fillna('')
    df_raw['name'] = (df_raw['Project Director First Name'].astype(str) + ' ' +
                      df_raw['Project Director Middle Name'].astype(str) + ' ' +
                      df_raw['Project Director Last Name'].astype(str))
    df_raw['name'] = df_raw['name'].str.replace(r'\s+', ' ', regex=True).str.strip()

    # Assign and clean other columns
    df_raw['year']        = df_raw['Year Awarded'].astype(str).str.strip()
    df_raw['affiliation'] = df_raw['Organization'].astype(str).str.strip()

    # Assign standard metadata
    df_raw['award']   = award
    df_raw['govid']   = govid
    df_raw['govname'] = govname
    df_raw['id']      = aid
    
    df = df_raw[['award', 'name', 'year','affiliation', 'govid', 'govname', 'id']]
    
    # Save the final dataframe
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    try:
        for f in os.listdir(download_dir):
            os.remove(os.path.join(download_dir, f))
        os.rmdir(download_dir)
    except Exception:
        pass

    return df

In [309]:
def scrape2860():
    award = "National Book Critics Circle Award"
    govid = "361"
    govname = "National Book Critics Circle"
    aid = "2860"
    url = "https://www.bookcritics.org/past-awards/2023/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome()
    driver.get(url)

    links = ["https://www.bookcritics.org/past-awards/2023/"]
    while True:
        try:
            prev = driver.find_element(By.CLASS_NAME, 'nav-previous')
            href = prev.find_element(By.TAG_NAME, 'a').get_attribute('href')
            links.append(href)
            driver.get(href)

        except NoSuchElementException:
            driver.quit()
            break

    for link in links:
        page = requests.get(link)
        soup = BeautifulSoup(page.content, "html.parser")

        mdiv = soup.find('div', class_='award-finalists-inner')
        uls = mdiv.find_all('ul', class_='award-year-list')
        yeart = mdiv.find('h2').text.split()[0].strip()
        year = int(yeart)
        try:
            if year >= 2017:
                for ul in uls:
                    subaward = ul.find('h3').text.strip()
                    wli = ul.find('li', class_='Winner').text
                    name = wli.split(',')[0].strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'subaward': subaward})

            elif year < 2017 and year != 1975:
                h3s = mdiv.find_all('h3')
                for h3 in h3s:
                    h3t = h3.text.strip()
                    subaward = h3t.strip()
                    ul = h3.find_next('ul').text
                    if 'Winner' in h3.text:
                        name = ul.split(',')[0].strip()
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'subaward': subaward})

            elif year == 1975:
                h3 = mdiv.find('h3')
                ul = h3.find_next('ul')
                lis = ul.find_all('li')
                for li in lis:
                    text = li.text.strip()
                    subaward = text.split(':')[0].strip()
                    name = text.split(':')[1].split(',')[0].strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'subaward': subaward})

        except AttributeError:
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [310]:
def scrape2890():
    award = "Franklin Medal"
    govid = "376"
    govname = "Royal Society of Arts (RSA)"
    aid = "2890"
    url = "https://en.wikipedia.org/wiki/Benjamin_Franklin_Medal_(Royal_Society_of_Arts)"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='bodyContent')
    ul = mdiv.find('ul')
    lis = ul.find_all('li')
    for li in lis:
        li = li.text.strip()
        year_match = re.search(r'\b\d{4}\b', li)
        if year_match:
            year = year_match.group()
        else:
            year = None

        # Extract name using regular expression
        name_match = re.search(r'(?<=\d{4}\s).+', li)
        if name_match:
            name = name_match.group().split(',')[0]
        else:
            name = None

        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [311]:
def scrape2768():
    # --- Configuration ---
    award = "Benjamin Franklin Medal"
    govid = "346"
    govname = "Franklin Institute"
    aid = "2768"
    url = "https://fi.edu/en/awards/laureates/search?field_lastname_value=&field_subject_target_id=All&field_awards_target_id=402&field_year_value=&field_year_value_1="
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    print(f"--- Starting scrape for Award ID: {aid} ({award}) ---")

    # --- Driver Initialization ---
    print("Initializing headless Chrome driver...")
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox") # Often needed in containerized environments
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument(f'user-agent={headers["User-Agent"]}')
    driver = webdriver.Chrome(options=options)
    
    # Set up a reusable wait object with a 10-second timeout
    wait = WebDriverWait(driver, 10)

    try:
        # --- Navigation ---
        print("Navigating to the target URL...")
        driver.get(url)

        # --- Scraping Loop ---
        page_num = 1
        total_laureates = 0
        while True:
            print(f"\n--- Scraping Page {page_num} ---")
            
            try:
                # Wait for the main content of the page to be visible
                wait.until(EC.visibility_of_element_located((By.CLASS_NAME, "view-content")))
                entries = driver.find_elements(By.CLASS_NAME, "views-row")
                if not entries:
                    print("Content loaded, but no laureate entries found. Ending scrape.")
                    break
            except TimeoutException:
                print("Timed out waiting for page content. Assuming no more results.")
                break

            print(f"Found {len(entries)} entries on this page.")
            laureates_on_page = 0
            for entry in entries:
                try:
                    # Extract name
                    first_name = entry.find_element(By.CLASS_NAME, "field--name-field-firstname").text.strip()
                    last_name = entry.find_element(By.CLASS_NAME, "field--name-field-lastname").text.strip()
                    name = f"{first_name} {last_name}"

                    # Extract year
                    year = entry.find_element(By.CLASS_NAME, "field--name-field-year").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Extract subject
                    subject = entry.find_element(By.CLASS_NAME, "field--name-field-subject").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Extract affiliation
                    affiliation = entry.find_element(By.CLASS_NAME, "field--name-field-occupation").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Append to data list (Corrected to include subject)
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'subject': subject, 'affiliation': affiliation})
                    laureates_on_page += 1

                except NoSuchElementException:
                    print(f"Warning: Skipped one entry on page {page_num} due to missing data.")
                    pass
            
            total_laureates += laureates_on_page
            print(f"Successfully scraped {laureates_on_page} laureates. Total so far: {total_laureates}.")
            
            # --- Pagination ---
            try:
                print("Looking for 'Next' button...")
                # Wait until the 'Next' button is clickable
                next_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".pager__item--next a")))
                
                # Get a reference to an element on the current page to check for staleness later
                first_entry_on_page = entries[0]
                
                next_button.click()
                print("Clicked 'Next'. Waiting for new page to load...")

                # Wait for the old page content to go stale, confirming navigation
                wait.until(EC.staleness_of(first_entry_on_page))
                page_num += 1
            except TimeoutException:
                print("No clickable 'Next' button found. This is the last page.")
                break
    
    finally:
        # --- Finalizing ---
        if driver:
            driver.quit()
            print("\n--- Scraping finished. Web driver closed. ---")

    if not db:
        print(f"Award ID {aid} - No data was scraped. Exiting.")
        return pd.DataFrame()

    print(f"Total laureates scraped: {len(db)}. Creating DataFrame.")
    df = pd.DataFrame(db)

    # Reorder columns to a logical sequence
    df = df[['id', 'govid', 'govname', 'award', 'year', 'name', 'subject', 'affiliation']]

    print("Displaying first 5 rows of the scraped data:")
    print(tabulate(df.head(), headers='keys', tablefmt='psql'))

    output_path = f'{filepath}{aid}.csv'
    print(f"\nSaving data to {output_path}...")
    df.to_csv(output_path, index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"Success! Award ID {aid} data saved at {current_time}")

    return df

In [312]:
def scrape2769():
    # --- Configuration ---
    award = "Bower Award for Business Leadership"
    govid = "346"
    govname = "Franklin Institute"
    aid = "2769"
    url = "https://fi.edu/en/awards/laureates/search?field_lastname_value=&field_subject_target_id=All&field_awards_target_id=379&field_year_value=&field_year_value_1="
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    print(f"--- Starting scrape for Award ID: {aid} ({award}) ---")

    # --- Driver Initialization ---
    print("Initializing headless Chrome driver...")
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument(f'user-agent={headers["User-Agent"]}')
    driver = webdriver.Chrome(options=options)
    
    # Set up a reusable wait object with a 10-second timeout
    wait = WebDriverWait(driver, 10)

    try:
        # --- Navigation ---
        print("Navigating to the target URL...")
        driver.get(url)

        # --- Scraping Loop ---
        page_num = 1
        total_laureates = 0
        while True:
            print(f"\n--- Scraping Page {page_num} ---")
            
            try:
                # Wait for the main content of the page to be visible
                wait.until(EC.visibility_of_element_located((By.CLASS_NAME, "view-content")))
                entries = driver.find_elements(By.CLASS_NAME, "views-row")
                if not entries:
                    print("Content loaded, but no laureate entries found. Ending scrape.")
                    break
            except TimeoutException:
                print("Timed out waiting for page content. Assuming no more results.")
                break

            print(f"Found {len(entries)} entries on this page.")
            laureates_on_page = 0
            for entry in entries:
                try:
                    # Extract name
                    first_name = entry.find_element(By.CLASS_NAME, "field--name-field-firstname").text.strip()
                    last_name = entry.find_element(By.CLASS_NAME, "field--name-field-lastname").text.strip()
                    name = f"{first_name} {last_name}"

                    # Extract year
                    year = entry.find_element(By.CLASS_NAME, "field--name-field-year").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Extract subject
                    subject = entry.find_element(By.CLASS_NAME, "field--name-field-subject").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Extract affiliation
                    affiliation = entry.find_element(By.CLASS_NAME, "field--name-field-occupation").find_element(By.CLASS_NAME, "field__item").text.strip()
                    
                    # Append to data list (Corrected to include subject)
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'subject': subject, 'affiliation': affiliation})
                    laureates_on_page += 1

                except NoSuchElementException:
                    print(f"Warning: Skipped one entry on page {page_num} due to missing data.")
                    pass
            
            total_laureates += laureates_on_page
            print(f"Successfully scraped {laureates_on_page} laureates. Total so far: {total_laureates}.")
            
            # --- Pagination ---
            try:
                print("Looking for 'Next' button...")
                # Wait until the 'Next' button is clickable
                next_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".pager__item--next a")))
                
                # Get a reference to an element on the current page to check for staleness later
                first_entry_on_page = entries[0]
                
                next_button.click()
                print("Clicked 'Next'. Waiting for new page to load...")

                # Wait for the old page content to go stale, confirming navigation
                wait.until(EC.staleness_of(first_entry_on_page))
                page_num += 1
            except TimeoutException:
                print("No clickable 'Next' button found. This is the last page.")
                break
    
    finally:
        # --- Finalizing ---
        if driver:
            driver.quit()
            print("\n--- Scraping finished. Web driver closed. ---")

    if not db:
        print(f"Award ID {aid} - No data was scraped. Exiting.")
        return pd.DataFrame()

    print(f"Total laureates scraped: {len(db)}. Creating DataFrame.")
    df = pd.DataFrame(db)

    # Reorder columns to a logical sequence
    df = df[['id', 'govid', 'govname', 'award', 'year', 'name', 'subject', 'affiliation']]

    print("Displaying first 5 rows of the scraped data:")
    print(tabulate(df.head(), headers='keys', tablefmt='psql'))

    output_path = f'{filepath}{aid}.csv'
    print(f"\nSaving data to {output_path}...")
    df.to_csv(output_path, index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"Success! Award ID {aid} data saved at {current_time}")

    return df

In [313]:
def scrape884():
    award = "Early Career Professional Awards/Arthur C Guyton Awards for Excellence in Integrative Physiology"
    govid = "94"
    govname = "National Academy of Sciences"
    aid = "884"
    url = "https://www.physiology.org/professional-development/awards/researchers/guyton/aguyton-awardees?SSO=Y"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    divs = soup.find_all('div', class_='accordion__label')
    for div in divs:
        year = div.find('strong').text.split()[0].strip()
        card = div.find_next('div', class_='accordion__content')
        name = card.find('p').contents[0].split(', ')[0].strip()
        affiliation = card.find('em').text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [314]:
def scrape906():
    award = "Established Professional/Walter B Cannon Award Lecture"
    govid = "94"
    govname = "National Academy of Sciences"
    aid = "906"
    url = "https://www.physiology.org/professional-development/awards/researchers/cannon-award/physiology-in-perspective-walter-b-cannon-award-lecture-award-recipients?SSO=Y"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    divs = soup.find_all('div', class_='accordion__label')
    for div in divs:
        year = div.find('strong').text.split()[0].strip()
        card = div.find_next('div', class_='accordion__content')
        name = card.find('p').contents[0].strip()
        affiliation = card.find('em').text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [315]:
def scrape2017():
    award = "Henry Draper Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2017"
    url = "https://www.nasonline.org/award/henry-draper-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [316]:
def scrape2015():
    award = "Gibbs Brothers Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2015"
    url = "https://www.nae.edu/219195/GibbsWinners#tabs"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(2)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                year = li.find_element(By.CLASS_NAME, 'listHeading')
                year = year.text.strip()
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    position = ""
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl03_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [317]:
def scrape2014():
    award = "G K Warren Prize"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2014"
    url = "https://www.nasonline.org/award/g-k-warren-prize/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [318]:
def scrape2012():
    award = "Comstock Prize in Physics"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2012"
    url = "https://www.nasonline.org/award/comstock-prize-in-physics/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [319]:
def scrape2010():
    award = "Arthur L Day Prize and Lectureship"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2010"
    url = "https://www.nasonline.org/award/arthur-l-day-prize-and-lectureship/"
    local_filepath = filepath if 'filepath' in globals() else '' 
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    if recentdiv:
        h5 = recentdiv.find('h5')
        h6 = recentdiv.find('h6')
        if h5 and h6:
            names = h5.text.strip()
            names = names.split(" and")
            year = h6.text.strip()
            for name in names:
                name = name.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdivs = soup.find_all('div', class_="repeater-grid")
    if len(prevdivs) > 1:
        prevdiv = prevdivs[1]
        cards = prevdiv.find_all('div', class_="repeater-card")
        for card in cards:
            h5 = card.find('h5')
            h6 = card.find('h6')
            if h5 and h6:
                names = h5.text.strip()
                names = names.split(" and")
                year = h6.text.strip()
                for name in names:
                    name = name.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    # display(df) # Removed display to avoid confusion in some environments
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{local_filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [320]:
def scrape2009():
    award = "Arctowski Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2009"
    url = "https://www.nasonline.org/award/arctowski-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    
    return df

In [321]:
def scrape2008():
    award = "Alexander Hollaender Award in Biophysics"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2008"
    url = "https://www.nasonline.org/award/alexander-hollaender-award-in-biophysics/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [322]:
def scrape2007():
    award = "Alexander Agassiz Medal"
    govid = "222"
    govname = "National Academy of Sciences"
    aid = "2007"
    url = "https://www.nasonline.org/award/alexander-agassiz-medal/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    recentdiv = soup.find('div', class_="recent-recipient-grid")
    names = recentdiv.find('h5').text.strip()
    names = names.split(" and")
    year = recentdiv.find('h6').text.strip()
    for name in names:
        name = name.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    prevdiv = soup.find_all('div', class_="repeater-grid")[1]
    cards = prevdiv.find_all('div', class_="repeater-card")
    for card in cards:
        names = card.find('h5').text.strip()
        names = names.split(" and")
        year = card.find('h6').text.strip()
        for name in names:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    
    return df

In [323]:
def scrape2006():
    award = "Simon Ramo Founders Award"
    govid = "221"
    govname = "National Academy of Engineering"
    aid = "2006"
    url = "https://www.nae.edu/55294/FoundersWinners?id=55294"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(2)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                year = li.find_element(By.CLASS_NAME, 'listHeading')
                year = year.text.strip()
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    position = ""
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl03_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [324]:
def scrape2005():
    award = "Charles Stark Draper Prize"
    govid = "221"
    govname = "National Academy of Engineering"
    aid = "2005"
    url = "https://www.nae.edu/55291/DraperWinners?id=55291"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(5)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                try:
                    year = li.find_element(By.CLASS_NAME, 'listHeading')
                    year = year.text.strip()
                except NoSuchElementException:
                    year = year
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    position = ""
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl00_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [325]:
def scrape2003():
    award = "Arthur M Bueche Award"
    govid = "221"
    govname = "National Academy of Engineering"
    aid = "2003"
    url = "https://www.nae.edu/55295/PreviousBuecheWinners?id=55295"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(5)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                try:
                    year = li.find_element(By.CLASS_NAME, 'listHeading')
                    year = year.text.strip()
                except NoSuchElementException:
                    year = year
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    position = ""
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl04_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [326]:
def scrape1984():
    award = "William Riley Parker Prize"
    govid = "216"
    govname = "Modern Language Association"
    aid = "1984"
    url = "https://www.mla.org/Resources/Career/MLA-Grants-and-Awards/Winners-of-MLA-Prizes/Annual-Prize-and-Award-Winners/William-Riley-Parker-Prize-Winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='ezrichtext-field')
    h2s = mdiv.find_all('h2')
    for h2 in h2s:
        year = h2.text.strip()
        ul = h2.find_next('ul')
        if ul:
            lis = ul.find_all('li')
            for li in lis:
                li_text_clean = li.text.strip()
                if li_text_clean.startswith('Honorable mention'):
                    continue
                
                parts = li_text_clean.split(' for ')
                if len(parts) > 0:
                    person_part = parts[0]
                    comma_parts = person_part.split(',')
                    
                    if len(comma_parts) >= 1:
                        name = comma_parts[0].strip()
                        aff = ''
                        if len(comma_parts) > 1:
                            aff = ','.join(comma_parts[1:]).strip()
                            if aff.endswith(','):
                                aff = aff[:-1].strip()
                        
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    try:
        df.to_csv(f'{filepath}{aid}.csv',index=False)
    except NameError:
        df.to_csv(f'{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [327]:
def scrape1977():
    award = "MLA Award for Lifetime Scholarly Achievement"
    govid = "216"
    govname = "Modern Language Association"
    aid = "1977"
    url = "https://www.mla.org/Resources/Career/MLA-Grants-and-Awards/Winners-of-MLA-Prizes/MLA-Award-for-Lifetime-Scholarly-Achievement"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='ezrichtext-field')
    h3s = mdiv.find_all('h2')
    for h3 in h3s:
        year = h3.text.strip()
        ul = h3.find_next('ul')
        lis = ul.find_all('li')
        for li in lis:
            litext = li.text.split(',')
            name = litext[0].strip()
            position = litext[1].strip()
            aff = ''.join(litext[2:]).strip()
            if position.startswith('Indiana'):
                aff = position + ' ' + aff
                position = ''
            if not name.startswith('Honorable'):
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff, 'position': position})
    
    df = pd.DataFrame(db)
    mask = (df['affiliation'] == '') & df['position'].notna()
    df.loc[mask, 'affiliation'] = df.loc[mask, 'position']
    df.loc[mask, 'position'] = ''
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [328]:
def scrape1972():
    award = "James Russell Lowell Prize"
    govid = "216"
    govname = "Modern Language Association"
    aid = "1972"
    url = "https://www.mla.org/Resources/Career/MLA-Grants-and-Awards/Winners-of-MLA-Prizes/Annual-Prize-and-Award-Winners/James-Russell-Lowell-Prize-Winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='ezrichtext-field')
    h2s = mdiv.find_all('h2')  # Changed from h3 to h2
    for h2 in h2s:
        year = h2.text.strip()
        # Find the next UL sibling
        ul = h2.find_next_sibling('ul')
        # Or find_next('ul') if it's not strictly a sibling but nearby. find_next is generally safer if structure varies slighty
        if not ul:
             ul = h2.find_next('ul')
        
        if ul:
            lis = ul.find_all('li')
            for li in lis:
                li_text_clean = li.text.strip()
                if li_text_clean.startswith('Honorable mention'):
                    continue
                
                # Split by ' for ' to separate name/aff from work title
                # Using ' for ' with spaces to avoid splitting words containing 'for'
                parts = li_text_clean.split(' for ')
                if len(parts) > 0:
                    person_part = parts[0]
                    
                    # Split by comma to separate Name and Affiliation
                    # Assuming format: Name, Affiliation, ...
                    comma_parts = person_part.split(',')
                    
                    name = comma_parts[0].strip()
                    aff = ''
                    if len(comma_parts) > 1:
                        # Join the rest, as affiliation might contain commas (e.g. University of Michigan, Ann Arbor)
                        aff = ','.join(comma_parts[1:]).strip()
                        # Remove trailing comma if it exists (from the ' for ' split)
                        if aff.endswith(','):
                            aff = aff[:-1].strip()
                    
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [329]:
def scrape1940():
    award = "MacArthur Fellow"
    govid = "212"
    govname = "MacArthur Foundation"
    aid = "1940"
    url = "https://www.macfound.org/programs/awards/fellows/search#fellowssearch"

    download_dir = tempfile.mkdtemp(prefix=f"award_{aid}_")
    chrome_options = Options()
    chrome_options.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })

    driver = webdriver.Chrome(options=chrome_options)
    df = pd.DataFrame()

    try:
        driver.get(url)

        reject_button = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.ID, "onetrust-reject-all-handler"))
        )
        reject_button.click()

        export_link = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//a[contains(@href, 'javascript:getExport()') and contains(@class, 'fellowsearchtext') and contains(text(), 'Download Fellows Data')]"))
        )
        export_link.click()

        timeout = time.time() + 30
        csv_file = None
        while time.time() < timeout:
            files = os.listdir(download_dir)
            csv_files = [f for f in files if f.lower().endswith(".csv")]
            if csv_files:
                csv_file = csv_files[0]
                break
            time.sleep(0.5)
        else:
            raise FileNotFoundError("CSV download did not complete in time")

        csv_path = os.path.join(download_dir, csv_file)
        df = pd.read_csv(csv_path)

    finally:
        driver.quit()

    df.iloc[:, 18] = df.iloc[:, 18].fillna('')
    df['name'] = df.iloc[:, 0]
    df['year'] = df.iloc[:, 3]
    df['field'] = df.iloc[:, 5].str.capitalize()
    df['affiliation'] = df.iloc[:, 18]
    df['id'] = aid
    df['govid'] = govid
    df['govname'] = govname
    df['award'] = award

    df = df[['name', 'year', 'field', 'affiliation', 'id', 'govid', 'govname', 'award']]
    
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    try:
        for f in os.listdir(download_dir):
            os.remove(os.path.join(download_dir, f))
        os.rmdir(download_dir)
    except Exception:
        pass
    
    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [330]:
def scrape1935():
    award = "Lasker-Bloomberg Public Service Award"
    govid = "210"
    govname = "Lasker Foundation"
    aid = "1935"
    url = "https://laskerfoundation.org/award/public-service/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    last_height = driver.execute_script("return document.body.scrollHeight")

    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        # Wait for some time to load new content
        time.sleep(2)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break  # Stop scrolling if no new content is loaded
        last_height = new_height
   
    mdiv = driver.find_element(By.CSS_SELECTOR, ".fusion-posts-container.fusion-posts-container-infinite")
    arts = mdiv.find_elements(By.TAG_NAME, 'h2')
    for art in arts:
        a = art.find_element(By.TAG_NAME, 'a')
        href = a.get_attribute('href')
        links.append(href)

    for link in links:
        driver.get(link)
        h3 = driver.find_element(By.TAG_NAME, 'h3')
        year = h3.text.split()[0].strip()

        mcard = driver.find_element(By.CLASS_NAME, 'center-main-content')
        cards = mcard.find_elements(By.CLASS_NAME, 'fusion-flex-column')
        for card in cards:
            name = card.find_element(By.CLASS_NAME, 'aw-name')
            name = name.text.strip()

            try:
                aff = card.find_element(By.CLASS_NAME, 'aw-work')
                aff = aff.text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
            except NoSuchElementException:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [331]:
def scrape1934():
    award = "Lasker-DeBakey Clinical Medical Research Award"
    govid = "210"
    govname = "Lasker Foundation"
    aid = "1934"
    url = "https://laskerfoundation.org/award/clinical/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    last_height = driver.execute_script("return document.body.scrollHeight")

    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        # Wait for some time to load new content
        time.sleep(2)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break  # Stop scrolling if no new content is loaded
        last_height = new_height
   
    mdiv = driver.find_element(By.CSS_SELECTOR, ".fusion-posts-container.fusion-posts-container-infinite")
    arts = mdiv.find_elements(By.TAG_NAME, 'h2')
    for art in arts:
        a = art.find_element(By.TAG_NAME, 'a')
        href = a.get_attribute('href')
        links.append(href)

    print(links)

    for link in links:
        driver.get(link)
        h3 = driver.find_element(By.TAG_NAME, 'h3')
        year = h3.text.split()[0].strip()

        mcard = driver.find_element(By.CLASS_NAME, 'center-main-content')
        cards = mcard.find_elements(By.CLASS_NAME, 'fusion-flex-column')
        for card in cards:
            name = card.find_element(By.CLASS_NAME, 'aw-name')
            name = name.text.strip()

            try:
                aff = card.find_element(By.CLASS_NAME, 'aw-work')
                aff = aff.text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
            except NoSuchElementException:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [332]:
def scrape1933():
    award = "Albert Lasker Basic Medical Research Award"
    govid = "210"
    govname = "Lasker Foundation"
    aid = "1933"
    url = "https://laskerfoundation.org/award/basic/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    last_height = driver.execute_script("return document.body.scrollHeight")

    while True:
        # Scroll down to bottom
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        # Wait for some time to load new content
        time.sleep(2)

        # Calculate new scroll height and compare with last scroll height
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break  # Stop scrolling if no new content is loaded
        last_height = new_height
   
    mdiv = driver.find_element(By.CSS_SELECTOR, ".fusion-posts-container.fusion-posts-container-infinite")
    arts = mdiv.find_elements(By.TAG_NAME, 'h2')
    for art in arts:
        a = art.find_element(By.TAG_NAME, 'a')
        href = a.get_attribute('href')
        links.append(href)

    for link in links:
        driver.get(link)
        h3 = driver.find_element(By.TAG_NAME, 'h3')
        year = h3.text.split()[0].strip()

        mcard = driver.find_element(By.CLASS_NAME, 'center-main-content')
        cards = mcard.find_elements(By.CLASS_NAME, 'fusion-flex-column')
        for card in cards:
            name = card.find_element(By.CLASS_NAME, 'aw-name')
            name = name.text.strip()

            try:
                aff = card.find_element(By.CLASS_NAME, 'aw-work')
                aff = aff.text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
            except NoSuchElementException:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [333]:
def scrape1932():
    award = "Lasker-Koshland Special Achievement Award in Medical Science"
    govid = "210"
    govname = "Lasker Foundation"
    aid = "1932"
    url = "https://laskerfoundation.org/award/special-achievement/"
        
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.add_argument(f'user-agent={headers["User-Agent"]}')
    options.add_argument("--headless=new")
    options.add_argument("--window-size=1920,1080")
    options.page_load_strategy = 'eager'

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []
    
    try:
        WebDriverWait(driver, 15).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, ".fusion-posts-container"))
        )
    except TimeoutException:
        print("Error: Main content container did not load in time.")
        driver.quit()
        return pd.DataFrame()

    last_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
   
    mdiv = driver.find_element(By.CSS_SELECTOR, ".fusion-posts-container.fusion-posts-container-infinite")
    arts = mdiv.find_elements(By.TAG_NAME, 'h2')
    for art in arts:
        try:
            a = art.find_element(By.TAG_NAME, 'a')
            href = a.get_attribute('href')
            links.append(href)
        except NoSuchElementException:
            continue

    for link in links:
        try:
            driver.get(link)
        except TimeoutException:
            print(f"Warning: Timed out loading page {link}. Skipping.")
            continue
        
        try:
            WebDriverWait(driver, 10).until(
                EC.visibility_of_element_located((By.CLASS_NAME, "post-content"))
            )
            
            h3 = driver.find_element(By.TAG_NAME, 'h3')
            year = h3.text.split()[0].strip()

            # --- FIX: Use a specific CSS selector to avoid duplicates ---
            cards = driver.find_elements(By.CSS_SELECTOR, '.fusion-flex-container > .fusion-flex-column')

            if cards:
                for card in cards:
                    try:
                        name_element = card.find_element(By.CLASS_NAME, 'aw-name')
                        name = name_element.text.strip()
                        if not name: continue

                        try:
                            aff = card.find_element(By.CLASS_NAME, 'aw-work').text.strip()
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})
                        except NoSuchElementException:
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                    except NoSuchElementException:
                        continue
            else: # Legacy layout parser
                try:
                    name_element = driver.find_element(By.CSS_SELECTOR, '.post-content p strong')
                    name = name_element.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                except NoSuchElementException:
                    continue
        except Exception:
            continue

    driver.quit()

    if not db:
        return pd.DataFrame()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    
    csv_path = f'{filepath}{aid}.csv'
    df.to_csv(csv_path, index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [334]:
def scrape1920():
    award = "Fields Medal"
    govid = "204"
    govname = "International Mathematical Union"
    aid = "1920"
    url = "https://www.mathunion.org/imu-awards/fields-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    h2 = soup.find('h2', string='The Fields Medalists, chronologically listed')
    mdiv = h2.find_next_sibling('div')

    divs = mdiv.find_all('div', class_='list__group')
    for div in divs:
        year = div.find('h3').text.strip()
        lis = div.find_all('li', class_='blue-link')
        for li in lis:
            name = li.find('a').text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [335]:
def scrape1776():
    award = "ESA Founders' Memorial Award"
    govid = "183"
    govname = "Entomological Society of America"
    aid = "1776"
    url = "https://www.entsoc.org/awards/honors/founders_list"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='page-wrapper')
    tbod = mdiv.find('table')
    trs = tbod.find_all('tr')
    for tr in trs[1:]:
        tds = tr.find_all('td')
        year = tds[0].text.strip()
        name1 = tds[1].text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name1, 'subaward': 'Lecturer'})
        name2 = tds[2].text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name2, 'subaward': 'Honoree'})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [336]:
def scrape1628():
    award = "Gold Medal Award for Distinguished Archaeological Achievement"
    govid = "155"
    govname = "Archaeological Institute of America"
    aid = "1628"
    url = "https://www.archaeological.org/grant/gold-medal-award/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='recipient_wrap')
    rows = mdiv.find_all('div', class_='row')
    for row in rows:
        year = row.find('p').text.strip()
        name_text = row.find('h4').text.strip()
        
        if " and " in name_text:
            names = name_text.split(" and ")
            for name in names:
                name = name.strip()
                if len(name) > 1:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        else:
            if len(name_text) > 1:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name_text})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [337]:
def scrape1607():
    award = "Constance M Rourke Prize"
    govid = "151"
    govname = "American Studies Association"
    aid = "1607"
    url = "https://www.theasa.net/awards/asa-awards-prizes/constance-m-rourke-prize"
    db = []
    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36')
    options.add_argument('--log-level=3')
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    
    driver = webdriver.Chrome(options=options)
    
    try:
        driver.get(url)

        time.sleep(5)
        
        h3 = driver.find_element(By.XPATH, "//h3[contains(text(), 'Past Winners')]")
        ul = h3.find_element(By.XPATH, "./following-sibling::ul[1]")
        list_items = ul.find_elements(By.TAG_NAME, "li")

        for li in list_items:
            text = li.text.replace('\n', ' ').strip()

            if 'Special recognition' in text:
                continue

            year_part, name_part = None, None
            
            # Prioritize Year detection at the start
            if text[:4].isdigit():
                year_part = text[:4]
                name_part = text[4:].strip()
                # Remove leading colon, dash, or whitespace
                name_part = name_part.lstrip(':-– ')
            elif ':' in text:
                parts = text.split(':', 1)
                year_part = parts[0].strip()
                name_part = parts[1].strip()

            if year_part and name_part:
                year = year_part
                name = name_part.split(',')[0].strip()
                # If name still contains quotes or seems to capture a title, clean it further if needed
                # But splitting by comma usually handles "Eric Lott, 'Title'" -> "Eric Lott"
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })
    finally:
        driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [338]:
def scrape1606():
    award = "Carl Bode-Norman Holmes Pearson Prize"
    govid = "151"
    govname = "American Studies Association"
    aid = "1606"
    url = "https://www.theasa.net/awards/asa-awards-prizes/carl-bode-%E2%80%93-norman-holmes-pearson-prize"
    db = []

    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36')
    options.add_argument('--log-level=3')
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    
    driver = webdriver.Chrome(options=options)
    
    try:
        driver.get(url)
        time.sleep(5)
        
        h3 = driver.find_element(By.XPATH, "//h3[contains(text(), 'Past Winners')]")
        ul = h3.find_element(By.XPATH, "./following-sibling::ul[1]")
        list_items = ul.find_elements(By.TAG_NAME, "li")

        for li in list_items:
            text = li.text.replace('\n', ' ').strip()

            if 'No selection' in text or not text:
                continue

            parts = text.split(':', 1)
            if len(parts) != 2:
                continue
            
            year = parts[0].strip()
            winner_data = parts[1].strip()

            individual_winners = winner_data.split(' and ')
            for winner_entry in individual_winners:
                winner_entry = winner_entry.strip()
                name = ''
                affiliation = ''
                
                if ',' in winner_entry:
                    name_aff_parts = winner_entry.split(',', 1)
                    name = name_aff_parts[0].strip()
                    affiliation = name_aff_parts[1].strip()
                else:
                    name = winner_entry

                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name,
                    'affiliation': affiliation
                })
    finally:
        driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [339]:
def scrape1438():
    award = "Stephen Hales Prize"
    govid = "143"
    govname = "American Society of Plant Biologists"
    aid = "1438"
    url = "https://aspb.org/awards-funding/aspb-awards/stephen-hales-prize/#tab-id-3"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    # Handle the most recent winner element
    try:
        recent_winner_h3 = soup.find('h3', string=lambda text: text and 'Winner:' in text)
        if recent_winner_h3:
            h3_text = recent_winner_h3.text.strip()
            parts = h3_text.split(' Winner: ')
            if len(parts) == 2:
                year = parts[0].strip()
                name = parts[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception:
        # Fails silently if the element isn't found or format is unexpected
        pass

    # Handle the list of past winners
    mdiv = soup.find('div', id='tab-id-3-content')
    if mdiv:
        ps = mdiv.find_all('p')
        for p in ps:
            pt = p.text.strip()
            # Skip empty or non-data paragraphs
            if not pt or not pt[0].isdigit():
                continue
            
            try:
                year = pt.split()[0].strip()
                name_tag = p.find('strong') or p.find('b')
                if name_tag:
                    name = name_tag.text.strip('*').strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            except (IndexError, AttributeError):
                # Skip paragraphs that don't match the expected format
                continue

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    # Clean, sort, and prepare the final DataFrame
    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [340]:
def scrape1437():
    award = "Martin Gibbs Medal"
    govid = "143"
    govname = "American Society of Plant Biologists"
    aid = "1437"
    url = "https://aspb.org/awards-funding/aspb-awards/martin-gibbs-medal/#tab-id-3"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    try:
        recent_winner_h3 = soup.find('h3', string=lambda text: text and 'Winner:' in text)
        if recent_winner_h3:
            h3_text = recent_winner_h3.text.strip()
            parts = h3_text.split(' Winner: ')
            if len(parts) == 2:
                year = parts[0].strip()
                name = parts[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception:
        pass

    mdiv = soup.find('div', id='tab-id-3-content')
    if mdiv:
        ps = mdiv.find_all('p')
        for p in ps:
            pt = p.text.strip()
            if not pt or not pt[0].isdigit():
                continue
            
            try:
                year = pt.split()[0].strip()
                name_tag = p.find('strong') or p.find('b')
                if name_tag:
                    name = name_tag.text.strip('*').strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            except (IndexError, AttributeError):
                continue

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [341]:
def scrape1429():
    award = "Charles Albert Shull Award"
    govid = "143"
    govname = "American Society of Plant Biologists"
    aid = "1429"
    url = "https://aspb.org/awards-funding/aspb-awards/charles-albert-shull-award/#tab-id-3"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    try:
        recent_winner_h3 = soup.find('h3', string=lambda text: text and 'Winner:' in text)
        if recent_winner_h3:
            h3_text = recent_winner_h3.text.strip()
            parts = h3_text.split(' Winner: ')
            if len(parts) == 2:
                year = parts[0].strip()
                name = parts[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception:
        pass

    mdiv = soup.find('div', id='tab-id-3-content')
    if mdiv:
        ps = mdiv.find_all('p')
        for p in ps:
            pt = p.text.strip()
            if not pt or not pt[0].isdigit():
                continue
            
            try:
                year = pt.split()[0].strip()
                name_tag = p.find('strong') or p.find('b')
                if name_tag:
                    name = name_tag.text.strip('*').strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            except (IndexError, AttributeError):
                continue

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [342]:
def scrape1428():
    award = "Adolph E Gude, Jr Award"
    govid = "143"
    govname = "American Society of Plant Biologists"
    aid = "1428"
    url = "https://aspb.org/awards-funding/aspb-awards/adolph-e-gude-jr-award/#tab-id-3"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    try:
        recent_winner_h3 = soup.find('h3', string=lambda text: text and 'Winner:' in text)
        if recent_winner_h3:
            h3_text = recent_winner_h3.text.strip()
            parts = h3_text.split(' Winner: ')
            if len(parts) == 2:
                year = parts[0].strip()
                name = parts[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception:
        pass

    mdiv = soup.find('div', id='tab-id-3-content')
    if mdiv:
        ps = mdiv.find_all('p')
        for p in ps:
            pt = p.text.strip()
            if '–' not in pt:
                continue
            
            try:
                year, names_str = [x.strip() for x in pt.split('–', 1)]
                if not year.isdigit() or len(year) != 4:
                    continue

                individual_names = [n.strip('*').strip() for n in names_str.split(' and ')]
                for name in individual_names:
                    if name:
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            except (ValueError, IndexError):
                continue

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [343]:
def scrape1393():
    award = "The ASME Medal"
    govid = "139"
    govname = "American Society of Mechanical Engineers (ASME)"
    aid = "1393"
    url = "https://www.asme.org/about-asme/honors-awards/achievement-awards/asme-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    h3 = soup.find('h3', string='ASME Medalists')
    table = h3.find_next_sibling('table')
    trs = table.find_all('tr')
    
    for tr in trs:
        tds = tr.find_all('td')
        year = tds[0].text.strip()
        name = tds[1].text.strip()
        if len(name) > 1:
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [344]:
def scrape1234():
    award = "The Morrison Award"
    govid = "125"
    govname = "American Society of Animal Science"
    aid = "1234"
    url = "https://www.asas.org/about/national-awards/past-awardees"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    table = driver.find_element(By.CLASS_NAME, 'past-award-winners')
    tbody = table.find_element(By.TAG_NAME, 'tbody')
    trs = tbody.find_elements(By.TAG_NAME, 'tr')
    
    for tr in trs:
        tds = tr.find_elements(By.TAG_NAME, 'td')
        if tds[3].text.strip() == 'The Morrison Award' or tds[3].text.strip() == 'Morrison Award':
            year = tds[0].text.strip()
            name = tds[1].text.strip()
            aff = tds[2].text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'affiliation': aff})

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [345]:
def scrape1194():
    award = "Cyrus Hall McCormick-Jerome Increase Case Gold Medal"
    govid = "123"
    govname = "American Society of Agricultural and Biological Engineers"
    aid = "1194"
    url = "https://www.asabe.org/Awards-Competitions/Major-Awards/CYRUS-HALL-McCORMICK-JEROME-INCREASE-CASE-GOLD-MEDAL"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the main URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    try:
        p_tags = soup.find_all('p', style="text-align: center;")
        for p in p_tags:
            if 'Recipient' in p.get_text():
                year_match = re.search(r'\b(20\d{2})\b', p.get_text())
                strong = p.find('strong')
                if year_match and strong:
                    year = year_match.group(1)
                    name = strong.get_text(strip=True)
                    if name:
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                        break
    except Exception as e:
        print(f"Could not parse current recipient. Error: {e}")

    temp_pdf_path = None
    try:
        pdf_link_tag = soup.find('a', string=re.compile("Past Recipients"))
        if not pdf_link_tag or not pdf_link_tag.has_attr('href'):
            raise Exception("PDF link not found on the page.")

        pdf_url = urljoin(url, pdf_link_tag['href'])
        pdf_response = requests.get(pdf_url, headers=headers)
        pdf_response.raise_for_status()

        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_f:
            temp_pdf_path = temp_f.name
            temp_f.write(pdf_response.content)

        pdf_text = extract_text(temp_pdf_path)
        for line in pdf_text.split('\n'):
            line = line.strip()
            if line and line[:4].isdigit() and len(line) > 4:
                year = line[:4]
                name = line.split('..')[-1].strip('.').strip()
                if name and 'No Recipient' not in name:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception as e:
        print(f"Failed during PDF processing: {e}")
    finally:
        if temp_pdf_path and os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    df['award'] = award

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [346]:
def scrape1123():
    award = "Award of Merit"
    govid = "113"
    govname = "Association for Information Science and Technology"
    aid = "1123"
    url = "https://www.asist.org/programs-services/awards-honors/award-of-merit/aom-recipients/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    h4 = soup.find('h4')
    divs = h4.find_all_next('div', class_='fl-col-group')
    for div in divs:
        try:
            cols = div.find_all('p')
            year = cols[0].text.strip()
            name = cols[1].text.strip()
            if len(name.split(' and ')) > 1:
                names = name.split(' and ')
                for name in names:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            elif len(year) == 4:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        except IndexError:
            pass
    
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [347]:
def scrape908():
    # Blocked behind sign in page now
    print("908 scraping skipped due to sign-in requirement.")
    # award = "Award of Distinction"
    # govid = "95"
    # govname = "American Phytopathological Society"
    # aid = "908"
    # url = "https://www.apsnet.org/members/give-awards/awards/AwardofDistinction/Pages/default.aspx"
    # db = []
    # headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")
    
    # tbod = soup.find('tbody')
    # ps = tbod.find_all('p')
    
    # for p in ps:
    #     pt = [str(text).strip() for text in p.strings if text.strip()]
    #     for p in pt:
    #         if len(p) == 4:
    #             year = p
    #         elif len(p) > 4 and p[0].isdigit():
    #             year = p.split()[0].strip()
    #             name = p[5:].strip()
    #             db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    #         elif len(p) > 4 and not p[0].isdigit():
    #             name = p.strip()
    #             db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    
    # df = pd.DataFrame(db)
    # print(tabulate(df, headers='keys', tablefmt='psql'))
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    # return df

In [348]:
def scrape823():
    award = "Thomas Jefferson Medal for Distinguished Achievement in the Arts, Humanities, and Social Sciences"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "823"
    url = "https://www.amphilsoc.org/prizes/thomas-jefferson-medal-distinguished-achievement-arts-humanities-and-social-sciences"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pt = p.find('strong').text.strip()

            if len(pt) == 4:
                year = pt
                name = p.find_next('a').text.strip()

            elif len(pt) > 4 and pt[0].isdigit():
                year = pt[:4].strip()
                name = pt.split('\n')[1].strip()

            elif len(pt) > 4 and not pt[0].isdigit():
                name = pt.strip()
                year = None
        
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except AttributeError:
            pass

    df = pd.DataFrame(db)
    df['year'] = df['year'].ffill()
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [349]:
def scrape822():
    award = "The Magellanic Premium of the American Philosophical Society"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "822"
    url = "https://www.amphilsoc.org/prizes/magellanic-premium-american-philosophical-society"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            ptt = p.find_all('strong')

            if len(ptt[0].text.strip()) == 4:
                year = ptt[0].text.strip()
                name = p.find_next('a').text.strip()
                if name == 'Return to top' and len(ptt) < 3:
                    name = ptt[1].text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                elif name == 'Return to top' and len(ptt) >= 3:
                    for pt in ptt[1:]:
                        name = pt.text.strip()
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                else:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif not ptt[0].text.strip()[0].isdigit() and len(ptt) == 1:
                name = ptt[0].text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except AttributeError:
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [350]:
def scrape821():
    award = "The Henry M Phillips Prize in Jurisprudence"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "821"
    url = "https://www.amphilsoc.org/prizes/henry-m-phillips-prize"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            ptt = p.find_all('strong')

            if len(ptt[0].text.strip()) == 4:
                year = ptt[0].text.strip()
                name = p.find_next('a').text.strip()
                if name == 'Return to top' and len(ptt) < 3:
                    name = ptt[1].text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                elif name == 'Return to top' and len(ptt) >= 3:
                    for pt in ptt[1:]:
                        name = pt.text.strip()
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                else:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif not ptt[0].text.strip()[0].isdigit() and len(ptt) == 1:
                name = ptt[0].text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [351]:
def scrape820():
    award = "Henry Allen Moe Prize in the Humanities"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "820"
    url = "https://www.amphilsoc.org/prizes/henry-allen-moe-prize-humanities"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            ptt = p.find_all('strong')

            if len(ptt[0].text.strip()) == 4:
                year = ptt[0].text.strip()
                name = p.find_next('a').text.strip()
                if name == 'Return to top' and len(ptt) < 3:
                    name = ptt[1].text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                elif name == 'Return to top' and len(ptt) >= 3:
                    for pt in ptt[1:]:
                        name = pt.text.strip()
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                else:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif not ptt[0].text.strip()[0].isdigit() and len(ptt) == 1:
                name = ptt[0].text.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [352]:
def scrape818():
    award = "Judson Daland Prize"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "818"
    url = "https://www.amphilsoc.org/prizes/judson-daland-prize-outstanding-achievement-clinical-investigation"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find('strong')

            if pst:
                year = pst.text.strip()
            
            name = p.find('a').find('span').text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [353]:
def scrape817():
    award = "John Frederick Lewis Award"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "817"
    url = "https://www.amphilsoc.org/prizes/john-frederick-lewis-award"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            ptt = p.find_all('strong')
            pzero = ptt[0].text.strip()

            if len(pzero) == 4 and pzero[0].isdigit():
                year = pzero
                for p in ptt[1:]:
                    name = p.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
            
            elif len(pzero) > 4 and pzero[0].isdigit():
                year = pzero[:4]
                names = pzero.split('\n')[1].split(' and ')
                for name in names:
                    name = name.strip('\xa0')
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
        except (AttributeError, IndexError):
            print("Error Occurred")
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [354]:
def scrape816():
    award = "Jacques Barzun Prize in Cultural History"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "816"
    url = "https://www.amphilsoc.org/prizes/jacques-barzun-prize-cultural-history"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find_all('strong')

            if len(pst) == 1 and pst[0].text[0].isdigit():
                year = pst[0].text.strip()
                name = p.find('a').find('span').text.strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) == 1:
                name = pst[0].text.strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) > 1:
                year = pst[0].text.strip()
                for p in pst[1:]:
                    name = p.text.strip().strip(',')
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            print('Error Occured')
            print(p)
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [355]:
def scrape815():
    award = "Benjamin Franklin Medal for Distinguished Public Service"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "815"
    url = "https://www.amphilsoc.org/prizes/benjamin-franklin-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Distinguished Public Services Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find_all('strong')

            if len(pst) == 1 and pst[0].text[0].isdigit():
                year = pst[0].text.split('\n')[0].strip()
                name = pst[0].text.split('\n')[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) == 1:
                name = pst[0].text.split('(')[0].strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) > 1:
                year = pst[0].text.strip()
                for p in pst[1:]:
                    name = p.text.strip().strip(',')
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            print('Error Occured')
            print(p)
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [356]:
def scrape814():
    award = "Benjamin Franklin Medal for Distinguished Achievement in the Sciences"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "814"
    url = "https://www.amphilsoc.org/prizes/benjamin-franklin-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Distinguished Achievement in the Sciences Recipients')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find_all('strong')

            if len(pst) == 1 and pst[0].text[0].isdigit():
                year = pst[0].text.split('\n')[0].strip()
                name = pst[0].text.split('\n')[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) == 1:
                name = pst[0].text.split('(')[0].strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) > 1:
                year = pst[0].text.strip()
                for p in pst[1:]:
                    name = p.text.strip().strip(',')
                    if ' and ' in name:
                        names = name.split(' and ')
                        for name in names:
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

                    elif len(name) > 1:
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            print('Error Occured')
            print(p)
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [357]:
def scrape809():
    award = "Goodwin Award of Merit"
    govid = "89"
    govname = "Society for Classical Studies"
    aid = "809"
    url = "https://classicalstudies.org/awards-and-fellowships/list-previous-goodwin-award-winners"
    db = []
    options = Options()
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(5)  # Allow time for the page to load completely
    soup = BeautifulSoup(driver.page_source, "html.parser")

    mdiv = soup.find('div', class_='block--system-main')

    # Process by paragraphs
    if mdiv:
        ps = mdiv.find_all('p')
        for p in ps:
            strongs = p.find_all('strong')
            if not strongs:
                continue
            
            # The first strong tag should be the year
            year_cand = strongs[0].get_text(strip=True).strip().strip('.')
            if not (year_cand.isdigit() and len(year_cand) == 4):
                continue
            
            year = year_cand
            
            # Subsequent strong tags are names
            for s in strongs[1:]:
                text = s.get_text(strip=True)
                
                # Handle " and " separation
                names = text.split(' and ')
                for n in names:
                    # Handle comma separation
                    sub_names = n.split(',')
                    for sn in sub_names:
                        clean_name = sn.strip().strip('.').strip().strip(',')
                        
                        # Basic validation
                        if len(clean_name) > 2 and any(c.isalpha() for c in clean_name):
                            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': clean_name})

    driver.quit()

    df = pd.DataFrame(db)
    # Filter known non-name entries
    if not df.empty:
        df = df[df['name'] != 'Sophocles']
        print(tabulate(df, headers='keys', tablefmt='psql'))
        df.to_csv(f'{filepath}{aid}.csv',index=False)
        
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    else:
        print("No data scraped.")

    return df

In [358]:
def scrape722():
    award = "Maryam Mirzakhani Prize in Mathematics of the National Academy of Sciences"
    govid = "80"
    govname = "American Mathematical Society"
    aid = "722"
    url = "https://www.ams.org/prizes-awards/pabrowse.cgi?parent_id=32&year=Year"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='paOutput')
    ps = mdiv.find_all('span', class_='paYear')

    for p in ps:
        year = p.text.strip()
        name = p.find_next('span', class_='paWinner').text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [359]:
def scrape611():
    award = "John K Fairbank Prize in East Asian History"
    govid = "69"
    govname = "American Historical Association"
    aid = "611"
    url = "https://www.historians.org/awards-and-grants/past-recipients/john-k-fairbank-prize-recipients"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(2)

    button = driver.find_element(By.XPATH, "//div[@class='fl-accordion-button' and @id='fl-accordion-kjelviqg8rpm-tab-0']")
    button.click()

    time.sleep(1)

    mdiv = driver.find_element(By.XPATH, "//div[@class='fl-accordion-content fl-clearfix' and @id='fl-accordion-kjelviqg8rpm-panel-0']")
    ps = mdiv.find_elements(By.TAG_NAME, 'p')

    for p in ps[1:]:
        sts = p.find_elements(By.TAG_NAME, 'strong')
        year = sts[0].text.strip()
        for st in sts[1:]:
            name = st.text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [360]:
def scrape594():
    award = "Awards for Scholarly Distinction"
    govid = "69"
    govname = "American Historical Association"
    aid = "594"
    url = "https://www.historians.org/awards-and-grants/past-recipients/award-for-scholarly-distinction-recipients"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(2)

    button = driver.find_element(By.XPATH, "//div[@class='fl-accordion-button' and @id='fl-accordion-kjelviqg8rpm-tab-0']")
    button.click()

    time.sleep(1)

    mdiv = driver.find_element(By.XPATH, "//div[@class='fl-accordion-content fl-clearfix' and @id='fl-accordion-kjelviqg8rpm-panel-0']")
    ps = mdiv.find_elements(By.TAG_NAME, 'p')

    for p in ps[1:]:
        sts = p.find_elements(By.TAG_NAME, 'strong')
        year = sts[0].text.strip()
        for st in sts[1:]:
            name = st.text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    driver.quit()

    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=["name", "year"], keep="first")
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [361]:
def scrape593():
    award = "Albert J Beveridge Award"
    govid = "69"
    govname = "American Historical Association"
    aid = "593"
    url = "https://www.historians.org/awards-and-grants/past-recipients/beveridge-family-prize-in-american-history-recipients"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(2)

    button = driver.find_element(By.XPATH, "//div[@class='fl-accordion-button' and @id='fl-accordion-kjelviqg8rpm-tab-0']")
    button.click()

    time.sleep(1)

    mdiv = driver.find_element(By.XPATH, "//div[@class='fl-accordion-content fl-clearfix' and @id='fl-accordion-kjelviqg8rpm-panel-0']")
    ps = mdiv.find_elements(By.TAG_NAME, 'p')

    for p in ps[1:]:
        sts = p.find_elements(By.TAG_NAME, 'strong')
        year = sts[0].text.strip()
        for st in sts[1:]:
            name = st.text.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    driver.quit()

    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=["name", "year"], keep="first")
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [362]:
def scrape528():
    award = "John Bates Clark Medal"
    govid = "59"
    govname = "American Economic Association"
    aid = "528"
    url = "https://www.aeaweb.org/about-aea/honors-awards/bates-clark"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    ps = soup.find_all('p')

    for p in ps:
        pt = p.get_text(strip=True)
        # Match pattern: Year followed by dash and name
        # Dashes can be hyphen (-), en-dash (–), or em-dash (—)
        match = re.match(r'^(\d{4})\s*[–—\-]\s*(.*)', pt)
        
        if match:
            year = match.group(1)
            name = match.group(2).strip()
            # Clean up unicode non-breaking spaces if any
            name = name.replace('\u00a0', ' ')
            
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    # Filter out "No Award" entries
    if not df.empty:
        df = df[df['name'] != 'No Award']
        df = df.drop_duplicates(subset=["name", "year"], keep="first")
        print(tabulate(df, headers='keys', tablefmt='psql'))
        df.to_csv(f'{filepath}{aid}.csv',index=False)

        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    else:
        print("No data scraped.")

    return df

In [363]:
def scrape441():
    award = "Harry Levin Prize"
    govid = "49"
    govname = "American Comparative Literature Association"
    aid = "441"
    url = "https://www.acla.org/prize-awards/harry-levin-prize"
    db = []

    driver = uc.Chrome()
    driver.get(url)

    time.sleep(3)

    try:
        ckbutton = driver.find_element(By.CLASS_NAME, 'eu-cookie-compliance-secondary-button')
        ckbutton.click()
    except Exception as e:
        print("Cookie compliance button not found or could not be clicked. Proceeding without clicking.")

    time.sleep(3)

    button = driver.find_element(By.CLASS_NAME, 'ckeditor-accordion-toggler')
    button.click()

    time.sleep(3)

    mdiv = driver.find_element(By.CLASS_NAME, 'ckeditor-accordion-container')
    items = mdiv.find_element(By.TAG_NAME, 'ul').find_elements(By.TAG_NAME, 'li')
    text = " ".join(item.text for item in items)

    response = model.generate_content(
        contents=(
            "OUTPUT ONLY A JSON ARRAY. NO CODE FENCES, NO MARKDOWN, NO EXPLANATION.\n"
            "Each element must be an object with keys: name, year, affiliation.\n"
            "Rules:\n"
            "  • Exclude any item containing \"honorable\" or \"mention\".\n"
            "  • If affiliation is blank or \"press\", use an empty string.\n\n"
            f"DATA:\n{text}"
        )
    )

    raw = response.text.strip()

    if raw.startswith("```"):
        raw = raw.strip("```json").strip("```").strip()

    match = re.search(r"\[\s*\{.*\}\s*\]", raw, re.DOTALL)
    json_text = match.group(0) if match else raw

    winners = json.loads(json_text)
    for w in winners:
        if len(w["name"]) > 3:
            db.append({
                "id":          aid,
                "govid":       govid,
                "govname":     govname,
                "award":       award,
                "year":        w["year"],
                "name":        w["name"]
            })

    soup = BeautifulSoup(driver.page_source, 'html.parser')
    extra_blocks = soup.find_all('h4')

    for h in extra_blocks:
        heading_text = h.get_text(strip=True)
        year_match = re.search(r'(\d{4})', heading_text)

        if year_match and 'Prize Winner' in heading_text:
            year = year_match.group(1)
            ul = h.find_next_sibling('ul')
            if not ul:
                continue
            for li in ul.find_all('li'):
                text = li.get_text(" ", strip=True)
                if "honorable" in text.lower() or "mention" in text.lower():
                    continue

                name_affil_match = re.match(r"(.+?)\s+\(([^)]+)\)", text)
                if name_affil_match:
                    name = name_affil_match.group(1).strip()
                    affil = name_affil_match.group(2).strip()
                else:
                    name = text.strip()
                    affil = ""

                if len(name) > 3:
                    db.append({
                        "id": aid,
                        "govid": govid,
                        "govname": govname,
                        "award": award,
                        "year": year,
                        "name": name
                    })

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [364]:
def scrape404():
    award = "Priestley Medal"
    govid = "41"
    govname = "American Chemical Society"
    aid = "404"
    url = "https://www.acs.org/funding/awards/priestley-medal/past-recipients.html"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    # options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument(f'user-agent={headers["User-Agent"]}')
    
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    
    time.sleep(3)
    
    soup = BeautifulSoup(driver.page_source, "html.parser")
    driver.quit()

    mdiv = soup.find('div', class_='articleContent')

    ul = mdiv.find_all('ul')

    for u in ul:
        lis = u.find_all('li')
        for li in lis:
            lt = li.text.strip()
            year = lt[:4].strip()
            name = lt.split('-')[1].strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [365]:
def scrape332():
    award = "Henry Norris Russell Lectureship"
    govid = "37"
    govname = "American Astronomical Society"
    aid = "332"
    url = "https://aas.org/grants-and-prizes/henry-norris-russell-lectureship"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    mdiv = driver.find_elements(By.CLASS_NAME,'tw--mx-3')
    divs = mdiv[4].find_elements(By.TAG_NAME, 'h4')

    for div in divs:
        h4 = div.text.strip()
        splat = h4.split('-')
        if len(splat) == 1:
            splat = h4.split('–')
        year = splat[0].strip()
        name = splat[1].strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    mdiv = driver.find_elements(By.CLASS_NAME, 'tw-max-w-2xl')
    tbod = mdiv[1].find_element(By.TAG_NAME, 'tbody')
    trs = tbod.find_elements(By.TAG_NAME, 'tr')
    
    for tr in trs[1:]:
        tds = tr.find_elements(By.TAG_NAME, 'td')
        year = tds[0].text.strip()
        name = tds[1].text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    df = df[df['name'] != 'Omitted']
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [366]:
def scrape203():
    award = "C.J. Herrick Award in Neuroanatomy"
    govid = "21"
    govname = "American Association for Anatomy"
    aid = "203"
    url = "https://www.anatomy.org/ANATOMY/Awards-Programs/Award-Recipients-Lists/Early-Career-Investigator-Award-Past-Recipients.aspx"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    tbod = soup.find('tbody')
    trs = tbod.find_all('tr')
    
    for tr in trs[1:]:
        tds = tr.find_all('td')
        year = tds[1].text.strip()
        name = tds[0].text.strip()
        aw = tds[2].text.strip()
        if 'Herrick Award' in aw:
            name_parts = name.split()
            name = ' '.join(name_parts).strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [367]:
def scrape504():
    award = "ADSA Award of Honor"
    govid = "57"
    govname = "American Dairy Science Association"
    aid = "504"
    db = []

    try:
        driver = uc.Chrome(headless=False, use_subprocess=False)
        pdf_url = None
        
        driver.get("https://www.adsa.org/about-adsa/awards")
        time.sleep(4)
        
        try:
            link_element = driver.find_element(By.PARTIAL_LINK_TEXT, "Award History Roster")
            pdf_url = link_element.get_attribute("href")
        except NoSuchElementException:
            try:
                links = driver.find_elements(By.TAG_NAME, "a")
                for link in links:
                    if "Award History Roster" in link.text or "2025_Awards_History.pdf" in link.get_attribute("href") or "Awards_History" in link.get_attribute("href"):
                        pdf_url = link.get_attribute("href")
                        break
            except:
                pass
                
            if not pdf_url:
                raise ValueError("Could not find the 'Award History Roster' link on the page.")
        finally:
            driver.quit()

        if not pdf_url:
            raise ValueError("Found the link element but could not retrieve the href attribute.")

        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
        }
        response = requests.get(pdf_url, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Failed to download PDF from {pdf_url}. Status code: {response.status_code}")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
            tmp_file.write(response.content)
            tmp_pdf_path = tmp_file.name

        pdf_text = extract_text(tmp_pdf_path)
        os.remove(tmp_pdf_path)
        
        lines = [line.strip() for line in pdf_text.split('\n') if line.strip()]

        start_indices = [i for i, line in enumerate(lines) if "ADSA Award of Honor" in line]
        
        if not start_indices:
            start_indices = [i for i, line in enumerate(lines) if "ADSA Award of Honor".lower() in line.lower()]
            
        if not start_indices:
            raise Exception("Could not find 'ADSA Award of Honor' section in PDF.")
            
        for start_index in start_indices:
            temp_db = []
            
            for i in range(start_index + 1, len(lines)):
                line = lines[i]
                
                if "ADSA Distinguished Service Award" in line:
                    break
                
                if line.isdigit() and len(line) < 4:
                    continue
                
                match = re.search(r'^\s*(\d{4})\s+(.*)', line)
                
                if match:
                    year = match.group(1)
                    raw_name = match.group(2).strip()
                    
                    if len(raw_name) > 2 and "Award" not in raw_name:
                         # Normalize Name:
                         name = re.sub(r'\s+', ' ', raw_name)
                         
                         parts = name.split()
                         formatted_parts = []
                         for part in parts:
                             if len(part) == 1 and part.isalpha():
                                 formatted_parts.append(f"{part}.")
                             else:
                                 formatted_parts.append(part)
                         name = " ".join(formatted_parts)

                         temp_db.append({
                            'id': aid,
                            'govid': govid,
                            'govname': govname,
                            'award': award,
                            'year': year,
                            'name': name
                        })

            if len(temp_db) > 0:
                db = temp_db
                break 

    except Exception as e:
        print(f"Exception occurred: {e}")
        return pd.DataFrame()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{aid}.csv", index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [368]:
def scrape1151():
    award = "Eli Lilly and Company Research Award"
    govid = "116"
    govname = "American Society for Microbiology"
    aid = "1151"
    url = "https://en.wikipedia.org/wiki/Eli_Lilly_and_Company-Elanco_Research_Award"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    div = soup.find('div', style="column-width:20em")
    ul = div.find('ul')
    lis = ul.find_all('li')
    for li in lis:
        lt = li.text.strip()
        year = lt[:4].strip()
        name = li.find('a').text.strip()
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [369]:
def scrape1182():
    award = "ASTR Honorees/Distinguished Scholar"
    govid = "121"
    govname = "American Society for Theatre Research"
    aid = "1182"
    url = "https://www.astr.org/page/AwardWinnerArchive"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = Driver(uc=True)
    driver.get(url)

    time.sleep(5)

    cookiebt = driver.find_element(By.XPATH, "//button[@id='openglobal_privacy_accept']")
    driver.execute_script("arguments[0].scrollIntoView({block: 'center', inline: 'center'});", cookiebt)
    time.sleep(1)
    location = cookiebt.location
    size = cookiebt.size
    x = location['x'] + (size['width'] / 2)
    y = location['y'] + (size['height'] / 2)
    pyautogui.moveTo(x, y, duration=0.3)
    pyautogui.click()

    time.sleep(5)

    awardheader = driver.find_element(By.XPATH, "//h2[a[@id='distinguishedscholar']]")
    driver.execute_script("arguments[0].scrollIntoView(true);", awardheader)

    time.sleep(3)

    accordion_div = driver.find_element(By.XPATH, "//h2[a[@id='distinguishedscholar']]/following-sibling::div[1][@class='accordion']")
    driver.execute_script("arguments[0].click();", accordion_div)

    time.sleep(3)

    firstdiv = driver.find_element(By.XPATH, "//h2[a[@id='distinguishedscholar']]/following-sibling::blockquote[@class='awards']")
    recent_text = firstdiv.text.strip()

    seconddiv = driver.find_element(By.XPATH, "//h2[a[@id='distinguishedscholar']]/following-sibling::div[@class='panel']")
    second_text = seconddiv.text.strip()

    combined_text = recent_text + "\n" + second_text

    prompt = f"""
    From the following text, extract the award winners (Distinguished Scholars/Honorees). 
    For each winner, provide their name, year, and affiliation. 
    The affiliation should be an empty string if not provided.
    Format the output as a clean JSON array of objects, where each object has the keys "name", "year", and "affiliation".
    The text is:
    {combined_text}
    """

    response = model.generate_content(contents=prompt)
    
    response_text = response.text.strip()
    json_start = response_text.find('[')
    json_end = response_text.rfind(']')
    
    winners_list = []
    if json_start != -1 and json_end != -1:
        json_string = response_text[json_start:json_end+1]
        try:
            winners_list = json.loads(json_string)
        except json.JSONDecodeError:
            print(f"Failed to decode JSON for AwardID {aid}")
            winners_list = []

    for winner_data in winners_list:
        name = winner_data.get('name', '').strip()
        year = str(winner_data.get('year', '')).strip()
        affiliation = winner_data.get('affiliation', '').strip()
        
        if len(name) > 3:
            db.append({
                'id': aid,
                'govid': govid,
                'govname': govname,
                'award': award,
                'year': year,
                'name': name,
                'affiliation': affiliation
            })

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [370]:
def scrape1186():
    award = "Barnard Hewitt Award for Outstanding Research in Theatre History"
    govid = "121"
    govname = "American Society for Theatre Research"
    aid = "1186"
    url = "https://www.astr.org/page/AwardWinnerArchive"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    driver = Driver(uc=True)
    driver.get(url)

    time.sleep(5)

    cookiebt = driver.find_element(By.XPATH, "//button[@id='openglobal_privacy_accept']")
    driver.execute_script("arguments[0].scrollIntoView({block: 'center', inline: 'center'});", cookiebt)
    time.sleep(1)
    location = cookiebt.location
    size = cookiebt.size
    x = location['x'] + (size['width'] / 2)
    y = location['y'] + (size['height'] / 2)
    pyautogui.moveTo(x, y, duration=0.3)
    pyautogui.click()

    time.sleep(5)

    awardheader = driver.find_element(By.XPATH, "//h2[a[@id='barnardhewitt']]")
    driver.execute_script("arguments[0].scrollIntoView(true);", awardheader)

    time.sleep(3)

    accordion_div = driver.find_element(By.XPATH, "//h2[a[@id='barnardhewitt']]/following-sibling::div[1][@class='accordion']")
    driver.execute_script("arguments[0].click();", accordion_div)

    time.sleep(3)

    firstdiv = driver.find_element(By.XPATH, "//h2[a[@id='barnardhewitt']]/following-sibling::blockquote[@class='awards']")
    recent_text = firstdiv.text.strip()

    seconddiv = driver.find_element(By.XPATH, "//h2[a[@id='barnardhewitt']]/following-sibling::div[@class='panel']")
    second_text = seconddiv.text.strip()

    combined_text = recent_text + "\n" + second_text

    prompt = f"""
    From the following text, extract the award winners. Do not include honorable mentions. 
    For each winner, provide their name, year, and affiliation. The affiliation should be an empty string if not provided. 
    Note that a 'press' (e.g., 'University of Michigan Press') is not an affiliation.
    Format the output as a clean JSON array of objects, where each object has the keys "name", "year", and "affiliation".
    The text is:
    {combined_text}
    """

    response = model.generate_content(contents=prompt)
    
    response_text = response.text.strip()
    json_start = response_text.find('[')
    json_end = response_text.rfind(']')
    
    winners_list = []
    if json_start != -1 and json_end != -1:
        json_string = response_text[json_start:json_end+1]
        try:
            winners_list = json.loads(json_string)
        except json.JSONDecodeError:
            print(f"Failed to decode JSON for AwardID {aid}")
            winners_list = []

    for winner_data in winners_list:
        name = winner_data.get('name', '').strip()
        year = str(winner_data.get('year', '')).strip()
        affiliation = winner_data.get('affiliation', '').strip()
        
        if len(name) > 3:
            db.append({
                'id': aid,
                'govid': govid,
                'govname': govname,
                'award': award,
                'year': year,
                'name': name,
                'affiliation': affiliation
            })
        
    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    
    return df

In [371]:
def scrape819():
    # Takes 30-35 minutes
    award = "American Philosophical Society Membership"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "819"
    url = "https://members.amphilsoc.org/s/member-directory"
    db = []
    
    options = Options()
    options.headless = False 
    
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(5) 

    # TEST MODE: Removed infinite scroll to test with just the first page (initial load)
    last_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(3) 
        new_height = driver.execute_script("return document.body.scrollHeight")
        if new_height == last_height:
            break
        last_height = new_height
   
    # Processing
    try:
        seen_keys = set()
        
        candidates = driver.find_elements(By.XPATH, "//*[contains(text(), 'Elected')]")
        
        for elem in candidates:
            try:
                text = elem.text.strip()
                if not re.search(r'^Elected\s+\d{4}', text) and not re.search(r'Birth Date', text):
                    continue

                card = elem
                found_card = False
                card_text_lines = []
                
                for _ in range(10): 
                    try:
                        card = card.find_element(By.XPATH, "..")
                    except:
                        break
                        
                    card_text = card.text
                    lines = [l.strip() for l in card_text.split('\n') if l.strip()]
                    
                    has_birth = any('Birth Date' in l for l in lines)
                    has_elected = any('Elected' in l for l in lines)
                    
                    if has_birth and has_elected:
                        candidate_name_line = lines[0]
                        if len(candidate_name_line) < 100: 
                            found_card = True
                            card_text_lines = lines
                            break
                
                if not found_card:
                    continue

                raw_name = card_text_lines[0]
                
                # Robust Name Cleaning
                name_clean = raw_name
                
                # Regex for Prefixes
                # Handles "The Honorable", "Professor", "Dr.", "Sir", etc. and combinations
                # Repeatedly apply until no change to catch "Professor Dr." etc.
                while True:
                    prev_name = name_clean
                    name_clean = re.sub(
                        r'^(The\s+)?(Honorable|Hon|Professor|Prof|Doctor|Dr|Mr|Mrs|Ms|Sir|Dame|Reverend|Rev|Ambassador|Amb)\.?\s+', 
                        '', 
                        name_clean, 
                        flags=re.IGNORECASE
                    )
                    if name_clean == prev_name:
                        break
                
                # Regex for Suffixes
                name_clean = re.sub(r',?\s*(Ph\.?D\.?|M\.?D\.?|J\.?D\.?|Jr\.|Sr\.|III|IV|V|Esq\.?|OBE|CBE|MBE|FRS|FBA)$', '', name_clean, flags=re.IGNORECASE)
                name_clean = name_clean.strip()

                meta_idx = -1
                for i, line in enumerate(card_text_lines):
                    if 'Birth Date' in line and 'Elected' in line:
                        meta_idx = i
                        break
                
                if meta_idx == -1: 
                    for i, line in enumerate(card_text_lines):
                         if 'Birth Date' in line:
                            meta_idx = i
                            break
                
                if meta_idx == -1:
                    continue
                    
                affiliation = ""
                if meta_idx > 1:
                    affiliation = "; ".join(card_text_lines[1:meta_idx])
                elif meta_idx == 1:
                    affiliation = "" 

                meta_text = " ".join(card_text_lines[meta_idx:])
                
                birth_year = ""
                birth_match = re.search(r'Birth Date\s+(\d{4})', meta_text)
                if birth_match:
                    birth_year = birth_match.group(1)
                
                elected_year = ""
                elected_match = re.search(r'Elected\s+(\d{4})', meta_text)
                if elected_match:
                    elected_year = elected_match.group(1)
                    
                is_deceased = 'N'
                if 'Deceased' in meta_text or 'Dead' in meta_text:
                    is_deceased = 'Y'
                elif 'Living' in meta_text:
                    is_deceased = 'N'
                
                unique_key = (name_clean, elected_year, birth_year)
                if unique_key in seen_keys:
                    continue
                seen_keys.add(unique_key)
                
                db.append({
                    'id': aid, 
                    'govid': govid, 
                    'govname': govname, 
                    'award': award, 
                    'year': elected_year, 
                    'name': name_clean, 
                    'affiliation': affiliation, 
                    'deceased': is_deceased
                    # 'dob': birth_year 
                })
                
            except Exception as e:
                continue

    except Exception as e:
        print(f"Global error: {e}")

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [372]:
def scrape8258():
    aid     = "8258"
    award   = "Mellon/ACLS Public Fellows"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url = "https://www.acls.org/fellows-grantees/?_fellow_program=426"
    
    # Simple fix to ignore Windows handle errors in undetected_chromedriver
    def _patched_quit(self):
        """Patched quit method that ignores Windows handle errors"""
        try:
            self._original_quit()
        except OSError as e:
            if "WinError 6" in str(e) or "The handle is invalid" in str(e):
                pass  # Ignore Windows handle errors
            else:
                raise

    # Apply the patch
    if hasattr(uc.Chrome, 'quit') and not hasattr(uc.Chrome, '_original_quit'):
        uc.Chrome._original_quit = uc.Chrome.quit
        uc.Chrome.quit = _patched_quit
    
    # --- Stealth Driver Setup (Inspired by provided code) ---
    options = uc.ChromeOptions()
    
    # Random User Agent
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
    ]
    options.add_argument(f'--user-agent={random.choice(user_agents)}')
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    # Preferences to disable automation flags
    prefs = {
        'credentials_enable_service': False,
        'profile.password_manager_enabled': False,
    }
    options.add_experimental_option('prefs', prefs)
    
    # Initialize undetected_chromedriver
    # headless=False is often better for bypassing captchas initially
    try:
        driver = uc.Chrome(options=options, headless=False)
    except TypeError:
        driver = uc.Chrome(options=options)

    # --- Inject Stealth JS ---
    stealth_js = """
    Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
    window.chrome = {runtime: {}};
    Object.defineProperty(navigator, 'plugins', {
        get: () => [1, 2, 3].map(n => ({
            name: `Plugin ${n}`,
            filename: `plugin${n}.dll`,
            length: 1
        }))
    });
    """
    driver.execute_script(stealth_js)
    
    # --- Adaptive Human Behavior ---
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6) # Initial wait

    try:
        # Check for CAPTCHA/Challenge title
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15) 
            
        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["name", "year", "affiliation", "id", "govid", "govname", "award"]
    )
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [373]:
def scrape2982():
    award = "Aldo Leopold Memorial Award"
    govid = "406"
    govname = "Wildlife Society, The"
    aid = "2982"
    url = "https://wildlife.org/awards/" 
    db = []
    
    options = uc.ChromeOptions()
    options.headless = False
    driver = uc.Chrome(options=options)
    
    try:
        driver.get(url)
        time.sleep(5)
        
        # Click the "Aldo Leopold Memorial Award Recipients" accordion
        # Target the text, then find the parent clickable div
        xpath_query = "//span[contains(text(), 'Aldo Leopold Memorial Award Recipients')]/ancestor::div[contains(@class, 'js-accordion-title')]"
        
        target_div = WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.XPATH, xpath_query))
        )
        
        # Smooth scroll attempt
        driver.execute_script("arguments[0].scrollIntoView({block: 'center', inline: 'nearest'});", target_div)
        time.sleep(2) # Give it a moment to settle
        
        try:
            # Try standard click first
            target_div.click()
        except Exception:
            # Fallback to JS click which ignores overlays/scroll issues
            print("Standard click failed, attempting JS click...")
            driver.execute_script("arguments[0].click();", target_div)
            
        time.sleep(3) # Wait for content to load/expand
        html = driver.page_source
    finally:
        driver.quit()

    soup = BeautifulSoup(html, "html.parser")

    # Find the header we clicked
    header_span = soup.find(lambda tag: tag.name == "span" and "Aldo Leopold Memorial Award Recipients" in tag.text)
    
    if header_span:
        # Navigate to the content div
        # Structure: <div class="js-accordion-title">...</div> <div class="js-accordion-content">...</div>
        title_div = header_span.find_parent("div", class_="js-accordion-title")
        if title_div:
            content_div = title_div.find_next_sibling("div", class_="js-accordion-content")
            if content_div:
                editor_div = content_div.find("div", class_="editor")
                if editor_div:
                    ps = editor_div.find_all("p")
                    for p in ps:
                        # Handle text like: "2025\nTerry Bowyer" (from <p>2025<br>Terry Bowyer</p>)
                        text = p.get_text(separator="\n", strip=True)
                        lines = text.split("\n")
                        
                        # Skip lines that are likely descriptions or links (e.g. "Read the ... biographies")
                        if len(lines) >= 2:
                            year = lines[0].strip()
                            name = lines[1].strip()
                            
                            # Clean name (remove "in honor of...")
                            name = re.sub(r'\s+in\s+honor\s+of.*', '', name, flags=re.IGNORECASE).strip()

                            # Basic validation: Year usually looks like a year
                            if year.isdigit() and len(year) == 4:
                                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    else:
        print("Could not find the 'Aldo Leopold Memorial Award Recipients' section in the page source.")

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [374]:
def scrape2981():
    award = "Japan Prize Laureates"
    govid = "405"
    govname = "Science and Technology Foundation of Japan, The"
    aid = "2981"
    url = "https://www.japanprize.jp/en/laureates_by_year"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    pageind = ['', '2010', '2000', '1990', '1980']

    for page in pageind:
        try:
            url1 = url+page+'.html'
            page = requests.get(url1, headers=headers)
            soup = BeautifulSoup(page.content, "html.parser")

            tbod = soup.find('tbody')
            rows = tbod.find_all('tr')

            for row in rows[2:]:
                tds = row.find_all('td')
                if tds and tds[0].text.strip():
                    if tds[0].text.strip()[0].isdigit():
                        year = tds[0].text[:4].strip()
                
                nametd = row.find('span', class_='tab_name')
                if nametd:
                    if nametd.find('a'):
                        name = nametd.find('a').text.split('(')[0].strip()
                    else:
                        name = nametd.text.split('(')[0].strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except IndexError:
            print(row)
            pass

        except AttributeError:
            print(nametd)
            pass

    for entry in db:
        entry['name'] = re.sub(r'^\s*(Dr\.|Prof\.|Mr\.|Ms\.|Mrs\.)\s*', '', entry['name'])
        entry['name'] = re.sub(r'\s*(PhD|MD|DDS|Esq|Jr\.|Sr\.|III|IV|V)\s*$', '', entry['name'])
        entry['name'] = entry['name'].strip()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [375]:
def scrape407():
    award = "Wolf Prize"
    govid = "2985"
    govname = "Wolf Foundation, The"
    aid = "407"
    url = "https://wolffund.org.il/the-wolf-prize/#The%20Prize"
    
    db = []
    links = []

    # Standard Driver Setup (Compatible)
    options = Options()
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
    ]
    options.add_argument(f'--user-agent={random.choice(user_agents)}')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)

    try:
        print(f"Navigating to main prize page: {url}")
        driver.get(url)

        try:
             # Wait for posts to load
             time.sleep(5)
             mdiv = driver.find_element(By.CLASS_NAME, 'posts')
        except NoSuchElementException:
             # Retry once
             time.sleep(2)
             mdiv = driver.find_element(By.CLASS_NAME, 'posts')

        arts = mdiv.find_elements(By.TAG_NAME, 'article')
        for art in arts:
            try:
                link = art.find_element(By.TAG_NAME, 'a').get_attribute('href')
                links.append(link)
            except:
                continue

        print(f"Found {len(links)} laureate pages to scrape.")

        # Use tqdm to create a progress bar for the loop
        for link in tqdm(links, desc="Scraping Laureates"):
            driver.get(link)
            
            try:
                name = driver.find_element(By.XPATH, "//h1[@class='entry-title']").text.strip()
            except: 
                name = ""
            
            try:
                desc = driver.find_element(By.ID, 'excerpt').text.strip()
                desc_parts = desc.split()
                year = desc_parts[-1].strip()
                field = desc_parts[-2].strip() if len(desc_parts) > 2 else "N/A"
            except:
                year = ""
                field = ""
            
            db.append({
                'id': aid, 
                'govid': govid, 
                'govname': govname, 
                'award': award, 
                'year': year, 
                'name': name, 
                'field': field
            })

    finally:
        print("Scraping finished. Closing the browser.")
        driver.quit()

    if not db:
        print("No data was scraped. Exiting.")
        return pd.DataFrame()

    df = pd.DataFrame(db)
    
    print("\n--- Scraped Data ---")
    print(tabulate(df, headers='keys', tablefmt='psql'))
    
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    
    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- scraped and saved to '{filepath}' at {current_time}")

    return df

In [376]:
def scrape3000():
    aid     = "3000"
    award   = "ACLS Digital Innovation Fellowships"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url = "https://www.acls.org/fellows-grantees/?_fellow_program=361"

    # Adjusted Driver Setup (Undetected Chromedriver)
    options = uc.ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-infobars")
    options.add_argument(
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )

    driver = uc.Chrome(options=options)
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        })
    except Exception as e:
        print(f"[WARN] Failed to inject script: {e}")
    
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6)

    try:
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15)
            
        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["name", "year", "affiliation", "id", "govid", "govname", "award"]
    )

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [377]:
def scrape3001():
    aid     = "3001"
    award   = "ACLS Collaborative Research Fellowships"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url = "https://www.acls.org/fellows-grantees/?_fellow_program=360"

    # Adjusted Driver Setup (Undetected Chromedriver)
    options = uc.ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_argument("--disable-infobars")
    options.add_argument(
        "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
    )

    driver = uc.Chrome(options=options)
    try:
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        })
    except Exception as e:
        print(f"[WARN] Failed to inject script: {e}")
    
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6)

    try:
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15)
            
        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["name", "year", "affiliation", "id", "govid", "govname", "award"]
    )

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [378]:
def scrape3010():
    award = "HHMI Investigator/Alumni Investigator"
    govid = "412"
    govname = "Howard Hughes Medical Institute (HHMI)"
    aid = "3010"
    base_url = "https://www.hhmi.org/search/people?f%5B0%5D=current_program_terms%3AInvestigator&sort_by=field_name_family&sort_order=ASC&items_per_page=96"

    scraped_data = []

    def clean_text(text):
        if not isinstance(text, str):
            return ""
        text = html.unescape(text)
        text = text.replace('\n', ' ').replace('\r', ' ')
        return ' '.join(text.split())

    options = uc.ChromeOptions()
    driver = uc.Chrome(options=options, headless=False)

    get_attribute_data_js = """
    const searchModule = document.querySelector('hhmi-search-module');
    if (!searchModule) return [];
    const searchModuleShadow = searchModule.shadowRoot;
    if (!searchModuleShadow) return [];
    const cards = searchModuleShadow.querySelectorAll('hhmi-card');
    const results = [];
    cards.forEach(card => {
        const headingText = card.getAttribute('heading') || '';
        const labelText = card.getAttribute('label') || '';
        results.push({ heading: headingText, label: labelText });
    });
    return results;
    """

    page = 0
    while True:
        url = base_url if page == 0 else f"{base_url}&page={page}"
        print(f"\n=== Page {page} ===")
        print(f"Navigating to: {url}")

        try:
            driver.get(url)
        except Exception as e:
            print(f"Failed to load page: {e}")
            break

        try:
            print("Waiting for dynamic content...")
            wait = WebDriverWait(driver, 25)
            wait.until(lambda d: d.execute_script(
                "return document.querySelector('hhmi-search-module').shadowRoot.querySelector('hhmi-card')"
            ))
            time.sleep(1)

        except (TimeoutException, JavascriptException):
            print("No more content found. This is the last page.")
            break

        try:
            card_data_list = driver.execute_script(get_attribute_data_js)
            print(f"Found {len(card_data_list)} entries.")
        except Exception as e:
            print(f"Failed to execute script to get card attributes: {e}")
            break

        if not card_data_list:
            print("Card list is empty, stopping.")
            break

        for i, card_data in enumerate(card_data_list):
            try:
                heading = clean_text(card_data.get('heading', ''))
                label = clean_text(card_data.get('label', ''))
                
                if not heading or not label:
                    continue
                
                name_parts = heading.split(',')
                name = name_parts[0].strip()
                label_parts = label.split('·')
                year = label_parts[0].strip()[:4]
                affiliation = label_parts[1].strip() if len(label_parts) > 1 else ""
                
                record = {
                    'id': aid, 'govid': govid, 'govname': govname, 'award': award,
                    'year': year, 'name': name, 'affiliation': affiliation
                }
                scraped_data.append(record)

            except Exception as e:
                print(f"---! Critical error parsing card {i+1}. Error: {type(e).__name__} - {e}")
                continue

        page += 1
        time.sleep(2)

    driver.quit()

    if not scraped_data:
        print("\nNo data was scraped. Please review logs.")
        return None

    df = pd.DataFrame(scraped_data)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"\n✅ Scraped {len(df)} entries — saved to {filepath} at {datetime.now().strftime('%H:%M:%S')}")
    
    return df

In [379]:
def scrape3011():
    aid     = "3011"
    award   = "Andrew W Mellon/ACLS Recent Doctoral Recipients Fellowships"
    govid   = "54"
    govname = "American Council of Learned Societies (ACLS)"
    base_url = "https://www.acls.org/fellows-grantees/?_fellow_program=431"

    # Simple fix to ignore Windows handle errors in undetected_chromedriver
    def _patched_quit(self):
        """Patched quit method that ignores Windows handle errors"""
        try:
            self._original_quit()
        except OSError as e:
            if "WinError 6" in str(e) or "The handle is invalid" in str(e):
                pass  # Ignore Windows handle errors
            else:
                raise

    # Apply the patch
    if hasattr(uc.Chrome, 'quit') and not hasattr(uc.Chrome, '_original_quit'):
        uc.Chrome._original_quit = uc.Chrome.quit
        uc.Chrome.quit = _patched_quit

    # --- Stealth Driver Setup ---
    options = uc.ChromeOptions()
    
    # Random User Agent
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
    ]
    options.add_argument(f'--user-agent={random.choice(user_agents)}')
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    # Preferences to disable automation flags
    prefs = {
        'credentials_enable_service': False,
        'profile.password_manager_enabled': False,
    }
    options.add_experimental_option('prefs', prefs)
    
    # Initialize undetected_chromedriver
    try:
        driver = uc.Chrome(options=options, headless=False)
    except TypeError:
        driver = uc.Chrome(options=options)

    # --- Inject Stealth JS ---
    stealth_js = """
    Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
    window.chrome = {runtime: {}};
    Object.defineProperty(navigator, 'plugins', {
        get: () => [1, 2, 3].map(n => ({
            name: `Plugin ${n}`,
            filename: `plugin${n}.dll`,
            length: 1
        }))
    });
    """
    driver.execute_script(stealth_js)
    
    # --- Adaptive Human Behavior ---
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    driver.get(base_url)
    human_delay(3, 6)  # Initial wait

    try:
        # Check for CAPTCHA/Challenge title
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15)

        last_button = driver.find_element(By.CSS_SELECTOR, "a.facetwp-page.last")
        num_pages = int(last_button.get_attribute("data-page"))
    except:
        num_pages = 1

    records = []

    for page in tqdm(range(1, num_pages + 1), desc="Scraping pages", unit="page"):
        if page > 1:
            driver.get(f"{base_url}&_paged={page}")
            human_delay(3, 6)

        cards = driver.find_elements(By.CSS_SELECTOR, ".card-fellow__body")
        for card in cards:
            try:
                name = card.find_element(By.CLASS_NAME, "card-fellow__title").text.strip()
            except:
                name = ""

            try:
                year = card.find_element(By.TAG_NAME, "li").text.strip()
            except:
                year = ""

            try:
                aff = card.find_element(By.TAG_NAME, "span").text.strip()
            except:
                aff = ""

            records.append((name, year, aff, aid, govid, govname, award))

        human_delay(1, 3)

    driver.quit()

    df = pd.DataFrame(
        records,
        columns=["name", "year", "affiliation", "id", "govid", "govname", "award"]
    )

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f"{filepath}{aid}.csv", index=False)
    print(f"AwardID {aid}: {len(df)} records across {num_pages} pages saved to {filepath}{aid}.csv")

    return df

In [380]:
def scrape3015():
    award = "Benjamin Franklin Medal for Distintinguished Achievement in the Humanities or Sciences: 1985-1991"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "3015"
    url = "https://www.amphilsoc.org/prizes/benjamin-franklin-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients, 1985-1991')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find_all('strong')

            if len(pst) == 1 and pst[0].text[0].isdigit():
                year = pst[0].text.split('\n')[0].strip()
                name = pst[0].text.split('\n')[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) == 1:
                name = pst[0].text.split('(')[0].strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) > 1:
                year = pst[0].text.strip()
                for p in pst[1:]:
                    name = p.text.strip().strip(',')
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            print('Error Occured')
            print(p)
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [381]:
def scrape3016():
    award = "Benjamin Franklin Medal Recipients: 1937-1983"
    govid = "91"
    govname = "American Philosophical Society"
    aid = "3016"
    url = "https://www.amphilsoc.org/prizes/benjamin-franklin-medal"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('div', string='Prize Recipients, 1937-1983 ')
    mdiv = h1.find_next('div', class_='field-content')

    ps = mdiv.find_all('p')
    for p in ps:
        try:
            pst = p.find_all('strong')

            if len(pst) == 1 and pst[0].text[0].isdigit():
                year = pst[0].text.split('\n')[0].strip()
                name = pst[0].text.split('\n')[1].strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) == 1:
                name = pst[0].text.split('(')[0].strip().strip(',')
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

            elif len(pst) > 1:
                year = pst[0].text.strip()
                for p in pst[1:]:
                    name = p.text.strip().strip(',')
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except (AttributeError, IndexError):
            print('Error Occured')
            print(p)
            pass

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
    
    return df

In [382]:
def scrape3024():
    award = "The Bancroft Prizes"
    govid = "414"
    govname = "Columbia University"
    aid = "3024"
    url = "https://library.columbia.edu/about/awards/bancroft/previous_awards.html"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    h1 = soup.find('h2', string='The Bancroft Prizes: Current & Previous Awards')
    heads = h1.find_all_next('div', class_='section_heading')

    for head in heads:
        try:
            year = head.find('h2').text.strip()
            tail = head.find_next('div', 'text')
            ps = tail.find_all('p')
            for p in ps:
                pt = p.text
                namez = pt.split('\n')[1].strip('by').strip('By').strip()
                names = namez.split(' and ')
                for x in names:
                    name = x.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except IndexError:
            pass
        
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [383]:
def scrape3092():
    award = "Emerson-Thoreau Medal"
    govid = "6"
    govname = "American Academy of Arts and Sciences"
    aid = "3092"
    url = "https://www.amacad.org/emerson-thoreau-medal-recipients"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='emerson-thoreau-medal-recipients')
    ps = mdiv.find_all('p')
    
    for p in ps:
        try:
            name = p.find('strong').text.strip()
            year = p.text[:4].strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except AttributeError:
            pass
        
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [384]:
def scrape3093():
    award = "Founders Award"
    govid = "6"
    govname = "American Academy of Arts and Sciences"
    aid = "3093"
    url = "https://www.amacad.org/about/prizes/founders-award"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    h2_recipients = soup.find('h2', string='Recipients')

    year = None

    if h2_recipients:
        parent_div = h2_recipients.find_parent('div')

    for tag in parent_div.find_all(["h2", "p"]):
        if tag.name == "h2" and tag.text.strip().isdigit():
            year = tag.text.strip()

        elif tag.name == "p" and year:
            names = [a.text.strip() for a in tag.find_all("a") if a.text.strip()]
            for name in names:
                if name != "Award press release":
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [385]:
def scrape3095():
    award = "Talcott Parsons Prize"
    govid = "6"
    govname = "American Academy of Arts and Sciences"
    aid = "3095"
    url = "https://www.amacad.org/about/prizes/talcott-parsons"
    db = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    sections = soup.find_all('div', class_='field-item')
    target_section = None
    for sec in sections:
        if sec.find('h2', string='Recipients'):
            target_section = sec
            break

    if not target_section:
        return pd.DataFrame()

    # Process all elements in order to capture both h2 years and p entries
    year = None
    elements = target_section.find_all(['h2', 'p'], class_=lambda x: x is None or 'large' in str(x))
    
    for elem in elements:
        if elem.name == 'h2':
            txt = elem.get_text().strip()
            if txt.isdigit() and len(txt) == 4:
                year = txt
        elif elem.name == 'p' and 'large' in (elem.get('class') or []):
            # Skip if it's just a year
            text_content = elem.get_text().strip()
            if text_content.isdigit() and len(text_content) == 4:
                year = text_content
                continue
            
            # Process as potential recipient entry
            strong = elem.find('strong')
            if strong:
                txt = strong.text.strip()
                if txt.isdigit() and len(txt) == 4:
                    year = txt
                else:
                    # Strong tag contains name
                    name = txt
                    affil_text = elem.get_text().replace(name, "").strip().strip(', ')
                    if year:
                        db.append({
                            'id': aid,
                            'govid': govid,
                            'govname': govname,
                            'award': award,
                            'year': year,
                            'name': name,
                            'affiliation': affil_text
                        })
            else:
                a = elem.find('a')
                if a and year:
                    name = a.text.strip()
                    if name:
                        full_text = elem.get_text()
                        if name in full_text:
                            rest = full_text.split(name, 1)[-1].strip().strip(', ')
                            affil_text = rest.split('(')[0].strip() if '(' in rest else rest
                        else:
                            affil_text = ""
                        
                        db.append({
                            'id': aid,
                            'govid': govid,
                            'govname': govname,
                            'award': award,
                            'year': year,
                            'name': name,
                            'affiliation': affil_text
                        })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)
    
    return df

In [386]:
def scrape3028():
    # Now hidden behind login wall
    print("scrape3028 is deprecated due to login wall.")
    # award = "Sabbatical Fellowships"
    # govid = "91"
    # govname = "American Philosophical Society"
    # aid = "3028"
    # url = "https://www.amphilsoc.org/grants/aps-neh-sabbatical-fellowships"
    # db = []
    # headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")

    # tab_panes = soup.find_all('div', class_='tab-pane')
    # for pane in tab_panes:
    #     year_heading = pane.find('div', class_='field-tab-heading__item').text.split("-")[0].strip()
    #     paragraphs = pane.find_all('p')
    #     for p in paragraphs:
    #         strong_tag = p.find('strong')
    #         if strong_tag:
                
    #             parts = p.text.split(',')
    #             name = parts[0].strip()
                
    #             affiliation = parts[1].strip() if len(parts) > 1 else 'N/A'

    #             db.append({
    #             'year': year_heading,
    #                 'name': name,
    #                 'affiliation': affiliation
    #             })
                
    # df = pd.DataFrame(db)
    # df['id'] = aid
    # df['govid'] = govid
    # df['govname'] = govname
    # df['award'] = award
    # print(tabulate(df, headers='keys', tablefmt='psql'))
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    # return df

In [387]:
def scrape3121():
    award = "George David Birkhoff Prize in Applied Mathematics"
    govid = "80"
    govname = "American Mathematical Society"
    aid = "3121"
    url = "https://www.ams.org/prizes-awards/pabrowse.cgi?parent_id=9"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='paOutput')
    ps = mdiv.find_all('span', class_='paYear')

    for p in ps:
        year = p.text.strip()
        name = p.find_next('span', class_='paWinner').text.strip()
        namez = name.split(';')
        for name in namez:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [388]:
def scrape3123():
    award = "Norbert Wiener Prize in Applied Mathematics"
    govid = "80"
    govname = "American Mathematical Society"
    aid = "3123"
    url = "https://www.ams.org/prizes-awards/pabrowse.cgi?parent_id=33"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', id='paOutput')
    ps = mdiv.find_all('span', class_='paYear')

    for p in ps:
        year = p.text.strip()
        name = p.find_next('span', class_='paWinner').text.strip()
        namez = name.split(';')
        for name in namez:
            name = name.strip()
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [389]:
def scrape4219():
    award = "Rene Wellek Prize"
    govid = "49"
    govname = "American Comparative Literature Association"
    aid = "4219"
    url = "https://www.acla.org/prize-awards/ren%C3%A9-wellek-prize"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(3)

    try:
        ckbutton = driver.find_element(By.CLASS_NAME, 'eu-cookie-compliance-secondary-button')
        ckbutton.click()
    except Exception as e:
        print("Cookie compliance button not found or could not be clicked. Proceeding without clicking.")

    time.sleep(3)

    button = driver.find_element(By.CLASS_NAME, 'ckeditor-accordion-toggler')
    button.click()

    time.sleep(3)

    mdiv = driver.find_element(By.CLASS_NAME, 'ckeditor-accordion-container')
    items = mdiv.find_element(By.TAG_NAME, 'ul').find_elements(By.TAG_NAME, 'li')
    text = " ".join(item.text for item in items)

    response = model.generate_content(
        contents=(
            "OUTPUT ONLY A JSON ARRAY. NO CODE FENCES, NO MARKDOWN, NO EXPLANATION.\n"
            "Each element must be an object with keys: name, year, affiliation.\n"
            "Rules:\n"
            "  • Exclude any item containing “honorable” or “mention”.\n"
            "  • If affiliation is blank or “press”, use an empty string.\n\n"
            f"DATA:\n{text}"
        )
    )

    raw = response.text.strip()

    if raw.startswith("```"):
        raw = raw.strip("```json").strip("```").strip()

    match = re.search(r"\[\s*\{.*\}\s*\]", raw, re.DOTALL)
    json_text = match.group(0) if match else raw

    winners = json.loads(json_text)
    for w in winners:
        if len(w["name"]) > 3:
            db.append({
                "id":          aid,
                "govid":       govid,
                "govname":     govname,
                "award":       award,
                "year":        w["year"],
                "name":        w["name"]
            })

    soup = BeautifulSoup(driver.page_source, 'html.parser')
    extra_blocks = soup.find_all('h4')

    for h in extra_blocks:
        heading_text = h.get_text(strip=True)
        year_match = re.search(r'(\d{4})', heading_text)

        if year_match and 'Prize Winner' in heading_text:
            year = year_match.group(1)
            ul = h.find_next_sibling('ul')
            if not ul:
                continue
            for li in ul.find_all('li'):
                text = li.get_text(" ", strip=True)
                if "honorable" in text.lower() or "mention" in text.lower():
                    continue

                name_affil_match = re.match(r"(.+?)\s+\(([^)]+)\)", text)
                if name_affil_match:
                    name = name_affil_match.group(1).strip()
                    affil = name_affil_match.group(2).strip()
                else:
                    name = text.strip()
                    affil = ""

                if len(name) > 3:
                    db.append({
                        "id": aid,
                        "govid": govid,
                        "govname": govname,
                        "award": award,
                        "year": year,
                        "name": name
                    })

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [390]:
def scrape3056():
    award = "Fritz J. and Dolores H. Russ Prize"
    govid = "221"
    govname = "National Academy of Engineering"
    aid = "3056"
    url = "https://www.nae.edu/55292/RussWinners#tabs"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    links = []

    try:
        while True:
            time.sleep(5)
            ul = driver.find_element(By.CSS_SELECTOR, "ul.items")
            lis = ul.find_elements(By.TAG_NAME, 'li')
            for li in lis:
                name = li.find_element(By.CLASS_NAME, 'name')
                name = name.text.strip()
                try:
                    year = li.find_element(By.CLASS_NAME, 'listHeading')
                    year = year.text.strip()
                except NoSuchElementException:
                    year = year
                pinfo = li.find_element(By.CLASS_NAME, 'personInfo')
                try:
                    position = pinfo.find_element(By.CLASS_NAME, 'jobTitle')
                    position = position.text.strip()
                    aff = pinfo.find_element(By.CLASS_NAME, 'organization')
                    aff = aff.text.strip()
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name, 'position': position, 'affiliation': aff})
                except NoSuchElementException:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                    pass

            try:
                next_button = driver.find_element(By.ID, "ctl06_ContentControls_awardsRecipientsList_ctl01_pagerControlBottom_lbNext")
                if not next_button.is_enabled() or 'disabled' in next_button.get_attribute('class'):
                    break
                time.sleep(2)
                next_button.click()

            except (ElementClickInterceptedException):
                break

    except NoSuchElementException:
        pass

    for entry in db:
        entry['name'] = re.sub(r'^\s*(Dr\.|Prof\.|Professor|Mr\.|Ms\.|Mrs\.)\s*', '', entry['name'])
        entry['name'] = re.sub(r'\s*(PhD|MD|DDS|Esq|Jr\.|Sr\.|III|IV|V)\s*$', '', entry['name'])
        entry['name'] = entry['name'].strip()

    driver.quit()

    df = pd.DataFrame(db).fillna("")
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [391]:
def scrape3064():
    award = "Rome Prize"
    govid = "4"
    govname = "American Academy In Rome"
    aid = "3064"
    url = "https://www.aarome.org/people/rome-prize-fellows"
    db = []

    options = uc.ChromeOptions()
    options.headless = False
    driver = uc.Chrome(options=options)
    
    try:
        driver.get(url)
        wait = WebDriverWait(driver, 20)
        
        dropdown_locator = (By.CSS_SELECTOR, '[data-drupal-selector="edit-field-affil-year-target-id"]')
        dropdown_element = wait.until(EC.presence_of_element_located(dropdown_locator))
        
        # Scroll to element to ensure visibility
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", dropdown_element)
        time.sleep(1)
        
        select = Select(dropdown_element)
        
        # Debug: Print available options to confirm text
        # print("Available options:", [o.text for o in select.options]) 
        
        # Attempt to select "All years" - logic to handle potential text variations or value
        selected = False
        try:
            select.select_by_visible_text("All years")
            selected = True
        except Exception:
            # Fallback: Find option containing "All"
            for opt in select.options:
                if "All" in opt.text:
                    select.select_by_visible_text(opt.text)
                    selected = True
                    break
            # Fallback 2: Try value="All" (common in Drupal)
            if not selected:
                try:
                    select.select_by_value("All")
                    selected = True
                except:
                    pass
        
        if not selected:
            print("Warning: Could not select 'All years' option.")
            
        # Generous wait for AJAX content load
        time.sleep(10)

        html_content = driver.page_source
    finally:
        driver.quit()

    soup = BeautifulSoup(html_content, 'html.parser')
    main_container = soup.find('div', class_='people-current')
    
    current_field = "Unknown"
    if main_container:
        for element in main_container.children:
            if not hasattr(element, 'name') or not element.name:
                continue

            if element.name == 'h3' and element.find('div', class_='field__item'):
                current_field = element.get_text(strip=True)
            
            elif element.name == 'div' and 'profile-container' in element.get('class', []):
                profiles = element.find_all('div', class_='profile')
                for profile in profiles:
                    name_element = profile.find('h3', class_='title sans')
                    if name_element:
                        full_name = name_element.text.strip().title()
                    else:
                        continue

                    year_element = profile.find('div', class_='field-affil-year')
                    year = year_element.text.strip() if year_element else 'Unknown'
                    
                    individual_names = re.split(r'\s+and\s+|\s*&\s*', full_name)
                    for name in individual_names:
                        name = name.strip()
                        if name:
                            db.append({
                                'id': aid, 
                                'govid': govid, 
                                'govname': govname, 
                                'award': award, 
                                'year': year, 
                                'name': name,
                                'field': current_field
                            })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [392]:
def scrape3456():
    award = "Jay Hubbell Medal for Lifetime Achievement in Advancing American Literature Study"
    govid = "216"
    govname = "Modern Language Association"
    aid = "3456"
    url = "https://americanliteraturesociety.wordpress.com/hubbell-medal-for-lifetime-achievement/"
    db = []
    # Simple fix to ignore Windows handle errors in undetected_chromedriver
    def _patched_quit(self):
        """Patched quit method that ignores Windows handle errors"""
        try:
            self._original_quit()
        except OSError as e:
            if "WinError 6" in str(e) or "The handle is invalid" in str(e):
                pass  # Ignore Windows handle errors
            else:
                raise

    # Apply the patch
    if hasattr(uc.Chrome, 'quit') and not hasattr(uc.Chrome, '_original_quit'):
        uc.Chrome._original_quit = uc.Chrome.quit
        uc.Chrome.quit = _patched_quit
    
    # --- Stealth Driver Setup ---
    options = uc.ChromeOptions()
    
    # Random User Agent
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
    ]
    options.add_argument(f'--user-agent={random.choice(user_agents)}')
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    
    # Preferences to disable automation flags
    prefs = {
        'credentials_enable_service': False,
        'profile.password_manager_enabled': False,
    }
    options.add_experimental_option('prefs', prefs)
    
    # Initialize undetected_chromedriver
    try:
        driver = uc.Chrome(options=options, headless=False)
    except TypeError:
        driver = uc.Chrome(options=options)

    # --- Inject Stealth JS ---
    stealth_js = """
    Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
    window.chrome = {runtime: {}};
    Object.defineProperty(navigator, 'plugins', {
        get: () => [1, 2, 3].map(n => ({
            name: `Plugin ${n}`,
            filename: `plugin${n}.dll`,
            length: 1
        }))
    });
    """
    driver.execute_script(stealth_js)
    
    # --- Adaptive Human Behavior ---
    def human_delay(min_sec=2, max_sec=5):
        time.sleep(random.uniform(min_sec, max_sec))

    try:
        driver.get(url)
        human_delay(3, 6) # Initial wait

        # Check for CAPTCHA
        if "challenge" in driver.title.lower() or "captcha" in driver.title.lower():
            print("CAPTCHA detected, waiting for manual solution...")
            time.sleep(15) 
        
        soup = BeautifulSoup(driver.page_source, "html.parser")
        
        # The content seems to be inside 'entry-content'
        content_div = soup.find('div', class_='entry-content')
        
        if not content_div:
            print(f"AwardID {aid} --- Could not find content area")
        else:
            # The page structure is a mix of <p> tags with dates and names sometimes separate, sometimes together.
            # Some years are in a list <ul>, others might be in paragraphs <p>.
            # Based on the error log, the list items were concatenated text.
            
            # Strategy: Get all text from the content div, ignoring specific tags if necessary, 
            # but usually getting text line by line or parsing <p> and <li> tags specifically works best.
            # We will look for text patterns "YYYY: Name" within all relevant child elements.
            
            elements = content_div.find_all(['p', 'li'])
            
            for element in elements:
                text = element.get_text(" ", strip=True) # Normalize whitespace
                
                # This regex looks for Year followed by colon and then Name
                # It handles multiple entries in one block if they are separated clearly
                # but "2017: Name2016: Name" suggests they run together without spaces sometimes in the source text
                
                # Regex explanation:
                # (\d{4}): capture the year
                # \s* handle space around colon
                # (.*?): capture the name (non-greedy)
                # (?=\d{4}:|$) lookahead for next year or end of string
                
                pattern = r'(\d{4})\s*:\s*(.*?)(?=\d{4}:|$)'
                
                matches = re.finditer(pattern, text)
                
                for match in matches:
                    year = match.group(1).strip()
                    name = match.group(2).strip()
                    
                    # Clean up trailing punctuation if any (like dates stuck to end)
                    # The lookahead handles most, but sometimes garbage remains
                    
                    if name and year:
                        db.append({
                            'id': aid, 
                            'govid': govid, 
                            'govname': govname, 
                            'award': award, 
                            'year': year, 
                            'name': name
                        })

    except Exception as e:
        print(f"Error scraping {aid}: {e}")
    finally:
        driver.quit()

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f"{filepath}{aid}.csv", index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"AwardID {aid} --- scraped and saved to {filepath}{aid}.csv at {current_time}")

    return df

In [393]:
def scrape3473():
    award = "Department of English/George Jean Nathan Award for Dramatic Criticism"
    govid = "456"
    govname = "Cornell University"
    aid = "3473"
    url = "https://english.cornell.edu/george-jean-nathan-award-dramatic-criticism"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    tbod = soup.find('tbody')
    trs = tbod.find_all('tr')

    for tr in trs[1:]:
        try:
            tds = tr.find_all('td')
            year = tds[0].text.split('-')[0].strip()
            name = tds[1].find('strong').text.strip()
            namez = name.split(' and ')
            for name in namez:
                name = name.strip()
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
        except (IndexError, AttributeError):
            print(tds)
            print('IndexError here ^')

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [394]:
def scrape3533(): #Defunct
    pass
    # aid = "3533"
    # award = "George P Merrill Award"
    # govid = "222"
    # govname = "National Academy of Sciences"
    
    # url = "https://www.nasonline.org/programs/awards/george-p-merrill-award.html"
    # db = []
    # headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")

    # header = soup.find('h3', string="Recipients:")
    # names = header.find_next_sibling('p')

    # nt = names.text
    # nt = nt.split(')')

    # for n in nt:
    #     try:
    #         sp = n.split('(')
    #         name = sp[0].strip()
    #         year = sp[1].strip()
    #         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

    #     except IndexError:
    #         pass

    # df = pd.DataFrame(db)
    # display(df)
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    # return df

In [395]:
def scrape3534(): #Defunct
    pass
    # award = "Benjamin Apthorp Gould Prize"
    # govid = "222"
    # govname = "National Academy of Sciences"
    # aid = "3534"
    # url = "http://www.nasonline.org/programs/awards/benjamin-apthorp-gould-prize.html"
    # db = []
    # headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    # page = requests.get(url, headers=headers)
    # soup = BeautifulSoup(page.content, "html.parser")

    # header = soup.find('h3', string="Recipients:")
    # names = header.find_next_siblings('p')

    # for x in names:
    #     try:
    #         nt = x.text
    #         sp = nt.split('(')
    #         name = sp[0].strip()
    #         year = sp[1].split(')')[0].strip()
    #         db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
        
    #     except IndexError:
    #         pass

    # df = pd.DataFrame(db)
    # display(df)
    # df.to_csv(f'{filepath}{aid}.csv',index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

In [396]:
def scrape3594():
    award = "NAEd Member"
    govid = "220"
    govname = "National Academy of Education"
    aid = "3594"
    url = "https://naeducation.org/our-members/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('div', class_='fwpl-layout')
    ndiv = mdiv.find_all('div', class_='fwpl-result')

    for div in ndiv:
        name_div = div.find('div', class_='el-usw4ek')
        name = name_div.find('a').text if name_div else None
        aff_div = div.find('div', class_='el-d33tnl')
        aff = aff_div.text if aff_div else None
        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name, 'affiliation': aff})

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [397]:
def scrape3177():
    award = "John Deere Gold Medal"
    govid = "123"
    govname = "American Society of Agricultural and Biological Engineers"
    aid = "3177"
    url = "https://www.asabe.org/Awards-Competitions/Major-Awards/JOHN-DEERE-GOLD-MEDAL"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    try:
        page = requests.get(url, headers=headers)
        page.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching the main URL: {e}")
        return pd.DataFrame()

    soup = BeautifulSoup(page.content, "html.parser")

    try:
        p_tags = soup.find_all('p', style="text-align: center;")
        for p in p_tags:
            if 'Recipient' in p.get_text():
                year_match = re.search(r'\b(20\d{2})\b', p.get_text())
                strong = p.find('strong')
                if year_match and strong:
                    year = year_match.group(1)
                    name = strong.get_text(strip=True)
                    if name:
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
                        break
    except Exception as e:
        print(f"Could not parse current recipient. Error: {e}")

    temp_pdf_path = None
    try:
        pdf_link_tag = soup.find('a', string=re.compile("Past Recipients"))
        if not pdf_link_tag or not pdf_link_tag.has_attr('href'):
            raise Exception("PDF link not found on the page.")

        pdf_url = urljoin(url, pdf_link_tag['href'])
        pdf_response = requests.get(pdf_url, headers=headers)
        pdf_response.raise_for_status()

        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_f:
            temp_pdf_path = temp_f.name
            temp_f.write(pdf_response.content)

        pdf_text = extract_text(temp_pdf_path)
        for line in pdf_text.split('\n'):
            line = line.strip()
            if line and line[:4].isdigit() and len(line) > 4:
                year = line[:4]
                name = line.split('..')[-1].strip('.').strip()
                if name and 'No Recipient' not in name:
                    db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})
    except Exception as e:
        print(f"Failed during PDF processing: {e}")
    finally:
        if temp_pdf_path and os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    df['award'] = award

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [398]:
def scrape3174():
    award = "Hall of Fame Award"
    govid = "112"
    govname = "American Society for Horticultural Science"
    aid = "3174"
    url = "https://ashs.org/page/HallofFameAward"
    db = []

    options = webdriver.ChromeOptions()
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(3)

    try:
        soup = BeautifulSoup(driver.page_source, "html.parser")
        pdf_link_tag = soup.find('a', href=re.compile(r"award_winners/ashs_hof\.pdf"), string=re.compile("Previous Hall of Fame Winners", re.I))
        if not pdf_link_tag or not pdf_link_tag.has_attr('href'):
            raise Exception("PDF link not found.")
        pdf_url = urljoin(url, pdf_link_tag['href'])
    except Exception as e:
        print(f"PDF detection failed: {e}")
        driver.quit()
        return pd.DataFrame()
    finally:
        driver.quit()

    temp_pdf_path = None
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        pdf_response = requests.get(pdf_url, headers=headers)
        pdf_response.raise_for_status()

        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_f:
            temp_pdf_path = temp_f.name
            temp_f.write(pdf_response.content)

        with open(temp_pdf_path, 'rb') as file:
            pdf_reader = PyPDF2.PdfReader(file)
            text = ""
            for page in pdf_reader.pages:
                text += page.extract_text() + "\n"

        response = model.generate_content(
            contents=f"I have a PDF file that lists ASHS Horticulture Hall of Fame winners. Give me the name and the year in a table format in that order. The following is the text from the PDF file: {text}"
        )

        lines = response.text.strip().split("\n")
        table_rows = lines[3:]

        for row in table_rows:
            columns = [col.strip() for col in row.split("|") if col.strip()]
            if len(columns) == 2:
                name, year = columns
            elif len(columns) == 3:
                name, year, _ = columns
            else:
                name = columns[0]
                year = ''
            if len(name.strip()) > 3:
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

    except Exception as e:
        print(f"Failed during PDF processing or LLM parsing: {e}")
    finally:
        if temp_pdf_path and os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)

    if not db:
        print(f"AwardID {aid} --- No data was scraped.")
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    df['award'] = award
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now()
    current_time = now.strftime("%H:%M:%S")
    print(f"\nAwardID {aid} --- Scraped {len(df)} records and saved to path at {current_time}")

    return df

In [399]:
def scrape3266():
    award = "Osborne and Mendel Award"
    govid = "322"
    govname = "American Society for Nutrition"
    aid = "3266"
    url = "https://nutrition.org/asn-foundation/past-award-honorees/"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    block = soup.find('h2', id='h-osborne-and-mendel-award')
    div = block.find_next_sibling('div', class_='wp-block-columns-is-layout-flex')
    raw_text = div.get_text(separator=" ", strip=True)

    response = model.generate_content(
        contents=f"""
You are a data extraction system.

Extract a clean JSON array of recipients from the following award winner text. 
Each item should be a dictionary with two keys only: "name" and "year".
- If a line lists multiple names, split them into separate entries.
- Do NOT include affiliations.
- Do NOT return markdown or explanation—just the raw JSON.

TEXT:
{raw_text}
"""
    )

    text = response.text.strip()

    json_match = re.search(r'\[.*?\]', text, re.DOTALL)
    json_blob = json_match.group(0) if json_match else text

    try:
        data = json.loads(json_blob)
        for item in data:
            name = item.get("name", "").strip()
            year = item.get("year", "")
            if name and year:
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })
    except Exception as e:
        print("Failed to parse JSON response:", e)
        print("Raw model response:\n", text)
        return pd.DataFrame()

    df = pd.DataFrame(db).drop_duplicates().sort_values(by='year', ascending=False).reset_index(drop=True)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [400]:
def scrape3306():
    award = "Fellow of National Academy of Public Administration"
    govid = "427"
    govname = "National Academy of Public Administration"
    aid = "3306"
    url = "https://napawash.org/search-fellows"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    links = []

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    time.sleep(3)

    cookiebt = driver.find_element(By.XPATH, "//button[contains(@id, 'privacy-policy-btn')]")
    cookiebt.click()

    time.sleep(3)

    while True:
        try:
            mdiv = driver.find_element(By.ID, 'fellow-listings-fellows')
            aas = mdiv.find_elements(By.TAG_NAME, 'a')
            for a in aas:
                link = a.get_attribute('href')
                links.append(link)

            try:
                cookie_notice = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.ID, "cookie-notice")))
                accept_button = cookie_notice.find_element(By.XPATH, "//button[contains(text(), 'Accept')]")
                accept_button.click()
            except:
                pass

            nextbt = driver.find_element(By.XPATH, "//a[contains(text(), 'Next')]")
            nextbt.click()

        except NoSuchElementException:
            break
    
    for link in links:
        try:
            driver.get(link)
            name = driver.find_element(By.XPATH, "//h1").text.strip()
            year = driver.find_element(By.XPATH, "//h4").text.strip().split()[-1].strip()
            
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'year': year, 'name': name})

        except NoSuchElementException:
            print('Error occurred here:')
            print(link)
            pass

    df = pd.DataFrame(db)

    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [401]:
def scrape3283():
    award = "Louis E Levy Medal"
    govid = "346"
    govname = "Franklin Institute"
    aid = "3283"
    url = "https://fi.edu/en/awards/laureates/search?field_lastname_value=&field_subject_target_id=All&field_awards_target_id=389&field_year_value=&field_year_value_1="
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    while True:
        mdiv = driver.find_element(By.CLASS_NAME, 'view-content')
        rows = mdiv.find_elements(By.CLASS_NAME, 'views-row')

        for row in rows:
            name = row.find_element(By.CLASS_NAME, 'container--names').text.strip().strip('. ').strip()
            year = row.find_element(By.CLASS_NAME, 'field--name-field-year').text.strip().split("\n")[1].strip()

            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name, 'year': year})
        
        try:
            nextbt = driver.find_element(By.CLASS_NAME, 'pager__item--next')
            nextbt.click()

        except NoSuchElementException:
            break

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [402]:
def scrape4891():
    govid = "1019"
    govname = "American Psychological Foundation"
    pdf_url = "https://www.apa.org/about/awards/apa-apf-awards/awards-booklet.pdf"
    db = []
    temp_dir = tempfile.mkdtemp()
    pdf_path = Path(temp_dir) / "apf_booklet.pdf"

    try:
        print(f"Downloading PDF from {pdf_url}...")
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        with requests.get(pdf_url, headers=headers, stream=True, timeout=60) as r:
            r.raise_for_status()
            with open(pdf_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
        
        # Extract text from PDF pages
        text = ""
        reader = pypdf.PdfReader(pdf_path)
        if len(reader.pages) >= 6:
            text += reader.pages[4].extract_text() + "\n"
            text += reader.pages[5].extract_text() + "\n"
        else:
            print("Error: The downloaded PDF does not have enough pages.")
            return

        print("Extracted text from PDF. Processing with Gemini...")
        
        # Use Gemini to clean and structure the data
        prompt = f"""OUTPUT ONLY A JSON ARRAY. NO CODE FENCES, NO MARKDOWN, NO EXPLANATION.
Each element must be an object with keys: year, name, subaward.
The subaward should be one of: "", "Practice", "Public Interest", "Science", "Application"

Rules:
  • Extract all award recipients from the PDF text.
  • Subaward categories are "Practice", "Public Interest", "Science", or empty string "" for general awards.
  • Extract year from each entry.
  • Extract recipient name (first and last name).
  • Remove any entries containing "no award given" or similar phrases.
  • Clean up any special characters or OCR artifacts.
  • If a name contains titles like "Dr.", "Prof.", remove them.

Here is the PDF text to process:
{text}"""

        response = model.generate_content(contents=prompt)
        raw = response.text.strip()

        # Clean up markdown formatting if present
        if raw.startswith("```"):
            raw = raw.strip("```json").strip("```").strip()

        # Extract JSON array
        match = re.search(r"\[\s*\{.*\}\s*\]", raw, re.DOTALL)
        json_text = match.group(0) if match else raw

        try:
            winners = json.loads(json_text)
            print(f"Successfully parsed {len(winners)} entries from Gemini")
            
            for w in winners:
                if len(w.get("name", "")) > 2:
                    db.append({
                        'govid': govid,
                        'govname': govname,
                        'year': str(w.get("year", "")),
                        'name': w.get("name", "").strip(),
                        'subaward': w.get("subaward", "")
                    })
        except json.JSONDecodeError as e:
            print(f"Error parsing Gemini JSON response: {e}")
            print("Falling back to regex parsing...")
            raise

        if not db:
            print("No award data could be extracted from the PDF.")
            return

        df = pd.DataFrame(db)
        # Remove entries with 'No award given' in name (case-insensitive)
        df = df[~df['name'].str.contains('no award given', case=False, na=False)]

        # 4891: Gold Medal Award for Impact in Psychology (General)
        df_curr = df[df['subaward'] == ''].copy()
        if not df_curr.empty:
            df_curr['id'] = 4891
            df_curr['award'] = "Gold Medal Award for Impact in Psychology"
            df_curr = df_curr.drop(columns=['subaward'])
            print("\n--- Gold Medal Award for Impact in Psychology (4891) ---")
            print(tabulate(df_curr, headers='keys', tablefmt='psql'))
            df_curr.to_csv(f'{filepath}4891.csv', index=False)
            df4891 = df_curr

        # 4892: Practice
        df_curr = df[df['subaward'] == 'Practice'].copy()
        if not df_curr.empty:
            df_curr['id'] = 4892
            df_curr['award'] = "Gold Medal Awards for Life Achievement, Practice"
            df_curr = df_curr.drop(columns=['subaward'])
            print("\n--- Gold Medal Awards for Life Achievement, Practice (4892) ---")
            print(tabulate(df_curr, headers='keys', tablefmt='psql'))
            df_curr.to_csv(f'{filepath}4892.csv', index=False)
            df4892 = df_curr

        # 4893: Public Interest
        df_curr = df[df['subaward'] == 'Public Interest'].copy()
        if not df_curr.empty:
            df_curr['id'] = 4893
            df_curr['award'] = "Gold Medal Awards for Life Achievement, Public Interest"
            df_curr = df_curr.drop(columns=['subaward'])
            print("\n--- Gold Medal Awards for Life Achievement, Public Interest (4893) ---")
            print(tabulate(df_curr, headers='keys', tablefmt='psql'))
            df_curr.to_csv(f'{filepath}4893.csv', index=False)
            df4893 = df_curr

        # 4894: Science
        df_curr = df[df['subaward'] == 'Science'].copy()
        if not df_curr.empty:
            df_curr['id'] = 4894
            df_curr['award'] = "Gold Medal Awards for Life Achievement, Science"
            df_curr = df_curr.drop(columns=['subaward'])
            print("\n--- Gold Medal Awards for Life Achievement, Science (4894) ---")
            print(tabulate(df_curr, headers='keys', tablefmt='psql'))
            df_curr.to_csv(f'{filepath}4894.csv', index=False)
            df4894 = df_curr
            
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"\nAward scraping complete at {current_time}")

    except requests.exceptions.RequestException as e:
        print(f"Error downloading the PDF: {e}")
    except pypdf.errors.PdfReadError as e:
        print(f"Error reading the downloaded PDF file: {e}. It may be corrupt.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
    finally:
        shutil.rmtree(temp_dir)

    return df4891, df4892, df4893, df4894

In [403]:
def scrape3282():
    award = "John Price Wetherill Medal"
    govid = "346"
    govname = "Franklin Institute"
    aid = "3282"
    base_url = "https://fi.edu/en/awards/laureates/search"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}
    page = 0

    def clean_name(name):
        name = re.sub(r"(?<=[a-zA-Z])(?=[A-Z])", " ", name)             # insert space before capital letters following a letter
        name = re.sub(r"(?<=[a-zA-Z])(?=\d)", " ", name)               # insert space before numbers
        name = re.sub(r"(?<=[.])(?=[A-Z])", " ", name)                 # space after periods if next is uppercase
        name = re.sub(r"\s+", " ", name)                               # normalize multiple spaces
        return name.strip()

    while True:
        params = {
            'field_lastname_value': '',
            'field_subject_target_id': 'All',
            'field_awards_target_id': '398',
            'field_year_value': '',
            'field_year_value_1': '',
            'page': page
        }
        resp = requests.get(base_url, params=params, headers=headers)
        soup = BeautifulSoup(resp.text, 'html.parser')
        rows = soup.select('.view-content .views-row')

        if not rows:
            break

        for row in rows:
            name = row.select_one('.container--names')
            year = row.select_one('.field--name-field-year')
            if name and year:
                raw_name = name.get_text(strip=True).strip('. ')
                name_text = clean_name(raw_name)
                year_lines = year.get_text(strip=True, separator="\n").split("\n")
                year_text = year_lines[1] if len(year_lines) > 1 else ''
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name_text, 'year': year_text})

        page += 1

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        print(f"AwardID {aid} --- scraped and saved to path at {now.strftime('%H:%M:%S')}")

    return df

In [404]:
def scrape3281():
    award = "Elliott Cresson Medal"
    govid = "346"
    govname = "Franklin Institute"
    aid = "3281"
    base_url = "https://fi.edu/en/awards/laureates/search"
    headers = {'User-Agent': 'Mozilla/5.0'}
    db = []
    page = 0

    def clean_name(name):
        name = re.sub(r"(?<=[a-zA-Z])(?=[A-Z])", " ", name)             # insert space before capital letters following a letter
        name = re.sub(r"(?<=[a-zA-Z])(?=\d)", " ", name)               # insert space before numbers
        name = re.sub(r"(?<=[.])(?=[A-Z])", " ", name)                 # space after periods if next is uppercase
        name = re.sub(r"\s+", " ", name)                               # normalize multiple spaces
        return name.strip()

    while True:
        params = {
            'field_lastname_value': '',
            'field_subject_target_id': 'All',
            'field_awards_target_id': '384',
            'field_year_value': '',
            'field_year_value_1': '',
            'page': page
        }
        resp = requests.get(base_url, params=params, headers=headers)
        soup = BeautifulSoup(resp.text, 'html.parser')
        rows = soup.select('.view-content .views-row')

        if not rows:
            break

        for row in rows:
            name = row.select_one('.container--names')
            year = row.select_one('.field--name-field-year')
            if name and year:
                raw_name = name.get_text(strip=True).strip('. ')
                name_text = clean_name(raw_name)
                year_lines = year.get_text(strip=True, separator="\n").split("\n")
                year_text = year_lines[1] if len(year_lines) > 1 else ''
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name_text, 'year': year_text})

        page += 1

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        print(f"AwardID {aid} --- scraped and saved to path at {now.strftime('%H:%M:%S')}")

    return df

In [405]:
def scrape3280():
    award = "Bolton L Corson Medal"
    govid = "346"
    govname = "Franklin Institute"
    aid = "3280"
    url = "https://fi.edu/en/awards/laureates/search?field_lastname_value=&field_subject_target_id=All&field_awards_target_id=383&field_year_value=&field_year_value_1="
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)

    while True:
        mdiv = driver.find_element(By.CLASS_NAME, 'view-content')
        rows = mdiv.find_elements(By.CLASS_NAME, 'views-row')

        for row in rows:
            name = row.find_element(By.CLASS_NAME, 'container--names').text.strip()
            year = row.find_element(By.CLASS_NAME, 'field--name-field-year').text.strip().split("\n")[1].strip()

            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name, 'year': year})
        
        try:
            nextbt = driver.find_element(By.CLASS_NAME, 'pager__item--next')
            nextbt.click()

        except NoSuchElementException:
            break

    driver.quit()

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [406]:
def scrape3304():
    award = "Harvard Society Junior Fellows"
    govid = "426"
    govname = "Harvard Society of Fellows"
    aid = "3304"
    url = "https://socfell.fas.harvard.edu/listed-term-0"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    
    # Function to clean names - remove asterisks, special characters, and trim
    def clean_name(name):
        import re
        # Remove leading/trailing asterisks and other special characters
        name = re.sub(r'^\s*\*+\s*|\s*\*+\s*$', '', name)  # Remove leading/trailing asterisks
        name = re.sub(r'[*†‡§¶†‖‡]', '', name)  # Remove special symbols
        return name.strip()

    # Scrape current junior fellows
    current_url = "https://socfell.fas.harvard.edu/current-junior-fellows"
    page = requests.get(current_url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    # Process page sequentially - track current year and look for links
    current_year = None
    seen_names = set()  # Track duplicates
    
    for elem in soup.descendants:
        if elem.name == 'h2':
            text = elem.get_text().strip()
            if '-' in text and text[0].isdigit():
                current_year = text.split('-')[0]
        
        elif elem.name == 'a' and '/people/' in elem.get('href', ''):
            name = clean_name(elem.get_text().strip())
            if current_year and name and name not in seen_names:
                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 
                           'name': name, 'year': current_year})
                seen_names.add(name)

    # Scrape past junior fellows from period pages
    past_periods = [
        "https://socfell.fas.harvard.edu/2020-present",
        "https://socfell.fas.harvard.edu/2010-2019",
        "https://socfell.fas.harvard.edu/2000-2009",
        "https://socfell.fas.harvard.edu/1990-1999",
        "https://socfell.fas.harvard.edu/1980-1989",
        "https://socfell.fas.harvard.edu/1970-1979",
        "https://socfell.fas.harvard.edu/1960-1969",
        "https://socfell.fas.harvard.edu/1950-1959",
        "https://socfell.fas.harvard.edu/1940-1949",
        "https://socfell.fas.harvard.edu/1933-1939"
    ]
    
    for period_url in past_periods:
        try:
            page = requests.get(period_url, headers=headers, timeout=10)
            soup = BeautifulSoup(page.content, "html.parser")
            current_year = None
            
            # Get all h3 tags (names are in these)
            h3s = soup.find_all('h3')
            
            for h3 in h3s:
                text = h3.get_text().strip()
                
                # Check if this h3 is a year heading (just digits or digits-digits with optional expand_more)
                if text and (text.isdigit() or (text.replace('expand_more', '').strip().isdigit())):
                    # Extract the year
                    year_text = text.replace('expand_more', '').strip()
                    if year_text.isdigit():
                        current_year = year_text
                
                # Otherwise, it's likely a name
                elif text and current_year and 'expand' not in text.lower():
                    # This is a fellow name
                    name = clean_name(text)
                    if name and name not in seen_names and len(name) > 2:  # Names should be at least 3 chars
                        db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 
                                   'name': name, 'year': current_year})
                        seen_names.add(name)
                        
        except Exception as e:
            print(f"Error scraping {period_url}: {e}")
            continue

    # Remove duplicates keeping only first occurrence
    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['name', 'year'], keep='first')
    
    print(f"\nTotal unique records: {len(df)}")
    print(tabulate(df.head(20), headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [407]:
def scrape3305():
    award = "Harvard Society Senior Fellows"
    govid = "426"
    govname = "Harvard Society of Fellows"
    aid = "3305"
    url = "https://socfell.fas.harvard.edu/current-and-former-senior-fellows"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}
    
    # Function to clean names - remove asterisks, special characters, and trim
    def clean_name(name):
        import re
        # Remove leading/trailing asterisks
        name = re.sub(r'^\s*\*+\s*|\s*\*+\s*$', '', name)
        # Remove special symbols
        name = re.sub(r'[*†‡§¶†‖‡]', '', name)
        # Remove things in parentheses like "(on leave AY2025-26)"
        name = re.sub(r'\s*\(.*?\)\s*', ' ', name)
        # Remove titles/roles like ", ex officio", ", Chair", ", Active Emeritus", ", Acting"
        name = re.sub(r',\s*(ex officio|Chair|Active Emeritus|Acting).*$', '', name, flags=re.IGNORECASE)
        return name.strip()
    
    # Function to extract year from "Years Served as a Senior Fellow: XXXX - YYYY"
    def extract_year(text):
        import re
        match = re.search(r'(\d{4})\s*-', text)
        if match:
            return match.group(1)
        return None

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")
    
    seen_names = set()
    h3_tags = soup.find_all('h3')
    
    for h3 in h3_tags:
        raw_name = h3.get_text().strip()
        name = clean_name(raw_name)
        
        # Skip section headers
        if not name or 'current' in name.lower() or 'former' in name.lower():
            continue
        
        if name in seen_names:
            continue
        
        # Find the next text containing "Years Served"
        year = None
        next_elem = h3.find_next()
        distance = 0
        
        while next_elem and distance < 20:
            elem_text = next_elem.get_text() if hasattr(next_elem, 'get_text') else str(next_elem)
            
            if 'Years Served as a Senior Fellow' in elem_text:
                year = extract_year(elem_text)
                break
            
            next_elem = next_elem.find_next()
            distance += 1
        
        if year:
            db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 
                       'name': name, 'year': year})
            seen_names.add(name)

    # Remove duplicates
    df = pd.DataFrame(db)
    df = df.drop_duplicates(subset=['name', 'year'], keep='first')
    
    print(f"\nTotal unique records: {len(df)}")
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [408]:
def scrape21775():
    award = "Dynamic Language Infrastructure-Documenting Endangered Languages Fellowships"
    govid = "234"
    govname = "National Endowment for the Humanities (NEH)"
    aid = "21775"
    url = "https://apps.neh.gov/PublicQuery/Default.aspx?q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&p=1&pv=238&d=0&at=0&y=0&prd=0&cov=0&prz=0&wp=0&sp=0&ca=0&arp=0&ob=Institution%20name&or=ASC"

    download_dir = tempfile.mkdtemp(prefix=f"neh_{aid}_")
    chrome_opts = Options()
    chrome_opts.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })
    chrome_opts.add_argument("--headless")
    driver = webdriver.Chrome(options=chrome_opts)

    try:
        driver.get(url)
        btn = driver.find_element(
            By.XPATH,
            '//button[contains(@id, "ExportToCSV")]'
        )
        btn.click()

        timeout = time.time() + 30
        csv_path = None
        while time.time() < timeout:
            files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
            if files:
                csv_path = os.path.join(download_dir, files[0])
                break
            time.sleep(0.5)
        if not csv_path:
            raise FileNotFoundError("NEH CSV download timed out")

    finally:
        driver.quit()

    df = pd.read_csv(csv_path)

    df.iloc[:, 4] = df.iloc[:, 4].fillna('')
    df['name'] = df.iloc[:, 3].str.cat(df.iloc[:, 4], sep=' ').str.cat(df.iloc[:, 5], sep=' ').str.strip()
    df['year'] = df.iloc[:, 14]
    df['field'] = df.iloc[:, 15].fillna('')
    df['affiliation'] = df.iloc[:, 9].fillna('')
    df['id'] = aid
    df['govid'] = govid
    df['govname'] = govname
    df['award'] = award

    df = df[['id', 'govid', 'govname', 'award', 'name', 'year', 'field', 'affiliation', ]]
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
        
    return df

In [409]:
def scrape3769():
    award = "NEH Fellowships for College Teachers and Independent Scholars"
    govid = "234"
    govname = "National Endowment for the Humanities (NEH)"
    aid = "3769"
    url = "https://apps.neh.gov/PublicQuery/Default.aspx?q=1&a=0&n=0&o=0&ot=0&k=0&f=0&s=0&cd=0&p=1&pv=2&d=0&at=0&y=0&prd=0&cov=0&prz=0&wp=0&sp=0&ca=0&arp=0&ob=Institution%20name&or=ASC"
    
    download_dir = tempfile.mkdtemp(prefix=f"neh_{aid}_")
    chrome_opts = Options()
    chrome_opts.add_experimental_option("prefs", {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "directory_upgrade": True
    })
    chrome_opts.add_argument("--headless")
    driver = webdriver.Chrome(options=chrome_opts)

    try:
        driver.get(url)
        btn = driver.find_element(
            By.XPATH,
            '//button[contains(@id, "ExportToCSV")]'
        )
        btn.click()

        timeout = time.time() + 30
        csv_path = None
        while time.time() < timeout:
            files = [f for f in os.listdir(download_dir) if f.lower().endswith(".csv")]
            if files:
                csv_path = os.path.join(download_dir, files[0])
                break
            time.sleep(0.5)
        if not csv_path:
            raise FileNotFoundError("NEH CSV download timed out")

    finally:
        driver.quit()

    df = pd.read_csv(csv_path)

    df.iloc[:, 4] = df.iloc[:, 4].fillna('')
    df['name'] = df.iloc[:, 3].str.cat(df.iloc[:, 4], sep=' ').str.cat(df.iloc[:, 5], sep=' ').str.strip()
    df['year'] = df.iloc[:, 14]
    df['field'] = df.iloc[:, 15].fillna('')
    df['affiliation'] = df.iloc[:, 9].fillna('')
    df['id'] = aid
    df['govid'] = govid
    df['govname'] = govname
    df['award'] = award

    df = df[['id', 'govid', 'govname', 'award', 'name', 'year', 'field', 'affiliation', ]]
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")
        
    return df

In [410]:
def scrape3096():
    award = "The Amory Prize"
    govid = "6"
    govname = "American Academy of Arts and Sciences"
    aid = "3096"
    url = "https://www.amacad.org/about/prizes/amory-prize"
    db = []

    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/122.0.0.0 Safari/537.36'
        )
    }

    options = Options()
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    content_section = None
    for div_tag in soup.find_all('div', class_='field-item'):
        if div_tag.find('h2', string='Recipients'):
            content_section = div_tag
            break
    
    driver.quit()

    response = model.generate_content(
        contents = f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name,
                    'affiliation': affiliation
                })

    if not db:
        return pd.DataFrame()

    df = pd.DataFrame(db)
    df = df[['id', 'govid', 'govname', 'award', 'name', 'year', 'affiliation']]
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now().strftime("%H:%M:%S")
    print(f"AwardID {aid} --- scraped and saved to path at {now}")
    
    return df

In [411]:
def scrape3097():
    award = "The Rumford Prize"
    govid = "6"
    govname = "American Academy of Arts and Sciences"
    aid = "3097"
    url = "https://www.amacad.org/about/prizes/rumford-prize"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    driver = webdriver.Chrome(options=options)
    driver.get(url)
    time.sleep(3)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    content_section = None
    for div_tag in soup.find_all('div', class_='field-item'):
        if div_tag.find('h2', string='Recipients'):
            content_section = div_tag
            break
    
    driver.quit()

    response = model.generate_content(
        contents = f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name,
                    'affiliation': affiliation
                })

    if not db:
        return pd.DataFrame()

    df = pd.DataFrame(db)
    df = df[['id', 'govid', 'govname', 'award', 'name', 'year', 'affiliation']]
    print(tabulate(df, headers='keys', tablefmt='psql'))

    df.to_csv(f'{filepath}{aid}.csv', index=False)

    now = datetime.now().strftime("%H:%M:%S")
    print(f"AwardID {aid} --- scraped and saved to path at {now}")
    
    return df

In [412]:
def scrape3213():
    print("website reworked, directory is a work in progress, scrape3213() paused")
    # aid = "3213"
    # award = "Robert Wood Johnson Policy Fellowship"
    # govid = "202"
    # govname = "National Academy of Medicine"
    # base_url = "https://healthpolicyfellows.org/alumni/health-policy-fellows-directory/page/"
    # db = []
    
    # options = Options()
    # options.headless = True
    # driver = webdriver.Chrome(options=options)
    # driver.implicitly_wait(10)
    # page = 1
    
    # try:
    #     while True:
    #         try:
    #             current_url = f"{base_url}{page}/" if page > 1 else "https://healthpolicyfellows.org/alumni/health-policy-fellows-directory/"
    #             driver.get(current_url)
    #             time.sleep(3)
                
    #             # Wait for directory results
    #             WebDriverWait(driver, 10).until(
    #                 EC.presence_of_element_located((By.CLASS_NAME, 'directory_results'))
    #             )
                
    #             mdiv = driver.find_element(By.CLASS_NAME, 'directory_results')
    #             rows = mdiv.find_elements(By.CLASS_NAME, 'directory_result')
                
    #             print(f"Processing page {page} - Found {len(rows)} entries")
                
    #             for row in rows:
    #                 try:
    #                     # Try multiple ways to get name
    #                     try:
    #                         name_elem = row.find_element(By.CLASS_NAME, 'display_name')
    #                     except:
    #                         try:
    #                             name_elem = row.find_element(By.TAG_NAME, 'h2')
    #                         except:
    #                             print(f"Could not find name element, skipping row")
    #                             continue
                                
    #                     name = name_elem.text.strip()
    #                     if ',' in name:
    #                         name = name.split(',')[0].strip()
                            
    #                     # Try to get year, set to empty string if not found
    #                     year = ""
    #                     try:
    #                         year_text = row.find_element(By.CLASS_NAME, 'fellowship_year').text
    #                         year = year_text.strip().strip('(').strip(')')[:4]
    #                     except:
    #                         try:
    #                             # Try to find any text that looks like a year
    #                             row_text = row.text
    #                             import re
    #                             year_match = re.search(r'\((\d{4})\)', row_text)
    #                             if year_match:
    #                                 year = year_match.group(1)
    #                         except:
    #                             pass  # Keep year as empty string if not found
                        
    #                     # Debug print before adding to database
    #                     print(f"Found: {name} - {year}")
                        
    #                     db.append({
    #                         'id': aid,
    #                         'govid': govid,
    #                         'govname': govname,
    #                         'award': award,
    #                         'name': name,
    #                         'year': year
    #                     })
                        
    #                 except Exception as e:
    #                     print(f"Error processing row: {str(e)}")
    #                     # Print the HTML of the problematic row for debugging
    #                     try:
    #                         print(f"Row HTML: {row.get_attribute('innerHTML')}")
    #                     except:
    #                         pass
    #                     continue
                
    #             # Look for next button
    #             time.sleep(2)
    #             try:
    #                 next_button = WebDriverWait(driver, 10).until(
    #                     EC.element_to_be_clickable((By.XPATH, "//a[@class='next page-numbers']"))
    #                 )
    #                 driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
    #                 time.sleep(1)
    #                 next_button.click()
    #                 page += 1
    #                 time.sleep(3)
    #             except:
    #                 print(f"Finished at page {page}")
    #                 break
                    
    #         except Exception as e:
    #             print(f"Error processing page {page}: {str(e)}")
    #             break
                
    # finally:
    #     driver.quit()

    # for entry in db:
    #     if not entry['year'].isdigit() or len(entry['year']) != 4:
    #         entry['year'] = ""
    
    # df = pd.DataFrame(db)
    # print(tabulate(df, headers='keys', tablefmt='psql'))
    # df.to_csv(f'{filepath}{aid}.csv', index=False)

    # if not df.empty:
    #     now = datetime.now()
    #     current_time = now.strftime("%H:%M:%S")
    #     print(f"AwardID {aid} --- scraped {len(df)} records and saved to path at {current_time}")
    # else:
    #     print("No data was collected")

    # return df

In [413]:
def scrape3233():
    award = "Award for Distinguished Service to the Humanities"
    govid = "254"
    govname = "Phi Beta Kappa Society"
    aid = "3233"
    url = "https://www.pbk.org/awards/past-winners-triennial"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0.0.0 Safari/537.36'}
    
    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    header = soup.find('h3', string="The Award for Distinguished Service to the Humanities")
    table = header.find_next('table')

    content_section = table

    response = model.generate_content(
        contents=f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name,
                    'affiliation': affiliation
                })

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv', index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [414]:
def scrape3238():
    award = "Sidney Hook Memorial Award"
    govid = "254"
    govname = "Phi Beta Kappa Society"
    aid = "3238"
    url = "https://www.pbk.org/awards/past-winners-triennial"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    headers = soup.find_all('h3')

    for header in headers:
        if 'The Sidney Hook Memorial Award' in header.get_text(separator=' ', strip=True):
            table = header.find_next('table')

            content_section = table

            response = model.generate_content(
                contents=f"""
                    Please extract the winner's Name, Year, and Affiliation from the text below.
                    Output the data as a Markdown table with exactly three columns.

                    **Requirements:**
                    - The table must have a header row: `| Name | Year | Affiliation |`
                    - Each row should contain one person's full name, the year they won, and their affiliation.
                    - If a year lists multiple winners, create a separate row for each winner, both with the same year.
                    - If multiple winners share a single affiliation, assign that same affiliation to each winner.
                    - If a winner has no affiliation listed, leave the Affiliation column empty.
                    - Do not include the reason for the award or links to press releases.

                    **Text to parse:**
                    {content_section.get_text(separator=' ', strip=True)}
                """
            )

            lines = response.text.strip().splitlines()
            table_lines = [l for l in lines if l.strip().startswith("|")]

            if len(table_lines) < 3:
                return pd.DataFrame()

            data_rows = table_lines[2:]

            for row in data_rows:
                cols = [c.strip() for c in row.split("|")[1:-1]]
                if len(cols) == 3:
                    name, year, affiliation = cols
                    if len(name) > 1 and year.isdigit():
                        db.append({
                            'id': aid,
                            'govid': govid,
                            'govname': govname,
                            'award': award,
                            'year': year,
                            'name': name,
                            'affiliation': affiliation
                        })

    df = pd.DataFrame(db)
    display(df)
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [415]:
def scrape3234():
    award = "Phi Beta Kappa Book Awards - Christian Gauss Award"
    govid = "254"
    govname = "Phi Beta Kappa Society"
    aid = "3234"
    url = "https://www.pbk.org/awards/bookawards/gauss-winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('main', id='content')
    
    content_section = mdiv

    response = model.generate_content(
        contents=f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [416]:
def scrape3235():
    award = "Phi Beta Kappa Book Awards - Ralph Waldo Emerson Award"
    govid = "254"
    govname = "Phi Beta Kappa Society"
    aid = "3235"
    url = "https://www.pbk.org/awards/bookawards/emerson-winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('main', id='content')
    
    content_section = mdiv

    response = model.generate_content(
        contents=f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [417]:
def scrape3236():
    award = "Phi Beta Kappa Book Awards - Science Book"
    govid = "254"
    govname = "Phi Beta Kappa Society"
    aid = "3236"
    url = "https://www.pbk.org/awards/bookawards/science-winners"
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser")

    mdiv = soup.find('main', id='content')
    
    content_section = mdiv

    response = model.generate_content(
        contents=f"""
            Please extract the winner's Name, Year, and Affiliation from the text below.
            Output the data as a Markdown table with exactly three columns.

            **Requirements:**
            - The table must have a header row: `| Name | Year | Affiliation |`
            - Each row should contain one person's full name, the year they won, and their affiliation.
            - If a year lists multiple winners, create a separate row for each winner, both with the same year.
            - If multiple winners share a single affiliation, assign that same affiliation to each winner.
            - If a winner has no affiliation listed, leave the Affiliation column empty.
            - Do not include the reason for the award or links to press releases.

            **Text to parse:**
            {content_section.get_text(separator=' ', strip=True)}
        """
    )

    lines = response.text.strip().splitlines()
    table_lines = [l for l in lines if l.strip().startswith("|")]

    if len(table_lines) < 3:
        return pd.DataFrame()

    data_rows = table_lines[2:]

    for row in data_rows:
        cols = [c.strip() for c in row.split("|")[1:-1]]
        if len(cols) == 3:
            name, year, affiliation = cols
            if len(name) > 1 and year.isdigit():
                db.append({
                    'id': aid,
                    'govid': govid,
                    'govname': govname,
                    'award': award,
                    'year': year,
                    'name': name
                })

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

In [ ]:
def scrape5711():
    award = "Senior von Humboldt Fellowship"
    govid = "303"
    govname = "Alexander Von Humboldt Foundation"
    aid = "5711"
    url = "https://www.humboldt-foundation.de/en/connect/explore-the-humboldt-network?tx_solr%5Bq%5D=&tx_solr%5Bfilter%5D%5Belectionprogram_stringS_1%5D=electionprogram_stringS%3AHumboldt+Research+Fellowship&tx_solr%5Bfilter%5D%5B3%5D=&tx_solr%5Bfilter%5D%5B4%5D=&tx_solr%5Bfilter%5D%5B5%5D=&tx_solr%5Bfilter%5D%5B6%5D=&tx_solr%5Bfilter%5D%5B7%5D=&tx_solr%5Bfilter%5D%5B8%5D="
    db = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    options = Options()
    options.headless = True

    driver = webdriver.Chrome(options=options)
    driver.get(url)
    driver.implicitly_wait(6)

    while True:
        try:
            mdiv = driver.find_element(By.XPATH, "//div[contains(@class, 'list__items')]")
            items = mdiv.find_elements(By.XPATH, ".//div[@class='list__item']")
            for item in items[1:]:
                h2_element = item.find_element(By.XPATH, ".//h2[contains(@class, 'headline headline--3 f-w-semibold headline--wide')]")

                a_element = h2_element.find_element(By.TAG_NAME, 'a')
                name = a_element.text.strip()

                selection_date_element = item.find_element(By.XPATH, ".//li[contains(@class, 'list-item__meta-item text--tiny') and strong[contains(text(), 'Selection date:')]]")
                year = selection_date_element.text.replace('Selection date: ', '').strip()[-4:]

                db.append({'id': aid, 'govid': govid, 'govname': govname, 'award': award, 'name': name.strip(), 'year': year.strip()})

            next_button = driver.find_element(By.XPATH, "//div[@class='pagination__next']/a")
            driver.execute_script("arguments[0].click();", next_button)
            time.sleep(2)
        
        except (NoSuchElementException, TimeoutException):
            break

    df = pd.DataFrame(db)
    print(tabulate(df, headers='keys', tablefmt='psql'))
    df.to_csv(f'{filepath}{aid}.csv',index=False)

    if not df.empty:
        now = datetime.now()
        current_time = now.strftime("%H:%M:%S")
        print(f"AwardID {aid} --- scraped and saved to path at {current_time}")

    return df

## Post Scrape (Join, Wikicheck, etc.)

In [3]:
#Post Scrape Initialization
import os
import time
import pickle
import hashlib
import gc
import re
from pathlib import Path

import pandas as pd
import numpy as np
import ftfy
from tqdm import tqdm
from tabulate import tabulate
import hashlib

from sklearn.cluster import DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix, vstack, hstack

In [419]:
#Step 0: Check for missing or extra IDs in the folder

# 1. Path to your folder
folder_path = "E:\\Ace\\Awards Scrape\\Results v4\\"

# 2. Replace this with your actual list of expected IDs
expected_ids = [
    101, 147, 152, 203, 332, 404, 407, 441, 479, 504, 528, 593, 594, 611, 722, 809,
    814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 884, 906, 908, 1123, 1151,
    1182, 1186, 1194, 1234, 1393, 1428, 1429, 1437, 1438, 1606, 1607, 1628, 1750,
    1758, 1776, 1809, 1888, 1909, 1920, 1932, 1933, 1934, 1935, 1940, 1972, 1977,
    1984, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2014, 2015, 2017,
    2018, 2019, 2020, 2021, 2022, 2023, 2025, 2026, 2027, 2028, 2029, 2030, 2031,
    2032, 2033, 2034, 2035, 2036, 2037, 2092, 2094, 2095, 2096, 2129, 2134, 2138,
    2157, 2230, 2231, 2232, 2233, 2234, 2235, 2270, 2274, 2313, 2466, 2467, 2516,
    2545, 2561, 2565, 2662, 2708, 2768, 2769, 2770, 2771, 2775, 2778, 2835, 2853,
    2860, 2873, 2875, 2878, 2879, 2890, 2891, 2892, 2893, 2937, 2942, 2956, 2959,
    2973, 2980, 2981, 2982, 2988, 3000, 3001, 3002, 3004, 3007, 3008, 3009,
    3010, 3011, 3015, 3016, 3024, 3028, 3038, 3056, 3064, 3086, 3092, 3093, 3095,
    3096, 3097, 3121, 3123, 3174, 3177, 3213, 3233, 3234, 3235, 3236, 3238, 3262,
    3266, 3280, 3281, 3282, 3283, 3304, 3305, 3306, 3307, 3456, 3473, 3504, 3533,
    3534, 3594, 3768, 3769, 4219, 4891, 4892, 4893, 4894, 5711, 5724, 5732, 8258,
    21775, 21776
]

# 3. Get list of IDs from file names
file_ids = [
    int(f.replace(".csv", ""))
    for f in os.listdir(folder_path)
    if f.endswith(".csv") and f.replace(".csv", "").isdigit()
]

# 4. Convert to sets for easy comparison
expected_set = set(expected_ids)
actual_set = set(file_ids)

# 5. Cross-check
missing = expected_set - actual_set
extra = actual_set - expected_set

# 5a. Check for empty or small CSVs (less than 2 lines = 0 data rows if header exists)
empty_or_small_files = []
print("Checking for empty or small files...")

for fid in actual_set:
    fname = os.path.join(folder_path, f"{fid}.csv")
    try:
        if os.stat(fname).st_size == 0:
            empty_or_small_files.append((fid, "Empty file (0 bytes)"))
            continue
            
        df_check = pd.read_csv(fname)
        # "less than 2 rows" likely means header + 0 data rows = 1 row total in file.
        # But if they meant < 2 data rows, we can flag that too.
        # Here we flag if data rows < 1 (Empty) or if data rows == 1 (Small)
        if len(df_check) == 0:
             empty_or_small_files.append((fid, "Empty (0 data rows)"))
        elif len(df_check) < 2:
             empty_or_small_files.append((fid, "Small (< 2 data rows)"))

    except Exception as e:
        empty_or_small_files.append((fid, f"Error reading: {str(e)}"))

# 6. Output results
print(f"Total Files Checked: {len(actual_set)}")
print("✅ Present:", sorted(expected_set & actual_set))
print("❌ Missing:", sorted(missing))
print("🛑 Extra:", sorted(extra))

if empty_or_small_files:
    print("\n⚠️ Empty or Small CSVs (< 2 data rows):")
    for ef in empty_or_small_files:
        print(f"  - ID {ef[0]}: {ef[1]}")
else:
    print("\n✅ No empty/small files found.")

Checking for empty or small files...
Total Files Checked: 186
✅ Present: [101, 147, 152, 203, 332, 404, 407, 441, 479, 504, 528, 593, 594, 611, 722, 809, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 884, 906, 1123, 1151, 1182, 1186, 1194, 1234, 1393, 1428, 1429, 1437, 1438, 1606, 1607, 1628, 1750, 1758, 1776, 1809, 1888, 1909, 1920, 1932, 1933, 1934, 1935, 1940, 1972, 1977, 1984, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2014, 2015, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2025, 2027, 2028, 2029, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2092, 2094, 2095, 2096, 2129, 2134, 2138, 2157, 2230, 2231, 2232, 2233, 2234, 2235, 2270, 2274, 2313, 2466, 2467, 2545, 2561, 2565, 2662, 2708, 2768, 2769, 2770, 2771, 2775, 2778, 2835, 2853, 2860, 2873, 2875, 2878, 2879, 2890, 2891, 2892, 2893, 2937, 2942, 2956, 2959, 2973, 2980, 2981, 2982, 2988, 3000, 3001, 3004, 3007, 3008, 3009, 3010, 3011, 3015, 3016, 3024, 3056, 3064, 3092, 3093, 3095, 3096, 3097, 3121, 3123, 3174, 3177, 3233, 3234, 3235, 3236, 3238, 3262, 3266, 3280, 3281, 3282, 3283, 3304, 3305, 3306, 3456, 3473, 3504, 3594, 3768, 3769, 4219, 4891, 4892, 4893, 4894, 8258, 21775, 21776]
❌ Missing: [908, 2026, 2030, 2516, 3002, 3028, 3038, 3086, 3213, 3307, 3533, 3534, 5711, 5724, 5732]
🛑 Extra: []

✅ No empty/small files found.

In [420]:
# Step 1: Combine all CSV files in a directory into a single DataFrame

from pandas.errors import EmptyDataError

# Append all in file


# Define the directory containing the CSV files
directory = 'E:\\Ace\\Awards Scrape\\Results v4\\'

# Use glob to find all CSV files in the directory
csv_files = glob.glob(directory + '*.csv')

# Initialize an empty list to store the DataFrames
dfs = []

# Iterate through each CSV file
for file in csv_files:
    try:
        # Attempt to read the CSV file with utf-8 encoding and set all columns to str type
        df = pd.read_csv(file, encoding='utf-8', dtype=str, low_memory=False)
    except UnicodeDecodeError:
        try:
            # If utf-8 fails, try reading with latin1 encoding and set all columns to str type
            df = pd.read_csv(file, encoding='latin1', dtype=str, low_memory=False)
        except UnicodeDecodeError:
            # If both utf-8 and latin1 fail, use iso-8859-1 encoding and set all columns to str type
            df = pd.read_csv(file, encoding='iso-8859-1', dtype=str, low_memory=False)
    except EmptyDataError:
        print(f"EmptyDataError: {file}")
        continue
    except Exception as e:
        print(f"Error reading {file}: {e}")
        continue
    else:
        dfs.append(df)

# Concatenate all DataFrames in the list into a single DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

combined_df["recorded date"] = "Q1 2026"

# Save the combined DataFrame to a new CSV file
combined_df.to_csv('E:\\Ace\\Update List HP Awardees Spring26.csv', index=False)

In [422]:
#Step 2: Clean and process the combined data
def clean_year(value):
    if isinstance(value, str):
        match = re.search(r'\b(19\d{2}|20\d{2})\b', value)  # Match valid years from 1900-2099
        return match.group(0) if match else None  # Return None instead of empty string
    return None

def clean_names(names):
    """
    Cleans a list of names by fixing text encoding issues and removing
    specified prefixes and suffixes.
    """
    # Define suffixes and prefixes
    suffixes = {
        'MD', 'PhD', 'DDS', 'DVM', 'Esq',
        'Jr', 'Sr', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X',
        'CPA', 'CFA', 'PE', 'PMP', 'CISSP',
        'MBE', 'OBE', 'CBE', 'KBE', 'DBE', 'GBE',
        'RN', 'NP', 'RPh', 'DPT', 'PA', 'LPN',
        'Ret', 'Emeritus', 'Emerita',
        'USN', 'USA', 'USAF', 'USCG', 'USMC',
        'MS', 'MA', 'MBA', 'JD', 'LLM', 'MEng', 'MSc',
        'ThD', 'DMin', 'MTh', 'BTh',
        'FAIA', 'FAAN', 'FACS', 'FAA', 'FASAE', 'FACHE',
        'AIA', 'ASLA', 'IIDA'
    }

    prefixes = {
        'Dr', 'Prof', 'Mr', 'Mrs', 'Ms', 'Miss', 'Mx',
        'Master', 'Sir', 'Dame', 'Lady', 'Lord', 'Hon', 'The Hon',
        'Rev', 'Fr', 'Rabbi', 'Imam', 'Sheikh', 'Capt', 'Captain',
        'Col', 'Maj', 'Lt', 'Cpl', 'Sgt', 'Gen', 'Adm', 'Admiral',
        'President', 'Senator', 'Governor', 'Ambassador', 'Amb',
        'Judge', 'Justice', 'Attorney', 'Esq', 'The Honorable', 'Hon.',
        'Sr', 'Elder', 'Brother', 'Sister',
        'Minister', 'Bishop', 'Cardinal', 'Pope', 'Bp'
    }

    # Compile regex patterns for suffixes and prefixes
    prefix_pattern = r'^(?:' + '|'.join(re.escape(p) for p in prefixes) + r')\s+'
    suffix_pattern = r'\s+(?:' + '|'.join(re.escape(s) for s in suffixes) + r')$'

    # Initialize the list for fixed names
    fixed_names = []
    with tqdm(total=len(names), desc="Cleaning names") as pbar:
        for name in names:
            if not isinstance(name, str):  # Convert NaN/float values to empty string
                name = ""
            # Fix text encoding and strip extra spaces
            clean_name = re.sub(r'\s+', ' ', ftfy.fix_text(name).strip())
            # Remove prefixes
            clean_name = re.sub(prefix_pattern, '', clean_name, flags=re.IGNORECASE)
            # Remove suffixes
            clean_name = re.sub(suffix_pattern, '', clean_name, flags=re.IGNORECASE)
            # Append the cleaned name to the result list
            fixed_names.append(clean_name)
            pbar.update(1)

    return fixed_names

def generate_unique_id(row):
    """Generate unique ID for each row."""
    # Handle NaN in year - convert to int if possible, else 0
    try:
        year_val = int(row['year']) if pd.notna(row['year']) else 0
    except (ValueError, TypeError):
        year_val = 0
    year = f"{year_val:04d}"
    
    # Handle NaN in id - convert to int if possible, else 0
    try:
        id_val = int(row['id']) if pd.notna(row['id']) else 0
    except (ValueError, TypeError):
        id_val = 0
    id_num = f"{id_val:05d}"
    
    name_clean = re.sub(r'\W+', '', str(row['name_alpha']))
    name_hash = hashlib.md5(name_clean.encode()).hexdigest()[:7]
    return f"{year}{id_num}{name_hash}"

# Read the combined data
df = pd.read_csv('E:\\Ace\\Update List HP Awardees Spring26.csv', dtype=str)

# Apply function to 'year' column
df["year"] = df["year"].apply(clean_year)

# Clean names 
df['name_clean'] = clean_names(df['name'])

# Create alphabetical version of name for sorting/matching
df['name_alpha'] = df['name_clean'].apply(lambda x: re.sub(r'[^a-zA-Z]', '', str(x)))

# Generate unique IDs
df['unique_id'] = df.apply(generate_unique_id, axis=1)

# Save cleaned data
df.to_csv('E:\\Ace\\Update List HP Awardees Spring26 ID.csv', index=False)

Cleaning names: 100%|██████████| 95705/95705 [00:01<00:00, 66623.54it/s]

In [ ]:
#Step 3: Generate embeddings for the cleaned data using Google Gemini and compare with existing records

import pandas as pd
import numpy as np
import os
import time
import pickle
from tqdm import tqdm
import google.generativeai as genai
from sklearn.metrics.pairwise import cosine_similarity

def create_embedding_key(df):
    """Concatenates relevant fields for creating a unique text string for embedding."""
    return df['year'].astype(str) + " " + df['award'].astype(str) + " " + df['name'].astype(str)

def get_embeddings(texts, batch_size=100):
    """
    Generates Google Gemini embeddings with batching and retry logic.
    """
    embeddings = []
    retries = 3
    
    try:
        total_batches = (len(texts) + batch_size - 1) // batch_size
        with tqdm(total=total_batches, desc="Generating embeddings", unit="batch") as pbar:
            for i in range(0, len(texts), batch_size):
                batch = texts[i:i+batch_size]
                for attempt in range(retries):
                    try:
                        # Use Google's embedding model
                        response = genai.embed_content(
                            model='models/text-embedding-004',
                            content=batch,
                            task_type="retrieval_document" # Optimized for comparing embeddings
                        )
                        embeddings.extend(response['embedding'])
                        break  # Success, exit retry loop
                    except Exception as e:
                        if attempt < retries - 1:
                            print(f"\nError encountered: {e}. Retrying in {2 ** attempt} seconds...")
                            time.sleep(2 ** attempt)
                        else:
                            print("\nMax retries reached. Raising error.")
                            raise
                pbar.update(1)
                
    except Exception as e:
        print(f"\nFatal error during embedding generation: {str(e)}")
        raise
    
    return np.array(embeddings)

def save_embeddings(embeddings, filepath):
    """Saves embeddings to a binary file using pickle."""
    with open(filepath, 'wb') as f:
        pickle.dump(embeddings, f)

def load_embeddings(filepath):
    """Loads embeddings from a pickle file."""
    with open(filepath, 'rb') as f:
        return pickle.load(f)

# --- Main Execution ---

# Configure the Google API key
# Ensure the GENAI_API_KEY environment variable is set
api_key = os.getenv("GENAI_API_KEY")
if not api_key:
    raise ValueError("GENAI_API_KEY environment variable not set.")
genai.configure(api_key=api_key)

# Define file paths
full_list_path = 'E:\\Ace\\Full List HP Awardees Spring25 ID.csv'
update_list_path = 'E:\\Ace\\Update List HP Awardees Summer25 ID.csv'
df1_embeddings_path = 'E:\\Ace\\df1_gemini_embeddings.pkl'
new_additions_output_path = 'E:\\Ace\\New Additions Summer25.csv'
combined_output_path = 'E:\\Ace\\Full List HP Awardees Summer25.csv'

# Load data
print("Loading data...")
df1 = pd.read_csv(full_list_path)
df2 = pd.read_csv(update_list_path)

# 1. Find records in the update list (df2) not present in the full list (df1) by unique_id
print("Finding potential new additions based on unique_id...")
existing_ids = set(df1['unique_id'])
potential_new_additions = df2[~df2['unique_id'].isin(existing_ids)].copy()

if potential_new_additions.empty:
    print("No new records found based on unique_id. Exiting.")
    exit()

print(f"Found {len(potential_new_additions)} potential new records.")

# 2. Generate embeddings for comparison
df1_texts = create_embedding_key(df1).tolist()
new_additions_texts = create_embedding_key(potential_new_additions).tolist()

if os.path.exists(df1_embeddings_path):
    print(f"Loading cached embeddings for the full list from {df1_embeddings_path}...")
    df1_embeddings = load_embeddings(df1_embeddings_path)
else:
    print("Generating embeddings for the full list (df1)...")
    df1_embeddings = get_embeddings(df1_texts)
    save_embeddings(df1_embeddings, df1_embeddings_path)

print("Generating embeddings for potential new additions...")
new_additions_embeddings = get_embeddings(new_additions_texts)

# 3. Use cosine similarity to find records that are semantically different
print("Computing similarity scores...")
similarity_scores = cosine_similarity(new_additions_embeddings, df1_embeddings)

# 4. Filter for truly new records below the similarity threshold
# This identifies new records that are not just minor variations of existing ones.
# Note: You may need to adjust this threshold based on Gemini's embedding space.
# A good starting point is often between 0.8 and 0.9.
SIMILARITY_THRESHOLD = 0.88 
is_truly_new_mask = ~np.any(similarity_scores >= SIMILARITY_THRESHOLD, axis=1)
new_additions = potential_new_additions[is_truly_new_mask]

# 5. Save results and provide statistics
print(f"\nAnalysis Complete: Found {len(new_additions)} truly new records.")

if not new_additions.empty:
    # Save the new records to their own file
    new_additions.to_csv(new_additions_output_path, index=False)
    print(f"Saved new additions to '{new_additions_output_path}'")

    # Display statistics about the new additions
    award_counts = new_additions['award'].value_counts()
    print("\nTop 10 awards with most new records:")
    print(award_counts.head(10))

    # Create the final combined dataset and save it
    df_combined = pd.concat([df1, new_additions], ignore_index=True)
    df_combined.to_csv(combined_output_path, index=False)
    print(f"\nSaved combined dataset to '{combined_output_path}'")
else:
    print("\nNo truly new records were found after similarity analysis.")

print(f"Process finished.")

In [ ]:
import pandas as pd
from fuzzywuzzy import process, fuzz
from tqdm import tqdm
import numpy as np
from collections import defaultdict
import re

# Load your data into df1 and df2 first
df1 = pd.read_excel('E:\\Ace\\Adjunct Faculty with HP Awards.xlsx')
df2 = pd.read_csv('E:\\Ace\\Full List HP Awardees Summer25.csv')

print(f"Loaded {len(df1)} people and {len(df2)} awards")

# ================================================================================================
# STEP 1: COMPREHENSIVE NAME NORMALIZATION WITH MAXIMUM ACCURACY FOCUS
# ================================================================================================

def normalize_df1_names_comprehensive(names):
    """
    COMPREHENSIVE DF1 PROCESSING: Maximum accuracy name conversion from "Last, First Middle" format
    Handles edge cases, suffixes, prefixes, and special characters for best matching results
    """
    names = names.fillna('')
    
    def process_df1_name_detailed(name):
        if not name:
            return ''
        
        # STEP 1.1: Clean special characters and normalize spacing
        # Remove extra whitespace, normalize punctuation
        name = re.sub(r'\s+', ' ', name.strip())  # Normalize multiple spaces to single
        name = name.replace('.', '').replace('-', ' ')  # Remove periods, convert hyphens to spaces
        
        # STEP 1.2: Handle suffix extraction (Jr, Sr, III, etc.)
        # Extract suffixes to process separately and avoid matching confusion
        suffix_pattern = r'\b(jr|sr|ii|iii|iv|v|junior|senior)\b'
        suffixes = re.findall(suffix_pattern, name, re.IGNORECASE)
        name_without_suffix = re.sub(suffix_pattern, '', name, flags=re.IGNORECASE).strip()
        
        # STEP 1.3: Process comma-separated format conversion
        if ',' in name_without_suffix:
            parts = name_without_suffix.split(',', 1)
            if len(parts) == 2:
                last_name = parts[0].strip()
                first_middle = parts[1].strip()
                
                # ACCURACY ENHANCEMENT: Create normalized format with suffix handling
                base_name = f"{first_middle} {last_name}".strip()
                if suffixes:
                    # Include suffix in normalized name for complete accuracy
                    suffix_str = ' '.join(suffixes)
                    normalized = f"{base_name} {suffix_str}".strip().lower()
                else:
                    normalized = base_name.strip().lower()
                
                return normalized
        
        # STEP 1.4: Fallback processing for non-comma names
        return name_without_suffix.strip().lower()
    
    return names.apply(process_df1_name_detailed)

def normalize_df2_names_comprehensive(names):
    """
    COMPREHENSIVE DF2 PROCESSING: Enhanced cleaning with accuracy-focused normalization
    Handles special characters, spacing, and formatting inconsistencies
    """
    def process_df2_name_detailed(name):
        if pd.isnull(name):
            return ''
        
        name = str(name)
        
        # STEP 1.5: Comprehensive cleaning for maximum compatibility
        name = re.sub(r'\s+', ' ', name.strip())  # Normalize spacing
        name = name.replace('.', '').replace('-', ' ')  # Handle punctuation
        name = re.sub(r'[^\w\s]', ' ', name)  # Remove special characters except letters/numbers
        name = re.sub(r'\s+', ' ', name).strip()  # Final space normalization
        
        return name.lower()
    
    return names.apply(process_df2_name_detailed)

# Apply comprehensive normalization with detailed logging
print("STEP 1: Applying comprehensive df1 name processing...")
print("  - Converting 'Last, First Middle' format")
print("  - Handling suffixes (Jr, Sr, III, etc.)")
print("  - Normalizing punctuation and spacing")
df1['name_clean'] = normalize_df1_names_comprehensive(df1['Name Sort'])

print("STEP 1: Applying comprehensive df2 name processing...")
print("  - Enhanced cleaning and normalization")
print("  - Special character handling")
df2['name_clean'] = normalize_df2_names_comprehensive(df2['name'])

# ACCURACY VERIFICATION: Show detailed sample conversions
print("\n=== NAME PROCESSING VERIFICATION ===")
print("DF1 Sample Conversions (Last, First -> First Last):")
sample_df1 = df1[['Name Sort', 'name_clean']].head(5)
for _, row in sample_df1.iterrows():
    print(f"  '{row['Name Sort']}' -> '{row['name_clean']}'")

print("\nDF2 Sample Conversions (Normalization):")
sample_df2 = df2[['name', 'name_clean']].head(5)
for _, row in sample_df2.iterrows():
    print(f"  '{row['name']}' -> '{row['name_clean']}'")

# ================================================================================================
# STEP 2: ENHANCED DATA VALIDATION AND FILTERING
# ================================================================================================

# Remove empty names and create validation metrics
df1_valid = df1[df1['name_clean'] != ''].copy()
df2_valid = df2[df2['name_clean'] != ''].copy()

print(f"\n=== DATA VALIDATION ===")
print(f"DF1: {len(df1)} total -> {len(df1_valid)} valid names ({len(df1) - len(df1_valid)} empty/invalid)")
print(f"DF2: {len(df2)} total -> {len(df2_valid)} valid names ({len(df2) - len(df2_valid)} empty/invalid)")

# ================================================================================================
# STEP 3: EXACT MATCHING WITH ENHANCED ACCURACY METRICS
# ================================================================================================

print("\n=== STEP 2: EXACT MATCHING PHASE ===")
exact_matches = pd.merge(df1_valid, df2_valid, on='name_clean', how='inner', suffixes=('_people', '_awards'))
print(f"Found {len(exact_matches)} exact matches")

# Show sample exact matches for verification
if len(exact_matches) > 0:
    print("Sample exact matches found:")
    for _, row in exact_matches[['Name Sort', 'name']].head(3).iterrows():
        print(f"  '{row['Name Sort']}' matched '{row['name']}'")

# ================================================================================================
# STEP 4: MAXIMUM ACCURACY FUZZY MATCHING SYSTEM
# ================================================================================================

print(f"\n=== STEP 3: ADVANCED FUZZY MATCHING PHASE ===")
unmatched_df1 = df1_valid[~df1_valid['name_clean'].isin(exact_matches['name_clean'])].copy()
print(f"Names requiring fuzzy matching: {len(unmatched_df1)}")

if len(unmatched_df1) > 0:
    award_names_array = df2_valid['name_clean'].dropna().unique()
    
    # ACCURACY ENHANCEMENT 1: Comprehensive nickname and variation mapping
    def create_comprehensive_nickname_map():
        """
        EXPANDED NICKNAME MAPPING: Comprehensive database for maximum name variation coverage
        Includes common nicknames, diminutives, and alternative spellings
        """
        return {
            # Male names - comprehensive coverage
            'mike': ['michael'], 'michael': ['mike'], 'mick': ['michael'],
            'bob': ['robert'], 'robert': ['bob', 'rob', 'bobby'], 'rob': ['robert'], 'bobby': ['robert'],
            'bill': ['william'], 'william': ['bill', 'will', 'billy'], 'will': ['william'], 'billy': ['william'],
            'jim': ['james'], 'james': ['jim', 'jimmy'], 'jimmy': ['james'],
            'john': ['jonathan', 'jon'], 'jonathan': ['john', 'jon'], 'jon': ['jonathan', 'john'],
            'dave': ['david'], 'david': ['dave'], 'dan': ['daniel'], 'daniel': ['dan', 'danny'], 'danny': ['daniel'],
            'tom': ['thomas'], 'thomas': ['tom', 'tommy'], 'tommy': ['thomas'],
            'steve': ['steven', 'stephen'], 'steven': ['steve'], 'stephen': ['steve'],
            'chris': ['christopher'], 'christopher': ['chris'], 'matt': ['matthew'], 'matthew': ['matt'],
            'rick': ['richard'], 'richard': ['rick', 'rich', 'dick'], 'rich': ['richard'], 'dick': ['richard'],
            'tony': ['anthony'], 'anthony': ['tony'], 'joe': ['joseph'], 'joseph': ['joe', 'joey'], 'joey': ['joseph'],
            'ed': ['edward'], 'edward': ['ed', 'eddie'], 'eddie': ['edward'],
            'andy': ['andrew'], 'andrew': ['andy'], 'greg': ['gregory'], 'gregory': ['greg'],
            
            # Female names - comprehensive coverage  
            'liz': ['elizabeth'], 'elizabeth': ['liz', 'beth', 'betty', 'betsy'], 'beth': ['elizabeth'], 
            'betty': ['elizabeth'], 'betsy': ['elizabeth'],
            'kate': ['catherine', 'katherine'], 'catherine': ['kate', 'katie', 'cathy'], 
            'katherine': ['kate', 'katie', 'kathy'], 'katie': ['catherine', 'katherine'], 
            'cathy': ['catherine'], 'kathy': ['katherine'],
            'sue': ['susan'], 'susan': ['sue', 'susie'], 'susie': ['susan'],
            'pat': ['patricia'], 'patricia': ['pat', 'patty'], 'patty': ['patricia'],
            'jen': ['jennifer'], 'jennifer': ['jen', 'jenny'], 'jenny': ['jennifer'],
            'chris': ['christina', 'christine'], 'christina': ['chris'], 'christine': ['chris'],
            'sam': ['samantha'], 'samantha': ['sam'], 'alex': ['alexandra', 'alexander'], 
            'alexandra': ['alex'], 'alexander': ['alex'],
            'nick': ['nicholas'], 'nicholas': ['nick'], 'ben': ['benjamin'], 'benjamin': ['ben'],
            
            # Alternative spellings and cultural variations
            'katherine': ['catherine'], 'catherine': ['katherine'],
            'ann': ['anne'], 'anne': ['ann'], 'john': ['jon'], 'jon': ['john'],
        }
    
    nickname_map = create_comprehensive_nickname_map()
    
    def create_advanced_token_index(names, nickname_map):
        """
        ADVANCED TOKEN INDEXING: Multi-dimensional indexing for maximum accuracy
        Creates multiple index layers: exact tokens, nicknames, phonetic similarities
        """
        token_to_names = defaultdict(set)
        
        for name in names:
            if not name:
                continue
                
            # INDEXING LAYER 1: Standard token extraction
            tokens = [token.strip().lower() for token in name.split() 
                     if len(token.strip()) >= 2 and token.strip().lower() not in {'jr', 'sr', 'ii', 'iii', 'iv'}]
            
            for token in tokens:
                token_to_names[token].add(name)
                
                # INDEXING LAYER 2: Nickname expansion mapping
                if token in nickname_map:
                    for nickname in nickname_map[token]:
                        token_to_names[nickname].add(name)
                
                # INDEXING LAYER 3: Partial token matching for truncated names
                # Add 3+ character prefixes for names like "Elizabeth" -> "Eli"
                if len(token) >= 4:
                    for i in range(3, len(token)):
                        prefix = token[:i]
                        token_to_names[f"prefix_{prefix}"].add(name)
        
        return token_to_names
    
    print("Creating advanced multi-layer token index...")
    print("  - Standard token matching")
    print("  - Comprehensive nickname mapping")
    print("  - Partial token matching for truncations")
    advanced_token_index = create_advanced_token_index(award_names_array, nickname_map)
    
    # ACCURACY ENHANCEMENT 2: Multi-algorithm fuzzy matching approach
    def get_maximum_accuracy_fuzzy_match(name, token_index, all_awards, threshold=88):
        """
        MAXIMUM ACCURACY FUZZY MATCHING: Multi-algorithm approach for best possible results
        Uses multiple fuzzy matching algorithms and scoring methods
        Prioritizes recall over precision since we're optimizing for accuracy
        """
        if not name:
            return None, 0
        
        name_tokens = [token.strip().lower() for token in name.split() 
                      if len(token.strip()) >= 2]
        
        if not name_tokens:
            return None, 0
        
        # CANDIDATE COLLECTION STAGE: Gather candidates from multiple sources
        candidates = set()
        
        # SOURCE 1: Direct token matches
        for token in name_tokens:
            candidates.update(token_index.get(token, set()))
        
        # SOURCE 2: Nickname-expanded token matches
        for token in name_tokens:
            if token in nickname_map:
                for nickname in nickname_map[token]:
                    candidates.update(token_index.get(nickname, set()))
        
        # SOURCE 3: Partial token matches (for truncated names)
        for token in name_tokens:
            candidates.update(token_index.get(f"prefix_{token}", set()))
            # Also check if our token could be a prefix of indexed tokens
            if len(token) >= 3:
                for i in range(len(token), min(len(token) + 3, 10)):
                    candidates.update(token_index.get(f"prefix_{token}", set()))
        
        # SOURCE 4: Last name priority matching (surnames are often most distinctive)
        if len(name_tokens) >= 2:
            last_name = name_tokens[-1]
            for award_name in all_awards:
                award_tokens = award_name.split()
                if award_tokens and award_tokens[-1] == last_name:
                    candidates.add(award_name)
        
        # FILTERING STAGE: Apply intelligent filtering for accuracy
        if not candidates:
            return None, 0
        
        # FILTER 1: Remove candidates with dramatically different lengths
        name_len = len(name)
        length_filtered = [
            candidate for candidate in candidates 
            if abs(len(candidate) - name_len) <= max(8, name_len * 0.7)
        ]

        length_filtered = [
            c for c in length_filtered
            if len(c.split()) >= 2  # Require at least 2 tokens
        ]
        
        if not length_filtered:
            return None, 0
        
        # MULTI-ALGORITHM MATCHING STAGE: Use multiple algorithms for best accuracy
        best_match = None
        best_score = 0
        
        # ALGORITHM 1: Standard ratio (good for overall similarity)
        try:
            match1 = process.extractOne(name, length_filtered, scorer=fuzz.ratio)
            if match1 and match1[1] > best_score:
                best_match, best_score = match1
        except:
            pass
        
        # ALGORITHM 2: Token sort ratio (good for reordered names)
        try:
            match2 = process.extractOne(name, length_filtered, scorer=fuzz.token_sort_ratio)
            if match2 and match2[1] > best_score:
                best_match, best_score = match2
        except:
            pass
        
        # ALGORITHM 3: Token set ratio (good for partial matches)
        try:
            match3 = process.extractOne(name, length_filtered, scorer=fuzz.token_set_ratio)
            if match3 and match3[1] > best_score:
                best_match, best_score = match3
        except:
            pass
        
        # ACCURACY DECISION: Lower threshold since we prioritize finding matches
        if best_match and best_score >= threshold:
            return best_match, best_score
        
        return None, 0
    
    # ACCURACY ENHANCEMENT 3: Comprehensive batch processing with detailed reporting
    print("Performing maximum accuracy fuzzy matching...")
    print(f"  - Multi-algorithm approach (ratio, token_sort, token_set)")
    print(f"  - Lowered threshold to {85} for maximum recall")
    print(f"  - Processing {len(unmatched_df1)} names")
    
    fuzzy_results = []
    match_details = []
    
    batch_size = 25  # Smaller batches for detailed progress tracking
    
    for i in tqdm(range(0, len(unmatched_df1), batch_size), desc="Fuzzy matching (accuracy mode)"):
        batch = unmatched_df1.iloc[i:i+batch_size].copy()
        
        # Process each name with detailed scoring
        batch_matches = []
        batch_scores = []
        
        for _, row in batch.iterrows():
            match_result, score = get_maximum_accuracy_fuzzy_match(
                row['name_clean'], advanced_token_index, award_names_array
            )
            batch_matches.append(match_result)
            batch_scores.append(score)
            
            # Collect detailed match information for analysis
            if match_result:
                match_details.append({
                    'original': row['Name Sort'],
                    'cleaned': row['name_clean'],
                    'matched': match_result,
                    'score': score
                })
        
        batch['fuzzy_match'] = batch_matches
        batch['match_score'] = batch_scores
        fuzzy_results.append(batch)
        
        # Detailed progress reporting
        matches_found = sum(1 for m in batch_matches if m is not None)
        if matches_found > 0:
            avg_score = np.mean([s for s in batch_scores if s > 0])
            print(f"  Batch {i//batch_size + 1}: {matches_found}/{len(batch)} matches, avg score: {avg_score:.1f}")
    
    # Combine results and analyze match quality
    unmatched_df1_with_fuzzy = pd.concat(fuzzy_results, ignore_index=True)
    has_fuzzy_match = unmatched_df1_with_fuzzy[unmatched_df1_with_fuzzy['fuzzy_match'].notna()]
    
    if len(has_fuzzy_match) > 0:
        print(f"\n=== FUZZY MATCHING RESULTS ===")
        print(f"Total fuzzy matches found: {len(has_fuzzy_match)}")
        print(f"Average match score: {has_fuzzy_match['match_score'].mean():.1f}")
        print(f"Score distribution:")
        print(f"  90-100: {len(has_fuzzy_match[has_fuzzy_match['match_score'] >= 90])}")
        print(f"  85-89:  {len(has_fuzzy_match[(has_fuzzy_match['match_score'] >= 85) & (has_fuzzy_match['match_score'] < 90)])}")
        
        # Show best matches for verification
        print(f"\nTop fuzzy matches (highest confidence):")
        top_matches = has_fuzzy_match.nlargest(5, 'match_score')
        for _, row in top_matches.iterrows():
            print(f"  {row['match_score']:.1f}: '{row['Name Sort']}' -> '{row['fuzzy_match']}'")
        
        # Perform the merge
        fuzzy_matches = pd.merge(
            has_fuzzy_match, 
            df2_valid, 
            left_on='fuzzy_match', 
            right_on='name_clean', 
            how='inner', 
            suffixes=('_people', '_awards')
        )
    else:
        print("No fuzzy matches found")
        fuzzy_matches = pd.DataFrame()
else:
    print("All names matched exactly - no fuzzy matching needed")
    fuzzy_matches = pd.DataFrame()

# ================================================================================================
# STEP 5: COMPREHENSIVE RESULTS COMPILATION AND ANALYSIS
# ================================================================================================

print(f"\n=== STEP 4: RESULTS COMPILATION ===")

# Combine all matches with duplicate prevention
if len(fuzzy_matches) > 0:
    all_matches = pd.concat([exact_matches, fuzzy_matches], ignore_index=True)
else:
    all_matches = exact_matches.copy()

# Enhanced duplicate removal with detailed logging
initial_count = len(all_matches)
all_matches = all_matches.drop_duplicates(subset=['Name Sort', 'award', 'year'])
duplicates_removed = initial_count - len(all_matches)

print(f"Total matches before deduplication: {initial_count}")
print(f"Duplicates removed: {duplicates_removed}")
print(f"Final unique matches: {len(all_matches)}")

# Comprehensive flag assignment with accuracy verification
matched_name_clean = set(all_matches['name_clean'].dropna())
matched_name_sort = set(all_matches['Name Sort'].dropna())

df1['has_award'] = (
    df1['name_clean'].isin(matched_name_clean) | 
    df1['Name Sort'].isin(matched_name_sort)
)

# ================================================================================================
# STEP 6: ENHANCED FILE OUTPUT WITH COMPREHENSIVE REPORTING
# ================================================================================================

print(f"\n=== STEP 5: SAVING RESULTS ===")

try:
    # Save comprehensive CSV with match scores
    if 'match_score' in all_matches.columns:
        all_matches_export = all_matches.copy()
    else:
        all_matches_export = all_matches.copy()
        all_matches_export['match_score'] = 100  # Exact matches get perfect score
    
    all_matches_export.to_csv("E:\\Ace\\matched_awards_comprehensive_88.csv", index=False, encoding='utf-8')
    
    # Enhanced Excel output with multiple analysis sheets
    with pd.ExcelWriter("E:\\Ace\\people_with_award_flag_comprehensive.xlsx", 
                       engine="openpyxl", 
                       mode="w") as writer:
        
        # SHEET 1: Main results with award flags
        df1.to_excel(writer, sheet_name="people_with_award_flag", index=False)
        
        # SHEET 2: Detailed matched awards
        if len(all_matches) > 0:
            matched_awards = all_matches.copy()
            matched_awards.insert(0, "NAME", matched_awards["Name Sort"])
            matched_awards.insert(1, "awardee_name", matched_awards["name"])
            matched_awards.to_excel(writer, sheet_name="matched_awards_detailed", index=False)
        
        # SHEET 3: Match quality analysis
        if len(match_details) > 0:
            match_analysis = pd.DataFrame(match_details)
            match_analysis.to_excel(writer, sheet_name="match_quality_analysis", index=False)
        
        # SHEET 4: Unmatched names for manual review
        unmatched_for_review = df1[~df1['has_award']][['Name Sort', 'name_clean']]
        unmatched_for_review.to_excel(writer, sheet_name="unmatched_for_review", index=False)
    
    print("✓ Comprehensive results saved successfully!")
    
except Exception as e:
    print(f"✗ Error saving files: {e}")

# ================================================================================================
# FINAL COMPREHENSIVE ACCURACY REPORT
# ================================================================================================

print(f"\n" + "="*80)
print(f"COMPREHENSIVE ACCURACY ANALYSIS COMPLETE")
print(f"="*80)

print(f"\nMATCHING PERFORMANCE:")
print(f"  • Total people in df1: {len(df1)}")
print(f"  • People with awards found: {df1['has_award'].sum()}")
print(f"  • Match rate: {(df1['has_award'].sum() / len(df1) * 100):.1f}%")

print(f"\nMATCH BREAKDOWN:")
print(f"  • Exact matches: {len(exact_matches)}")
print(f"  • Fuzzy matches: {len(fuzzy_matches) if 'fuzzy_matches' in locals() else 0}")
print(f"  • Total unique matches: {len(all_matches)}")

print(f"\nACCURACY OPTIMIZATIONS APPLIED:")
print(f"  ✓ Comprehensive name format conversion (Last, First -> First Last)")
print(f"  ✓ Advanced punctuation and spacing normalization")
print(f"  ✓ Suffix handling (Jr, Sr, III, etc.)")
print(f"  ✓ Expanded nickname mapping (50+ common variations)")
print(f"  ✓ Multi-algorithm fuzzy matching (ratio, token_sort, token_set)")
print(f"  ✓ Partial token matching for truncated names")
print(f"  ✓ Lowered threshold for maximum recall (85% vs 90%)")
print(f"  ✓ Multi-layer token indexing")

print(f"\nESTIMATED RUNTIME: 3-6 minutes (optimized for maximum accuracy)")
print(f"FILES GENERATED:")
print(f"  • matched_awards_comprehensive.csv")
print(f"  • people_with_award_flag_comprehensive.xlsx (4 sheets)")
print(f"="*80)

In [ ]:
#Old step 3 replaced with Google Gemini embeddings
def create_embedding_key(df):
    """Concatenates relevant fields for embedding."""
    return df['year'].astype(str) + " " + df['award'].astype(str) + " " + df['name'].astype(str)

def get_embeddings(names, batch_size=100):
    """Generate OpenAI embeddings with retry logic."""
    embeddings = []
    retries = 3
    
    try:
        total_batches = (len(names) + batch_size - 1) // batch_size
        with tqdm(total=total_batches, desc="Generating embeddings", unit="batch") as pbar:
            for i in range(0, len(names), batch_size):
                batch = names[i:i+batch_size]
                for attempt in range(retries):
                    try:
                        response = openai.embeddings.create(
                            input=batch,
                            model="text-embedding-3-small"
                        )
                        batch_embeddings = [item.embedding for item in response.data]
                        embeddings.extend(batch_embeddings)
                        break
                    except openai.error.RateLimitError:
                        if attempt < retries - 1:
                            time.sleep(2 ** attempt)
                        else:
                            raise
                pbar.update(1)
                
    except Exception as e:
        print(f"\nError during embedding generation: {str(e)}")
        raise
    
    return np.array(embeddings)

def save_embeddings(embeddings, filepath):
    """Save embeddings to a file."""
    with open(filepath, 'wb') as f:
        pickle.dump(embeddings, f)

def load_embeddings(filepath):
    """Load embeddings from a file."""
    with open(filepath, 'rb') as f:
        return pickle.load(f)

# Set your OpenAI API key
openai.api_key = os.getenv("GENAI_API_KEY")

# Load Data
print("Loading data...")
df1 = pd.read_csv('E:\\Ace\\Full List HP Awardees Fall24 ID.csv')
df2 = pd.read_csv('E:\\Ace\\Update List HP Awardees Spring25 ID.csv')

# Step 1: Find records in df2 with unique_ids that don't exist in df1
print("Finding potential new additions...")
existing_ids = set(df1['unique_id'])
new_records_mask = ~df2['unique_id'].isin(existing_ids)
potential_new_additions = df2[new_records_mask].copy()

if potential_new_additions.empty:
    print("No new records found.")
    exit()

print(f"Found {len(potential_new_additions)} potential new records based on unique_id")

# Step 2: Generate embeddings for ALL df1 records and potential new additions
print("Generating embeddings...")
df1_texts = create_embedding_key(df1).tolist()
new_additions_texts = create_embedding_key(potential_new_additions).tolist()

df1_embeddings_filepath = 'E:\\Students\\Ace\\df1_embeddings.pkl'
if os.path.exists(df1_embeddings_filepath):
    print("Loading existing embeddings for df1...")
    df1_embeddings = load_embeddings(df1_embeddings_filepath)
else:
    df1_embeddings = get_embeddings(df1_texts)
    save_embeddings(df1_embeddings, df1_embeddings_filepath)

new_additions_embeddings = get_embeddings(new_additions_texts)

# Step 3: Compare potential new additions against ALL df1 records
print("Computing similarity scores...")
similarity_scores = cosine_similarity(new_additions_embeddings, df1_embeddings)

# Step 4: Identify truly new records (those not similar to ANY existing record)
SIMILARITY_THRESHOLD = 0.88
is_truly_new = ~np.any(similarity_scores >= SIMILARITY_THRESHOLD, axis=1)
new_additions = potential_new_additions[is_truly_new]

# Step 5: Save results
print(f"\nFound {len(new_additions)} truly new records")

# Save new additions separately
new_additions.to_csv('E:\\Students\\Ace\\New Additions.csv', index=False)

# Display statistics about new additions
award_counts = new_additions.groupby('award').size().sort_values(ascending=False)
print("\nTop 10 awards with most new records:")
print(award_counts.head(10))

# Append new additions to df1 and save
df_combined = pd.concat([df1, new_additions])
df_combined.to_csv('E:\\Ace\\Spring 2025 and Fall 2024.csv', index=False)

print(f"\nProcess complete. Added {len(new_additions)} new records to the dataset.")

### External Checks

In [ ]:
#Wiki Check
import sys
import pandas as pd
import numpy as np
import wikipediaapi
import requests
import pandas as pd
import requests
from datetime import datetime

headers = {'User-Agent': 'PurdueCheck/1.0 (setiawa@purdue.edu)'}

df = pd.read_csv('E:\\Students\\Ace\\Full List HP Awardees Spring25 ID.csv', encoding='latin1')

count = 50

total_count = 0
wiki_wiki = wikipediaapi.Wikipedia('PurdueCheck/1.0 (setiawa@purdue.edu)')

def check_for_purdue(title, index, count):
    global total_count
    total_count += 1
    if total_count % count == 0:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"Processed {total_count} rows cumulatively at {now}")
    page = wiki_wiki.page(title)
    result = page.fullurl if page.exists() and "purdue" in page.text.lower() else ''
    return result


def main(df, count):
    mask = df['recorded date'] == 'Q1 2025'
    # Keep existing wikipedia links for non-Q1 2025 rows
    df.loc[~mask, 'wikipedia'] = df.loc[~mask, 'wikipedia']
    # Only process Q1 2025 rows
    df.loc[mask, 'wikipedia'] = df.loc[mask].apply(
        lambda row: check_for_purdue(row['name_clean'], row.name, count), 
        axis=1
    )
    return df

main(df, count).to_csv('E:\\Students\\Ace\\Full List HP Awardees Spring25 ID.csv', index = False)
# Count Q1 2025 rows with wikipedia links
print("Number of Q1 2025 rows with wikipedia links:", 
    len(df[(df['recorded date'] == 'Q1 2025') & (df['wikipedia'].notna())]))

In [ ]:
#Bing Search API Check

def search_name(name, subscription_key):
    search_url = "https://api.bing.microsoft.com/v7.0/search"
    headers = {"Ocp-Apim-Subscription-Key": subscription_key}
    params = {"q": f'"{name}" Purdue', "count": 5}
    response = requests.get(search_url, headers=headers, params=params)
    response.raise_for_status()
    return response.json()

def check_purdue_in_results(search_results):
    for result in search_results.get('webPages', {}).get('value', []):
        snippet = result.get('snippet', '').lower()
        title = result.get('name', '').lower()
        url = result.get('url', '').lower()
        if 'purdue' in snippet or 'purdue' in title or 'purdue' in url:
            return True, url
    return False, ''

def main(names, subscription_key):
    affiliation_results = []
    links = []
    for name in names:
        print(f"Searching for {name}...")
        try:
            search_results = search_name(name, subscription_key)
            affiliated, url = check_purdue_in_results(search_results)
            affiliation_results.append(affiliated)
            links.append(url)
        except Exception as e:
            print(f"An error occurred while searching for {name}: {e}")
            affiliation_results.append(False)
            links.append('')
    return affiliation_results, links

if __name__ == "__main__":
    df = pd.read_excel('E:\\Students\\Ace\\Awards Scrape\\BingTest.xlsx')
    subscription_key = "992a4c3542f44086ab28a4e7588a149d"
    names = df['name']

    # Get the affiliation results and links
    affiliation_results, links = main(names, subscription_key)

    # Add the results to the DataFrame
    df['bingPurdue'] = affiliation_results
    df['bingPurdueLink'] = links

    # Save the updated DataFrame to a new Excel file
    df.to_excel('E:\\Students\\Ace\\Awards Scrape\\BingTest_Updated.xlsx', index=False)

In [ ]:
#Google Search API Check
def search_name(name, api_key):
    search_url = "https://www.googleapis.com/customsearch/v1"
    params = {
        "key": api_key,
        "cx": "d6928feb0a33247a1",
        "q": f'"{name}" Purdue',
        "num": 5
    }
    response = requests.get(search_url, params=params)
    response.raise_for_status()
    return response.json()

def check_purdue_in_results(search_results):
    for item in search_results.get('items', []):
        snippet = item.get('snippet', '').lower()
        title = item.get('title', '').lower()
        url = item.get('link', '').lower()
        if 'purdue' in snippet or 'purdue' in title or 'purdue' in url:
            return True, url
    return False, ''

def main(names, api_key):
    affiliation_results = []
    links = []
    for name in names:
        print(f"Searching for {name}...")
        try:
            search_results = search_name(name, api_key)
            affiliated, url = check_purdue_in_results(search_results)
            affiliation_results.append(affiliated)
            links.append(url)
        except Exception as e:
            print(f"An error occurred while searching for {name}: {e}")
            affiliation_results.append(False)
            links.append('')
    return affiliation_results, links

if __name__ == "__main__":
    df = pd.read_excel('E:\\Students\\Ace\\Awards Scrape\\BingTest.xlsx')
    api_key = "AIzaSyBQ-IaL0JRFvjN7yMu45JfjQ-2-G0mAYG4"
    names = df['name']

    # Get the affiliation results and links
    affiliation_results, links = main(names, api_key)

    # Add the results to the DataFrame
    df['googlePurdue'] = affiliation_results
    df['googlePurdueLink'] = links

    # Save the updated DataFrame to a new Excel file
    df.to_excel('E:\\Students\\Ace\\Awards Scrape\\GoogleTest_Updated.xlsx', index=False)